update=Вт 16 фев 2016 10:12:11
version=1
last_client=pcbnew
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=/home/alexey/Projects/lazertag/schematic/components/3rdparty/w_rtx/w_rtx
LibName32=/home/alexey/Projects/lazertag/schematic/components/extension-connector
LibName33=/home/alexey/Projects/lazertag/schematic/components/mcp73831
LibName34=/home/alexey/Projects/lazertag/schematic/components/MCU-board-connectors
LibName35=/home/alexey/Projects/lazertag/schematic/components/ncp551
LibName36=/home/alexey/Projects/lazertag/schematic/components/nrf24l01
LibName37=/home/alexey/Projects/lazertag/schematic/components/linStab-(1-GND,Adj,2-Out,3-in)
LibName38=/home/alexey/Projects/lazertag/schematic/components/usblc6-4
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=bluetooth-bridge.net
UseCmpFile=1
PadDrill="    0,600000"
PadDrillOvalY="    0,600000"
PadSizeH="    1,000000"
PadSizeV="    1,000000"
PcbTextSizeV="    1,000000"
PcbTextSizeH="    1,000000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,000000"
ModuleTextSizeH="    1,000000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,000000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,150000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_crystal&oscillator
LibName9=smd_dil
LibName10=smd_transistors
LibName11=libcms
LibName12=display
LibName13=led
LibName14=dip_sockets
LibName15=pga_sockets
LibName16=valves
LibName17=/home/alexey/Projects/lazertag/schematic/components/3rdparty/w_rf/w_rf_modules
LibName18=/home/alexey/Projects/lazertag/schematic/components/pin-array-10x2
LibName19=/home/alexey/Projects/lazertag/schematic/components/pin-arr-2mm-horiz
LibName20=/home/alexey/Projects/lazertag/schematic/components/pin-arr-5x2-socket
