Caustic lasertag system: IRPresentationReceiverMT2 Class Reference
IRPresentationReceiverMT2 Class Reference
#include <ir-presentation-mt2.hpp>
Public Member Functions
void init ()
void assignReceiversGroup (IPresentationReceiversGroup &group)
void interrogate ()
void setDamageCoefficient (const FloatParameter *coefficient)
Public Member Functions inherited from IRPresentationReceiverBase
void setPhysicalReceiver (IIRPhysicalReceiver *receiver)
void setVibroEngine (IIOPin *pin)
Public Member Functions inherited from IIRPresentationReceiver
virtual ~IIRPresentationReceiver ()
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Private Member Functions
void receiverCallback (const uint8_t *data, uint16_t size)
void parseShot (const uint8_t *data, uint16_t size)
void parseMT2Command (const uint8_t *data, uint16_t size)
void parseSetTeam (const uint8_t *data, uint16_t size)
void parseAddHealth (const uint8_t *data, uint16_t size)
void parseRCSP (const uint8_t *data, uint16_t size)
void enableVibro ()
uint8_t decodeDamage (uint8_t damage)
void updateOperationCallback (OperationCallback callback)
Private Attributes
PresentationReceiversGroupMT2 * m_group = nullptr
const FloatParameter * m_damageCoefficient = &defaultDamageCoefficient
Time m_vibroEnabledTime = 0
Static Private Attributes
static constexpr uint32_t vibroPeriod = 200000
static FloatParameter defaultDamageCoefficient = 1.0
Additional Inherited Members
Protected Attributes inherited from IRPresentationReceiverBase
IIRPhysicalReceiver * m_physicalReceiver = nullptr
IIOPin * m_vibro = nullptr
Detailed Description
Definition at line 52 of file ir-presentation-mt2.hpp.
Member Function Documentation
assignReceiversGroup()
void IRPresentationReceiverMT2::assignReceiversGroup (IPresentationReceiversGroup & group) virtual
Implements IIRPresentationReceiver.
Definition at line 152 of file ir-presentation-mt2.cpp.
decodeDamage()
uint8_t IRPresentationReceiverMT2::decodeDamage (uint8_t damage) private
Definition at line 344 of file ir-presentation-mt2.cpp.
enableVibro()
void IRPresentationReceiverMT2::enableVibro () private
Definition at line 335 of file ir-presentation-mt2.cpp.
References ISystemClock::getTime(), and systemClock.
init()
void IRPresentationReceiverMT2::init () virtual
Implements IIRPresentationReceiver.
Definition at line 147 of file ir-presentation-mt2.cpp.
interrogate()
void IRPresentationReceiverMT2::interrogate () virtual
Implements IInterrogatable.
Definition at line 157 of file ir-presentation-mt2.cpp.
References ISystemClock::getTime(), and systemClock.
parseAddHealth()
void IRPresentationReceiverMT2::parseAddHealth (const uint8_t * data, uint16_t size) private
Definition at line 257 of file ir-presentation-mt2.cpp.
References MT2Extended::decodeAddHealth(), instance, and UNUSED_ARG.
parseMT2Command()
void IRPresentationReceiverMT2::parseMT2Command (const uint8_t * data, uint16_t size) private
Definition at line 268 of file ir-presentation-mt2.cpp.
References MT2Extended::Commands::adminKill, MT2Extended::Commands::clearScores, MT2Extended::Commands::disarmPlayer, MT2Extended::Commands::endGame, MT2Extended::Commands::explodePlayer, MT2Extended::Commands::fullAmmo, MT2Extended::Commands::fullArmor, MT2Extended::Commands::fullHealth, MT2Extended::Commands::initializePlayer, instance, MT2Extended::Commands::newGameImmediate, MT2Extended::Commands::newGameReady, MT2Extended::Commands::pauseOrUnpause, MT2Extended::Commands::resetClock, MT2Extended::Commands::respawn, MT2Extended::Commands::restoreDefaults, MT2Extended::Commands::startGame, MT2Extended::Commands::stunPlayer, MT2Extended::Commands::testSensors, and UNUSED_ARG.
parseRCSP()
void IRPresentationReceiverMT2::parseRCSP (const uint8_t * data, uint16_t size) private
Definition at line 314 of file ir-presentation-mt2.cpp.
References PresentationReceiversGroupMT2::argumentBufferSize, debug, error, instance, and warning.
parseSetTeam()
void IRPresentationReceiverMT2::parseSetTeam (const uint8_t * data, uint16_t size) private
Definition at line 243 of file ir-presentation-mt2.cpp.
References instance, MT2Extended::Byte1::setTeam, UNUSED_ARG, and warning.
parseShot()
void IRPresentationReceiverMT2::parseShot (const uint8_t * data, uint16_t size) private
Definition at line 218 of file ir-presentation-mt2.cpp.
References ShotMessage::damage, instance, ShotMessage::playerId, MT2Extended::shotLength, ShotMessage::teamId, UNUSED_ARG, and warning.
receiverCallback()
void IRPresentationReceiverMT2::receiverCallback (const uint8_t * data, uint16_t size) private virtual
Implements IRPresentationReceiverBase.
Definition at line 171 of file ir-presentation-mt2.cpp.
References MT2Extended::Byte1::addHealth, MT2Extended::Byte1::command, MT2Extended::Byte3::commandEnd, MT2Extended::commandLength, debug, MT2Extended::messageLength, RCSPAggregator::minimalStreamSize, printHex(), MT2Extended::Byte1::RCSPMessage, MT2Extended::Byte1::setTeam, and MT2Extended::Byte1::shotMask.
setDamageCoefficient()
void IRPresentationReceiverMT2::setDamageCoefficient (const FloatParameter * coefficient) virtual
Implements IIRPresentationReceiver.
Definition at line 166 of file ir-presentation-mt2.cpp.
updateOperationCallback()
void IRPresentationReceiverMT2::updateOperationCallback (OperationCallback callback) private
Definition at line 368 of file ir-presentation-mt2.cpp.
References ISystemClock::getTime(), and systemClock.
Member Data Documentation
defaultDamageCoefficient
FloatParameter IRPresentationReceiverMT2::defaultDamageCoefficient = 1.0 static private
Definition at line 75 of file ir-presentation-mt2.hpp.
m_damageCoefficient
const FloatParameter* IRPresentationReceiverMT2::m_damageCoefficient = &defaultDamageCoefficient private
Definition at line 76 of file ir-presentation-mt2.hpp.
m_group
PresentationReceiversGroupMT2* IRPresentationReceiverMT2::m_group = nullptr private
Definition at line 74 of file ir-presentation-mt2.hpp.
m_vibroEnabledTime
Time IRPresentationReceiverMT2::m_vibroEnabledTime = 0 private
Definition at line 77 of file ir-presentation-mt2.hpp.
vibroPeriod
constexpr uint32_t IRPresentationReceiverMT2::vibroPeriod = 200000 static private
Definition at line 61 of file ir-presentation-mt2.hpp.
The documentation for this class was generated from the following files:
include/ir/ir-presentation-mt2.hpp
src/ir/ir-presentation-mt2.cpp