Caustic lasertag system: IInterrogatable Class Reference
IInterrogatable Class Reference abstract
#include <interfaces.hpp>
Public Member Functions
virtual ~IInterrogatable ()
virtual void interrogate ()=0
Detailed Description
Definition at line 28 of file interfaces.hpp.
Constructor & Destructor Documentation
~IInterrogatable()
virtual IInterrogatable::~IInterrogatable () inline virtual
Definition at line 31 of file interfaces.hpp.
References interrogate().
Member Function Documentation
interrogate()
virtual void IInterrogatable::interrogate () pure virtual
Implemented in PresentationReceiversGroupMT2, NRF24L01Manager, IRReceiverTV, IRPresentationReceiverMT2, ButtonManager, PowerMonitor, and RC552Wrapper.
Referenced by NetworkLayer::interrogate(), and ~IInterrogatable().
The documentation for this class was generated from the following file:
include/utils/interfaces.hpp