Caustic lasertag system: StagerStub Class Reference
StagerStub Class Reference
#include <diagnostic.hpp>
Public Member Functions
StagerStub (const char *name="", Time aliveCheckPeriod=0)
void stage (const char *description)
void setName (const char *name)
void printStages () const
Detailed Description
Definition at line 41 of file diagnostic.hpp.
Constructor & Destructor Documentation
StagerStub()
StagerStub::StagerStub (const char * name = "", Time aliveCheckPeriod = 0) inline
Definition at line 44 of file diagnostic.hpp.
References UNUSED_ARG.
Member Function Documentation
printStages()
void StagerStub::printStages () const inline
Definition at line 47 of file diagnostic.hpp.
setName()
void StagerStub::setName (const char * name) inline
Definition at line 46 of file diagnostic.hpp.
References UNUSED_ARG.
stage()
void StagerStub::stage (const char * description) inline
Definition at line 45 of file diagnostic.hpp.
References UNUSED_ARG.
Referenced by SPIManager::init(), SPIManager::Receive(), SPIManager::Transmit(), and SPIManager::TransmitReceive().
The documentation for this class was generated from the following file:
include/core/diagnostic.hpp