Caustic lasertag system: RifleLCD5110Display Class Reference
RifleLCD5110Display Class Reference
#include <rifle-display.hpp>
Public Member Functions
RifleLCD5110Display (const RifleOwnerConfiguration *owner, const RifleState *state, const PlayerPartialState *playerState)
void init ()
void update ()
Private Attributes
LCD5110Controller m_lcd
const RifleOwnerConfiguration * m_owner
const RifleState * m_state
const PlayerPartialState * m_playerState
Detailed Description
Definition at line 31 of file rifle-display.hpp.
Constructor & Destructor Documentation
RifleLCD5110Display()
RifleLCD5110Display::RifleLCD5110Display (const RifleOwnerConfiguration * owner, const RifleState * state, const PlayerPartialState * playerState)
Definition at line 29 of file rifle-display.cpp.
Member Function Documentation
init()
void RifleLCD5110Display::init ()
Definition at line 36 of file rifle-display.cpp.
update()
void RifleLCD5110Display::update ()
Definition at line 57 of file rifle-display.cpp.
References LCD5110Controller::clearBuffer(), LCD5110Controller::configureSPI(), LCD5110Controller::fontStandardAscii5x7, RifleState::isHSConnected, m_lcd, m_playerState, m_state, LCD5110Controller::setFont(), LCD5110Controller::stringXY(), and LCD5110Controller::write().
Member Data Documentation
m_lcd
LCD5110Controller RifleLCD5110Display::m_lcd private
Definition at line 39 of file rifle-display.hpp.
Referenced by update().
m_owner
const RifleOwnerConfiguration* RifleLCD5110Display::m_owner private
Definition at line 40 of file rifle-display.hpp.
m_playerState
const PlayerPartialState* RifleLCD5110Display::m_playerState private
Definition at line 42 of file rifle-display.hpp.
Referenced by update().
m_state
const RifleState* RifleLCD5110Display::m_state private
Definition at line 41 of file rifle-display.hpp.
Referenced by update().
The documentation for this class was generated from the following files:
include/rifle/rifle-display.hpp
src/rifle/rifle-display.cpp