Caustic lasertag system: NetworkLayer Class Reference
NetworkLayer Class Reference
#include <network-layer.hpp>
Classes
struct AckPayload
struct WaitingPackage
Public Types
using RadioReinitCallback = std::function< void(IRadioPhysicalDevice *rfPhysicalDevice)>
Public Member Functions
NetworkLayer ()
~NetworkLayer ()
void init (IRadioPhysicalDevice *rfPhysicalDevice)
void setAddress (const DeviceAddress &address)
void setPackageReceiver (ReceivePackageCallback callback)
void setRadioReinitCallback (RadioReinitCallback callback)
PackageId send (DeviceAddress target, uint8_t *data, uint16_t size, bool waitForAck=false, PackageSendingDoneCallback doneCallback=nullptr, PackageTimings timings=PackageTimings())
bool stopSending (PackageId packageId)
void dropAllForAddress (const DeviceAddress &address)
bool updateTimeout (PackageId packageId)
void registerBroadcast (const DeviceAddress &address)
void registerBroadcastTester (Broadcast::IBroadcastTester *tester)
void enableRegularNRFReinit (bool enabled=true)
void enableDebug (bool debug=true)
SIGLETON_IN_CLASS (NetworkLayer)
Static Public Attributes
static constexpr uint32_t defaultTimeout = 20000000
static constexpr uint32_t defaultResendTime = 300000
static constexpr uint32_t defaultResendTimeDelta = 300000
Private Member Functions
void interrogate ()
uint16_t generatePackageId ()
void TXDoneCallback ()
void RXCallback (uint8_t channel, uint8_t *data)
void sendNext ()
void receiveIncoming ()
bool checkIfIdStoredAndStore (uint16_t id)
bool isTranslationAllowed ()
void temproraryProhibitTransmission (uint32_t delay)
bool isBroadcast (const DeviceAddress &addr)
void printAndSend (Package &package)
void reinitNRF ()
Private Attributes
Time m_transmissionProhibitedTime = 0
Time m_transmissionProhibitionPeriod = 0
uint16_t currentlySendingPackageId = 0
bool isSendingNow = false
Mutex m_packagesQueueMutex
std::list< Package > m_packagesNoAck
IRadioPhysicalDevice * m_rfPhysicalDevice = nullptr
std::map< PackageId, WaitingPackage > m_packages
std::list< Package > m_incoming
std::list< PackageId > m_lastReceivedIds
std::set< DeviceAddress > m_broadcasts
std::list< Broadcast::IBroadcastTester * > m_broadcastTesters
const DeviceAddress * m_selfAddress = nullptr
ReceivePackageCallback m_receivePackageCallback = nullptr
TaskCycled m_modemTask {std::bind(&NetworkLayer::interrogate, this)}
bool m_regularNRFReinit = false
bool m_debug = false
Time m_lastNRFReinitializationTime = 0
RadioReinitCallback m_radioReinitCallback = nullptr
Stager m_stager {"Network layer", 5000000}
Static Private Attributes
static constexpr uint32_t lastReceivedIdsBufferSize = 30
static constexpr uint32_t NRFReinitPeriod = 5000000
Detailed Description
Definition at line 78 of file network-layer.hpp.
Member Typedef Documentation
RadioReinitCallback
using NetworkLayer::RadioReinitCallback = std::function<void(IRadioPhysicalDevice* rfPhysicalDevice)>
Definition at line 81 of file network-layer.hpp.
Constructor & Destructor Documentation
NetworkLayer()
NetworkLayer::NetworkLayer ()
Definition at line 76 of file network-layer.cpp.
References interrogate(), m_modemTask, TaskBase::setName(), TaskBase::setStackSize(), and TaskBase::setTask().
~NetworkLayer()
NetworkLayer::~NetworkLayer ()
Definition at line 83 of file network-layer.cpp.
References m_broadcastTesters.
Member Function Documentation
checkIfIdStoredAndStore()
bool NetworkLayer::checkIfIdStoredAndStore (uint16_t id) private
Definition at line 293 of file network-layer.cpp.
References lastReceivedIdsBufferSize, and m_lastReceivedIds.
Referenced by RXCallback().
dropAllForAddress()
void NetworkLayer::dropAllForAddress (const DeviceAddress & address)
Definition at line 488 of file network-layer.cpp.
References m_packages, and m_packagesQueueMutex.
enableDebug()
void NetworkLayer::enableDebug (bool debug = true)
Definition at line 136 of file network-layer.cpp.
References debug, and m_debug.
enableRegularNRFReinit()
void NetworkLayer::enableRegularNRFReinit (bool enabled = true)
Definition at line 131 of file network-layer.cpp.
References m_regularNRFReinit.
generatePackageId()
uint16_t NetworkLayer::generatePackageId () private
Definition at line 141 of file network-layer.cpp.
References ISystemClock::getTime(), and systemClock.
Referenced by RXCallback(), and send().
init()
void NetworkLayer::init (IRadioPhysicalDevice * rfPhysicalDevice)
Definition at line 107 of file network-layer.cpp.
References info, instance, m_modemTask, m_receivePackageCallback, m_rfPhysicalDevice, m_selfAddress, TaskCycled::run(), RXCallback(), IRadioPhysicalDevice::setDataReceiveCallback(), IRadioPhysicalDevice::setTXDoneCallback(), and TXDoneCallback().
interrogate()
void NetworkLayer::interrogate () private
Todo:
Remove comment below after some time
Definition at line 308 of file network-layer.cpp.
References debug, ISystemClock::getTime(), IInterrogatable::interrogate(), m_debug, m_lastNRFReinitializationTime, m_regularNRFReinit, m_rfPhysicalDevice, m_stager, NRFReinitPeriod, IRadioPhysicalDevice::printStatus(), receiveIncoming(), reinitNRF(), sendNext(), Stager::stage(), and systemClock.
Referenced by NetworkLayer().
isBroadcast()
bool NetworkLayer::isBroadcast (const DeviceAddress & addr) private
Definition at line 455 of file network-layer.cpp.
References m_broadcasts, and m_broadcastTesters.
Referenced by RXCallback().
isTranslationAllowed()
bool NetworkLayer::isTranslationAllowed () private
Definition at line 434 of file network-layer.cpp.
References ISystemClock::getTime(), isSendingNow, m_transmissionProhibitedTime, m_transmissionProhibitionPeriod, and systemClock.
Referenced by sendNext().
printAndSend()
void NetworkLayer::printAndSend (Package & package) private
Definition at line 465 of file network-layer.cpp.
References Logger::isEnabled(), m_rfPhysicalDevice, m_stager, Package::packageLength, printHex(), radio, IRadioPhysicalDevice::sendData(), Stager::stage(), and trace.
Referenced by sendNext().
receiveIncoming()
void NetworkLayer::receiveIncoming () private
Todo:
[Refactoring] Remove stream from there
Definition at line 409 of file network-layer.cpp.
References ADDRESS_TO_STREAM, m_incoming, m_receivePackageCallback, and radio.
Referenced by interrogate().
registerBroadcast()
void NetworkLayer::registerBroadcast (const DeviceAddress & address)
Definition at line 121 of file network-layer.cpp.
References m_broadcasts.
registerBroadcastTester()
void NetworkLayer::registerBroadcastTester (Broadcast::IBroadcastTester * tester)
Definition at line 126 of file network-layer.cpp.
References m_broadcastTesters.
reinitNRF()
void NetworkLayer::reinitNRF () private
Todo:
Remove this function after some time
Todo:
Remove this code after some time
Definition at line 515 of file network-layer.cpp.
References m_radioReinitCallback, m_rfPhysicalDevice, TXDoneCallback(), and warning.
Referenced by interrogate().
RXCallback()
void NetworkLayer::RXCallback (uint8_t channel, uint8_t * data) private
Definition at line 220 of file network-layer.cpp.
References ADDRESS_TO_STREAM, checkIfIdStoredAndStore(), Package::details, generatePackageId(), NetworkLayer::AckPayload::isAck(), isBroadcast(), Logger::isEnabled(), m_incoming, m_packages, m_packagesNoAck, m_packagesQueueMutex, m_selfAddress, m_stager, PackageDetails::needAck, PackageDetails::packageId, NetworkLayer::AckPayload::packageId, Package::payload, Package::payloadLength, printHex(), radio, Package::sender, Stager::stage(), Package::target, temproraryProhibitTransmission(), trace, and UNUSED_ARG.
Referenced by init().
send()
PackageId NetworkLayer::send (DeviceAddress target, uint8_t * data, uint16_t size, bool waitForAck = false, PackageSendingDoneCallback doneCallback = nullptr, PackageTimings timings = PackageTimings())
Send package and optionaly wait for acknowledgement
Parameters
target Target device address
data Payload
size Payload's size
waitForAck Need waiting for acknoledgement
doneCallback Function to call after sending done
timings Timings for package
Returns
Todo:
Check package zerification!
Definition at line 150 of file network-layer.cpp.
References broadcast, NetworkLayer::WaitingPackage::callback, Package::details, error, generatePackageId(), ISystemClock::getTime(), Broadcast::isBroadcast(), NetworkLayer::WaitingPackage::isBroadcast, m_packages, m_packagesNoAck, m_packagesQueueMutex, m_selfAddress, m_stager, PackageDetails::needAck, NetworkLayer::WaitingPackage::nextTransmission, NetworkLayer::WaitingPackage::package, PackageDetails::packageId, Package::payload, Package::payloadLength, Package::sender, Stager::stage(), systemClock, Package::target, NetworkLayer::WaitingPackage::timings, and NetworkLayer::WaitingPackage::wasCreated.
sendNext()
void NetworkLayer::sendNext () private
Definition at line 345 of file network-layer.cpp.
References ADDRESS_TO_STREAM, currentlySendingPackageId, ISystemClock::getTime(), NetworkLayer::AckPayload::isAck(), isSendingNow, isTranslationAllowed(), m_packages, m_packagesNoAck, m_packagesQueueMutex, m_stager, NetworkLayer::AckPayload::packageId, printAndSend(), radio, Random::random(), Stager::stage(), and systemClock.
Referenced by interrogate().
setAddress()
void NetworkLayer::setAddress (const DeviceAddress & address)
Definition at line 92 of file network-layer.cpp.
References m_selfAddress.
setPackageReceiver()
void NetworkLayer::setPackageReceiver (ReceivePackageCallback callback)
Definition at line 97 of file network-layer.cpp.
References m_receivePackageCallback.
setRadioReinitCallback()
void NetworkLayer::setRadioReinitCallback (RadioReinitCallback callback)
Definition at line 102 of file network-layer.cpp.
References m_radioReinitCallback.
SIGLETON_IN_CLASS()
NetworkLayer::SIGLETON_IN_CLASS (NetworkLayer)
stopSending()
bool NetworkLayer::stopSending (PackageId packageId)
Definition at line 476 of file network-layer.cpp.
References m_packages, and m_packagesQueueMutex.
temproraryProhibitTransmission()
void NetworkLayer::temproraryProhibitTransmission (uint32_t delay) private
This variable might be optimized. This value means time delay between last receiving and first transmission.
4000 is too small even for two devices in network: at least some acks does not reach 8000 is enough, but may be too large
Definition at line 442 of file network-layer.cpp.
References ISystemClock::getTime(), m_transmissionProhibitedTime, m_transmissionProhibitionPeriod, and systemClock.
Referenced by RXCallback(), and TXDoneCallback().
TXDoneCallback()
void NetworkLayer::TXDoneCallback () private
be shure that this line improve stability or remove it
Definition at line 213 of file network-layer.cpp.
References isSendingNow, and temproraryProhibitTransmission().
Referenced by init(), and reinitNRF().
updateTimeout()
bool NetworkLayer::updateTimeout (PackageId packageId)
Definition at line 501 of file network-layer.cpp.
References ISystemClock::getTime(), m_packages, m_packagesQueueMutex, and systemClock.
Member Data Documentation
currentlySendingPackageId
uint16_t NetworkLayer::currentlySendingPackageId = 0 private
Definition at line 175 of file network-layer.hpp.
Referenced by sendNext().
defaultResendTime
constexpr uint32_t NetworkLayer::defaultResendTime = 300000 static
Definition at line 83 of file network-layer.hpp.
defaultResendTimeDelta
constexpr uint32_t NetworkLayer::defaultResendTimeDelta = 300000 static
Definition at line 84 of file network-layer.hpp.
defaultTimeout
constexpr uint32_t NetworkLayer::defaultTimeout = 20000000 static
Definition at line 82 of file network-layer.hpp.
isSendingNow
bool NetworkLayer::isSendingNow = false private
Definition at line 176 of file network-layer.hpp.
Referenced by isTranslationAllowed(), sendNext(), and TXDoneCallback().
lastReceivedIdsBufferSize
constexpr uint32_t NetworkLayer::lastReceivedIdsBufferSize = 30 static private
Definition at line 154 of file network-layer.hpp.
Referenced by checkIfIdStoredAndStore().
m_broadcasts
std::set<DeviceAddress> NetworkLayer::m_broadcasts private
Definition at line 188 of file network-layer.hpp.
Referenced by isBroadcast(), and registerBroadcast().
m_broadcastTesters
std::list<Broadcast::IBroadcastTester*> NetworkLayer::m_broadcastTesters private
Definition at line 189 of file network-layer.hpp.
Referenced by isBroadcast(), registerBroadcastTester(), and ~NetworkLayer().
m_debug
bool NetworkLayer::m_debug = false private
Definition at line 197 of file network-layer.hpp.
Referenced by enableDebug(), and interrogate().
m_incoming
std::list<Package> NetworkLayer::m_incoming private
Definition at line 184 of file network-layer.hpp.
Referenced by receiveIncoming(), and RXCallback().
m_lastNRFReinitializationTime
Time NetworkLayer::m_lastNRFReinitializationTime = 0 private
Definition at line 198 of file network-layer.hpp.
Referenced by interrogate().
m_lastReceivedIds
std::list<PackageId> NetworkLayer::m_lastReceivedIds private
Definition at line 186 of file network-layer.hpp.
Referenced by checkIfIdStoredAndStore().
m_modemTask
TaskCycled NetworkLayer::m_modemTask {std::bind(&NetworkLayer::interrogate, this)} private
Definition at line 194 of file network-layer.hpp.
Referenced by init(), and NetworkLayer().
m_packages
std::map<PackageId, WaitingPackage> NetworkLayer::m_packages private
Definition at line 182 of file network-layer.hpp.
Referenced by dropAllForAddress(), RXCallback(), send(), sendNext(), stopSending(), and updateTimeout().
m_packagesNoAck
std::list<Package> NetworkLayer::m_packagesNoAck private
Definition at line 178 of file network-layer.hpp.
Referenced by RXCallback(), send(), and sendNext().
m_packagesQueueMutex
Mutex NetworkLayer::m_packagesQueueMutex private
Definition at line 177 of file network-layer.hpp.
Referenced by dropAllForAddress(), RXCallback(), send(), sendNext(), stopSending(), and updateTimeout().
m_radioReinitCallback
RadioReinitCallback NetworkLayer::m_radioReinitCallback = nullptr private
Definition at line 200 of file network-layer.hpp.
Referenced by reinitNRF(), and setRadioReinitCallback().
m_receivePackageCallback
ReceivePackageCallback NetworkLayer::m_receivePackageCallback = nullptr private
Definition at line 192 of file network-layer.hpp.
Referenced by init(), receiveIncoming(), and setPackageReceiver().
m_regularNRFReinit
bool NetworkLayer::m_regularNRFReinit = false private
Definition at line 196 of file network-layer.hpp.
Referenced by enableRegularNRFReinit(), and interrogate().
m_rfPhysicalDevice
IRadioPhysicalDevice* NetworkLayer::m_rfPhysicalDevice = nullptr private
Definition at line 180 of file network-layer.hpp.
Referenced by init(), interrogate(), printAndSend(), and reinitNRF().
m_selfAddress
const DeviceAddress* NetworkLayer::m_selfAddress = nullptr private
Definition at line 191 of file network-layer.hpp.
Referenced by init(), RXCallback(), send(), and setAddress().
m_stager
Stager NetworkLayer::m_stager {"Network layer", 5000000} private
Definition at line 202 of file network-layer.hpp.
Referenced by interrogate(), printAndSend(), RXCallback(), send(), and sendNext().
m_transmissionProhibitedTime
Time NetworkLayer::m_transmissionProhibitedTime = 0 private
Definition at line 172 of file network-layer.hpp.
Referenced by isTranslationAllowed(), and temproraryProhibitTransmission().
m_transmissionProhibitionPeriod
Time NetworkLayer::m_transmissionProhibitionPeriod = 0 private
Definition at line 173 of file network-layer.hpp.
Referenced by isTranslationAllowed(), and temproraryProhibitTransmission().
NRFReinitPeriod
constexpr uint32_t NetworkLayer::NRFReinitPeriod = 5000000 static private
Definition at line 155 of file network-layer.hpp.
Referenced by interrogate().
The documentation for this class was generated from the following files:
include/network/network-layer.hpp
src/network/network-layer.cpp