Caustic lasertag system: WavPlayer Class Reference
WavPlayer Class Reference
#include <wav-player.hpp>
Classes
struct ChannelContext
struct WavHeader
Public Member Functions
WavPlayer ()
~WavPlayer ()
void init ()
Result play (const char *fileName, uint8_t channel)
Static Public Attributes
static constexpr uint32_t audioBufferSize = 1000
static constexpr uint8_t channelsCount = 2
Private Member Functions
bool openFile (uint8_t channel)
void fragmentDoneCallback (SoundSample *oldBuffer)
bool loadFragment (SoundSample *buffer, uint8_t channel)
void loader ()
void silenceToBuffer (SoundSample *buffer)
Private Attributes
SoundSample * m_buffer1 = nullptr
SoundSample * m_buffer2 = nullptr
SoundSample * m_currentBuffer
SoundSample * m_nextBuffer
SoundSample * m_tempBuffer = nullptr
ChannelContext m_contexts [channelsCount]
bool m_fragmentPlayerReady = false
Worker m_loader {10}
Detailed Description
Definition at line 35 of file wav-player.hpp.
Constructor & Destructor Documentation
WavPlayer()
WavPlayer::WavPlayer ()
Definition at line 34 of file wav-player.cpp.
References debug, and trace.
~WavPlayer()
WavPlayer::~WavPlayer ()
Definition at line 56 of file wav-player.cpp.
References m_buffer1, m_buffer2, and m_tempBuffer.
Member Function Documentation
fragmentDoneCallback()
void WavPlayer::fragmentDoneCallback (SoundSample * oldBuffer) private
Definition at line 135 of file wav-player.cpp.
References Worker::addFromISR(), channelsCount, fragmentPlayer, loadFragment(), m_currentBuffer, m_loader, m_nextBuffer, IFragmentPlayer::playFragment(), silenceToBuffer(), and UNUSED_ARG.
Referenced by init().
init()
void WavPlayer::init ()
Definition at line 64 of file wav-player.cpp.
References audioBufferSize, fragmentDoneCallback(), fragmentPlayer, IFragmentPlayer::init(), m_currentBuffer, m_loader, m_nextBuffer, Worker::run(), IFragmentPlayer::setFragmentDoneCallback(), IFragmentPlayer::setFragmentSize(), and silenceToBuffer().
loader()
void WavPlayer::loader () private
This function is a queue-listener. It perform sound fragments loading, buffer cleaning and any other job related to audio buffer prepairing
loadFragment()
bool WavPlayer::loadFragment (SoundSample * buffer, uint8_t channel) private
Todo:
increase blockSize to maximum
Definition at line 198 of file wav-player.cpp.
References audioBufferSize, error, f_read_huge(), WavPlayer::ChannelContext::fileIsOpened, m_contexts, m_tempBuffer, parseFRESULT(), and WavPlayer::ChannelContext::totalReaded.
Referenced by fragmentDoneCallback(), and openFile().
openFile()
bool WavPlayer::openFile (uint8_t channel) private
Definition at line 84 of file wav-player.cpp.
References debug, error, WavPlayer::ChannelContext::fileIsOpened, loadFragment(), m_contexts, m_nextBuffer, parseFRESULT(), and WavPlayer::ChannelContext::totalReaded.
Referenced by play().
play()
Result WavPlayer::play (const char * fileName, uint8_t channel)
Definition at line 118 of file wav-player.cpp.
References Worker::add(), WavPlayer::ChannelContext::filename, fragmentPlayer, m_contexts, m_currentBuffer, m_fragmentPlayerReady, m_loader, openFile(), and IFragmentPlayer::playFragment().
silenceToBuffer()
void WavPlayer::silenceToBuffer (SoundSample * buffer) private
Definition at line 77 of file wav-player.cpp.
References audioBufferSize.
Referenced by fragmentDoneCallback(), and init().
Member Data Documentation
audioBufferSize
constexpr uint32_t WavPlayer::audioBufferSize = 1000 static
Definition at line 38 of file wav-player.hpp.
Referenced by init(), loadFragment(), and silenceToBuffer().
channelsCount
constexpr uint8_t WavPlayer::channelsCount = 2 static
Definition at line 39 of file wav-player.hpp.
Referenced by fragmentDoneCallback().
m_buffer1
SoundSample* WavPlayer::m_buffer1 = nullptr private
Definition at line 89 of file wav-player.hpp.
Referenced by ~WavPlayer().
m_buffer2
SoundSample * WavPlayer::m_buffer2 = nullptr private
Definition at line 89 of file wav-player.hpp.
Referenced by ~WavPlayer().
m_contexts
ChannelContext WavPlayer::m_contexts[channelsCount] private
Definition at line 92 of file wav-player.hpp.
Referenced by loadFragment(), openFile(), and play().
m_currentBuffer
SoundSample* WavPlayer::m_currentBuffer private
Definition at line 90 of file wav-player.hpp.
Referenced by fragmentDoneCallback(), init(), and play().
m_fragmentPlayerReady
bool WavPlayer::m_fragmentPlayerReady = false private
Definition at line 94 of file wav-player.hpp.
Referenced by play().
m_loader
Worker WavPlayer::m_loader {10} private
Definition at line 96 of file wav-player.hpp.
Referenced by fragmentDoneCallback(), init(), and play().
m_nextBuffer
SoundSample * WavPlayer::m_nextBuffer private
Definition at line 90 of file wav-player.hpp.
Referenced by fragmentDoneCallback(), init(), and openFile().
m_tempBuffer
SoundSample* WavPlayer::m_tempBuffer = nullptr private
Definition at line 91 of file wav-player.hpp.
Referenced by loadFragment(), and ~WavPlayer().
The documentation for this class was generated from the following files:
include/dev/wav-player.hpp
src/dev/wav-player.cpp