Caustic lasertag system: RifleConfiguration Class Reference
RifleConfiguration Class Reference
#include <rifle-config-and-state.hpp>
Public Member Functions
RifleConfiguration ()
void setDefault ()
bool isAutoReloading ()
bool isReloadingByDistortingTheBolt ()
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, slot)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, weightInSlot)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, damageMin)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, damageMax)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, firePeriod)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, shotDelay)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, jamProb)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, criticalProb)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, criticalCoeff)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, semiAutomaticAllowed)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, automaticAllowed)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadIsMagazineSmart)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadNeedMagDisconnect)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadNeedMagChange)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadNeedBolt)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadPlaySound)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, magazinesCountStart)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, magazinesCountMax)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, bulletsInMagazineStart)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, bulletsInMagazineMax)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, reloadingTime)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, heatPerShot)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, heatLossPerSec)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, fireFlashPeriod)
PAR_ST (NOT_RESTORABLE, ConfigCodes::Rifle::Configuration, fireVibroPeriod)
PAR_CL (RESTORABLE, ConfigCodes::Rifle::Configuration, headSensorAddr)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::Configuration, outputPower)
Detailed Description
Definition at line 41 of file rifle-config-and-state.hpp.
Constructor & Destructor Documentation
RifleConfiguration()
RifleConfiguration::RifleConfiguration ()
Definition at line 101 of file rifle.cpp.
Member Function Documentation
isAutoReloading()
bool RifleConfiguration::isAutoReloading ()
Definition at line 106 of file rifle.cpp.
References ConfigCodes::Rifle::Configuration::reloadIsMagazineSmart, and ConfigCodes::Rifle::Configuration::reloadNeedMagChange.
Referenced by Rifle::detectRifleState(), Rifle::init(), and Rifle::makeShot().
isReloadingByDistortingTheBolt()
bool RifleConfiguration::isReloadingByDistortingTheBolt ()
Definition at line 114 of file rifle.cpp.
References ConfigCodes::Rifle::Configuration::reloadNeedMagChange.
Referenced by Rifle::detectRifleState(), Rifle::distortBolt(), and Rifle::init().
PAR_CL()
RifleConfiguration::PAR_CL (RESTORABLE , ConfigCodes::Rifle::Configuration , headSensorAddr)
PAR_ST() [1/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , slot)
PAR_ST() [2/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , weightInSlot)
PAR_ST() [3/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , damageMin)
PAR_ST() [4/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , damageMax)
PAR_ST() [5/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , firePeriod)
PAR_ST() [6/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , shotDelay)
PAR_ST() [7/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , jamProb)
PAR_ST() [8/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , criticalProb)
PAR_ST() [9/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , criticalCoeff)
PAR_ST() [10/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , semiAutomaticAllowed)
PAR_ST() [11/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , automaticAllowed)
PAR_ST() [12/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadIsMagazineSmart)
PAR_ST() [13/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadNeedMagDisconnect)
PAR_ST() [14/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadNeedMagChange)
PAR_ST() [15/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadNeedBolt)
PAR_ST() [16/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadPlaySound)
PAR_ST() [17/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , magazinesCountStart)
PAR_ST() [18/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , magazinesCountMax)
PAR_ST() [19/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , bulletsInMagazineStart)
PAR_ST() [20/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , bulletsInMagazineMax)
PAR_ST() [21/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , reloadingTime)
PAR_ST() [22/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , heatPerShot)
PAR_ST() [23/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , heatLossPerSec)
PAR_ST() [24/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , fireFlashPeriod)
PAR_ST() [25/26]
RifleConfiguration::PAR_ST (NOT_RESTORABLE , ConfigCodes::Rifle::Configuration , fireVibroPeriod)
PAR_ST() [26/26]
RifleConfiguration::PAR_ST (RESTORABLE , ConfigCodes::Rifle::Configuration , outputPower)
setDefault()
void RifleConfiguration::setDefault ()
Definition at line 121 of file rifle.cpp.
References ConfigCodes::Rifle::Configuration::reloadIsMagazineSmart, ConfigCodes::Rifle::Configuration::reloadNeedMagChange, and ConfigCodes::Rifle::Configuration::reloadPlaySound.
The documentation for this class was generated from the following files:
include/rifle/rifle-config-and-state.hpp
src/rifle/rifle.cpp