Caustic lasertag system: IAnyDevice Class Reference
IAnyDevice Class Reference abstract
#include <device-initializer.hpp>
Public Member Functions
virtual ~IAnyDevice ()
virtual void init (const Pinout &pinout)=0
virtual void setDafaultPinout (Pinout &pinout)=0
virtual bool checkPinout (const Pinout &pinout)=0
Detailed Description
Definition at line 31 of file device-initializer.hpp.
Constructor & Destructor Documentation
~IAnyDevice()
virtual IAnyDevice::~IAnyDevice () inline virtual
Definition at line 34 of file device-initializer.hpp.
References checkPinout(), init(), and setDafaultPinout().
Member Function Documentation
checkPinout()
virtual bool IAnyDevice::checkPinout (const Pinout & pinout) pure virtual
Implemented in HeadSensor, Rifle, BluetoothBridge, and SmartPoint.
Referenced by DeviceInitializer::initDevice(), and ~IAnyDevice().
init()
virtual void IAnyDevice::init (const Pinout & pinout) pure virtual
Implemented in HeadSensor, Rifle, BluetoothBridge, and SmartPoint.
Referenced by DeviceInitializer::initDevice(), and ~IAnyDevice().
setDafaultPinout()
virtual void IAnyDevice::setDafaultPinout (Pinout & pinout) pure virtual
Implemented in HeadSensor, Rifle, BluetoothBridge, and SmartPoint.
Referenced by DeviceInitializer::initDevice(), and ~IAnyDevice().
The documentation for this class was generated from the following file:
include/core/device-initializer.hpp