Caustic lasertag system: HeadSensor Class Reference
HeadSensor Class Reference
#include <head-sensor.hpp>
Classes
class TeamBroadcastTester
Public Member Functions
HeadSensor ()
void init (const Pinout &pinout) override
void setDafaultPinout (Pinout &pinout) override
bool checkPinout (const Pinout &pinout) override
FUNCTION_NP (ConfigCodes::HeadSensor::Functions, HeadSensor, playerRespawn)
FUNCTION_NP (ConfigCodes::HeadSensor::Functions, HeadSensor, playerReset)
FUNCTION_NP (ConfigCodes::HeadSensor::Functions, HeadSensor, playerKill)
FUNCTION_NP (ConfigCodes::HeadSensor::Functions, HeadSensor, resetStats)
FUNCTION_NP (ConfigCodes::HeadSensor::Functions, HeadSensor, readStats)
FUNCTION_NP (ConfigCodes::AnyDevice::Functions, HeadSensor, resetToDefaults)
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, registerWeapon)
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, deregisterWeapon)
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, setTeam)
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, addMaxHealth)
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, notifyIsDamager)
Feedback when player was damaged or killed.
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, HeadSensor, catchShot)
Replacement for receive shot callback.
Public Member Functions inherited from IAnyDevice
virtual ~IAnyDevice ()
Public Attributes
DeviceConfiguration deviceConfig
PlayerConfiguration playerConfig
PlayerState playerState {&playerConfig}
Private Member Functions
void testDie (const char *)
void dieWeapons ()
void respawnWeapons ()
void turnOffWeapons ()
void notifyDamager (PlayerGameId player, uint8_t damagerTeam, uint8_t state=0)
void weaponWoundAndShock ()
void setFRIDToWriteAddr ()
void sendHeartbeat ()
Private Attributes
WeaponManagerFactory weaponManagerFactory
RGBLeds m_leds {playerConfig.teamId}
Time m_shockDelayBegin = 0
TasksPool m_tasksPool {"HStpool"}
IIRPhysicalReceiver * m_irPhysicalReceivers [killZonesCount]
IIRPresentationReceiver * m_irPresentationReceivers [killZonesCount]
IPresentationReceiversGroup * m_irPresentationReceiversGroup = nullptr
Interrogator m_killZonesInterogator
GameLog::BaseStatsCounter m_statsCounter {playerConfig.plyerMT2Id}
Stager m_taskPoolStager {"HS task pool"}
Stager m_callbackStager {"HS callbacks"}
RC552Wrapper m_mfrcWrapper
uint8_t m_RFIDWriteBuffer [RFIDWriteBufferSize]
Static Private Attributes
static constexpr uint32_t heartbeatPeriod = 2000000
static constexpr uint8_t killZonesCount = 6
static constexpr uint16_t RFIDWriteBufferSize = 16
Detailed Description
Definition at line 66 of file head-sensor.hpp.
Constructor & Destructor Documentation
HeadSensor()
HeadSensor::HeadSensor ()
Definition at line 106 of file head-sensor.cpp.
References DeviceTypes::headSensor.
Member Function Documentation
checkPinout()
bool HeadSensor::checkPinout (const Pinout & pinout) override virtual
Todo:
Add cheching here
Implements IAnyDevice.
Definition at line 607 of file head-sensor.cpp.
dieWeapons()
void HeadSensor::dieWeapons () private
Notifying weapons
Definition at line 402 of file head-sensor.cpp.
References WeaponManager::die(), and info.
FUNCTION_1P() [1/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , registerWeapon)
FUNCTION_1P() [2/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , deregisterWeapon)
FUNCTION_1P() [3/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , setTeam)
FUNCTION_1P() [4/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , addMaxHealth)
FUNCTION_1P() [5/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , notifyIsDamager)
Feedback when player was damaged or killed.
FUNCTION_1P() [6/6]
HeadSensor::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , HeadSensor , catchShot)
Replacement for receive shot callback.
FUNCTION_NP() [1/6]
HeadSensor::FUNCTION_NP (ConfigCodes::HeadSensor::Functions , HeadSensor , playerRespawn)
FUNCTION_NP() [2/6]
HeadSensor::FUNCTION_NP (ConfigCodes::HeadSensor::Functions , HeadSensor , playerReset)
FUNCTION_NP() [3/6]
HeadSensor::FUNCTION_NP (ConfigCodes::HeadSensor::Functions , HeadSensor , playerKill)
FUNCTION_NP() [4/6]
HeadSensor::FUNCTION_NP (ConfigCodes::HeadSensor::Functions , HeadSensor , resetStats)
FUNCTION_NP() [5/6]
HeadSensor::FUNCTION_NP (ConfigCodes::HeadSensor::Functions , HeadSensor , readStats)
FUNCTION_NP() [6/6]
HeadSensor::FUNCTION_NP (ConfigCodes::AnyDevice::Functions , HeadSensor , resetToDefaults)
init()
void HeadSensor::init (const Pinout & pinout) override virtual
Todo:
Add support for only red (and LED-less) devices
Implements IAnyDevice.
Definition at line 114 of file head-sensor.cpp.
References Broadcast::any, BlinkPatterns::anyCommand, blinkPatterns, broadcast, ShotMessage::damage, BlinkPatterns::death, debug, error, IIOPinsPool::getIOPin(), ISystemClock::getTime(), Broadcast::headSensors, info, HardwareInitializer::init(), BlinkPatterns::init, DamageNotification::injured, instance, IOPins, DamageNotification::killed, Pinout::PinDescr::pin, Pinout::pin, ShotMessage::playerId, Pinout::PinDescr::port, Pinout::port, BlinkPatterns::respawn, BlinkPatterns::respawnLimitIsOver, IRReceiverBase::setIOPin(), IRPresentationReceiverBase::setPhysicalReceiver(), systemClock, ShotMessage::teamId, warning, and BlinkPatterns::wound.
notifyDamager()
void HeadSensor::notifyDamager (PlayerGameId player, uint8_t damagerTeam, uint8_t state = 0) private
Definition at line 528 of file head-sensor.cpp.
References broadcast, DamageNotification::damagedTeam, DamageNotification::damager, HeadSensorPackageTimings::damagerNotificationBroadcast, NotificationSoundCase::friendInjured, headSensorPackageTimings, Broadcast::headSensors, info, RCSPStream::remoteCall(), sound, DamageNotification::state, DamageNotification::target, and UNUSED_ARG.
respawnWeapons()
void HeadSensor::respawnWeapons () private
Notifying weapons
Definition at line 414 of file head-sensor.cpp.
References info, and WeaponManager::respawn().
sendHeartbeat()
void HeadSensor::sendHeartbeat () private
Definition at line 451 of file head-sensor.cpp.
References RCSPStream::addCall(), ADDRESS_TO_STREAM, RCSPStream::addValue(), BlinkPatterns::anyCommand, blinkPatterns, debug, info, instance, RCSPStream::remotePullValue(), RCSPStream::send(), MT2Extended::Byte1::setTeam, and trace.
setDafaultPinout()
void HeadSensor::setDafaultPinout (Pinout & pinout) override virtual
Implements IAnyDevice.
Definition at line 588 of file head-sensor.cpp.
setFRIDToWriteAddr()
void HeadSensor::setFRIDToWriteAddr () private
Definition at line 565 of file head-sensor.cpp.
References BlinkPatterns::anyCommand, blinkPatterns, instance, and UNUSED_ARG.
testDie()
void HeadSensor::testDie (const char *) private
Definition at line 632 of file head-sensor.cpp.
turnOffWeapons()
void HeadSensor::turnOffWeapons () private
Definition at line 426 of file head-sensor.cpp.
References info, and RCSPStream::remoteCall().
weaponWoundAndShock()
void HeadSensor::weaponWoundAndShock () private
Definition at line 435 of file head-sensor.cpp.
References RCSPMultiStream::addCall(), RCSPMultiStream::addValue(), headSensorPackageTimings, info, RCSPMultiStream::send(), and HeadSensorPackageTimings::woundPlayer.
Member Data Documentation
deviceConfig
DeviceConfiguration HeadSensor::deviceConfig
Definition at line 74 of file head-sensor.hpp.
heartbeatPeriod
constexpr uint32_t HeadSensor::heartbeatPeriod = 2000000 static private
Definition at line 100 of file head-sensor.hpp.
killZonesCount
constexpr uint8_t HeadSensor::killZonesCount = 6 static private
Definition at line 102 of file head-sensor.hpp.
m_callbackStager
Stager HeadSensor::m_callbackStager {"HS callbacks"} private
Definition at line 145 of file head-sensor.hpp.
m_irPhysicalReceivers
IIRPhysicalReceiver* HeadSensor::m_irPhysicalReceivers[killZonesCount] private
Definition at line 137 of file head-sensor.hpp.
m_irPresentationReceivers
IIRPresentationReceiver* HeadSensor::m_irPresentationReceivers[killZonesCount] private
Definition at line 138 of file head-sensor.hpp.
m_irPresentationReceiversGroup
IPresentationReceiversGroup* HeadSensor::m_irPresentationReceiversGroup = nullptr private
Definition at line 139 of file head-sensor.hpp.
m_killZonesInterogator
Interrogator HeadSensor::m_killZonesInterogator private
Definition at line 141 of file head-sensor.hpp.
m_leds
RGBLeds HeadSensor::m_leds {playerConfig.teamId} private
Definition at line 118 of file head-sensor.hpp.
m_mfrcWrapper
RC552Wrapper HeadSensor::m_mfrcWrapper private
Definition at line 146 of file head-sensor.hpp.
m_RFIDWriteBuffer
uint8_t HeadSensor::m_RFIDWriteBuffer[RFIDWriteBufferSize] private
Definition at line 148 of file head-sensor.hpp.
m_shockDelayBegin
Time HeadSensor::m_shockDelayBegin = 0 private
Definition at line 121 of file head-sensor.hpp.
m_statsCounter
GameLog::BaseStatsCounter HeadSensor::m_statsCounter {playerConfig.plyerMT2Id} private
Definition at line 143 of file head-sensor.hpp.
m_taskPoolStager
Stager HeadSensor::m_taskPoolStager {"HS task pool"} private
Definition at line 144 of file head-sensor.hpp.
m_tasksPool
TasksPool HeadSensor::m_tasksPool {"HStpool"} private
Definition at line 122 of file head-sensor.hpp.
playerConfig
PlayerConfiguration HeadSensor::playerConfig
Definition at line 75 of file head-sensor.hpp.
playerState
PlayerState HeadSensor::playerState {&playerConfig}
Definition at line 76 of file head-sensor.hpp.
RFIDWriteBufferSize
constexpr uint16_t HeadSensor::RFIDWriteBufferSize = 16 static private
Definition at line 103 of file head-sensor.hpp.
weaponManagerFactory
WeaponManagerFactory HeadSensor::weaponManagerFactory private
Definition at line 116 of file head-sensor.hpp.
The documentation for this class was generated from the following files:
include/head-sensor/head-sensor.hpp
src/head-sensor/head-sensor.cpp