Caustic lasertag system: LCD5110Controller Class Reference
LCD5110Controller Class Reference
#include <lcd5110.hpp>
Classes
struct LcdIO
Public Member Functions
PAR_ST (RESTORABLE, ConfigCodes::AnyDevice::Configuration, lcdContrast)
LCD5110Controller ()
void configureSPI () override
void init (const LcdIO &io)
void line (uint8_t x1, uint8_t y1, uint8_t x2, uint8_t y2, uint8_t color)
void circle (uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
void fillCircle (uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
void rect (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
void fillRect (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
void rectLineShadow (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t tx, uint8_t ty, uint8_t color)
void stringXY (uint8_t x, uint8_t y, const char *c)
void barHorizontal (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void barVertical (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void setFont (uint8_t font)
void clearBuffer ()
void updateContrast ()
void write ()
Public Member Functions inherited from ISPIUser
virtual ~ISPIUser ()
Static Public Attributes
static constexpr uint8_t black = 1
static constexpr uint8_t white = 0
static constexpr uint8_t fontStandardAscii5x7 = 0
static constexpr uint8_t fontLiberationSans15x21Numbers = 1
Private Attributes
bool m_fontIsTiny = true
Detailed Description
Definition at line 32 of file lcd5110.hpp.
Constructor & Destructor Documentation
LCD5110Controller()
LCD5110Controller::LCD5110Controller ()
Definition at line 108 of file lcd5110.cpp.
Member Function Documentation
barHorizontal()
void LCD5110Controller::barHorizontal (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Definition at line 170 of file lcd5110.cpp.
barVertical()
void LCD5110Controller::barVertical (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Definition at line 175 of file lcd5110.cpp.
circle()
void LCD5110Controller::circle (uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
Definition at line 137 of file lcd5110.cpp.
clearBuffer()
void LCD5110Controller::clearBuffer ()
Definition at line 196 of file lcd5110.cpp.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
configureSPI()
void LCD5110Controller::configureSPI () override virtual
Implements ISPIUser.
Definition at line 113 of file lcd5110.cpp.
References ISPIManager::BaudRatePrescaler32, LCD5110Controller::LcdIO::chipEnable, ISPIManager::init(), LCD5110Controller::LcdIO::spi, and ISPIManager::SPIPhase2edge.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
fillCircle()
void LCD5110Controller::fillCircle (uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
Definition at line 142 of file lcd5110.cpp.
fillRect()
void LCD5110Controller::fillRect (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
Definition at line 152 of file lcd5110.cpp.
init()
void LCD5110Controller::init (const LcdIO & io)
Definition at line 118 of file lcd5110.cpp.
References fontStandardAscii5x7, glcd_init(), setFont(), and updateContrast().
line()
void LCD5110Controller::line (uint8_t x1, uint8_t y1, uint8_t x2, uint8_t y2, uint8_t color)
Definition at line 132 of file lcd5110.cpp.
PAR_ST()
LCD5110Controller::PAR_ST (RESTORABLE , ConfigCodes::AnyDevice::Configuration , lcdContrast)
rect()
void LCD5110Controller::rect (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
Definition at line 147 of file lcd5110.cpp.
rectLineShadow()
void LCD5110Controller::rectLineShadow (uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t tx, uint8_t ty, uint8_t color)
Definition at line 157 of file lcd5110.cpp.
setFont()
void LCD5110Controller::setFont (uint8_t font)
Definition at line 180 of file lcd5110.cpp.
References fontLiberationSans15x21Numbers, fontStandardAscii5x7, and m_fontIsTiny.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), init(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
stringXY()
void LCD5110Controller::stringXY (uint8_t x, uint8_t y, const char * c)
Definition at line 162 of file lcd5110.cpp.
References m_fontIsTiny.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
updateContrast()
void LCD5110Controller::updateContrast ()
Definition at line 127 of file lcd5110.cpp.
Referenced by UIInitScreen::doIteration(), and init().
write()
void LCD5110Controller::write ()
Definition at line 201 of file lcd5110.cpp.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
Member Data Documentation
black
constexpr uint8_t LCD5110Controller::black = 1 static
Definition at line 43 of file lcd5110.hpp.
fontLiberationSans15x21Numbers
constexpr uint8_t LCD5110Controller::fontLiberationSans15x21Numbers = 1 static
Definition at line 47 of file lcd5110.hpp.
Referenced by setFont().
fontStandardAscii5x7
constexpr uint8_t LCD5110Controller::fontStandardAscii5x7 = 0 static
Definition at line 46 of file lcd5110.hpp.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), init(), setFont(), SmartPointLCD5110Display::update(), and RifleLCD5110Display::update().
m_fontIsTiny
bool LCD5110Controller::m_fontIsTiny = true private
Definition at line 73 of file lcd5110.hpp.
Referenced by setFont(), and stringXY().
white
constexpr uint8_t LCD5110Controller::white = 0 static
Definition at line 44 of file lcd5110.hpp.
The documentation for this class was generated from the following files:
include/dev/lcd5110.hpp
src/dev/lcd5110.cpp