Caustic lasertag system: TaskOnce Class Reference
TaskOnce Class Reference
#include <os-wrappers.hpp>
Public Member Functions
TaskOnce (const STask &task=nullptr)
bool run (STime delay=0, osPriority priority=osPriorityNormal)
Public Member Functions inherited from TaskBase
TaskBase (const STask &task=nullptr, const char *name="Unknown")
bool isRunning () const
void deleteAfterRun (bool doDelete=true)
void setTask (const STask &_task)
void setStackSize (uint32_t stackSize)
void setName (const char *name)
STaskId taskId ()
bool safelyStop ()
void stopUnsafe ()
Static Private Member Functions
static void runTaskOnce (void const *pTask)
Private Attributes
STime m_firstRunDelay = 0
Additional Inherited Members
Protected Member Functions inherited from TaskBase
void stopThread ()
Protected Attributes inherited from TaskBase
STask m_task
uint32_t m_stackSize = 128
STaskId m_taskId = nullptr
uint8_t m_state = 0
char * m_name
Static Protected Attributes inherited from TaskBase
static constexpr uint8_t runningNow = 1
static constexpr uint8_t needDeleteSelf = 2
static constexpr uint8_t needStop = 4
static constexpr uint8_t executingNow = 8
Detailed Description
Definition at line 104 of file os-wrappers.hpp.
Constructor & Destructor Documentation
TaskOnce()
TaskOnce::TaskOnce (const STask & task = nullptr) inline
Definition at line 107 of file os-wrappers.hpp.
References Kernel::run().
Member Function Documentation
run()
bool TaskOnce::run (STime delay = 0, osPriority priority = osPriorityNormal)
Definition at line 157 of file os-wrappers.cpp.
References ADD_BITS, error, info, and REMOVE_BITS.
Referenced by Worker::run().
runTaskOnce()
void TaskOnce::runTaskOnce (void const * pTask) static private
Definition at line 63 of file os-wrappers.cpp.
References ADD_BITS, m_firstRunDelay, TaskBase::m_state, TaskBase::m_task, and TaskBase::stopThread().
Member Data Documentation
m_firstRunDelay
STime TaskOnce::m_firstRunDelay = 0 private
Definition at line 113 of file os-wrappers.hpp.
Referenced by runTaskOnce().
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp