Caustic lasertag system: RTCBase Class Reference
RTCBase Class Reference
#include <rtc.hpp>
Public Member Functions
void getDateTime (RTCDateTime &dateTime)
void setDateTime (const RTCDateTime &dateTime)
Public Member Functions inherited from IRTC
virtual ~IRTC ()
virtual void init ()=0
virtual void getDate (RTCDate &date)=0
virtual void setDate (const RTCDate &date)=0
virtual void getTime (RTCTime &time)=0
virtual void setTime (const RTCTime &time)=0
Detailed Description
Definition at line 46 of file rtc.hpp.
Member Function Documentation
getDateTime()
void RTCBase::getDateTime (RTCDateTime & dateTime) inline virtual
Implements IRTC.
Definition at line 49 of file rtc.hpp.
References RTCDateTime::date, IRTC::getDate(), IRTC::getTime(), and RTCDateTime::time.
setDateTime()
void RTCBase::setDateTime (const RTCDateTime & dateTime) inline virtual
Implements IRTC.
Definition at line 50 of file rtc.hpp.
References RTCDateTime::date, RTCManager, IRTC::setDate(), IRTC::setTime(), and RTCDateTime::time.
The documentation for this class was generated from the following file:
include/hal/rtc.hpp