Caustic lasertag system: ISystemClock Class Reference
ISystemClock Class Reference abstract
#include <system-clock.hpp>
Public Member Functions
virtual ~ISystemClock ()
virtual void wait_us (uint32_t time)=0
virtual void init ()=0
virtual Time getTime ()=0
Detailed Description
Definition at line 31 of file system-clock.hpp.
Constructor & Destructor Documentation
~ISystemClock()
virtual ISystemClock::~ISystemClock () inline virtual
Definition at line 34 of file system-clock.hpp.
References getTime(), init(), systemClock, and wait_us().
Member Function Documentation
getTime()
virtual Time ISystemClock::getTime () pure virtual
Implemented in SystemClock.
Referenced by TasksPool::add(), SmartPointState::beginGame(), Rifle::checkHeartBeat(), IRPresentationReceiverMT2::enableVibro(), ButtonManager::extiCallback(), NetworkLayer::generatePackageId(), MatrixKeyboard::getKeyPressed(), HeadSensor::init(), RC552Wrapper::interrogate(), ButtonManager::interrogate(), IRPresentationReceiverMT2::interrogate(), IRReceiverTV::interrogate(), NRF24L01Manager::interrogate(), PresentationReceiversGroupMT2::interrogate(), NetworkLayer::interrogate(), IRReceiverTV::interruptHandler(), Rifle::isHSConnected(), Rifle::isShocked(), NetworkLayer::isTranslationAllowed(), TasksPool::main(), Rifle::onCardReaded(), Rifle::onHSDisconnected(), GameLog::BaseStatsCounter::onTransmissionSucceeded(), MFRC522::PCD_Reset(), Stager::printStages(), Random::random32(), NetworkLayer::send(), NRF24L01Manager::sendData(), NetworkLayer::sendNext(), Stager::stage(), NetworkLayer::temproraryProhibitTransmission(), SmartPointState::ticTime(), IRPresentationReceiverMT2::updateOperationCallback(), Rifle::updatePlayerState(), NetworkLayer::updateTimeout(), GameLog::BaseStatsCounter::waitDelay(), SPIManager::waitForISR(), ButtonManager::wasBounce(), and ~ISystemClock().
init()
virtual void ISystemClock::init () pure virtual
Implemented in SystemClock.
Referenced by DeviceInitializer::initEnvironment(), and ~ISystemClock().
wait_us()
virtual void ISystemClock::wait_us (uint32_t time) pure virtual
Implemented in SystemClock.
Referenced by NRF24L01Manager::CEImpulse(), delay_ms(), MatrixKeyboard::getKeyPressed(), MFRC522::PCD_Init(), MFRC522::PCD_Reset(), BluetoothBridge::receiveNetworkPackage(), NRF24L01Manager::switchToRX(), NRF24L01Manager::switchToTX(), and ~ISystemClock().
The documentation for this class was generated from the following file:
include/hal/system-clock.hpp