Caustic lasertag system: ISPIManager Class Reference
ISPIManager Class Reference abstract
#include <spi.hpp>
Public Member Functions
virtual ~ISPIManager ()
virtual void init (uint32_t prescaler, IIOPin *NSSPin, uint8_t SPIPhase=SPIPhase1edge)=0
virtual bool Transmit (uint8_t *pData, uint16_t Size, uint32_t Timeout=DefaultTimeout)=0
add overloadings for one byte
virtual bool Receive (uint8_t *pData, uint16_t Size, uint32_t Timeout=DefaultTimeout)=0
virtual bool TransmitReceive (uint8_t *pTxData, uint8_t *pRxData, uint16_t Size, uint32_t Timeout=DefaultTimeout)=0
bool Transmit (uint8_t byte, uint32_t Timeout=DefaultTimeout)
bool Receive (uint8_t byte, uint32_t Timeout=DefaultTimeout)
uint8_t TransmitReceive (uint8_t byte, uint32_t Timeout=DefaultTimeout)
Static Public Attributes
static constexpr uint32_t BaudRatePrescaler4 = 1
static constexpr uint32_t BaudRatePrescaler8 = 2
static constexpr uint32_t BaudRatePrescaler16 = 3
static constexpr uint32_t BaudRatePrescaler32 = 4
static constexpr uint32_t BaudRatePrescaler64 = 5
static constexpr uint32_t BaudRatePrescaler128 = 6
static constexpr uint32_t BaudRatePrescaler256 = 7
static constexpr uint8_t SPIPhase1edge = 1
static constexpr uint8_t SPIPhase2edge = 2
static constexpr uint32_t DefaultTimeout = 100000
Detailed Description
Definition at line 30 of file spi.hpp.
Constructor & Destructor Documentation
~ISPIManager()
virtual ISPIManager::~ISPIManager () inline virtual
Definition at line 45 of file spi.hpp.
References init(), Receive(), Transmit(), and TransmitReceive().
Member Function Documentation
init()
virtual void ISPIManager::init (uint32_t prescaler, IIOPin * NSSPin, uint8_t SPIPhase = SPIPhase1edge) pure virtual
Implemented in SPIManager.
Referenced by LCD5110Controller::configureSPI(), MFRC522::configureSPI(), glcd_init(), NRF24L01Manager::init(), and ~ISPIManager().
Receive() [1/2]
virtual bool ISPIManager::Receive (uint8_t * pData, uint16_t Size, uint32_t Timeout = DefaultTimeout) pure virtual
Implemented in SPIManager.
Referenced by NRF24L01Manager::readReg(), Receive(), NRF24L01Manager::receiveData(), and ~ISPIManager().
Receive() [2/2]
bool ISPIManager::Receive (uint8_t byte, uint32_t Timeout = DefaultTimeout) inline
Definition at line 59 of file spi.hpp.
References Receive().
Transmit() [1/2]
virtual bool ISPIManager::Transmit (uint8_t * pData, uint16_t Size, uint32_t Timeout = DefaultTimeout) pure virtual
add overloadings for one byte
Implemented in SPIManager.
Referenced by glcd_spi_write(), MFRC522::PCD_ReadRegister(), MFRC522::PCD_WriteRegister(), NRF24L01Manager::resetMaxRetriesReached(), NRF24L01Manager::resetRXDataReady(), NRF24L01Manager::resetTXDataSent(), NRF24L01Manager::sendData(), Transmit(), NRF24L01Manager::writeReg(), and ~ISPIManager().
Transmit() [2/2]
bool ISPIManager::Transmit (uint8_t byte, uint32_t Timeout = DefaultTimeout) inline
Definition at line 54 of file spi.hpp.
References Transmit().
TransmitReceive() [1/2]
virtual bool ISPIManager::TransmitReceive (uint8_t * pTxData, uint8_t * pRxData, uint16_t Size, uint32_t Timeout = DefaultTimeout) pure virtual
Implemented in SPIManager.
Referenced by NRF24L01Manager::flushRX(), NRF24L01Manager::flushTX(), MFRC522::PCD_ReadRegister(), NRF24L01Manager::readReg(), NRF24L01Manager::receiveData(), NRF24L01Manager::sendData(), TransmitReceive(), NRF24L01Manager::updateStatus(), NRF24L01Manager::writeReg(), and ~ISPIManager().
TransmitReceive() [2/2]
uint8_t ISPIManager::TransmitReceive (uint8_t byte, uint32_t Timeout = DefaultTimeout) inline
Definition at line 64 of file spi.hpp.
References TransmitReceive().
Member Data Documentation
BaudRatePrescaler128
constexpr uint32_t ISPIManager::BaudRatePrescaler128 = 6 static
Definition at line 38 of file spi.hpp.
Referenced by MFRC522::configureSPI(), and SPIManager::init().
BaudRatePrescaler16
constexpr uint32_t ISPIManager::BaudRatePrescaler16 = 3 static
Definition at line 35 of file spi.hpp.
Referenced by SPIManager::init().
BaudRatePrescaler256
constexpr uint32_t ISPIManager::BaudRatePrescaler256 = 7 static
Definition at line 39 of file spi.hpp.
Referenced by SPIManager::init().
BaudRatePrescaler32
constexpr uint32_t ISPIManager::BaudRatePrescaler32 = 4 static
Definition at line 36 of file spi.hpp.
Referenced by LCD5110Controller::configureSPI(), glcd_init(), SPIManager::init(), and NRF24L01Manager::init().
BaudRatePrescaler4
constexpr uint32_t ISPIManager::BaudRatePrescaler4 = 1 static
Definition at line 33 of file spi.hpp.
Referenced by SPIManager::init().
BaudRatePrescaler64
constexpr uint32_t ISPIManager::BaudRatePrescaler64 = 5 static
Definition at line 37 of file spi.hpp.
Referenced by SPIManager::init().
BaudRatePrescaler8
constexpr uint32_t ISPIManager::BaudRatePrescaler8 = 2 static
Definition at line 34 of file spi.hpp.
Referenced by SPIManager::init().
DefaultTimeout
constexpr uint32_t ISPIManager::DefaultTimeout = 100000 static
Definition at line 44 of file spi.hpp.
SPIPhase1edge
constexpr uint8_t ISPIManager::SPIPhase1edge = 1 static
Definition at line 41 of file spi.hpp.
Referenced by MFRC522::configureSPI(), SPIManager::init(), and SPIManager::~SPIManager().
SPIPhase2edge
constexpr uint8_t ISPIManager::SPIPhase2edge = 2 static
Definition at line 42 of file spi.hpp.
Referenced by LCD5110Controller::configureSPI(), and glcd_init().
The documentation for this class was generated from the following file:
include/hal/spi.hpp