Caustic lasertag system: IIRPhysicalReceiver Class Reference
IIRPhysicalReceiver Class Reference abstract
#include <ir-physical.hpp>
Public Member Functions
virtual ~IIRPhysicalReceiver ()
virtual void setCallback (IRReceiverCallback callback)=0
virtual void setIOPin (IIOPin *input)=0
virtual void setEnabled (bool enabled)=0
virtual void init ()=0
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
virtual void interrogate ()=0
Detailed Description
Definition at line 48 of file ir-physical.hpp.
Constructor & Destructor Documentation
~IIRPhysicalReceiver()
virtual IIRPhysicalReceiver::~IIRPhysicalReceiver () inline virtual
Definition at line 51 of file ir-physical.hpp.
References IIRTransmitter::init().
Member Function Documentation
init()
virtual void IIRPhysicalReceiver::init () pure virtual
Implemented in IRReceiverTV.
Referenced by SmartPoint::init().
setCallback()
virtual void IIRPhysicalReceiver::setCallback (IRReceiverCallback callback) pure virtual
Implemented in IRReceiverBase.
Referenced by IRPresentationReceiverBase::setPhysicalReceiver().
setEnabled()
virtual void IIRPhysicalReceiver::setEnabled (bool enabled) pure virtual
Implemented in IRReceiverTV.
Referenced by SmartPoint::init().
setIOPin()
virtual void IIRPhysicalReceiver::setIOPin (IIOPin * input) pure virtual
Implemented in IRReceiverBase.
Referenced by SmartPoint::init().
The documentation for this class was generated from the following file:
include/ir/ir-physical.hpp