Caustic lasertag system: IADC Class Reference
IADC Class Reference abstract
#include <adc.hpp>
Public Member Functions
virtual ~IADC ()
virtual Result init (uint8_t port, uint8_t pin)=0
virtual UintParameter get ()=0
virtual UintParameter max ()=0
Detailed Description
Definition at line 30 of file adc.hpp.
Constructor & Destructor Documentation
~IADC()
virtual IADC::~IADC () inline virtual
Definition at line 33 of file adc.hpp.
References init(), and max().
Member Function Documentation
get()
virtual UintParameter IADC::get () pure virtual
Implemented in ADC.
Referenced by PowerMonitor::interrogate().
init()
virtual Result IADC::init (uint8_t port, uint8_t pin) pure virtual
Implemented in ADC.
Referenced by PowerMonitor::PowerMonitor(), and ~IADC().
max()
virtual UintParameter IADC::max () pure virtual
Implemented in ADC.
Referenced by PowerMonitor::interrogate(), and ~IADC().
The documentation for this class was generated from the following file:
include/hal/adc.hpp