Caustic lasertag system: WeaponManager Class Reference
WeaponManager Class Reference
#include <head-sensor.hpp>
Public Member Functions
~WeaponManager ()
void assign (const DeviceAddress &addr)
void dropAllPackages ()
void respawn ()
void die ()
Public Member Functions inherited from IWeaponObresver
virtual ~IWeaponObresver ()
Private Attributes
PackageId m_respawnPackage = 0
PackageId m_diePackage = 0
DeviceAddress m_addr
Detailed Description
Definition at line 43 of file head-sensor.hpp.
Constructor & Destructor Documentation
~WeaponManager()
WeaponManager::~WeaponManager ()
Definition at line 43 of file head-sensor.cpp.
References dropAllPackages().
Member Function Documentation
assign()
void WeaponManager::assign (const DeviceAddress & addr) virtual
Implements IWeaponObresver.
Definition at line 48 of file head-sensor.cpp.
References m_addr.
die()
void WeaponManager::die ()
Definition at line 84 of file head-sensor.cpp.
References headSensorPackageTimings, instance, HeadSensorPackageTimings::killPlayer, m_addr, m_diePackage, and RCSPStream::remoteCall().
Referenced by HeadSensor::dieWeapons().
dropAllPackages()
void WeaponManager::dropAllPackages ()
Definition at line 53 of file head-sensor.cpp.
References instance, m_diePackage, and m_respawnPackage.
Referenced by ~WeaponManager().
respawn()
void WeaponManager::respawn ()
Definition at line 67 of file head-sensor.cpp.
References info, instance, m_addr, m_respawnPackage, and RCSPStream::remoteCall().
Referenced by HeadSensor::respawnWeapons().
Member Data Documentation
m_addr
DeviceAddress WeaponManager::m_addr private
Definition at line 57 of file head-sensor.hpp.
Referenced by assign(), die(), and respawn().
m_diePackage
PackageId WeaponManager::m_diePackage = 0 private
Definition at line 55 of file head-sensor.hpp.
Referenced by die(), and dropAllPackages().
m_respawnPackage
PackageId WeaponManager::m_respawnPackage = 0 private
Definition at line 54 of file head-sensor.hpp.
Referenced by dropAllPackages(), and respawn().
The documentation for this class was generated from the following files:
include/head-sensor/head-sensor.hpp
src/head-sensor/head-sensor.cpp