Caustic lasertag system: SmartPointUI Class Reference
SmartPointUI Class Reference
#include <smart-point-ui.hpp>
Public Member Functions
SmartPointUI (SmartPointState &sps)
void init ()
void doIteration ()
Public Attributes
SmartPointState & smartPointState
MatrixKeyboard keyboard
LCD5110Controller lcd
UIStateBase * m_uiState = nullptr
UIInitScreen initScreen {*this}
UITimeLeftScreen timeLeftScreen {*this}
RGBLeds leds
Static Public Attributes
static SmartPointBlinkPatterns patterns
Private Member Functions
void initKbd ()
void initLCD ()
void initLEDs ()
Private Attributes
IIOPin * m_keybRows [4]
IIOPin * m_keybCols [4]
Detailed Description
Definition at line 75 of file smart-point-ui.hpp.
Constructor & Destructor Documentation
SmartPointUI()
SmartPointUI::SmartPointUI (SmartPointState & sps)
Definition at line 36 of file smart-point-ui.cpp.
Member Function Documentation
doIteration()
void SmartPointUI::doIteration ()
Definition at line 97 of file smart-point-ui.cpp.
References UIStateBase::doIteration(), and m_uiState.
Referenced by SmartPoint::init().
init()
void SmartPointUI::init ()
Definition at line 43 of file smart-point-ui.cpp.
References RGBLeds::blink(), RGBLeds::blue, RGBLeds::green, initKbd(), initLCD(), initLEDs(), initScreen, leds, m_uiState, and RGBLeds::red.
Referenced by SmartPoint::init().
initKbd()
void SmartPointUI::initKbd () private
Definition at line 52 of file smart-point-ui.cpp.
References IIOPinsPool::getIOPin(), MatrixKeyboard::init(), IOPins, keyboard, m_keybCols, and m_keybRows.
Referenced by init().
initLCD()
void SmartPointUI::initLCD () private
Definition at line 67 of file smart-point-ui.cpp.
Referenced by init().
initLEDs()
void SmartPointUI::initLEDs () private
Definition at line 87 of file smart-point-ui.cpp.
References IIOPinsPool::getIOPin(), RGBLeds::init(), IOPins, and leds.
Referenced by init().
Member Data Documentation
initScreen
UIInitScreen SmartPointUI::initScreen {*this}
Definition at line 87 of file smart-point-ui.hpp.
Referenced by UITimeLeftScreen::doIteration(), and init().
keyboard
MatrixKeyboard SmartPointUI::keyboard
Definition at line 83 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), and initKbd().
lcd
LCD5110Controller SmartPointUI::lcd
Definition at line 84 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration(), and UITimeLeftScreen::doIteration().
leds
RGBLeds SmartPointUI::leds
Definition at line 89 of file smart-point-ui.hpp.
Referenced by UITimeLeftScreen::doIteration(), init(), and initLEDs().
m_keybCols
IIOPin* SmartPointUI::m_keybCols[4] private
Definition at line 97 of file smart-point-ui.hpp.
Referenced by initKbd().
m_keybRows
IIOPin* SmartPointUI::m_keybRows[4] private
Definition at line 96 of file smart-point-ui.hpp.
Referenced by initKbd().
m_uiState
UIStateBase* SmartPointUI::m_uiState = nullptr
Definition at line 86 of file smart-point-ui.hpp.
Referenced by doIteration(), and init().
patterns
SmartPointBlinkPatterns SmartPointUI::patterns static
Definition at line 91 of file smart-point-ui.hpp.
smartPointState
SmartPointState& SmartPointUI::smartPointState
Definition at line 82 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration(), and UITimeLeftScreen::doIteration().
timeLeftScreen
UITimeLeftScreen SmartPointUI::timeLeftScreen {*this}
Definition at line 88 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-ui.hpp
src/smart-point/smart-point-ui.cpp