Caustic lasertag system: TaskBase Class Reference
TaskBase Class Reference
#include <os-wrappers.hpp>
Public Member Functions
TaskBase (const STask &task=nullptr, const char *name="Unknown")
bool isRunning () const
void deleteAfterRun (bool doDelete=true)
void setTask (const STask &_task)
void setStackSize (uint32_t stackSize)
void setName (const char *name)
STaskId taskId ()
bool safelyStop ()
void stopUnsafe ()
Protected Member Functions
void stopThread ()
Protected Attributes
STask m_task
uint32_t m_stackSize = 128
STaskId m_taskId = nullptr
uint8_t m_state = 0
char * m_name
Static Protected Attributes
static constexpr uint8_t runningNow = 1
static constexpr uint8_t needDeleteSelf = 2
static constexpr uint8_t needStop = 4
static constexpr uint8_t executingNow = 8
Detailed Description
Definition at line 57 of file os-wrappers.hpp.
Constructor & Destructor Documentation
TaskBase()
TaskBase::TaskBase (const STask & task = nullptr, const char * name = "Unknown") inline
Definition at line 60 of file os-wrappers.hpp.
Member Function Documentation
deleteAfterRun()
void TaskBase::deleteAfterRun (bool doDelete = true) inline
Definition at line 66 of file os-wrappers.hpp.
isRunning()
bool TaskBase::isRunning () const inline
Definition at line 65 of file os-wrappers.hpp.
safelyStop()
bool TaskBase::safelyStop ()
Stop task safely, all destructors will be called
Returns
is task executing after this call
Definition at line 121 of file os-wrappers.cpp.
References ADD_BITS, and REMOVE_BITS.
setName()
void TaskBase::setName (const char * name) inline
Definition at line 75 of file os-wrappers.hpp.
Referenced by NetworkLayer::NetworkLayer(), RGBLeds::RGBLeds(), and TasksPool::run().
setStackSize()
void TaskBase::setStackSize (uint32_t stackSize) inline
Definition at line 74 of file os-wrappers.hpp.
Referenced by main(), NetworkLayer::NetworkLayer(), RGBLeds::RGBLeds(), TasksPool::setStackSize(), and Worker::setStackSize().
setTask()
void TaskBase::setTask (const STask & _task) inline
Definition at line 73 of file os-wrappers.hpp.
Referenced by NetworkLayer::NetworkLayer(), RGBLeds::RGBLeds(), TasksPool::TasksPool(), and Worker::Worker().
stopThread()
void TaskBase::stopThread () protected
Definition at line 149 of file os-wrappers.cpp.
References REMOVE_BITS.
Referenced by TaskCycled::runTaskInCycle(), and TaskOnce::runTaskOnce().
stopUnsafe()
void TaskBase::stopUnsafe ()
Call vTaskDelete. Attention! This operation immediately stop the task without calling any destructors
Definition at line 139 of file os-wrappers.cpp.
taskId()
STaskId TaskBase::taskId () inline
Definition at line 76 of file os-wrappers.hpp.
Member Data Documentation
executingNow
constexpr uint8_t TaskBase::executingNow = 8 static protected
Definition at line 93 of file os-wrappers.hpp.
m_name
char* TaskBase::m_name protected
Definition at line 101 of file os-wrappers.hpp.
m_stackSize
uint32_t TaskBase::m_stackSize = 128 protected
Definition at line 98 of file os-wrappers.hpp.
m_state
uint8_t TaskBase::m_state = 0 protected
Definition at line 100 of file os-wrappers.hpp.
Referenced by TaskCycled::runTaskInCycle(), and TaskOnce::runTaskOnce().
m_task
STask TaskBase::m_task protected
Definition at line 97 of file os-wrappers.hpp.
Referenced by TaskCycled::runTaskInCycle(), and TaskOnce::runTaskOnce().
m_taskId
STaskId TaskBase::m_taskId = nullptr protected
Definition at line 99 of file os-wrappers.hpp.
needDeleteSelf
constexpr uint8_t TaskBase::needDeleteSelf = 2 static protected
Definition at line 91 of file os-wrappers.hpp.
needStop
constexpr uint8_t TaskBase::needStop = 4 static protected
Definition at line 92 of file os-wrappers.hpp.
runningNow
constexpr uint8_t TaskBase::runningNow = 1 static protected
Definition at line 90 of file os-wrappers.hpp.
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp