Caustic lasertag system: IRadioPhysicalDevice Class Reference
IRadioPhysicalDevice Class Reference abstract
#include <radio-physical.hpp>
Public Types
using DataReceiveCallback = std::function< void(uint8_t, uint8_t *)>
using TXDoneCallback = std::function< void(void)>
Public Member Functions
virtual ~IRadioPhysicalDevice ()
virtual void printStatus ()=0
virtual UintParameter getPayloadSize ()=0
virtual void setDataReceiveCallback (DataReceiveCallback callback)=0
virtual void setTXDoneCallback (TXDoneCallback callback)=0
virtual void setRXAddress (uint8_t channel, uint8_t *address)=0
virtual void setTXAddress (uint8_t *address)=0
virtual void sendData (uint8_t size, uint8_t *data)=0
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
virtual void interrogate ()=0
Static Public Attributes
static constexpr unsigned int defaultRFPhysicalPayloadSize = 32
Detailed Description
Definition at line 30 of file radio-physical.hpp.
Member Typedef Documentation
DataReceiveCallback
using IRadioPhysicalDevice::DataReceiveCallback = std::function<void(uint8_t, uint8_t*)>
Definition at line 33 of file radio-physical.hpp.
TXDoneCallback
using IRadioPhysicalDevice::TXDoneCallback = std::function<void(void)>
Definition at line 34 of file radio-physical.hpp.
Constructor & Destructor Documentation
~IRadioPhysicalDevice()
virtual IRadioPhysicalDevice::~IRadioPhysicalDevice () inline virtual
Definition at line 38 of file radio-physical.hpp.
References getPayloadSize(), printStatus(), sendData(), setDataReceiveCallback(), setRXAddress(), setTXAddress(), and setTXDoneCallback().
Member Function Documentation
getPayloadSize()
virtual UintParameter IRadioPhysicalDevice::getPayloadSize () pure virtual
Implemented in NRF24L01Manager.
Referenced by ~IRadioPhysicalDevice().
printStatus()
virtual void IRadioPhysicalDevice::printStatus () pure virtual
Implemented in NRF24L01Manager.
Referenced by NetworkLayer::interrogate(), and ~IRadioPhysicalDevice().
sendData()
virtual void IRadioPhysicalDevice::sendData (uint8_t size, uint8_t * data) pure virtual
Implemented in NRF24L01Manager.
Referenced by NetworkLayer::printAndSend(), and ~IRadioPhysicalDevice().
setDataReceiveCallback()
virtual void IRadioPhysicalDevice::setDataReceiveCallback (DataReceiveCallback callback) pure virtual
Implemented in NRF24L01Manager.
Referenced by NetworkLayer::init(), and ~IRadioPhysicalDevice().
setRXAddress()
virtual void IRadioPhysicalDevice::setRXAddress (uint8_t channel, uint8_t * address) pure virtual
Implemented in NRF24L01Manager.
Referenced by ~IRadioPhysicalDevice().
setTXAddress()
virtual void IRadioPhysicalDevice::setTXAddress (uint8_t * address) pure virtual
Implemented in NRF24L01Manager.
Referenced by ~IRadioPhysicalDevice().
setTXDoneCallback()
virtual void IRadioPhysicalDevice::setTXDoneCallback (TXDoneCallback callback) pure virtual
Implemented in NRF24L01Manager.
Referenced by NetworkLayer::init(), and ~IRadioPhysicalDevice().
Member Data Documentation
defaultRFPhysicalPayloadSize
constexpr unsigned int IRadioPhysicalDevice::defaultRFPhysicalPayloadSize = 32 static
Definition at line 36 of file radio-physical.hpp.
The documentation for this class was generated from the following file:
include/network/radio-physical.hpp