Caustic lasertag system: Pinout Class Reference
Pinout Class Reference
#include <pinout.hpp>
Classes
struct PinDescr
Note: GPIOA has port number 0, GPIOB has 1, ...
Public Member Functions
Result readIni (const char *filename)
__attribute__ ((always_inline)) void set(const char *pinName
const PinDescr & operator[] (const char *key) const
void printPinout () const
DetailedResult< std::string > getParameter (const char *name) const
Public Attributes
uint8_t port
uint8_t uint8_t pin
Private Member Functions
void readConfigLine (const char *key, const char *value)
Private Attributes
std::map< std::string, PinDescr > m_pins
std::map< std::string, std::string > m_other
Detailed Description
Definition at line 32 of file pinout.hpp.
Member Function Documentation
__attribute__()
Pinout::__attribute__ ((always_inline)) const inline
getParameter()
DetailedResult< std::string > Pinout::getParameter (const char * name) const
Definition at line 97 of file pinout.cpp.
References m_other.
Referenced by LEDFireEmitter::init().
operator[]()
const PinDescr& Pinout::operator[] (const char * key) const inline
Definition at line 73 of file pinout.hpp.
References m_pins.
printPinout()
void Pinout::printPinout () const
Definition at line 88 of file pinout.cpp.
References info, and m_pins.
Referenced by Rifle::init().
readConfigLine()
void Pinout::readConfigLine (const char * key, const char * value) private
Todo:
[stability] replace atoi by ananlog without undefined behavior
Todo:
[stability] replace atoi by ananlog without undefined behavior
Definition at line 41 of file pinout.cpp.
References checkSuffix(), error, m_other, m_pins, and StringParser< Type >::parse().
Referenced by readIni().
readIni()
Result Pinout::readIni (const char * filename)
Definition at line 32 of file pinout.cpp.
References IniParcer::parseFile(), readConfigLine(), and IniParcer::setCallback().
Referenced by DeviceInitializer::initDevice().
Member Data Documentation
m_other
std::map<std::string, std::string> Pinout::m_other private
Definition at line 91 of file pinout.hpp.
Referenced by getParameter(), and readConfigLine().
m_pins
std::map<std::string, PinDescr> Pinout::m_pins private
Definition at line 90 of file pinout.hpp.
Referenced by operator[](), printPinout(), and readConfigLine().
pin
uint8_t uint8_t Pinout::pin
Initial value:
{
        m_pins[pinName] = PinDescr(port, pin)
Definition at line 69 of file pinout.hpp.
Referenced by HeadSensor::init().
port
uint8_t Pinout::port
Definition at line 68 of file pinout.hpp.
Referenced by HeadSensor::init().
The documentation for this class was generated from the following files:
include/core/pinout.hpp
src/core/pinout.cpp