Caustic lasertag system: RC552Wrapper Class Reference
RC552Wrapper Class Reference
#include <MFRC522-wrapper.hpp>
Public Types
using RWDoneCallback = std::function< void(uint8_t *, uint16_t)>
Public Member Functions
RC552Wrapper ()
void init ()
void interrogate () override
void readBlock (RWDoneCallback callback, byte size)
void writeBlock (uint8_t *data, uint16_t size, RWDoneCallback callback=nullptr)
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Private Types
using LoopFunc = std::function< void()>
Private Member Functions
bool cardReadyToOperate ()
void readBlockLoop ()
void writeBlockLoop ()
Private Attributes
bool m_initResult = false
RWDoneCallback m_readCallback = nullptr
RWDoneCallback m_writeDoneCallback = nullptr
uint8_t * m_dataToWrite = nullptr
uint16_t m_dataToWriteSize = 0
uint8_t m_inputBuffer [inputBufferMaxSize]
byte m_inputBufferSize = 0
byte m_nuidPICC [3]
MFRC522 m_mfrc
LoopFunc m_currentLoop = nullptr
MFRC522::MIFARE_Key m_key
Time m_lastReinitTime = 0
Static Private Attributes
static constexpr Time reinitPeriod = 10000000
static constexpr uint16_t inputBufferMaxSize = 32
static constexpr byte trailerBlock = 7
static constexpr byte sector = 1
static constexpr byte blockAddr = 4
Detailed Description
Definition at line 31 of file MFRC522-wrapper.hpp.
Member Typedef Documentation
LoopFunc
using RC552Wrapper::LoopFunc = std::function<void()> private
Definition at line 44 of file MFRC522-wrapper.hpp.
RWDoneCallback
using RC552Wrapper::RWDoneCallback = std::function<void(uint8_t*, uint16_t)>
Definition at line 35 of file MFRC522-wrapper.hpp.
Constructor & Destructor Documentation
RC552Wrapper()
RC552Wrapper::RC552Wrapper ()
Definition at line 31 of file MFRC522-wrapper.cpp.
References MFRC522::MIFARE_Key::keyByte, and m_key.
Member Function Documentation
cardReadyToOperate()
bool RC552Wrapper::cardReadyToOperate () private
Definition at line 179 of file MFRC522-wrapper.cpp.
References debug, error, m_mfrc, MFRC522::PICC_GetType(), MFRC522::PICC_GetTypeName(), MFRC522::PICC_IsNewCardPresent(), MFRC522::PICC_ReadCardSerial(), MFRC522::PICC_TYPE_MIFARE_1K, MFRC522::PICC_TYPE_MIFARE_4K, MFRC522::PICC_TYPE_MIFARE_MINI, MFRC522::Uid::sak, and MFRC522::uid.
Referenced by readBlockLoop(), and writeBlockLoop().
init()
void RC552Wrapper::init ()
Definition at line 40 of file MFRC522-wrapper.cpp.
References MFRC522::RC522IO::chipSelect, IIOPinsPool::getIOPin(), ISPIsPool::getSPI(), IOPins, m_initResult, m_mfrc, MFRC522::PCD_Init(), MFRC522::PCD_SetAntennaGain(), MFRC522::RC522IO::resetPowerDown, MFRC522::RC522IO::spi, and SPIs.
Referenced by interrogate().
interrogate()
void RC552Wrapper::interrogate () override virtual
Implements IInterrogatable.
Definition at line 52 of file MFRC522-wrapper.cpp.
References MFRC522::configureSPI(), ISystemClock::getTime(), info, init(), m_currentLoop, m_initResult, m_lastReinitTime, m_mfrc, reinitPeriod, and systemClock.
readBlock()
void RC552Wrapper::readBlock (RWDoneCallback callback, byte size)
Definition at line 72 of file MFRC522-wrapper.cpp.
References m_currentLoop, m_inputBufferSize, m_readCallback, and readBlockLoop().
readBlockLoop()
void RC552Wrapper::readBlockLoop () private
Definition at line 87 of file MFRC522-wrapper.cpp.
References blockAddr, cardReadyToOperate(), debug, error, MFRC522::GetStatusCodeName(), m_inputBuffer, m_inputBufferSize, m_key, m_mfrc, m_readCallback, MFRC522::MIFARE_Read(), MFRC522::PCD_Authenticate(), MFRC522::PCD_StopCrypto1(), MFRC522::PICC_CMD_MF_AUTH_KEY_A, MFRC522::PICC_HaltA(), MFRC522::STATUS_OK, trailerBlock, and MFRC522::uid.
Referenced by readBlock().
writeBlock()
void RC552Wrapper::writeBlock (uint8_t * data, uint16_t size, RWDoneCallback callback = nullptr)
Definition at line 79 of file MFRC522-wrapper.cpp.
References m_currentLoop, m_dataToWrite, m_dataToWriteSize, m_writeDoneCallback, and writeBlockLoop().
writeBlockLoop()
void RC552Wrapper::writeBlockLoop () private
Definition at line 121 of file MFRC522-wrapper.cpp.
References blockAddr, cardReadyToOperate(), debug, error, MFRC522::GetStatusCodeName(), m_dataToWrite, m_dataToWriteSize, m_key, m_mfrc, m_writeDoneCallback, MFRC522::MIFARE_Read(), MFRC522::MIFARE_Write(), MFRC522::PCD_Authenticate(), MFRC522::PCD_StopCrypto1(), MFRC522::PICC_CMD_MF_AUTH_KEY_B, MFRC522::PICC_HaltA(), MFRC522::STATUS_OK, trailerBlock, and MFRC522::uid.
Referenced by writeBlock().
Member Data Documentation
blockAddr
constexpr byte RC552Wrapper::blockAddr = 4 static private
Definition at line 50 of file MFRC522-wrapper.hpp.
Referenced by readBlockLoop(), and writeBlockLoop().
inputBufferMaxSize
constexpr uint16_t RC552Wrapper::inputBufferMaxSize = 32 static private
Definition at line 46 of file MFRC522-wrapper.hpp.
m_currentLoop
LoopFunc RC552Wrapper::m_currentLoop = nullptr private
Definition at line 69 of file MFRC522-wrapper.hpp.
Referenced by interrogate(), readBlock(), and writeBlock().
m_dataToWrite
uint8_t* RC552Wrapper::m_dataToWrite = nullptr private
Definition at line 60 of file MFRC522-wrapper.hpp.
Referenced by writeBlock(), and writeBlockLoop().
m_dataToWriteSize
uint16_t RC552Wrapper::m_dataToWriteSize = 0 private
Definition at line 61 of file MFRC522-wrapper.hpp.
Referenced by writeBlock(), and writeBlockLoop().
m_initResult
bool RC552Wrapper::m_initResult = false private
Definition at line 56 of file MFRC522-wrapper.hpp.
Referenced by init(), and interrogate().
m_inputBuffer
uint8_t RC552Wrapper::m_inputBuffer[inputBufferMaxSize] private
Definition at line 63 of file MFRC522-wrapper.hpp.
Referenced by readBlockLoop().
m_inputBufferSize
byte RC552Wrapper::m_inputBufferSize = 0 private
Definition at line 64 of file MFRC522-wrapper.hpp.
Referenced by readBlock(), and readBlockLoop().
m_key
MFRC522::MIFARE_Key RC552Wrapper::m_key private
Definition at line 71 of file MFRC522-wrapper.hpp.
Referenced by RC552Wrapper(), readBlockLoop(), and writeBlockLoop().
m_lastReinitTime
Time RC552Wrapper::m_lastReinitTime = 0 private
Definition at line 73 of file MFRC522-wrapper.hpp.
Referenced by interrogate().
m_mfrc
MFRC522 RC552Wrapper::m_mfrc private
Definition at line 68 of file MFRC522-wrapper.hpp.
Referenced by cardReadyToOperate(), init(), interrogate(), readBlockLoop(), and writeBlockLoop().
m_nuidPICC
byte RC552Wrapper::m_nuidPICC[3] private
Definition at line 67 of file MFRC522-wrapper.hpp.
m_readCallback
RWDoneCallback RC552Wrapper::m_readCallback = nullptr private
Definition at line 58 of file MFRC522-wrapper.hpp.
Referenced by readBlock(), and readBlockLoop().
m_writeDoneCallback
RWDoneCallback RC552Wrapper::m_writeDoneCallback = nullptr private
Definition at line 59 of file MFRC522-wrapper.hpp.
Referenced by writeBlock(), and writeBlockLoop().
reinitPeriod
constexpr Time RC552Wrapper::reinitPeriod = 10000000 static private
Definition at line 43 of file MFRC522-wrapper.hpp.
Referenced by interrogate().
sector
constexpr byte RC552Wrapper::sector = 1 static private
Definition at line 49 of file MFRC522-wrapper.hpp.
trailerBlock
constexpr byte RC552Wrapper::trailerBlock = 7 static private
Definition at line 48 of file MFRC522-wrapper.hpp.
Referenced by readBlockLoop(), and writeBlockLoop().
The documentation for this class was generated from the following files:
include/dev/MFRC522-wrapper.hpp
src/dev/MFRC522-wrapper.cpp