Caustic lasertag system: RCSPCodeManipulator Class Reference
RCSPCodeManipulator Class Reference
#include <RCSP-codes-manipulation.hpp>
Static Public Member Functions
static constexpr OperationCode clearOptionBits (OperationCode operationCode)
static constexpr OperationCode makeCallRequest (OperationCode operationCode)
static constexpr OperationCode makeSetObject (OperationCode operationCode)
static constexpr OperationCode makeObjectRequestOC (OperationCode operationCode)
static constexpr bool __attribute__ ((always_inline)) isSetObject(uint16_t operationCode)
static constexpr bool __attribute__ ((always_inline)) isCallRequest(uint16_t operationCode)
static constexpr bool __attribute__ ((always_inline)) isObjectRequest(uint16_t operationCode)
Static Private Member Functions
static constexpr bool __attribute__ ((always_inline)) getBit(OperationCode code
Private Attributes
static constexpr bool uint8_t bit { return (code & (1 << bit)) ? true : false
Static Private Attributes
static constexpr OperationCode OperationCodeMask = (OperationCode) ~((1<<15) | (1<<14))
All bits =1 except two upper bits.
Detailed Description
Compile-time class used to manipulate with operation codes
Definition at line 43 of file RCSP-codes-manipulation.hpp.
Member Function Documentation
__attribute__() [1/4]
static constexpr bool RCSPCodeManipulator::__attribute__ ((always_inline)) inline static
Definition at line 53 of file RCSP-codes-manipulation.hpp.
Referenced by __attribute__().
__attribute__() [2/4]
static constexpr bool RCSPCodeManipulator::__attribute__ ((always_inline)) inline static
Definition at line 56 of file RCSP-codes-manipulation.hpp.
__attribute__() [3/4]
static constexpr bool RCSPCodeManipulator::__attribute__ ((always_inline)) inline static
Definition at line 59 of file RCSP-codes-manipulation.hpp.
References __attribute__(), and bit.
__attribute__() [4/4]
static constexpr bool RCSPCodeManipulator::__attribute__ ((always_inline)) inline static private
clearOptionBits()
static constexpr OperationCode RCSPCodeManipulator::clearOptionBits (OperationCode operationCode) inline static
Definition at line 46 of file RCSP-codes-manipulation.hpp.
References OperationCodeMask.
makeCallRequest()
static constexpr OperationCode RCSPCodeManipulator::makeCallRequest (OperationCode operationCode) inline static
Definition at line 47 of file RCSP-codes-manipulation.hpp.
References OperationCodeMask.
Referenced by RCSPAggregator::serializeCallRequest().
makeObjectRequestOC()
static constexpr OperationCode RCSPCodeManipulator::makeObjectRequestOC (OperationCode operationCode) inline static
Definition at line 50 of file RCSP-codes-manipulation.hpp.
References OperationCodeMask.
Referenced by RCSPAggregator::serializeObjectRequest().
makeSetObject()
static constexpr OperationCode RCSPCodeManipulator::makeSetObject (OperationCode operationCode) inline static
Definition at line 48 of file RCSP-codes-manipulation.hpp.
References OperationCodeMask.
Referenced by RCSPAggregator::dispatchOperation(), RCSPAggregator::getLocalObject(), and RCSPAggregator::serializeObject().
Member Data Documentation
bit
constexpr bool uint8_t RCSPCodeManipulator::bit { return (code & (1 << bit)) ? true : false private
Definition at line 65 of file RCSP-codes-manipulation.hpp.
Referenced by __attribute__().
OperationCodeMask
constexpr OperationCode RCSPCodeManipulator::OperationCodeMask = (OperationCode) ~((1<<15) | (1<<14)) static private
All bits =1 except two upper bits.
Definition at line 68 of file RCSP-codes-manipulation.hpp.
Referenced by clearOptionBits(), makeCallRequest(), makeObjectRequestOC(), and makeSetObject().
The documentation for this class was generated from the following file:
include/rcsp/RCSP-codes-manipulation.hpp