Caustic lasertag system: SmartPoint Class Reference
SmartPoint Class Reference
#include <smart-point.hpp>
Public Member Functions
SmartPoint ()
~SmartPoint ()
void init (const Pinout &pinout) override
void setDafaultPinout (Pinout &pinout) override
bool checkPinout (const Pinout &pinout) override
FUNCTION_1P (ConfigCodes::HeadSensor::Functions, SmartPoint, catchShot)
Public Member Functions inherited from IAnyDevice
virtual ~IAnyDevice ()
Public Attributes
DeviceConfiguration deviceConfig
SmartPointConfig samrtPointConfig
SmartPointState state {samrtPointConfig}
SmartPointUI ui {state}
Private Member Functions
void initSounds ()
Private Attributes
TasksPool m_tasksPool {"SmPntPl"}
SoundPlayer m_systemReadySound
SmartPointUI m_ui {state}
IIRPhysicalReceiver * m_irPhysicalReceiver = nullptr
IIRPresentationReceiver * m_irPresentationReceiver = nullptr
IPresentationReceiversGroup * m_irPresentationReceiversGroup = nullptr
Interrogator m_MT2Interogator {"MT2Itrg"}
Detailed Description
Definition at line 39 of file smart-point.hpp.
Constructor & Destructor Documentation
SmartPoint()
SmartPoint::SmartPoint ()
Definition at line 36 of file smart-point.cpp.
References deviceConfig, m_tasksPool, TasksPool::setStackSize(), and DeviceTypes::smartPoint.
~SmartPoint()
SmartPoint::~SmartPoint () inline
Definition at line 43 of file smart-point.hpp.
References checkPinout(), init(), and setDafaultPinout().
Member Function Documentation
checkPinout()
bool SmartPoint::checkPinout (const Pinout & pinout) override virtual
Todo:
Implement here
Implements IAnyDevice.
Definition at line 144 of file smart-point.cpp.
References SmartPointState::acitateByTeam(), info, state, and ShotMessage::teamId.
Referenced by ~SmartPoint().
FUNCTION_1P()
SmartPoint::FUNCTION_1P (ConfigCodes::HeadSensor::Functions , SmartPoint , catchShot)
init()
void SmartPoint::init (const Pinout & pinout) override virtual
Todo:
Chack that rife is turned on/off correctly anway
Implements IAnyDevice.
Definition at line 42 of file smart-point.cpp.
References TasksPool::add(), Broadcast::any, broadcast, IPresentationReceiversGroup::connectReceiver(), deviceConfig, SmartPointUI::doIteration(), error, IIOPinsPool::getIOPin(), info, HardwareInitializer::init(), IIRPresentationReceiver::init(), IIRPhysicalReceiver::init(), SmartPointUI::init(), initSounds(), instance, IOPins, m_irPhysicalReceiver, m_irPresentationReceiver, m_irPresentationReceiversGroup, m_MT2Interogator, m_systemReadySound, m_tasksPool, m_ui, SoundPlayer::play(), Interrogator::registerObject(), SmartPointConfig::resetToDefault(), Interrogator::run(), TasksPool::run(), samrtPointConfig, IIRPhysicalReceiver::setEnabled(), IIRPhysicalReceiver::setIOPin(), IIRPresentationReceiver::setPhysicalReceiver(), Interrogator::setStackSize(), Broadcast::smartPoint, state, SmartPointState::ticTime(), and warning.
Referenced by ~SmartPoint().
initSounds()
void SmartPoint::initSounds () private
Definition at line 156 of file smart-point.cpp.
References m_systemReadySound, and SoundPlayer::readVariants().
Referenced by init().
setDafaultPinout()
void SmartPoint::setDafaultPinout (Pinout & pinout) override virtual
Implements IAnyDevice.
Definition at line 139 of file smart-point.cpp.
Referenced by ~SmartPoint().
Member Data Documentation
deviceConfig
DeviceConfiguration SmartPoint::deviceConfig
Definition at line 48 of file smart-point.hpp.
Referenced by init(), and SmartPoint().
m_irPhysicalReceiver
IIRPhysicalReceiver* SmartPoint::m_irPhysicalReceiver = nullptr private
Definition at line 62 of file smart-point.hpp.
Referenced by init().
m_irPresentationReceiver
IIRPresentationReceiver* SmartPoint::m_irPresentationReceiver = nullptr private
Definition at line 63 of file smart-point.hpp.
Referenced by init().
m_irPresentationReceiversGroup
IPresentationReceiversGroup* SmartPoint::m_irPresentationReceiversGroup = nullptr private
Definition at line 64 of file smart-point.hpp.
Referenced by init().
m_MT2Interogator
Interrogator SmartPoint::m_MT2Interogator {"MT2Itrg"} private
Definition at line 65 of file smart-point.hpp.
Referenced by init().
m_systemReadySound
SoundPlayer SmartPoint::m_systemReadySound private
Definition at line 59 of file smart-point.hpp.
Referenced by init(), and initSounds().
m_tasksPool
TasksPool SmartPoint::m_tasksPool {"SmPntPl"} private
Definition at line 58 of file smart-point.hpp.
Referenced by init(), and SmartPoint().
m_ui
SmartPointUI SmartPoint::m_ui {state} private
Definition at line 60 of file smart-point.hpp.
Referenced by init().
samrtPointConfig
SmartPointConfig SmartPoint::samrtPointConfig
Definition at line 49 of file smart-point.hpp.
Referenced by init().
state
SmartPointState SmartPoint::state {samrtPointConfig}
Definition at line 50 of file smart-point.hpp.
Referenced by checkPinout(), and init().
ui
SmartPointUI SmartPoint::ui {state}
Definition at line 51 of file smart-point.hpp.
The documentation for this class was generated from the following files:
include/smart-point/smart-point.hpp
src/smart-point/smart-point.cpp