Caustic lasertag system: BluetoothBridge Class Reference
BluetoothBridge Class Reference
#include <bluetooth-bridge.hpp>
Public Member Functions
void init (const Pinout &pinout)
void setDafaultPinout (Pinout &pinout)
bool checkPinout (const Pinout &pinout)
Public Member Functions inherited from IAnyDevice
virtual ~IAnyDevice ()
Public Attributes
DeviceConfiguration deviceConfig
Private Member Functions
void receiveNetworkPackage (const DeviceAddress sender, uint8_t *payload, uint16_t payloadLength)
void receiveBluetoothOneByteISR (uint8_t byte)
void receiveBluetoothPackageISR (uint8_t *buffer, uint16_t size)
void sendBluetoothMessage (AnyBuffer *buffer)
void sendNetworkPackage (AnyBuffer *buffer)
Private Attributes
Bluetooth::MessageCreator m_bluetoothMsgCreator
IUARTManager * m_bluetoothPort = nullptr
Worker m_workerToBluetooth {30}
Worker m_workerToNetwork {30}
Bluetooth::MessageReceiver m_receiver
Static Private Attributes
static constexpr uint16_t bluetoothIncommingBufferSize = 200
Detailed Description
Definition at line 45 of file bluetooth-bridge.hpp.
Member Function Documentation
checkPinout()
bool BluetoothBridge::checkPinout (const Pinout & pinout) virtual
Implements IAnyDevice.
Definition at line 119 of file bluetooth-bridge.cpp.
init()
void BluetoothBridge::init (const Pinout & pinout) virtual
Implements IAnyDevice.
Definition at line 49 of file bluetooth-bridge.cpp.
References Broadcast::any, Broadcast::bluetoothBridges, broadcast, IUARTsFactory::create(), IIOPinsPool::getIOPin(), HardwareInitializer::init(), instance, IOPins, IUARTManager::setBlockSize(), AnyBuffer::size, UARTSFactory, and UNUSED_ARG.
receiveBluetoothOneByteISR()
void BluetoothBridge::receiveBluetoothOneByteISR (uint8_t byte) private
Definition at line 143 of file bluetooth-bridge.cpp.
receiveBluetoothPackageISR()
void BluetoothBridge::receiveBluetoothPackageISR (uint8_t * buffer, uint16_t size) private
Definition at line 154 of file bluetooth-bridge.cpp.
References AnyBuffer::AnyBuffer(), AnyBuffer::data, info, printHex(), and AnyBuffer::size.
receiveNetworkPackage()
void BluetoothBridge::receiveNetworkPackage (const DeviceAddress sender, uint8_t * payload, uint16_t payloadLength) private
Definition at line 124 of file bluetooth-bridge.cpp.
References AnyBuffer::AnyBuffer(), AnyBuffer::data, debug, printHex(), AnyBuffer::size, systemClock, trace, and ISystemClock::wait_us().
sendBluetoothMessage()
void BluetoothBridge::sendBluetoothMessage (AnyBuffer * buffer) private
Definition at line 168 of file bluetooth-bridge.cpp.
References AnyBuffer::data, debug, AnyBuffer::size, and Kernel::yeld().
sendNetworkPackage()
void BluetoothBridge::sendNetworkPackage (AnyBuffer * buffer) private
Definition at line 177 of file bluetooth-bridge.cpp.
References Bluetooth::Message::address, ADDRESS_TO_STREAM, broadcast, BluetoothBridgePackageTimings::broadcast, AnyBuffer::data, Bluetooth::Message::data, debug, instance, Broadcast::isBroadcast(), and Bluetooth::Message::payloadLength().
setDafaultPinout()
void BluetoothBridge::setDafaultPinout (Pinout & pinout) virtual
Implements IAnyDevice.
Definition at line 115 of file bluetooth-bridge.cpp.
Member Data Documentation
bluetoothIncommingBufferSize
constexpr uint16_t BluetoothBridge::bluetoothIncommingBufferSize = 200 static private
Definition at line 55 of file bluetooth-bridge.hpp.
deviceConfig
DeviceConfiguration BluetoothBridge::deviceConfig
Definition at line 52 of file bluetooth-bridge.hpp.
m_bluetoothMsgCreator
Bluetooth::MessageCreator BluetoothBridge::m_bluetoothMsgCreator private
Definition at line 63 of file bluetooth-bridge.hpp.
m_bluetoothPort
IUARTManager* BluetoothBridge::m_bluetoothPort = nullptr private
Definition at line 65 of file bluetooth-bridge.hpp.
m_receiver
Bluetooth::MessageReceiver BluetoothBridge::m_receiver private
Definition at line 70 of file bluetooth-bridge.hpp.
m_workerToBluetooth
Worker BluetoothBridge::m_workerToBluetooth {30} private
Todo:
Queues should be as large as possible, so need to increase its size
Definition at line 68 of file bluetooth-bridge.hpp.
m_workerToNetwork
Worker BluetoothBridge::m_workerToNetwork {30} private
Definition at line 69 of file bluetooth-bridge.hpp.
The documentation for this class was generated from the following files:
include/bluetooth-bridge/bluetooth-bridge.hpp
src/bluetooth-bridge/bluetooth-bridge.cpp