Caustic lasertag system: SPIManager Class Reference
SPIManager Class Reference
#include <spi-hw.hpp>
Public Member Functions
SPIManager (uint8_t SPIindex)
~SPIManager ()
void init (uint32_t prescaler, IIOPin *NSSPin, uint8_t SPIPhase=SPIPhase1edge)
bool Transmit (uint8_t *pData, uint16_t Size, uint32_t Timeout=defaultTimeout)
add overloadings for one byte
bool Receive (uint8_t *pData, uint16_t Size, uint32_t Timeout=defaultTimeout)
bool TransmitReceive (uint8_t *pTxData, uint8_t *pRxData, uint16_t Size, uint32_t Timeout=defaultTimeout)
void operationDone_ISR ()
Public Member Functions inherited from ISPIManager
virtual ~ISPIManager ()
bool Transmit (uint8_t byte, uint32_t Timeout=DefaultTimeout)
bool Receive (uint8_t byte, uint32_t Timeout=DefaultTimeout)
uint8_t TransmitReceive (uint8_t byte, uint32_t Timeout=DefaultTimeout)
Private Member Functions
bool waitForISR (uint32_t timeout=0)
uint8_t sendByte (uint8_t byte)
uint8_t receiveByte ()
Private Attributes
SPI_HandleTypeDef * m_hspi
StagerStub m_stager {"SPIManager"}
bool m_operationDone = false
uint8_t m_portNumber = 1
IIOPin * m_NSSPin = nullptr
uint32_t m_configHash = 0
Static Private Attributes
static constexpr uint32_t defaultTimeout = 100000
Additional Inherited Members
Static Public Attributes inherited from ISPIManager
static constexpr uint32_t BaudRatePrescaler4 = 1
static constexpr uint32_t BaudRatePrescaler8 = 2
static constexpr uint32_t BaudRatePrescaler16 = 3
static constexpr uint32_t BaudRatePrescaler32 = 4
static constexpr uint32_t BaudRatePrescaler64 = 5
static constexpr uint32_t BaudRatePrescaler128 = 6
static constexpr uint32_t BaudRatePrescaler256 = 7
static constexpr uint8_t SPIPhase1edge = 1
static constexpr uint8_t SPIPhase2edge = 2
static constexpr uint32_t DefaultTimeout = 100000
Detailed Description
Definition at line 35 of file spi-hw.hpp.
Constructor & Destructor Documentation
SPIManager()
SPIManager::SPIManager (uint8_t SPIindex)
Definition at line 62 of file spi.cpp.
References error, hspi1, hspi2, hspi3, m_hspi, and zerify().
Referenced by SPIsPool::getSPI().
~SPIManager()
SPIManager::~SPIManager () inline
Definition at line 39 of file spi-hw.hpp.
References defaultTimeout, init(), operationDone_ISR(), Receive(), ISPIManager::SPIPhase1edge, Transmit(), and TransmitReceive().
Member Function Documentation
init()
void SPIManager::init (uint32_t prescaler, IIOPin * NSSPin, uint8_t SPIPhase = SPIPhase1edge) virtual
Implements ISPIManager.
Definition at line 88 of file spi.cpp.
References ISPIManager::BaudRatePrescaler128, ISPIManager::BaudRatePrescaler16, ISPIManager::BaudRatePrescaler256, ISPIManager::BaudRatePrescaler32, ISPIManager::BaudRatePrescaler4, ISPIManager::BaudRatePrescaler64, ISPIManager::BaudRatePrescaler8, error, hashLy(), m_configHash, m_hspi, m_NSSPin, m_stager, IIOPin::set(), ISPIManager::SPIPhase1edge, StagerStub::stage(), and IIOPin::switchToOutput().
Referenced by ~SPIManager().
operationDone_ISR()
void SPIManager::operationDone_ISR ()
Definition at line 213 of file spi.cpp.
References m_operationDone.
Referenced by HAL_SPI_RxCpltCallback(), HAL_SPI_TxCpltCallback(), HAL_SPI_TxRxCpltCallback(), and ~SPIManager().
Receive()
bool SPIManager::Receive (uint8_t * pData, uint16_t Size, uint32_t Timeout = defaultTimeout) virtual
Implements ISPIManager.
Definition at line 163 of file spi.cpp.
References error, m_hspi, m_operationDone, m_stager, StagerStub::stage(), and waitForISR().
Referenced by ~SPIManager().
receiveByte()
uint8_t SPIManager::receiveByte () private
sendByte()
uint8_t SPIManager::sendByte (uint8_t byte) private
Transmit()
bool SPIManager::Transmit (uint8_t * pData, uint16_t Size, uint32_t Timeout = defaultTimeout) virtual
add overloadings for one byte
Implements ISPIManager.
Definition at line 137 of file spi.cpp.
References error, m_hspi, m_operationDone, m_stager, StagerStub::stage(), and waitForISR().
Referenced by ~SPIManager().
TransmitReceive()
bool SPIManager::TransmitReceive (uint8_t * pTxData, uint8_t * pRxData, uint16_t Size, uint32_t Timeout = defaultTimeout) virtual
Implements ISPIManager.
Definition at line 188 of file spi.cpp.
References error, m_hspi, m_operationDone, m_stager, StagerStub::stage(), and waitForISR().
Referenced by ~SPIManager().
waitForISR()
bool SPIManager::waitForISR (uint32_t timeout = 0) private
Definition at line 218 of file spi.cpp.
References ISystemClock::getTime(), m_operationDone, and systemClock.
Referenced by Receive(), Transmit(), and TransmitReceive().
Member Data Documentation
defaultTimeout
constexpr uint32_t SPIManager::defaultTimeout = 100000 static private
Definition at line 49 of file spi-hw.hpp.
Referenced by ~SPIManager().
m_configHash
uint32_t SPIManager::m_configHash = 0 private
Definition at line 61 of file spi-hw.hpp.
Referenced by init().
m_hspi
SPI_HandleTypeDef* SPIManager::m_hspi private
Definition at line 54 of file spi-hw.hpp.
Referenced by init(), Receive(), SPIManager(), Transmit(), and TransmitReceive().
m_NSSPin
IIOPin* SPIManager::m_NSSPin = nullptr private
Definition at line 59 of file spi-hw.hpp.
Referenced by init().
m_operationDone
bool SPIManager::m_operationDone = false private
Definition at line 56 of file spi-hw.hpp.
Referenced by operationDone_ISR(), Receive(), Transmit(), TransmitReceive(), and waitForISR().
m_portNumber
uint8_t SPIManager::m_portNumber = 1 private
Definition at line 58 of file spi-hw.hpp.
m_stager
StagerStub SPIManager::m_stager {"SPIManager"} private
Definition at line 55 of file spi-hw.hpp.
Referenced by init(), Receive(), Transmit(), and TransmitReceive().
The documentation for this class was generated from the following files:
include/hw/spi-hw.hpp
src/hw/spi.cpp