Caustic lasertag system: Logger Class Reference
Logger Class Reference
#include <logging.hpp>
Classes
struct LoggerUnnamed
Public Member Functions
Logger (const char *loggerName)
void enable (bool enabled=true)
bool isEnabled ()
template<class T >
LoggerUnnamed & operator<< (T &&data)
Private Attributes
LoggerUnnamed m_unnamedLogger
const char * m_loggerName
bool m_enabled = false
Detailed Description
Definition at line 56 of file logging.hpp.
Constructor & Destructor Documentation
Logger()
Logger::Logger (const char * loggerName) inline
Definition at line 62 of file logging.hpp.
Member Function Documentation
enable()
void Logger::enable (bool enabled = true)
Definition at line 173 of file logging.cpp.
Referenced by Loggers::initLoggers(), and main().
isEnabled()
bool Logger::isEnabled ()
Definition at line 179 of file logging.cpp.
Referenced by NetworkLayer::printAndSend(), NetworkLayer::RXCallback(), and Rifle::updatePlayerState().
operator<<()
template<class T > LoggerUnnamed& Logger::operator<< (T && data) inline
Definition at line 68 of file logging.hpp.
References Loggers::loggersMutex, Loggers::tags, IUARTManager::transmitSync(), and Loggers::uart.
Member Data Documentation
m_enabled
bool Logger::m_enabled = false private
Definition at line 105 of file logging.hpp.
m_loggerName
const char* Logger::m_loggerName private
Definition at line 104 of file logging.hpp.
m_unnamedLogger
LoggerUnnamed Logger::m_unnamedLogger private
Definition at line 103 of file logging.hpp.
The documentation for this class was generated from the following files:
include/core/logging.hpp
src/core/logging.cpp