Caustic lasertag system: NRF24L01Manager Class Reference
NRF24L01Manager Class Reference
#include <nrf24l01.hpp>
Public Types
enum EnableDisable { DISABLE_OPTION = 0, ENABLE_OPTION = 1 }
Public Types inherited from IRadioPhysicalDevice
using DataReceiveCallback = std::function< void(uint8_t, uint8_t *)>
using TXDoneCallback = std::function< void(void)>
Public Member Functions
NRF24L01Manager ()
UintParameter getPayloadSize () override
void setDataReceiveCallback (DataReceiveCallback callback) override
void setTXDoneCallback (TXDoneCallback callback) override
void sendData (uint8_t size, uint8_t *data) override
void setRXAddress (uint8_t channel, uint8_t *address) override
void setTXAddress (uint8_t *address) override
void printStatus () override
void init (IIOPin *chipEnablePin, IIOPin *chipSelectPin, IIOPin *IRQPin, uint8_t SPIIndex, bool useInterrupts, uint8_t radioChannel=defaultRadioChannel)
void setTXMaxRetriesCallback (TXMaxRetriesCallback callback)
void resetAllIRQ ()
void interrogate ()
void enablePipe (uint8_t pipe, uint8_t value)
void flushTX ()
void flushRX ()
void enableDebug (bool debug=true)
Public Member Functions inherited from IRadioPhysicalDevice
virtual ~IRadioPhysicalDevice ()
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Static Public Attributes
static constexpr unsigned int payloadSize = 32
static constexpr uint8_t defaultRadioChannel = 1
Static Public Attributes inherited from IRadioPhysicalDevice
static constexpr unsigned int defaultRFPhysicalPayloadSize = 32
Private Types
enum Power { POWER_OFF = 0, POWER_ON = 1 }
enum InterruptionsMasks { IM_MASK_MAX_RETRIES = 1, IM_MASK_TX_DATA_READY = 2, IM_MASK_RX_DATA_READY = 4 }
enum CRCEnableDisable { CRC_DISABLE = 0, CRC_ENABLE = 1 }
enum CRCLen { CRC1BYTE = 0, CRC2BYTES = 1 }
enum AdressWidth { AW_3BYTES, AW_4BYTES, AW_5BYTES }
enum Baudrate { BR_1MBIT = 0, BR_2MBIT = 1 }
enum TXPower { PW_m18DB = 0, PW_m12DB = 1, PW_m6DB = 2, PW_0DB = 3 }
enum LNAGain { LNA_DISABLE = 0, LNA_ENABLE = 1 }
enum RXTXMODE { MODE_TRANSMITTER = 0, MODE_RECEIVER = 1 }
Private Member Functions
void switchToTX ()
void switchToRX ()
void receiveData (uint8_t size, uint8_t *data)
void initInterrupts ()
void writeReg (uint8_t reg, uint8_t size, uint8_t *data)
void readReg (uint8_t reg, uint8_t size, uint8_t *data)
void extiHandler (bool state)
void setConfig (uint8_t interruptionsMask, uint8_t enableCRC, uint8_t CRC2bytes, uint8_t powerUP, uint8_t isRecieving)
void switchToReceiver ()
void switchToTranmitter ()
void updateStatus ()
bool isRXDataReady ()
bool isTXDataSent ()
bool isMaxRetriesReached ()
int getPipeNumberAvaliableForRXFIFO ()
bool isTXFIFOFull ()
void resetRXDataReady ()
void resetTXDataSent ()
void resetMaxRetriesReached ()
bool isCarrierDetected ()
void setAutoACK (uint8_t channel, bool value)
void setAdressWidth (AdressWidth width)
void setupRetransmission (uint8_t delay, uint8_t count)
void setRFChannel (uint8_t number)
void clearLostPackagesCount ()
void setRFSettings (uint8_t use2MBits, uint8_t power, uint8_t LNAGain)
uint8_t getLostPackagesCount ()
uint8_t getResentPackagesCount ()
void readRXAdresses ()
void readTXAdress ()
void setRXPayloadLength (uint8_t channel, uint8_t payloadLength)
bool isReuseEnabled ()
bool isTXFull ()
bool isTXEmpty ()
bool isRXFull ()
bool isRXEmpty ()
void chipEnableOn ()
void chipEnableOff ()
void chipSelect ()
void chipDeselect ()
void CEImpulse ()
void onRXDataReady ()
void onTXDataSent ()
void onMaxRetriesReached ()
Private Attributes
IIOPin * m_chipEnablePin = nullptr
IIOPin * m_chipSelectPin = nullptr
IIOPin * m_IRQPin = nullptr
IIOPin * m_NSSPin = nullptr
ISPIManager * m_spi = nullptr
bool m_useInterrupts = false
bool m_needInterrogation = false
uint8_t m_status = 0
uint8_t m_config = 0
uint8_t m_RFChannel = defaultRadioChannel
uint8_t m_TXAdress [RADIO_ADDRESS_SIZE]
uint8_t m_RXAdressP0 [RADIO_ADDRESS_SIZE]
uint8_t m_RXAdressP1 [RADIO_ADDRESS_SIZE]
uint8_t m_RXAdressP2
uint8_t m_RXAdressP3
uint8_t m_RXAdressP4
uint8_t m_RXAdressP5
DataReceiveCallback m_RXcallback = nullptr
TXMaxRetriesCallback m_TXMaxRTcallback = nullptr
TXDoneCallback m_TXDoneCallback = nullptr
Time m_lastTransmissionTime = 0
bool m_waitingForTransmissionEnd = false
bool m_debug = false
Stager m_stager {"NRF24L01Manager", 1000000}
Static Private Attributes
static constexpr uint16_t timeEnoughForTransmission = 1000
Detailed Description
Definition at line 39 of file nrf24l01.hpp.
Member Enumeration Documentation
AdressWidth
enum NRF24L01Manager::AdressWidth private
Enumerator
AW_3BYTES
AW_4BYTES
AW_5BYTES
Definition at line 110 of file nrf24l01.hpp.
Baudrate
enum NRF24L01Manager::Baudrate private
Enumerator
BR_1MBIT
BR_2MBIT
Definition at line 117 of file nrf24l01.hpp.
CRCEnableDisable
enum NRF24L01Manager::CRCEnableDisable private
Enumerator
CRC_DISABLE
CRC_ENABLE
Definition at line 98 of file nrf24l01.hpp.
CRCLen
enum NRF24L01Manager::CRCLen private
Enumerator
CRC1BYTE
CRC2BYTES
Definition at line 104 of file nrf24l01.hpp.
EnableDisable
enum NRF24L01Manager::EnableDisable
Enumerator
DISABLE_OPTION
ENABLE_OPTION
Definition at line 42 of file nrf24l01.hpp.
InterruptionsMasks
enum NRF24L01Manager::InterruptionsMasks private
Enumerator
IM_MASK_MAX_RETRIES
IM_MASK_TX_DATA_READY
IM_MASK_RX_DATA_READY
Definition at line 91 of file nrf24l01.hpp.
LNAGain
enum NRF24L01Manager::LNAGain private
Enumerator
LNA_DISABLE
LNA_ENABLE
Definition at line 131 of file nrf24l01.hpp.
Power
enum NRF24L01Manager::Power private
Enumerator
POWER_OFF
POWER_ON
Definition at line 85 of file nrf24l01.hpp.
RXTXMODE
enum NRF24L01Manager::RXTXMODE private
Enumerator
MODE_TRANSMITTER
MODE_RECEIVER
Definition at line 137 of file nrf24l01.hpp.
TXPower
enum NRF24L01Manager::TXPower private
Enumerator
PW_m18DB
PW_m12DB
PW_m6DB
PW_0DB
Definition at line 123 of file nrf24l01.hpp.
Constructor & Destructor Documentation
NRF24L01Manager()
NRF24L01Manager::NRF24L01Manager ()
Definition at line 172 of file nrf24l01.cpp.
Member Function Documentation
CEImpulse()
void NRF24L01Manager::CEImpulse () private
Definition at line 313 of file nrf24l01.cpp.
References chipEnableOff(), chipEnableOn(), systemClock, and ISystemClock::wait_us().
Referenced by sendData().
chipDeselect()
void NRF24L01Manager::chipDeselect () private
Definition at line 306 of file nrf24l01.cpp.
References m_chipSelectPin, and IIOPin::set().
Referenced by flushRX(), flushTX(), init(), readReg(), receiveData(), resetMaxRetriesReached(), resetRXDataReady(), resetTXDataSent(), sendData(), updateStatus(), and writeReg().
chipEnableOff()
void NRF24L01Manager::chipEnableOff () private
Definition at line 294 of file nrf24l01.cpp.
References m_chipEnablePin, and IIOPin::reset().
Referenced by CEImpulse(), init(), receiveData(), and switchToTX().
chipEnableOn()
void NRF24L01Manager::chipEnableOn () private
Definition at line 289 of file nrf24l01.cpp.
References m_chipEnablePin, and IIOPin::set().
Referenced by CEImpulse(), onRXDataReady(), and switchToRX().
chipSelect()
void NRF24L01Manager::chipSelect () private
Definition at line 300 of file nrf24l01.cpp.
References m_chipSelectPin, and IIOPin::reset().
Referenced by flushRX(), flushTX(), readReg(), receiveData(), resetMaxRetriesReached(), resetRXDataReady(), resetTXDataSent(), sendData(), updateStatus(), and writeReg().
clearLostPackagesCount()
void NRF24L01Manager::clearLostPackagesCount () private
Definition at line 492 of file nrf24l01.cpp.
References m_RFChannel, NRF_REG_RF_CH, and writeReg().
enableDebug()
void NRF24L01Manager::enableDebug (bool debug = true)
Definition at line 850 of file nrf24l01.cpp.
References debug, and m_debug.
enablePipe()
void NRF24L01Manager::enablePipe (uint8_t pipe, uint8_t value)
Definition at line 450 of file nrf24l01.cpp.
References NRF_REG_EN_RXADDR, readReg(), and writeReg().
Referenced by init().
extiHandler()
void NRF24L01Manager::extiHandler (bool state) private
Todo:
Create function with code below
Definition at line 829 of file nrf24l01.cpp.
References isTXDataSent(), m_needInterrogation, m_TXDoneCallback, resetTXDataSent(), switchToRX(), and updateStatus().
Referenced by init().
flushRX()
void NRF24L01Manager::flushRX ()
Definition at line 672 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), FLUSH_RX, m_spi, m_status, and ISPIManager::TransmitReceive().
flushTX()
void NRF24L01Manager::flushTX ()
Definition at line 665 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), FLUSH_TX, m_spi, m_status, and ISPIManager::TransmitReceive().
getLostPackagesCount()
unsigned char NRF24L01Manager::getLostPackagesCount () private
Definition at line 507 of file nrf24l01.cpp.
References NRF_REG_OBSERVE_TX, NRF_REGF_PLOS_CNT, and readReg().
Referenced by printStatus().
getPayloadSize()
UintParameter NRF24L01Manager::getPayloadSize () override virtual
Implements IRadioPhysicalDevice.
Definition at line 259 of file nrf24l01.cpp.
References payloadSize.
getPipeNumberAvaliableForRXFIFO()
int NRF24L01Manager::getPipeNumberAvaliableForRXFIFO () inline private
Definition at line 366 of file nrf24l01.cpp.
References m_status, and NRF_REGF_RX_P_NO_MASK.
Referenced by onRXDataReady(), and printStatus().
getResentPackagesCount()
unsigned char NRF24L01Manager::getResentPackagesCount () private
Definition at line 514 of file nrf24l01.cpp.
References NRF_REG_OBSERVE_TX, NRF_REGF_ARC_CNT_MASK, and readReg().
Referenced by printStatus().
init()
void NRF24L01Manager::init (IIOPin * chipEnablePin, IIOPin * chipSelectPin, IIOPin * IRQPin, uint8_t SPIIndex, bool useInterrupts, uint8_t radioChannel = defaultRadioChannel)
Definition at line 176 of file nrf24l01.cpp.
References AW_5BYTES, ISPIManager::BaudRatePrescaler32, BR_1MBIT, chipDeselect(), chipEnableOff(), debug, DISABLE_OPTION, ENABLE_OPTION, IIOPin::enableExti(), enablePipe(), error, extiHandler(), ISPIsPool::getSPI(), ISPIManager::init(), LNA_ENABLE, m_chipEnablePin, m_chipSelectPin, m_IRQPin, m_needInterrogation, m_RFChannel, m_spi, m_TXAdress, m_useInterrupts, payloadSize, printStatus(), PW_0DB, readRXAdresses(), readTXAdress(), setAdressWidth(), setAutoACK(), IIOPin::setExtiCallback(), setRFChannel(), setRFSettings(), setRXPayloadLength(), setupRetransmission(), SPIs, IIOPin::state(), IIOPin::switchToInput(), IIOPin::switchToOutput(), switchToRX(), and trace.
initInterrupts()
void NRF24L01Manager::initInterrupts () private
interrogate()
void NRF24L01Manager::interrogate () virtual
Implements IInterrogatable.
Definition at line 716 of file nrf24l01.cpp.
References ISystemClock::getTime(), isMaxRetriesReached(), isRXDataReady(), isTXDataSent(), m_IRQPin, m_lastTransmissionTime, m_stager, m_waitingForTransmissionEnd, onMaxRetriesReached(), onRXDataReady(), onTXDataSent(), Stager::stage(), IIOPin::state(), systemClock, timeEnoughForTransmission, and updateStatus().
isCarrierDetected()
bool NRF24L01Manager::isCarrierDetected () private
Definition at line 424 of file nrf24l01.cpp.
References NRF_REG_CD, NRF_REGF_CD, and readReg().
isMaxRetriesReached()
bool NRF24L01Manager::isMaxRetriesReached () inline private
Definition at line 361 of file nrf24l01.cpp.
References m_status, and NRF_REGF_MAX_RT.
Referenced by interrogate(), and printStatus().
isReuseEnabled()
bool NRF24L01Manager::isReuseEnabled () private
Definition at line 599 of file nrf24l01.cpp.
References NRF_REG_FIFO_STATUS, NRF_REGF_FIFO_TX_REUSE, and readReg().
Referenced by printStatus().
isRXDataReady()
bool NRF24L01Manager::isRXDataReady () inline private
Definition at line 351 of file nrf24l01.cpp.
References m_status, and NRF_REGF_RX_DR.
Referenced by interrogate(), and printStatus().
isRXEmpty()
bool NRF24L01Manager::isRXEmpty () private
Definition at line 627 of file nrf24l01.cpp.
References NRF_REG_FIFO_STATUS, NRF_REGF_FIFO_RX_EMPTY, and readReg().
Referenced by onRXDataReady(), and printStatus().
isRXFull()
bool NRF24L01Manager::isRXFull () private
Definition at line 620 of file nrf24l01.cpp.
References NRF_REG_FIFO_STATUS, NRF_REGF_FIFO_RX_FULL, and readReg().
Referenced by printStatus().
isTXDataSent()
bool NRF24L01Manager::isTXDataSent () inline private
Definition at line 356 of file nrf24l01.cpp.
References m_status, and NRF_REGF_TX_DS.
Referenced by extiHandler(), interrogate(), and printStatus().
isTXEmpty()
bool NRF24L01Manager::isTXEmpty () private
Definition at line 613 of file nrf24l01.cpp.
References NRF_REG_FIFO_STATUS, NRF_REGF_FIFO_TX_EMPTY, and readReg().
Referenced by printStatus().
isTXFIFOFull()
bool NRF24L01Manager::isTXFIFOFull () inline private
Definition at line 371 of file nrf24l01.cpp.
References m_status, and NRF_REGF_TX_FULL.
isTXFull()
bool NRF24L01Manager::isTXFull () private
Definition at line 606 of file nrf24l01.cpp.
References NRF_REG_FIFO_STATUS, NRF_REGF_FIFO_TX_FULL, and readReg().
Referenced by printStatus().
onMaxRetriesReached()
void NRF24L01Manager::onMaxRetriesReached () private
Definition at line 812 of file nrf24l01.cpp.
References m_RFChannel, m_stager, m_TXMaxRTcallback, resetMaxRetriesReached(), setRFChannel(), and Stager::stage().
Referenced by interrogate().
onRXDataReady()
void NRF24L01Manager::onRXDataReady () private
Definition at line 786 of file nrf24l01.cpp.
References chipEnableOn(), getPipeNumberAvaliableForRXFIFO(), isRXEmpty(), m_debug, m_RXcallback, m_stager, payloadSize, printHex(), receiveData(), resetRXDataReady(), Stager::stage(), and trace.
Referenced by interrogate().
onTXDataSent()
void NRF24L01Manager::onTXDataSent () private
Definition at line 772 of file nrf24l01.cpp.
References m_stager, m_TXDoneCallback, m_waitingForTransmissionEnd, resetTXDataSent(), Stager::stage(), and switchToRX().
Referenced by interrogate().
printStatus()
void NRF24L01Manager::printStatus () override virtual
Implements IRadioPhysicalDevice.
Definition at line 679 of file nrf24l01.cpp.
References getLostPackagesCount(), getPipeNumberAvaliableForRXFIFO(), getResentPackagesCount(), isMaxRetriesReached(), isReuseEnabled(), isRXDataReady(), isRXEmpty(), isRXFull(), isTXDataSent(), isTXEmpty(), isTXFull(), m_RXAdressP0, m_RXAdressP1, m_RXAdressP2, m_RXAdressP3, m_RXAdressP4, m_RXAdressP5, m_status, m_TXAdress, readRXAdresses(), readTXAdress(), and updateStatus().
Referenced by init().
readReg()
void NRF24L01Manager::readReg (uint8_t reg, uint8_t size, uint8_t * data) private
Definition at line 333 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, m_status, R_REGISTER, ISPIManager::Receive(), and ISPIManager::TransmitReceive().
Referenced by enablePipe(), getLostPackagesCount(), getResentPackagesCount(), isCarrierDetected(), isReuseEnabled(), isRXEmpty(), isRXFull(), isTXEmpty(), isTXFull(), readRXAdresses(), readTXAdress(), and setAutoACK().
readRXAdresses()
void NRF24L01Manager::readRXAdresses () private
Definition at line 556 of file nrf24l01.cpp.
References m_RXAdressP0, m_RXAdressP1, m_RXAdressP2, m_RXAdressP3, m_RXAdressP4, m_RXAdressP5, NRF_REG_RX_ADDR_P0, NRF_REG_RX_ADDR_P1, NRF_REG_RX_ADDR_P2, NRF_REG_RX_ADDR_P3, NRF_REG_RX_ADDR_P4, NRF_REG_RX_ADDR_P5, and readReg().
Referenced by init(), and printStatus().
readTXAdress()
void NRF24L01Manager::readTXAdress () private
Definition at line 574 of file nrf24l01.cpp.
References m_TXAdress, NRF_REG_TX_ADDR, RADIO_ADDRESS_SIZE, and readReg().
Referenced by init(), and printStatus().
receiveData()
void NRF24L01Manager::receiveData (uint8_t size, uint8_t * data) private
Definition at line 654 of file nrf24l01.cpp.
References chipDeselect(), chipEnableOff(), chipSelect(), m_spi, m_stager, m_status, R_RX_PAYLOAD, ISPIManager::Receive(), Stager::stage(), and ISPIManager::TransmitReceive().
Referenced by onRXDataReady().
resetAllIRQ()
void NRF24L01Manager::resetAllIRQ ()
Definition at line 709 of file nrf24l01.cpp.
References resetMaxRetriesReached(), resetRXDataReady(), and resetTXDataSent().
resetMaxRetriesReached()
void NRF24L01Manager::resetMaxRetriesReached () private
Definition at line 394 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, NRF_REG_STATUS, NRF_REGF_MAX_RT, ISPIManager::Transmit(), updateStatus(), and W_REGISTER.
Referenced by onMaxRetriesReached(), and resetAllIRQ().
resetRXDataReady()
void NRF24L01Manager::resetRXDataReady () private
Definition at line 376 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, NRF_REG_STATUS, NRF_REGF_RX_DR, ISPIManager::Transmit(), updateStatus(), and W_REGISTER.
Referenced by onRXDataReady(), and resetAllIRQ().
resetTXDataSent()
void NRF24L01Manager::resetTXDataSent () private
Definition at line 385 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, NRF_REG_STATUS, NRF_REGF_TX_DS, ISPIManager::Transmit(), updateStatus(), and W_REGISTER.
Referenced by extiHandler(), onTXDataSent(), and resetAllIRQ().
sendData()
void NRF24L01Manager::sendData (uint8_t size, uint8_t * data) override virtual
Implements IRadioPhysicalDevice.
Definition at line 636 of file nrf24l01.cpp.
References CEImpulse(), chipDeselect(), chipSelect(), ISystemClock::getTime(), m_debug, m_lastTransmissionTime, m_spi, m_status, m_waitingForTransmissionEnd, printHex(), switchToTX(), systemClock, trace, ISPIManager::Transmit(), ISPIManager::TransmitReceive(), and W_TX_PAYLOAD.
setAdressWidth()
void NRF24L01Manager::setAdressWidth (AdressWidth width) private
Definition at line 464 of file nrf24l01.cpp.
References AW_3BYTES, AW_4BYTES, AW_5BYTES, NRF_REG_SETUP_AW, and writeReg().
Referenced by init().
setAutoACK()
void NRF24L01Manager::setAutoACK (uint8_t channel, bool value) private
Definition at line 434 of file nrf24l01.cpp.
References NRF_REG_EN_AA, readReg(), and writeReg().
Referenced by init().
setConfig()
void NRF24L01Manager::setConfig (uint8_t interruptionsMask, uint8_t enableCRC, uint8_t CRC2bytes, uint8_t powerUP, uint8_t isRecieving) private
Definition at line 406 of file nrf24l01.cpp.
References m_config, NRF_REG_CONFIG, NRF_REGF_CRCO, NRF_REGF_EN_CRC, NRF_REGF_MASK_MAX_RT, NRF_REGF_PRIM_RX, NRF_REGF_PWR_UP, and writeReg().
Referenced by switchToRX(), and switchToTX().
setDataReceiveCallback()
void NRF24L01Manager::setDataReceiveCallback (DataReceiveCallback callback) override virtual
Implements IRadioPhysicalDevice.
Definition at line 254 of file nrf24l01.cpp.
References m_RXcallback.
setRFChannel()
void NRF24L01Manager::setRFChannel (uint8_t number) private
Definition at line 486 of file nrf24l01.cpp.
References m_RFChannel, NRF_REG_RF_CH, and writeReg().
Referenced by init(), and onMaxRetriesReached().
setRFSettings()
void NRF24L01Manager::setRFSettings (uint8_t use2MBits, uint8_t power, uint8_t LNAGain) private
Definition at line 499 of file nrf24l01.cpp.
References NRF_REG_RF_SETUP, NRF_REGF_LNA_HCURR, NRF_REGF_RF_DR, NRF_REGF_RF_PWR, and writeReg().
Referenced by init().
setRXAddress()
void NRF24L01Manager::setRXAddress (uint8_t channel, uint8_t * address) override virtual
Implements IRadioPhysicalDevice.
Definition at line 523 of file nrf24l01.cpp.
References m_RXAdressP0, m_RXAdressP1, m_RXAdressP2, m_RXAdressP3, m_RXAdressP4, m_RXAdressP5, NRF_REG_RX_ADDR_P0, NRF_REG_RX_ADDR_P1, NRF_REG_RX_ADDR_P2, NRF_REG_RX_ADDR_P3, NRF_REG_RX_ADDR_P4, NRF_REG_RX_ADDR_P5, RADIO_ADDRESS_SIZE, and writeReg().
setRXPayloadLength()
void NRF24L01Manager::setRXPayloadLength (uint8_t channel, uint8_t payloadLength) private
Definition at line 581 of file nrf24l01.cpp.
References NRF_REG_RX_PW_P0, NRF_REG_RX_PW_P1, NRF_REG_RX_PW_P2, NRF_REG_RX_PW_P3, NRF_REG_RX_PW_P4, NRF_REG_RX_PW_P5, and writeReg().
Referenced by init().
setTXAddress()
void NRF24L01Manager::setTXAddress (uint8_t * address) override virtual
Implements IRadioPhysicalDevice.
Definition at line 568 of file nrf24l01.cpp.
References m_TXAdress, NRF_REG_TX_ADDR, RADIO_ADDRESS_SIZE, and writeReg().
setTXDoneCallback()
void NRF24L01Manager::setTXDoneCallback (TXDoneCallback callback) override virtual
Implements IRadioPhysicalDevice.
Definition at line 269 of file nrf24l01.cpp.
References m_TXDoneCallback.
setTXMaxRetriesCallback()
void NRF24L01Manager::setTXMaxRetriesCallback (TXMaxRetriesCallback callback)
Definition at line 264 of file nrf24l01.cpp.
References m_TXMaxRTcallback.
setupRetransmission()
void NRF24L01Manager::setupRetransmission (uint8_t delay, uint8_t count) private
Definition at line 478 of file nrf24l01.cpp.
References NRF_REG_SETUP_RETR, NRF_REGF_ARC, NRF_REGF_ARD, and writeReg().
Referenced by init().
switchToReceiver()
void NRF24L01Manager::switchToReceiver () private
switchToRX()
void NRF24L01Manager::switchToRX () private
Definition at line 281 of file nrf24l01.cpp.
References chipEnableOn(), CRC2BYTES, CRC_ENABLE, IM_MASK_MAX_RETRIES, MODE_RECEIVER, POWER_ON, setConfig(), systemClock, and ISystemClock::wait_us().
Referenced by extiHandler(), init(), and onTXDataSent().
switchToTranmitter()
void NRF24L01Manager::switchToTranmitter () private
switchToTX()
void NRF24L01Manager::switchToTX () private
Definition at line 274 of file nrf24l01.cpp.
References chipEnableOff(), CRC2BYTES, CRC_ENABLE, IM_MASK_MAX_RETRIES, MODE_TRANSMITTER, POWER_ON, setConfig(), systemClock, and ISystemClock::wait_us().
Referenced by sendData().
updateStatus()
void NRF24L01Manager::updateStatus () private
Definition at line 341 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, m_stager, m_status, NRF_NOP, Stager::stage(), and ISPIManager::TransmitReceive().
Referenced by extiHandler(), interrogate(), printStatus(), resetMaxRetriesReached(), resetRXDataReady(), and resetTXDataSent().
writeReg()
void NRF24L01Manager::writeReg (uint8_t reg, uint8_t size, uint8_t * data) private
Definition at line 324 of file nrf24l01.cpp.
References chipDeselect(), chipSelect(), m_spi, m_status, ISPIManager::Transmit(), ISPIManager::TransmitReceive(), and W_REGISTER.
Referenced by clearLostPackagesCount(), enablePipe(), setAdressWidth(), setAutoACK(), setConfig(), setRFChannel(), setRFSettings(), setRXAddress(), setRXPayloadLength(), setTXAddress(), and setupRetransmission().
Member Data Documentation
defaultRadioChannel
constexpr uint8_t NRF24L01Manager::defaultRadioChannel = 1 static
Definition at line 49 of file nrf24l01.hpp.
m_chipEnablePin
IIOPin* NRF24L01Manager::m_chipEnablePin = nullptr private
Definition at line 228 of file nrf24l01.hpp.
Referenced by chipEnableOff(), chipEnableOn(), and init().
m_chipSelectPin
IIOPin* NRF24L01Manager::m_chipSelectPin = nullptr private
Definition at line 229 of file nrf24l01.hpp.
Referenced by chipDeselect(), chipSelect(), and init().
m_config
uint8_t NRF24L01Manager::m_config = 0 private
Definition at line 239 of file nrf24l01.hpp.
Referenced by setConfig().
m_debug
bool NRF24L01Manager::m_debug = false private
Definition at line 256 of file nrf24l01.hpp.
Referenced by enableDebug(), onRXDataReady(), and sendData().
m_IRQPin
IIOPin* NRF24L01Manager::m_IRQPin = nullptr private
Definition at line 230 of file nrf24l01.hpp.
Referenced by init(), and interrogate().
m_lastTransmissionTime
Time NRF24L01Manager::m_lastTransmissionTime = 0 private
Definition at line 253 of file nrf24l01.hpp.
Referenced by interrogate(), and sendData().
m_needInterrogation
bool NRF24L01Manager::m_needInterrogation = false private
Definition at line 236 of file nrf24l01.hpp.
Referenced by extiHandler(), and init().
m_NSSPin
IIOPin* NRF24L01Manager::m_NSSPin = nullptr private
Definition at line 231 of file nrf24l01.hpp.
m_RFChannel
uint8_t NRF24L01Manager::m_RFChannel = defaultRadioChannel private
Definition at line 240 of file nrf24l01.hpp.
Referenced by clearLostPackagesCount(), init(), onMaxRetriesReached(), and setRFChannel().
m_RXAdressP0
uint8_t NRF24L01Manager::m_RXAdressP0[RADIO_ADDRESS_SIZE] private
Definition at line 242 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXAdressP1
uint8_t NRF24L01Manager::m_RXAdressP1[RADIO_ADDRESS_SIZE] private
Definition at line 243 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXAdressP2
uint8_t NRF24L01Manager::m_RXAdressP2 private
Definition at line 244 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXAdressP3
uint8_t NRF24L01Manager::m_RXAdressP3 private
Definition at line 245 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXAdressP4
uint8_t NRF24L01Manager::m_RXAdressP4 private
Definition at line 246 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXAdressP5
uint8_t NRF24L01Manager::m_RXAdressP5 private
Definition at line 247 of file nrf24l01.hpp.
Referenced by printStatus(), readRXAdresses(), and setRXAddress().
m_RXcallback
DataReceiveCallback NRF24L01Manager::m_RXcallback = nullptr private
Definition at line 249 of file nrf24l01.hpp.
Referenced by onRXDataReady(), and setDataReceiveCallback().
m_spi
ISPIManager* NRF24L01Manager::m_spi = nullptr private
Definition at line 232 of file nrf24l01.hpp.
Referenced by flushRX(), flushTX(), init(), readReg(), receiveData(), resetMaxRetriesReached(), resetRXDataReady(), resetTXDataSent(), sendData(), updateStatus(), and writeReg().
m_stager
Stager NRF24L01Manager::m_stager {"NRF24L01Manager", 1000000} private
Definition at line 258 of file nrf24l01.hpp.
Referenced by interrogate(), onMaxRetriesReached(), onRXDataReady(), onTXDataSent(), receiveData(), and updateStatus().
m_status
uint8_t NRF24L01Manager::m_status = 0 private
Definition at line 238 of file nrf24l01.hpp.
Referenced by flushRX(), flushTX(), getPipeNumberAvaliableForRXFIFO(), isMaxRetriesReached(), isRXDataReady(), isTXDataSent(), isTXFIFOFull(), printStatus(), readReg(), receiveData(), sendData(), updateStatus(), and writeReg().
m_TXAdress
uint8_t NRF24L01Manager::m_TXAdress[RADIO_ADDRESS_SIZE] private
Definition at line 241 of file nrf24l01.hpp.
Referenced by init(), printStatus(), readTXAdress(), and setTXAddress().
m_TXDoneCallback
TXDoneCallback NRF24L01Manager::m_TXDoneCallback = nullptr private
Definition at line 251 of file nrf24l01.hpp.
Referenced by extiHandler(), onTXDataSent(), and setTXDoneCallback().
m_TXMaxRTcallback
TXMaxRetriesCallback NRF24L01Manager::m_TXMaxRTcallback = nullptr private
Definition at line 250 of file nrf24l01.hpp.
Referenced by onMaxRetriesReached(), and setTXMaxRetriesCallback().
m_useInterrupts
bool NRF24L01Manager::m_useInterrupts = false private
Definition at line 234 of file nrf24l01.hpp.
Referenced by init().
m_waitingForTransmissionEnd
bool NRF24L01Manager::m_waitingForTransmissionEnd = false private
Definition at line 254 of file nrf24l01.hpp.
Referenced by interrogate(), onTXDataSent(), and sendData().
payloadSize
constexpr unsigned int NRF24L01Manager::payloadSize = 32 static
Definition at line 48 of file nrf24l01.hpp.
Referenced by getPayloadSize(), init(), and onRXDataReady().
timeEnoughForTransmission
constexpr uint16_t NRF24L01Manager::timeEnoughForTransmission = 1000 static private
Definition at line 143 of file nrf24l01.hpp.
Referenced by interrogate().
The documentation for this class was generated from the following files:
include/dev/nrf24l01.hpp
src/dev/nrf24l01.cpp