Caustic lasertag system: IFireEmitter Class Reference
IFireEmitter Class Reference abstract
#include <fire-emitter.hpp>
Public Member Functions
virtual ~IFireEmitter ()
virtual void init (const Pinout &pinout)=0
virtual void setCallback (FireEmitterCallback callback)=0
virtual void startImpulsePack (bool isLedOn, unsigned int delayMs)=0
virtual void setPower (UintParameter powerPercent)=0
virtual void setChannel (unsigned int channel)=0
virtual void setCarrierFrequency (uint32_t frequency)=0
Detailed Description
Definition at line 33 of file fire-emitter.hpp.
Constructor & Destructor Documentation
~IFireEmitter()
virtual IFireEmitter::~IFireEmitter () inline virtual
Definition at line 36 of file fire-emitter.hpp.
References init(), setCallback(), setCarrierFrequency(), setChannel(), setPower(), and startImpulsePack().
Member Function Documentation
init()
virtual void IFireEmitter::init (const Pinout & pinout) pure virtual
Implemented in LEDFireEmitter.
Referenced by IRTransmitterTV::init(), and ~IFireEmitter().
setCallback()
virtual void IFireEmitter::setCallback (FireEmitterCallback callback) pure virtual
Implemented in FireEmitterBase.
Referenced by IRTransmitterTV::init(), and ~IFireEmitter().
setCarrierFrequency()
virtual void IFireEmitter::setCarrierFrequency (uint32_t frequency) pure virtual
Implemented in LEDFireEmitter.
Referenced by ~IFireEmitter().
setChannel()
virtual void IFireEmitter::setChannel (unsigned int channel) pure virtual
Implemented in LEDFireEmitter.
Referenced by ~IFireEmitter().
setPower()
virtual void IFireEmitter::setPower (UintParameter powerPercent) pure virtual
Implemented in LEDFireEmitter.
Referenced by IRTransmitterTV::send(), and ~IFireEmitter().
startImpulsePack()
virtual void IFireEmitter::startImpulsePack (bool isLedOn, unsigned int delayMs) pure virtual
Implemented in LEDFireEmitter.
Referenced by IRTransmitterTV::emitterCallback(), IRTransmitterTV::send(), and ~IFireEmitter().
The documentation for this class was generated from the following file:
include/hal/fire-emitter.hpp