Caustic lasertag system: SmartPointLCD5110Display Class Reference
SmartPointLCD5110Display Class Reference
#include <smart-point-display.hpp>
Public Member Functions
SmartPointLCD5110Display ()
void update ()
void init ()
Private Attributes
LCD5110Controller m_lcd
Detailed Description
Definition at line 30 of file smart-point-display.hpp.
Constructor & Destructor Documentation
SmartPointLCD5110Display()
SmartPointLCD5110Display::SmartPointLCD5110Display ()
Definition at line 28 of file smart-point-display.cpp.
Member Function Documentation
init()
void SmartPointLCD5110Display::init ()
Definition at line 44 of file smart-point-display.cpp.
update()
void SmartPointLCD5110Display::update ()
Definition at line 33 of file smart-point-display.cpp.
References LCD5110Controller::clearBuffer(), LCD5110Controller::configureSPI(), LCD5110Controller::fontStandardAscii5x7, m_lcd, LCD5110Controller::setFont(), LCD5110Controller::stringXY(), and LCD5110Controller::write().
Member Data Documentation
m_lcd
LCD5110Controller SmartPointLCD5110Display::m_lcd private
Definition at line 39 of file smart-point-display.hpp.
Referenced by update().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-display.hpp
src/smart-point/smart-point-display.cpp