Caustic lasertag system: TasksPool Class Reference
TasksPool Class Reference
Tasks pool with cooperative multitasking. One class instance = one OS thread.
#include <os-wrappers.hpp>
Classes
struct TaskContext
Public Types
using TaskId = uint16_t
Public Member Functions
TasksPool (const char *name="UnkPool")
TaskId add (STask &&newTask, uint32_t period, uint32_t firstDelay=0, uint32_t count=0, uint32_t lifetime=0)
TaskId addOnce (STask &&newTask, uint32_t firstDelay)
void stop (TaskId id)
void setStackSize (uint16_t stackSize)
void setName (char *name)
void run (uint32_t sleepTime=1)
Private Member Functions
void main ()
Private Attributes
std::list< TaskContext > m_runningTasks
Mutex m_taskModifyMutex
One mutex for both add and delete task lists, because actual adding and deleting operations are quick.
std::list< TaskContext > m_tasksToAdd
std::list< TaskId > m_idsToDelete
TaskId m_nextTaskId = 1
TaskCycled m_poolThread
char * m_name
Detailed Description
Tasks pool with cooperative multitasking. One class instance = one OS thread.
Definition at line 287 of file os-wrappers.hpp.
Member Typedef Documentation
TaskId
using TasksPool::TaskId = uint16_t
Definition at line 290 of file os-wrappers.hpp.
Constructor & Destructor Documentation
TasksPool()
TasksPool::TasksPool (const char * name = "UnkPool")
Definition at line 292 of file os-wrappers.cpp.
References m_poolThread, main(), and TaskBase::setTask().
Member Function Documentation
add()
TasksPool::TaskId TasksPool::add (STask && newTask, uint32_t period, uint32_t firstDelay = 0, uint32_t count = 0, uint32_t lifetime = 0)
Definition at line 298 of file os-wrappers.cpp.
References ISystemClock::getTime(), m_nextTaskId, m_taskModifyMutex, m_tasksToAdd, TasksPool::TaskContext::period, TasksPool::TaskContext::repetitionsCountMax, systemClock, TasksPool::TaskContext::task, TasksPool::TaskContext::taskId, TasksPool::TaskContext::timeout, and TasksPool::TaskContext::timeToRun.
Referenced by addOnce(), and SmartPoint::init().
addOnce()
TasksPool::TaskId TasksPool::addOnce (STask && newTask, uint32_t firstDelay)
Definition at line 320 of file os-wrappers.cpp.
References add().
Referenced by delayedSwitchPin().
main()
void TasksPool::main () private
Definition at line 349 of file os-wrappers.cpp.
References ISystemClock::getTime(), Mutex::lock(), m_idsToDelete, m_runningTasks, m_taskModifyMutex, m_tasksToAdd, systemClock, and Mutex::unlock().
Referenced by TasksPool().
run()
void TasksPool::run (uint32_t sleepTime = 1)
Definition at line 337 of file os-wrappers.cpp.
References m_name, m_poolThread, TaskCycled::run(), and TaskBase::setName().
Referenced by SmartPoint::init().
setName()
void TasksPool::setName (char * name)
Definition at line 331 of file os-wrappers.cpp.
References m_name.
setStackSize()
void TasksPool::setStackSize (uint16_t stackSize)
Definition at line 326 of file os-wrappers.cpp.
References m_poolThread, and TaskBase::setStackSize().
Referenced by SmartPoint::SmartPoint().
stop()
void TasksPool::stop (TaskId id)
Definition at line 343 of file os-wrappers.cpp.
References m_idsToDelete, and m_taskModifyMutex.
Member Data Documentation
m_idsToDelete
std::list<TaskId> TasksPool::m_idsToDelete private
Definition at line 317 of file os-wrappers.hpp.
Referenced by main(), and stop().
m_name
char* TasksPool::m_name private
Definition at line 321 of file os-wrappers.hpp.
Referenced by run(), and setName().
m_nextTaskId
TaskId TasksPool::m_nextTaskId = 1 private
Definition at line 318 of file os-wrappers.hpp.
Referenced by add().
m_poolThread
TaskCycled TasksPool::m_poolThread private
Definition at line 320 of file os-wrappers.hpp.
Referenced by run(), setStackSize(), and TasksPool().
m_runningTasks
std::list<TaskContext> TasksPool::m_runningTasks private
Definition at line 313 of file os-wrappers.hpp.
Referenced by main().
m_taskModifyMutex
Mutex TasksPool::m_taskModifyMutex private
One mutex for both add and delete task lists, because actual adding and deleting operations are quick.
Definition at line 315 of file os-wrappers.hpp.
Referenced by add(), main(), and stop().
m_tasksToAdd
std::list<TaskContext> TasksPool::m_tasksToAdd private
Definition at line 316 of file os-wrappers.hpp.
Referenced by add(), and main().
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp