Caustic lasertag system: ConnectedWeaponsList Class Reference
ConnectedWeaponsList Class Reference
#include <head-sensor-base-types.hpp>
Public Member Functions
void deserialize (void *source, OperationSize size)
void serialize (void *destination)
uint32_t serializedSize ()
void setWeaponObserverFactory (const IWeaponObserverFactory *factory)
void clear ()
void insert (DeviceAddress addr)
void remove (DeviceAddress addr)
bool empty ()
const std::map< DeviceAddress, IWeaponObresver * > & weapons ()
Private Attributes
const IWeaponObserverFactory * m_factory = nullptr
std::map< DeviceAddress, IWeaponObresver * > m_weapons
Detailed Description
Definition at line 46 of file head-sensor-base-types.hpp.
Member Function Documentation
clear()
void ConnectedWeaponsList::clear ()
Definition at line 75 of file head-sensor-base-types.cpp.
References m_weapons.
deserialize()
void ConnectedWeaponsList::deserialize (void * source, OperationSize size)
Definition at line 30 of file head-sensor-base-types.cpp.
References ADDRESS_TO_STREAM, deserializeAndInc(), error, info, insert(), m_weapons, and trace.
empty()
bool ConnectedWeaponsList::empty ()
insert()
void ConnectedWeaponsList::insert (DeviceAddress addr)
Definition at line 80 of file head-sensor-base-types.cpp.
References IWeaponObresver::assign(), IWeaponObserverFactory::create(), error, m_factory, and m_weapons.
Referenced by deserialize().
remove()
void ConnectedWeaponsList::remove (DeviceAddress addr)
Definition at line 94 of file head-sensor-base-types.cpp.
References m_weapons.
serialize()
void ConnectedWeaponsList::serialize (void * destination)
Definition at line 51 of file head-sensor-base-types.cpp.
References m_weapons, serializeAndInc(), and trace.
serializedSize()
uint32_t ConnectedWeaponsList::serializedSize ()
Definition at line 65 of file head-sensor-base-types.cpp.
References m_weapons.
setWeaponObserverFactory()
void ConnectedWeaponsList::setWeaponObserverFactory (const IWeaponObserverFactory * factory)
Definition at line 70 of file head-sensor-base-types.cpp.
References factory, and m_factory.
weapons()
const std::map< DeviceAddress, IWeaponObresver * > & ConnectedWeaponsList::weapons ()
Definition at line 104 of file head-sensor-base-types.cpp.
References m_weapons.
Member Data Documentation
m_factory
const IWeaponObserverFactory* ConnectedWeaponsList::m_factory = nullptr private
Definition at line 64 of file head-sensor-base-types.hpp.
Referenced by insert(), and setWeaponObserverFactory().
m_weapons
std::map<DeviceAddress, IWeaponObresver*> ConnectedWeaponsList::m_weapons private
Definition at line 65 of file head-sensor-base-types.hpp.
Referenced by clear(), deserialize(), insert(), remove(), serialize(), serializedSize(), and weapons().
The documentation for this class was generated from the following files:
include/head-sensor/head-sensor-base-types.hpp
src/head-sensor/head-sensor-base-types.cpp