Caustic lasertag system: Stager Class Reference
Stager Class Reference
#include <diagnostic.hpp>
Classes
struct StagerRec
Public Member Functions
Stager (const char *name="", Time aliveCheckPeriod=0)
void stage (const char *description)
void setName (const char *name)
void printStages () const
Private Attributes
StagerRec m_stagesRingBuffer [ringBufferSize]
uint8_t m_pointer = 0
const char * m_name
Time m_aliveCheckPeriod = 0
Static Private Attributes
static constexpr uint8_t ringBufferSize = 10
Detailed Description
Definition at line 50 of file diagnostic.hpp.
Constructor & Destructor Documentation
Stager()
Stager::Stager (const char * name = "", Time aliveCheckPeriod = 0)
Definition at line 34 of file diagnostic.cpp.
References instance.
Member Function Documentation
printStages()
void Stager::printStages () const
Definition at line 60 of file diagnostic.cpp.
References debug, Stager::StagerRec::description, ISystemClock::getTime(), m_aliveCheckPeriod, m_name, m_pointer, m_stagesRingBuffer, ringBufferSize, systemClock, and Stager::StagerRec::t.
setName()
void Stager::setName (const char * name)
Definition at line 55 of file diagnostic.cpp.
References m_name.
stage()
void Stager::stage (const char * description)
Definition at line 44 of file diagnostic.cpp.
References Stager::StagerRec::description, ISystemClock::getTime(), m_pointer, m_stagesRingBuffer, ringBufferSize, systemClock, and Stager::StagerRec::t.
Referenced by NRF24L01Manager::interrogate(), NetworkLayer::interrogate(), NRF24L01Manager::onMaxRetriesReached(), NRF24L01Manager::onRXDataReady(), NRF24L01Manager::onTXDataSent(), NetworkLayer::printAndSend(), NRF24L01Manager::receiveData(), NetworkLayer::RXCallback(), NetworkLayer::send(), NetworkLayer::sendNext(), and NRF24L01Manager::updateStatus().
Member Data Documentation
m_aliveCheckPeriod
Time Stager::m_aliveCheckPeriod = 0 private
Definition at line 70 of file diagnostic.hpp.
Referenced by printStages().
m_name
const char* Stager::m_name private
Definition at line 69 of file diagnostic.hpp.
Referenced by printStages(), and setName().
m_pointer
uint8_t Stager::m_pointer = 0 private
Definition at line 67 of file diagnostic.hpp.
Referenced by printStages(), and stage().
m_stagesRingBuffer
StagerRec Stager::m_stagesRingBuffer[ringBufferSize] private
Definition at line 66 of file diagnostic.hpp.
Referenced by printStages(), and stage().
ringBufferSize
constexpr uint8_t Stager::ringBufferSize = 10 static private
Definition at line 64 of file diagnostic.hpp.
Referenced by printStages(), and stage().
The documentation for this class was generated from the following files:
include/core/diagnostic.hpp
src/core/diagnostic.cpp