Caustic lasertag system: MatrixKeyboard Class Reference
MatrixKeyboard Class Reference
#include <matrix-keyboard.hpp>
Public Member Functions
void init (uint8_t rowCount, uint8_t colCount, IIOPin **row, IIOPin **col)
uint8_t getKeyPressed ()
Static Public Attributes
static constexpr TimeInterval antiBounceDelay = 100000
static constexpr uint8_t keyA = 'A'
static constexpr uint8_t keyB = 'B'
static constexpr uint8_t keyC = 'C'
static constexpr uint8_t keyD = 'D'
static constexpr uint8_t keySharp = '#'
static constexpr uint8_t keyAsterisk = '*'
static constexpr uint8_t keyNotPressed = 254
static constexpr uint8_t keyInvalid = 255
Static Private Member Functions
static uint8_t parseKey (uint8_t row, uint8_t col)
Private Attributes
uint8_t m_rowCount = 0
uint8_t m_colCount = 0
IIOPin ** m_row = nullptr
IIOPin ** m_col = nullptr
Time m_lastKeypressTime = 0
Detailed Description
Definition at line 31 of file matrix-keyboard.hpp.
Member Function Documentation
getKeyPressed()
uint8_t MatrixKeyboard::getKeyPressed ()
Definition at line 46 of file matrix-keyboard.cpp.
References antiBounceDelay, ISystemClock::getTime(), keyNotPressed, m_col, m_colCount, m_lastKeypressTime, m_row, m_rowCount, parseKey(), IIOPin::reset(), IIOPin::set(), systemClock, and ISystemClock::wait_us().
Referenced by UIInitScreen::doIteration(), and UITimeLeftScreen::doIteration().
init()
void MatrixKeyboard::init (uint8_t rowCount, uint8_t colCount, IIOPin ** row, IIOPin ** col)
Definition at line 28 of file matrix-keyboard.cpp.
References m_col, m_colCount, m_row, m_rowCount, IIOPin::set(), IIOPin::switchToInput(), and IIOPin::switchToOutput().
Referenced by SmartPointUI::initKbd().
parseKey()
uint8_t MatrixKeyboard::parseKey (uint8_t row, uint8_t col) static private
Definition at line 68 of file matrix-keyboard.cpp.
References keyA, keyAsterisk, keyInvalid, and keySharp.
Referenced by getKeyPressed().
Member Data Documentation
antiBounceDelay
constexpr TimeInterval MatrixKeyboard::antiBounceDelay = 100000 static
Definition at line 34 of file matrix-keyboard.hpp.
Referenced by getKeyPressed().
keyA
constexpr uint8_t MatrixKeyboard::keyA = 'A' static
Definition at line 36 of file matrix-keyboard.hpp.
Referenced by parseKey().
keyAsterisk
constexpr uint8_t MatrixKeyboard::keyAsterisk = '*' static
Definition at line 41 of file matrix-keyboard.hpp.
Referenced by parseKey().
keyB
constexpr uint8_t MatrixKeyboard::keyB = 'B' static
Definition at line 37 of file matrix-keyboard.hpp.
keyC
constexpr uint8_t MatrixKeyboard::keyC = 'C' static
Definition at line 38 of file matrix-keyboard.hpp.
keyD
constexpr uint8_t MatrixKeyboard::keyD = 'D' static
Definition at line 39 of file matrix-keyboard.hpp.
keyInvalid
constexpr uint8_t MatrixKeyboard::keyInvalid = 255 static
Definition at line 43 of file matrix-keyboard.hpp.
Referenced by parseKey().
keyNotPressed
constexpr uint8_t MatrixKeyboard::keyNotPressed = 254 static
Definition at line 42 of file matrix-keyboard.hpp.
Referenced by UITimeLeftScreen::doIteration(), and getKeyPressed().
keySharp
constexpr uint8_t MatrixKeyboard::keySharp = '#' static
Definition at line 40 of file matrix-keyboard.hpp.
Referenced by parseKey().
m_col
IIOPin** MatrixKeyboard::m_col = nullptr private
Definition at line 54 of file matrix-keyboard.hpp.
Referenced by getKeyPressed(), and init().
m_colCount
uint8_t MatrixKeyboard::m_colCount = 0 private
Definition at line 52 of file matrix-keyboard.hpp.
Referenced by getKeyPressed(), and init().
m_lastKeypressTime
Time MatrixKeyboard::m_lastKeypressTime = 0 private
Definition at line 56 of file matrix-keyboard.hpp.
Referenced by getKeyPressed().
m_row
IIOPin** MatrixKeyboard::m_row = nullptr private
Definition at line 53 of file matrix-keyboard.hpp.
Referenced by getKeyPressed(), and init().
m_rowCount
uint8_t MatrixKeyboard::m_rowCount = 0 private
Definition at line 51 of file matrix-keyboard.hpp.
Referenced by getKeyPressed(), and init().
The documentation for this class was generated from the following files:
include/dev/matrix-keyboard.hpp
src/dev/matrix-keyboard.cpp