Caustic lasertag system: IIRPresentationReceiver Class Reference
IIRPresentationReceiver Class Reference abstract
#include <ir-presentation.hpp>
Public Member Functions
virtual ~IIRPresentationReceiver ()
virtual void init ()=0
virtual void setPhysicalReceiver (IIRPhysicalReceiver *receiver)=0
virtual void assignReceiversGroup (IPresentationReceiversGroup &group)=0
virtual void setDamageCoefficient (const FloatParameter *coefficient)=0
virtual void setVibroEngine (IIOPin *pin)=0
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
virtual void interrogate ()=0
Detailed Description
Definition at line 33 of file ir-presentation.hpp.
Constructor & Destructor Documentation
~IIRPresentationReceiver()
virtual IIRPresentationReceiver::~IIRPresentationReceiver () inline virtual
Definition at line 36 of file ir-presentation.hpp.
References assignReceiversGroup(), init(), setDamageCoefficient(), setPhysicalReceiver(), and setVibroEngine().
Member Function Documentation
assignReceiversGroup()
virtual void IIRPresentationReceiver::assignReceiversGroup (IPresentationReceiversGroup & group) pure virtual
Implemented in IRPresentationReceiverMT2.
Referenced by PresentationReceiversGroupMT2::connectReceiver(), and ~IIRPresentationReceiver().
init()
virtual void IIRPresentationReceiver::init () pure virtual
Implemented in IRPresentationReceiverMT2.
Referenced by SmartPoint::init(), ~IIRPresentationReceiver(), and IIRPresentationTransmitter::~IIRPresentationTransmitter().
setDamageCoefficient()
virtual void IIRPresentationReceiver::setDamageCoefficient (const FloatParameter * coefficient) pure virtual
Implemented in IRPresentationReceiverMT2.
Referenced by ~IIRPresentationReceiver().
setPhysicalReceiver()
virtual void IIRPresentationReceiver::setPhysicalReceiver (IIRPhysicalReceiver * receiver) pure virtual
Implemented in IRPresentationReceiverBase.
Referenced by SmartPoint::init(), and ~IIRPresentationReceiver().
setVibroEngine()
virtual void IIRPresentationReceiver::setVibroEngine (IIOPin * pin) pure virtual
Implemented in IRPresentationReceiverBase.
Referenced by ~IIRPresentationReceiver().
The documentation for this class was generated from the following file:
include/ir/ir-presentation.hpp