Caustic lasertag system: LEDFireEmitter Class Reference
LEDFireEmitter Class Reference
#include <fire-emitter-hw.hpp>
Public Member Functions
LEDFireEmitter ()
void init (const Pinout &pinout)
void startImpulsePack (bool isLedOn, unsigned int delayMs)
void setPower (UintParameter powerPercent)
void setCarrierFrequency (uint32_t frequency)
void IRQHandler ()
Public Member Functions inherited from FireEmitterBase
FireEmitterBase ()
void setCallback (FireEmitterCallback callback)
Public Member Functions inherited from IFireEmitter
virtual ~IFireEmitter ()
Private Member Functions
void modulationOn ()
void modulationOff ()
void setChannel (unsigned int channel)
Private Attributes
unsigned int m_videoPrescaler
bool m_isOn = false
uint8_t m_PWMChannel
unsigned int m_carrierFrequency = 56000
unsigned int m_radioPrescaler
uint8_t m_powerLevelsCount = 0
uint8_t m_powerChannels [4]
Static Private Attributes
static constexpr unsigned int m_radioTimerPeriod = 10
Additional Inherited Members
Protected Attributes inherited from FireEmitterBase
FireEmitterCallback m_callback
Detailed Description
Definition at line 31 of file fire-emitter-hw.hpp.
Constructor & Destructor Documentation
LEDFireEmitter()
LEDFireEmitter::LEDFireEmitter ()
Definition at line 36 of file fire-emitter.cpp.
Referenced by FireEmittersPool::getFireEmitter().
Member Function Documentation
init()
void LEDFireEmitter::init (const Pinout & pinout) virtual
Implements IFireEmitter.
Definition at line 42 of file fire-emitter.cpp.
References Pinout::getParameter(), m_carrierFrequency, m_powerChannels, m_powerLevelsCount, m_videoPrescaler, modulationOff(), StringParser< Type >::parse(), setCarrierFrequency(), and setPower().
IRQHandler()
void LEDFireEmitter::IRQHandler ()
Definition at line 249 of file fire-emitter.cpp.
References FireEmitterBase::m_callback, m_isOn, and modulationOff().
Referenced by TIM7_IRQHandler().
modulationOff()
void LEDFireEmitter::modulationOff () private
Definition at line 227 of file fire-emitter.cpp.
References m_powerLevelsCount, m_PWMChannel, and m_radioTimerPeriod.
Referenced by init(), IRQHandler(), and startImpulsePack().
modulationOn()
void LEDFireEmitter::modulationOn () private
Definition at line 203 of file fire-emitter.cpp.
References m_powerLevelsCount, m_PWMChannel, and m_radioTimerPeriod.
Referenced by startImpulsePack().
setCarrierFrequency()
void LEDFireEmitter::setCarrierFrequency (uint32_t frequency) virtual
Implements IFireEmitter.
Definition at line 141 of file fire-emitter.cpp.
References m_carrierFrequency, m_radioPrescaler, and m_radioTimerPeriod.
Referenced by init().
setChannel()
void LEDFireEmitter::setChannel (unsigned int channel) private virtual
Implements IFireEmitter.
Definition at line 172 of file fire-emitter.cpp.
References m_PWMChannel, and m_radioTimerPeriod.
Referenced by setPower().
setPower()
void LEDFireEmitter::setPower (UintParameter powerPercent) virtual
Implements IFireEmitter.
Definition at line 159 of file fire-emitter.cpp.
References m_powerChannels, m_powerLevelsCount, and setChannel().
Referenced by init().
startImpulsePack()
void LEDFireEmitter::startImpulsePack (bool isLedOn, unsigned int delayMs) virtual
Implements IFireEmitter.
Definition at line 116 of file fire-emitter.cpp.
References m_isOn, m_videoPrescaler, modulationOff(), and modulationOn().
Member Data Documentation
m_carrierFrequency
unsigned int LEDFireEmitter::m_carrierFrequency = 56000 private
Definition at line 51 of file fire-emitter-hw.hpp.
Referenced by init(), and setCarrierFrequency().
m_isOn
bool LEDFireEmitter::m_isOn = false private
Definition at line 49 of file fire-emitter-hw.hpp.
Referenced by IRQHandler(), and startImpulsePack().
m_powerChannels
uint8_t LEDFireEmitter::m_powerChannels[4] private
Definition at line 55 of file fire-emitter-hw.hpp.
Referenced by init(), and setPower().
m_powerLevelsCount
uint8_t LEDFireEmitter::m_powerLevelsCount = 0 private
Definition at line 54 of file fire-emitter-hw.hpp.
Referenced by init(), modulationOff(), modulationOn(), and setPower().
m_PWMChannel
uint8_t LEDFireEmitter::m_PWMChannel private
Definition at line 50 of file fire-emitter-hw.hpp.
Referenced by modulationOff(), modulationOn(), and setChannel().
m_radioPrescaler
unsigned int LEDFireEmitter::m_radioPrescaler private
Definition at line 53 of file fire-emitter-hw.hpp.
Referenced by setCarrierFrequency().
m_radioTimerPeriod
constexpr unsigned int LEDFireEmitter::m_radioTimerPeriod = 10 static private
Definition at line 52 of file fire-emitter-hw.hpp.
Referenced by modulationOff(), modulationOn(), setCarrierFrequency(), and setChannel().
m_videoPrescaler
unsigned int LEDFireEmitter::m_videoPrescaler private
Definition at line 47 of file fire-emitter-hw.hpp.
Referenced by init(), and startImpulsePack().
The documentation for this class was generated from the following files:
include/hw/fire-emitter-hw.hpp
src/hw/fire-emitter.cpp