Caustic lasertag system: IRReceiverTV Class Reference
IRReceiverTV Class Reference
#include <ir-physical-tv.hpp>
Public Member Functions
~IRReceiverTV ()
void init ()
Receiver.
void setEnabled (bool enabled)
void interrogate ()
Public Member Functions inherited from IRReceiverBase
void setCallback (IRReceiverCallback callback)
void setIOPin (IIOPin *input)
Public Member Functions inherited from IIRPhysicalReceiver
virtual ~IIRPhysicalReceiver ()
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Private Types
enum ReceivingState { RS_WAITING_HEADER = 0, RS_HEADER_BEGINNED = 1, RS_SPACE = 2, RS_BIT = 3 }
Private Member Functions
void resetReceiver ()
bool isCorrect (unsigned int value, unsigned int min, unsigned int max)
void saveBit (bool value)
int getCurrentLength ()
void interruptHandler (bool state)
Private Attributes
uint8_t m_data [bufferMaxSize]
uint8_t * m_pCurrentByte
uint8_t m_currentBit
bool m_falseImpulse
ReceivingState m_state
Time m_lastTime = 0
uint32_t m_dtime = 0
uint32_t m_lastDtime = 0
bool m_haveSomeData = false
bool m_debug = false
Static Private Attributes
static constexpr int bufferMaxSize = 100
static constexpr int headerPeriodMin = 1700
static constexpr int headerPeriodMax = 2600
static constexpr int bitOnePeriodMin = 1100
static constexpr int bitOnePeriodMax = 1500
static constexpr int bitZeroPeriodMin = 500
static constexpr int bitZeroPeriodMax = 750
static constexpr int bitWaitPeriodMin = 500
static constexpr int bitWaitPeriodMax = 900
Additional Inherited Members
Protected Attributes inherited from IRReceiverBase
IRReceiverCallback m_callback = nullptr
IIOPin * m_input = nullptr
Detailed Description
Definition at line 62 of file ir-physical-tv.hpp.
Member Enumeration Documentation
ReceivingState
enum IRReceiverTV::ReceivingState private
Enumerator
RS_WAITING_HEADER
RS_HEADER_BEGINNED
RS_SPACE
RS_BIT
Definition at line 72 of file ir-physical-tv.hpp.
Constructor & Destructor Documentation
~IRReceiverTV()
IRReceiverTV::~IRReceiverTV () inline
Definition at line 65 of file ir-physical-tv.hpp.
References IRTransmitterTV::init().
Member Function Documentation
getCurrentLength()
int IRReceiverTV::getCurrentLength () private
Definition at line 147 of file ir-physical-tv.cpp.
References IRTransmitterTV::m_currentBit, IRTransmitterTV::m_data, and IRTransmitterTV::m_pCurrentByte.
init()
void IRReceiverTV::init () virtual
Receiver.
For debugging "true" should be replaced by "false" to disable direct call from IRQ
Implements IIRPhysicalReceiver.
Definition at line 118 of file ir-physical-tv.cpp.
References interruptHandler().
interrogate()
void IRReceiverTV::interrogate () virtual
Implements IInterrogatable.
Definition at line 130 of file ir-physical-tv.cpp.
References error, ISystemClock::getTime(), IRTransmitterTV::m_data, and systemClock.
interruptHandler()
void IRReceiverTV::interruptHandler (bool state) private
Definition at line 187 of file ir-physical-tv.cpp.
References ISystemClock::getTime(), and systemClock.
Referenced by init().
isCorrect()
bool IRReceiverTV::isCorrect (unsigned int value, unsigned int min, unsigned int max) private
Definition at line 163 of file ir-physical-tv.cpp.
resetReceiver()
void IRReceiverTV::resetReceiver () private
Definition at line 152 of file ir-physical-tv.cpp.
References IRTransmitterTV::bufferMaxSize, IRTransmitterTV::m_currentBit, IRTransmitterTV::m_data, and IRTransmitterTV::m_pCurrentByte.
saveBit()
void IRReceiverTV::saveBit (bool value) private
Definition at line 168 of file ir-physical-tv.cpp.
References IRTransmitterTV::bufferMaxSize, IRTransmitterTV::m_currentBit, IRTransmitterTV::m_data, and IRTransmitterTV::m_pCurrentByte.
setEnabled()
void IRReceiverTV::setEnabled (bool enabled) virtual
Implements IIRPhysicalReceiver.
Definition at line 125 of file ir-physical-tv.cpp.
Member Data Documentation
bitOnePeriodMax
constexpr int IRReceiverTV::bitOnePeriodMax = 1500 static private
Definition at line 87 of file ir-physical-tv.hpp.
bitOnePeriodMin
constexpr int IRReceiverTV::bitOnePeriodMin = 1100 static private
Definition at line 86 of file ir-physical-tv.hpp.
bitWaitPeriodMax
constexpr int IRReceiverTV::bitWaitPeriodMax = 900 static private
Definition at line 93 of file ir-physical-tv.hpp.
bitWaitPeriodMin
constexpr int IRReceiverTV::bitWaitPeriodMin = 500 static private
Definition at line 92 of file ir-physical-tv.hpp.
bitZeroPeriodMax
constexpr int IRReceiverTV::bitZeroPeriodMax = 750 static private
Definition at line 90 of file ir-physical-tv.hpp.
bitZeroPeriodMin
constexpr int IRReceiverTV::bitZeroPeriodMin = 500 static private
Definition at line 89 of file ir-physical-tv.hpp.
bufferMaxSize
constexpr int IRReceiverTV::bufferMaxSize = 100 static private
Definition at line 80 of file ir-physical-tv.hpp.
headerPeriodMax
constexpr int IRReceiverTV::headerPeriodMax = 2600 static private
Definition at line 84 of file ir-physical-tv.hpp.
headerPeriodMin
constexpr int IRReceiverTV::headerPeriodMin = 1700 static private
Definition at line 83 of file ir-physical-tv.hpp.
m_currentBit
uint8_t IRReceiverTV::m_currentBit private
Definition at line 97 of file ir-physical-tv.hpp.
m_data
uint8_t IRReceiverTV::m_data[bufferMaxSize] private
Definition at line 95 of file ir-physical-tv.hpp.
m_debug
bool IRReceiverTV::m_debug = false private
Definition at line 107 of file ir-physical-tv.hpp.
m_dtime
uint32_t IRReceiverTV::m_dtime = 0 private
Definition at line 102 of file ir-physical-tv.hpp.
m_falseImpulse
bool IRReceiverTV::m_falseImpulse private
Definition at line 98 of file ir-physical-tv.hpp.
m_haveSomeData
bool IRReceiverTV::m_haveSomeData = false private
Definition at line 105 of file ir-physical-tv.hpp.
m_lastDtime
uint32_t IRReceiverTV::m_lastDtime = 0 private
Definition at line 103 of file ir-physical-tv.hpp.
m_lastTime
Time IRReceiverTV::m_lastTime = 0 private
Definition at line 101 of file ir-physical-tv.hpp.
m_pCurrentByte
uint8_t* IRReceiverTV::m_pCurrentByte private
Definition at line 96 of file ir-physical-tv.hpp.
m_state
ReceivingState IRReceiverTV::m_state private
Definition at line 99 of file ir-physical-tv.hpp.
The documentation for this class was generated from the following files:
include/ir/ir-physical-tv.hpp
src/ir/ir-physical-tv.cpp