Caustic lasertag system: DeviceInitializer Class Reference
DeviceInitializer Class Reference
#include <device-initializer.hpp>
Public Member Functions
void startOS ()
void initEnvironment ()
IAnyDevice * initDevice (const char *filename)
bool isSdcardOk () const
Private Member Functions
void initGPIO ()
void initSDIO ()
void initFatFS ()
void initClock ()
Private Attributes
FATFS m_fatfs
bool m_fatfsSuccess = false
Detailed Description
Definition at line 40 of file device-initializer.hpp.
Member Function Documentation
initClock()
void DeviceInitializer::initClock () private
initDevice()
IAnyDevice * DeviceInitializer::initDevice (const char * filename)
Definition at line 62 of file device-initializer.cpp.
References IAnyDevice::checkPinout(), error, Result::errorText, info, IAnyDevice::init(), isSdcardOk(), IniParcer::parseFile(), Pinout::readIni(), IniParcer::setCallback(), IAnyDevice::setDafaultPinout(), and warning.
Referenced by main().
initEnvironment()
void DeviceInitializer::initEnvironment ()
Definition at line 48 of file device-initializer.cpp.
References hardwareInitializer, info, IHardwareInitializer::init(), IRTC::init(), ISystemClock::init(), initFatFS(), Loggers::initLoggers(), RTCManager, and systemClock.
Referenced by main().
initFatFS()
void DeviceInitializer::initFatFS () private
Definition at line 163 of file device-initializer.cpp.
References error, info, m_fatfs, m_fatfsSuccess, and MX_FATFS_Init().
Referenced by initEnvironment().
initGPIO()
void DeviceInitializer::initGPIO () private
initSDIO()
void DeviceInitializer::initSDIO () private
isSdcardOk()
bool DeviceInitializer::isSdcardOk () const
Definition at line 180 of file device-initializer.cpp.
References m_fatfsSuccess.
Referenced by initDevice().
startOS()
void DeviceInitializer::startOS ()
Definition at line 157 of file device-initializer.cpp.
References info.
Member Data Documentation
m_fatfs
FATFS DeviceInitializer::m_fatfs private
Definition at line 55 of file device-initializer.hpp.
Referenced by initFatFS().
m_fatfsSuccess
bool DeviceInitializer::m_fatfsSuccess = false private
Definition at line 56 of file device-initializer.hpp.
Referenced by initFatFS(), and isSdcardOk().
The documentation for this class was generated from the following files:
include/core/device-initializer.hpp
src/core/device-initializer.cpp