Caustic lasertag system: RCSPMultiStream Class Reference
RCSPMultiStream Class Reference
#include <RCSP-stream.hpp>
Public Member Functions
RCSPMultiStream ()
RCSPAggregator::ResultType addValue (OperationCode code)
RCSPAggregator::ResultType addRequest (OperationCode code)
RCSPAggregator::ResultType addCall (OperationCode code)
template<typename Type >
RCSPAggregator::ResultType addCall (OperationCode code, const Type &arg)
void send (DeviceAddress target, bool waitForAck=false, PackageTimings &&timings=PackageTimings())
bool empty ()
void dispatch ()
DetailedResult< FRESULT > writeToFile (FIL *file)
Private Member Functions
void pushBackStream ()
Private Attributes
std::list< std::shared_ptr< RCSPStream > > m_streams
Detailed Description
Definition at line 131 of file RCSP-stream.hpp.
Constructor & Destructor Documentation
RCSPMultiStream()
RCSPMultiStream::RCSPMultiStream ()
Definition at line 139 of file RCSP-stream.cpp.
Member Function Documentation
addCall() [1/2]
RCSPAggregator::ResultType RCSPMultiStream::addCall (OperationCode code)
Definition at line 171 of file RCSP-stream.cpp.
References DetailedResult< T >::details, Result::isSuccess, and RCSPAggregator::NOT_ENOUGH_SPACE.
Referenced by HeadSensor::weaponWoundAndShock().
addCall() [2/2]
template<typename Type > RCSPAggregator::ResultType RCSPMultiStream::addCall (OperationCode code, const Type & arg) inline
Definition at line 140 of file RCSP-stream.hpp.
References DetailedResult< T >::details, RCSPStream::dispatch(), RCSPStream::empty(), Result::isSuccess, RCSPAggregator::NOT_ENOUGH_SPACE, and RCSPStream::send().
addRequest()
RCSPAggregator::ResultType RCSPMultiStream::addRequest (OperationCode code)
Definition at line 160 of file RCSP-stream.cpp.
References DetailedResult< T >::details, Result::isSuccess, and RCSPAggregator::NOT_ENOUGH_SPACE.
Referenced by PlayerPartialState::syncAll().
addValue()
RCSPAggregator::ResultType RCSPMultiStream::addValue (OperationCode code)
Definition at line 149 of file RCSP-stream.cpp.
References DetailedResult< T >::details, Result::isSuccess, and RCSPAggregator::NOT_ENOUGH_SPACE.
Referenced by RCSPAggregator::dispatchOperation(), MainStateSaver::saveState(), and HeadSensor::weaponWoundAndShock().
dispatch()
void RCSPMultiStream::dispatch ()
Definition at line 199 of file RCSP-stream.cpp.
empty()
bool RCSPMultiStream::empty ()
Definition at line 194 of file RCSP-stream.cpp.
Referenced by RCSPNetworkListener::packagesReceiver().
pushBackStream()
void RCSPMultiStream::pushBackStream () private
Definition at line 144 of file RCSP-stream.cpp.
send()
void RCSPMultiStream::send (DeviceAddress target, bool waitForAck = false, PackageTimings && timings = PackageTimings())
Definition at line 182 of file RCSP-stream.cpp.
Referenced by RCSPNetworkListener::packagesReceiver(), PlayerPartialState::syncAll(), and HeadSensor::weaponWoundAndShock().
writeToFile()
DetailedResult< FRESULT > RCSPMultiStream::writeToFile (FIL * file)
Definition at line 207 of file RCSP-stream.cpp.
Referenced by MainStateSaver::saveState().
Member Data Documentation
m_streams
std::list<std::shared_ptr<RCSPStream> > RCSPMultiStream::m_streams private
Definition at line 165 of file RCSP-stream.hpp.
The documentation for this class was generated from the following files:
include/rcsp/RCSP-stream.hpp
src/rscp/RCSP-stream.cpp