Caustic lasertag system: PowerMonitor Class Reference
PowerMonitor Class Reference
#include <power-monitor.hpp>
Public Member Functions
PAR_ST (NOT_RESTORABLE, ConfigCodes::AnyDevice::State, supplyVoltage)
PAR_ST (NOT_RESTORABLE, ConfigCodes::AnyDevice::Configuration, supplyVoltageMin)
PAR_ST (NOT_RESTORABLE, ConfigCodes::AnyDevice::Configuration, supplyVoltageMax)
PAR_ST (NOT_RESTORABLE, ConfigCodes::AnyDevice::Configuration, adcCalibrationCoeff)
PAR_ST (NOT_RESTORABLE, ConfigCodes::AnyDevice::State, chargePercent)
void interrogate () override
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Private Member Functions
PowerMonitor ()
Private Attributes
IADC * m_adc
float m_internalCalibrationCoeff = 1.1954
Detailed Description
Definition at line 34 of file power-monitor.hpp.
Constructor & Destructor Documentation
PowerMonitor()
PowerMonitor::PowerMonitor () private
Definition at line 31 of file power-monitor.cpp.
References ADCs, IADCBuilder::create(), and IADC::init().
Member Function Documentation
interrogate()
void PowerMonitor::interrogate () override virtual
Implements IInterrogatable.
Definition at line 40 of file power-monitor.cpp.
References IADC::get(), m_adc, m_internalCalibrationCoeff, and IADC::max().
PAR_ST() [1/5]
PowerMonitor::PAR_ST (NOT_RESTORABLE , ConfigCodes::AnyDevice::State , supplyVoltage)
PAR_ST() [2/5]
PowerMonitor::PAR_ST (NOT_RESTORABLE , ConfigCodes::AnyDevice::Configuration , supplyVoltageMin)
PAR_ST() [3/5]
PowerMonitor::PAR_ST (NOT_RESTORABLE , ConfigCodes::AnyDevice::Configuration , supplyVoltageMax)
PAR_ST() [4/5]
PowerMonitor::PAR_ST (NOT_RESTORABLE , ConfigCodes::AnyDevice::Configuration , adcCalibrationCoeff)
PAR_ST() [5/5]
PowerMonitor::PAR_ST (NOT_RESTORABLE , ConfigCodes::AnyDevice::State , chargePercent)
Member Data Documentation
m_adc
IADC* PowerMonitor::m_adc private
Definition at line 50 of file power-monitor.hpp.
Referenced by interrogate().
m_internalCalibrationCoeff
float PowerMonitor::m_internalCalibrationCoeff = 1.1954 private
Definition at line 51 of file power-monitor.hpp.
Referenced by interrogate().
The documentation for this class was generated from the following files:
include/core/power-monitor.hpp
src/core/power-monitor.cpp