Caustic lasertag system: HardwareInitializer Class Reference
HardwareInitializer Class Reference
#include <hardware-initializer-hw.hpp>
Public Member Functions
void init ()
Public Member Functions inherited from IHardwareInitializer
~IHardwareInitializer ()
Private Member Functions
void SystemClock_Config ()
void MX_GPIO_Init (void)
void MX_SDIO_SD_Init (void)
void MX_DMA_Init (void)
Detailed Description
Definition at line 30 of file hardware-initializer-hw.hpp.
Member Function Documentation
init()
void HardwareInitializer::init () virtual
Implements IHardwareInitializer.
Definition at line 37 of file hardware-initializer-hw.cpp.
References MX_DMA_Init(), MX_GPIO_Init(), MX_SDIO_SD_Init(), and SystemClock_Config().
Referenced by SmartPoint::init(), BluetoothBridge::init(), Rifle::init(), and HeadSensor::init().
MX_DMA_Init()
void HardwareInitializer::MX_DMA_Init (void) private
Definition at line 121 of file hardware-initializer-hw.cpp.
Referenced by init().
MX_GPIO_Init()
void HardwareInitializer::MX_GPIO_Init (void) private
Definition at line 97 of file hardware-initializer-hw.cpp.
References IOPins, and IIOPinsPool::resetAllPins().
Referenced by init().
MX_SDIO_SD_Init()
void HardwareInitializer::MX_SDIO_SD_Init (void) private
Definition at line 108 of file hardware-initializer-hw.cpp.
References hsd.
Referenced by init().
SystemClock_Config()
void HardwareInitializer::SystemClock_Config () private
Definition at line 50 of file hardware-initializer-hw.cpp.
References DECL_CLEAN.
Referenced by init().
The documentation for this class was generated from the following files:
include/hw/hardware-initializer-hw.hpp
src/hw/hardware-initializer-hw.cpp