Caustic lasertag system: RCSPAggregator Class Reference
RCSPAggregator Class Reference
#include <RCSP-aggregator.hpp>
Classes
struct Operation
Public Types
enum AddingResult { OK = 0, INVALID_OPCODE, NOT_ENOUGH_SPACE, NOT_READABLE }
using ResultType = DetailedResult< AddingResult >
Public Member Functions
RCSPAggregator ()
void registerAccessor (OperationCode code, const char *textName, IOperationAccessor *accessor, bool restorable=false)
uint32_t dispatchStream (uint8_t *stream, uint32_t size, RCSPMultiStream *answerStream=nullptr)
const uint8_t * extractNextOperation (const uint8_t *stream, Operation &commad, uint16_t streamSize, bool &success)
bool isStreamConsistent (const uint8_t *stream, uint32_t size)
Result readIni (const char *filename)
Result parseSring (const char *key, const char *value)
ResultType serializeObject (uint8_t *stream, OperationCode code, uint16_t freeSpace, uint16_t &actualSize, const uint8_t *pCustomValue=nullptr)
ResultType serializeObjectRequest (uint8_t *stream, OperationCode variableCode, uint16_t freeSpace, uint16_t &actualSize)
ResultType serializeCallRequest (uint8_t *stream, OperationCode functionCode, uint16_t freeSpace, uint16_t &actualSize)
template<typename Type >
ResultType serializeCallRequest (uint8_t *stream, OperationCode functionCode, uint16_t freeSpace, uint16_t &actualSize, const Type &parameter)
bool doOperation (OperationCode code)
template<typename Type >
bool doOperation (OperationCode code, Type &arg)
template<typename T >
DetailedResult< T > getLocalObject (OperationCode code)
Static Public Attributes
static constexpr unsigned int minimalStreamSize = sizeof(OperationSize) + sizeof(OperationCode)
Private Member Functions
bool dispatchOperation (OperationSize *size, OperationCode *code, uint8_t *arg, RCSPMultiStream *answerStream=nullptr)
void printWarningUnknownCode (OperationCode code)
Private Attributes
std::map< OperationCode, IOperationAccessor * > m_accessorsByOpCode
std::map< std::string, IOperationAccessor * > m_accessorsByOpText
Static Private Attributes
static constexpr OperationCode OperationCodeMask = (OperationCode) ~((1<<15) | (1<<14))
All bits =1 except two upper bits.
static RCSPAggregator * m_RCSPAggregator = nullptr
Detailed Description
Remote Control and Synchronization Protocol Aggregator
Definition at line 141 of file RCSP-aggregator.hpp.
Member Typedef Documentation
ResultType
using RCSPAggregator::ResultType = DetailedResult<AddingResult>
Definition at line 161 of file RCSP-aggregator.hpp.
Member Enumeration Documentation
AddingResult
enum RCSPAggregator::AddingResult
Enumerator
OK
INVALID_OPCODE
NOT_ENOUGH_SPACE
NOT_READABLE
Definition at line 144 of file RCSP-aggregator.hpp.
Constructor & Destructor Documentation
RCSPAggregator()
RCSPAggregator::RCSPAggregator () inline
Definition at line 163 of file RCSP-aggregator.hpp.
Member Function Documentation
dispatchOperation()
bool RCSPAggregator::dispatchOperation (OperationSize * size, OperationCode * code, uint8_t * arg, RCSPMultiStream * answerStream = nullptr) private
Definition at line 93 of file RCSP-aggregator.cpp.
References RCSPMultiStream::addValue(), debug, m_accessorsByOpCode, RCSPCodeManipulator::makeSetObject(), printWarningUnknownCode(), and trace.
Referenced by dispatchStream().
dispatchStream()
uint32_t RCSPAggregator::dispatchStream (uint8_t * stream, uint32_t size, RCSPMultiStream * answerStream = nullptr)
Dispatch binary stream with encoded operations
Parameters
stream Binary stream
size Stream size in bytes
answerStream stream to put answer for object requests
Returns
Count of unsupported operation found on stream
Definition at line 52 of file RCSP-aggregator.cpp.
References dispatchOperation().
doOperation() [1/2]
bool RCSPAggregator::doOperation (OperationCode code) inline
Definition at line 265 of file RCSP-aggregator.hpp.
doOperation() [2/2]
template<typename Type > bool RCSPAggregator::doOperation (OperationCode code, Type & arg) inline
Definition at line 272 of file RCSP-aggregator.hpp.
extractNextOperation()
const uint8_t * RCSPAggregator::extractNextOperation (const uint8_t * stream, RCSPAggregator::Operation & commad, uint16_t streamSize, bool & success)
Definition at line 69 of file RCSP-aggregator.cpp.
References RCSPAggregator::Operation::argument, RCSPAggregator::Operation::argumentSize, RCSPAggregator::Operation::code, and deserializeAndInc().
getLocalObject()
template<typename T > DetailedResult<T> RCSPAggregator::getLocalObject (OperationCode code) inline
Definition at line 279 of file RCSP-aggregator.hpp.
References RCSPCodeManipulator::makeSetObject(), and SIGLETON_IN_CLASS.
isStreamConsistent()
bool RCSPAggregator::isStreamConsistent (const uint8_t * stream, uint32_t size)
TODO Add "nope" ignoring support
Definition at line 142 of file RCSP-aggregator.cpp.
parseSring()
Result RCSPAggregator::parseSring (const char * key, const char * value)
Definition at line 160 of file RCSP-aggregator.cpp.
References m_accessorsByOpText.
Referenced by readIni().
printWarningUnknownCode()
void RCSPAggregator::printWarningUnknownCode (OperationCode code) private
Definition at line 134 of file RCSP-aggregator.cpp.
References warning.
Referenced by dispatchOperation().
readIni()
Result RCSPAggregator::readIni (const char * filename)
Definition at line 249 of file RCSP-aggregator.cpp.
References IniParcer::parseFile(), parseSring(), and IniParcer::setCallback().
registerAccessor()
void RCSPAggregator::registerAccessor (OperationCode code, const char * textName, IOperationAccessor * accessor, bool restorable = false)
Definition at line 37 of file RCSP-aggregator.cpp.
References error, and instance.
serializeCallRequest() [1/2]
DetailedResult< RCSPAggregator::AddingResult > RCSPAggregator::serializeCallRequest (uint8_t * stream, OperationCode functionCode, uint16_t freeSpace, uint16_t & actualSize)
Put to stream request for function call without parameters
Parameters
stream Array where to put
variableCode Code of variable
freeSpace Max available space in stream. Will be decremented after successful adding
Returns
result of operation
Definition at line 233 of file RCSP-aggregator.cpp.
References RCSPCodeManipulator::makeCallRequest(), NOT_ENOUGH_SPACE, and OK.
serializeCallRequest() [2/2]
template<typename Type > ResultType RCSPAggregator::serializeCallRequest (uint8_t * stream, OperationCode functionCode, uint16_t freeSpace, uint16_t & actualSize, const Type & parameter) inline
Put to stream request for function call with parameter
Parameters
stream Array where to put
variableCode Code of variable
freeSpace Max available space in stream. Will be decremented after successful adding
parameter Parameter value
Returns
result of operation
Todo:
[refactor] Remove code duplication with functionCallwithout parameters
Definition at line 240 of file RCSP-aggregator.hpp.
References RCSPCodeManipulator::makeCallRequest().
serializeObject()
DetailedResult< RCSPAggregator::AddingResult > RCSPAggregator::serializeObject (uint8_t * stream, OperationCode code, uint16_t freeSpace, uint16_t & actualSize, const uint8_t * pCustomValue = nullptr)
Serialize variable or other object with accessor and put it to stream
Parameters
stream Array where to put
code Code of variable/accessible object
freeSpace Max available space in stream. Will be decremented after successful adding
actualSize Resulting size of added data
pCustomValue Pointer to custom value of parameter that should be put into stream. Using this parameter means that serialization is trivial, so data of size = arctual parameter size will be copied to stream from pCustomValue
Returns
result of operation
Definition at line 178 of file RCSP-aggregator.cpp.
References INVALID_OPCODE, m_accessorsByOpCode, RCSPCodeManipulator::makeSetObject(), NOT_ENOUGH_SPACE, NOT_READABLE, and OK.
serializeObjectRequest()
DetailedResult< RCSPAggregator::AddingResult > RCSPAggregator::serializeObjectRequest (uint8_t * stream, OperationCode variableCode, uint16_t freeSpace, uint16_t & actualSize)
Put to stream request for variable
Parameters
stream Array where to put
code Code of variable
freeSpace Max available space in stream. Will be decremented after successful adding
Returns
result of operation
Definition at line 217 of file RCSP-aggregator.cpp.
References RCSPCodeManipulator::makeObjectRequestOC(), NOT_ENOUGH_SPACE, and OK.
Member Data Documentation
m_accessorsByOpCode
std::map<OperationCode, IOperationAccessor*> RCSPAggregator::m_accessorsByOpCode private
Definition at line 304 of file RCSP-aggregator.hpp.
Referenced by dispatchOperation(), and serializeObject().
m_accessorsByOpText
std::map<std::string, IOperationAccessor*> RCSPAggregator::m_accessorsByOpText private
Definition at line 305 of file RCSP-aggregator.hpp.
Referenced by parseSring().
m_RCSPAggregator
RCSPAggregator * RCSPAggregator::m_RCSPAggregator = nullptr static private
Definition at line 306 of file RCSP-aggregator.hpp.
minimalStreamSize
constexpr unsigned int RCSPAggregator::minimalStreamSize = sizeof(OperationSize) + sizeof(OperationCode) static
Definition at line 159 of file RCSP-aggregator.hpp.
Referenced by IRPresentationReceiverMT2::receiverCallback().
OperationCodeMask
constexpr OperationCode RCSPAggregator::OperationCodeMask = (OperationCode) ~((1<<15) | (1<<14)) static private
All bits =1 except two upper bits.
Definition at line 299 of file RCSP-aggregator.hpp.
The documentation for this class was generated from the following files:
include/rcsp/RCSP-aggregator.hpp
src/rscp/RCSP-aggregator.cpp