Caustic lasertag system: IOperationAccessor Class Reference
IOperationAccessor Class Reference abstract
Any kind of object that can read data from stream and write data to stream.
#include <RCSP-aggregator.hpp>
Public Member Functions
virtual ~IOperationAccessor ()
virtual void deserialize (void *source, OperationSize size)=0
Get data from stream and set parameter, call function etc.
virtual void serialize (void *destination)=0
Put parameter, function return value etc. to stream.
virtual void parseString (const char *str)=0
Get data from string.
virtual bool isReadable ()=0
Check if serialize is callable method.
virtual bool isWritable ()=0
Check if deserialize is callable method.
virtual uint32_t getSize ()=0
Get data size in stream.
Detailed Description
Any kind of object that can read data from stream and write data to stream.
Definition at line 117 of file RCSP-aggregator.hpp.
Constructor & Destructor Documentation
~IOperationAccessor()
virtual IOperationAccessor::~IOperationAccessor () inline virtual
Definition at line 120 of file RCSP-aggregator.hpp.
References deserialize(), getSize(), isReadable(), isWritable(), parseString(), and serialize().
Member Function Documentation
deserialize()
virtual void IOperationAccessor::deserialize (void * source, OperationSize size) pure virtual
Get data from stream and set parameter, call function etc.
Implemented in ParameterAccessorBase< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
getSize()
virtual uint32_t IOperationAccessor::getSize () pure virtual
Get data size in stream.
Implemented in ParameterAccessorBase< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
isReadable()
virtual bool IOperationAccessor::isReadable () pure virtual
Check if serialize is callable method.
Implemented in ParameterAccessorBase< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
isWritable()
virtual bool IOperationAccessor::isWritable () pure virtual
Check if deserialize is callable method.
Implemented in ParameterAccessorBase< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
parseString()
virtual void IOperationAccessor::parseString (const char * str) pure virtual
Get data from string.
Implemented in CustomStrParseParameterAccessor< Type >, StandartStrParseParameterAccessor< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
serialize()
virtual void IOperationAccessor::serialize (void * destination) pure virtual
Put parameter, function return value etc. to stream.
Implemented in ParameterAccessorBase< Type >, SelfSerializingParameterAccessor< Type >, DefaultFunctionAccessor< ArgType >, and DefaultFunctionAccessor<>.
Referenced by ~IOperationAccessor().
The documentation for this class was generated from the following file:
include/rcsp/RCSP-aggregator.hpp