Caustic lasertag system: PlayerConfiguration Class Reference
PlayerConfiguration Class Reference
#include <player-config-and-state.hpp>
Public Member Functions
PlayerConfiguration ()
void setDefault ()
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, healthMax)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, armorMax)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, healthStart)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, armorStart)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, armorCoeffStart)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, damageCoeffStart)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, shotsCoeffStart)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, frendlyFireCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, selfShotCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, isHealable)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, lifesCount)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, shockDelayImmortal)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, shockDelayInactive)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, preRespawnDelay)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, postRespawnDelay)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, autoRespawn)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, plyerMT2Id)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, teamId)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, slot1MaxWeight)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, slot2MaxWeight)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, slot3MaxWeight)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, slot4MaxWeight)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, slot5MaxWeight)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone1DamageCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone2DamageCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone3DamageCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone4DamageCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone5DamageCoeff)
PAR_ST (RESTORABLE, ConfigCodes::HeadSensor::Configuration, zone6DamageCoeff)
Detailed Description
Definition at line 32 of file player-config-and-state.hpp.
Constructor & Destructor Documentation
PlayerConfiguration()
PlayerConfiguration::PlayerConfiguration ()
Definition at line 29 of file player.cpp.
References setDefault().
Member Function Documentation
PAR_ST() [1/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , healthMax)
Todo:
[Refactor!] Add this values to another state saver or any other way
Referenced by PlayerState::PlayerState().
PAR_ST() [2/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , armorMax)
PAR_ST() [3/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , healthStart)
PAR_ST() [4/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , armorStart)
PAR_ST() [5/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , armorCoeffStart)
PAR_ST() [6/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , damageCoeffStart)
PAR_ST() [7/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , shotsCoeffStart)
PAR_ST() [8/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , frendlyFireCoeff)
PAR_ST() [9/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , selfShotCoeff)
PAR_ST() [10/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , isHealable)
PAR_ST() [11/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , lifesCount)
PAR_ST() [12/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , shockDelayImmortal)
PAR_ST() [13/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , shockDelayInactive)
PAR_ST() [14/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , preRespawnDelay)
PAR_ST() [15/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , postRespawnDelay)
PAR_ST() [16/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , autoRespawn)
PAR_ST() [17/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , plyerMT2Id)
PAR_ST() [18/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , teamId)
PAR_ST() [19/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , slot1MaxWeight)
PAR_ST() [20/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , slot2MaxWeight)
PAR_ST() [21/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , slot3MaxWeight)
PAR_ST() [22/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , slot4MaxWeight)
PAR_ST() [23/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , slot5MaxWeight)
PAR_ST() [24/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone1DamageCoeff)
PAR_ST() [25/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone2DamageCoeff)
PAR_ST() [26/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone3DamageCoeff)
PAR_ST() [27/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone4DamageCoeff)
PAR_ST() [28/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone5DamageCoeff)
PAR_ST() [29/29]
PlayerConfiguration::PAR_ST (RESTORABLE , ConfigCodes::HeadSensor::Configuration , zone6DamageCoeff)
setDefault()
void PlayerConfiguration::setDefault ()
Definition at line 34 of file player.cpp.
Referenced by PlayerConfiguration().
The documentation for this class was generated from the following files:
include/head-sensor/player-config-and-state.hpp
src/player/player.cpp