Caustic lasertag system: IRPresentationTransmitterMT2 Class Reference
IRPresentationTransmitterMT2 Class Reference
#include <ir-presentation-mt2.hpp>
Public Member Functions
void init ()
void sendMessage (const RCSPStream &stream)
Public Member Functions inherited from IRPresentationTransmitterBase
void setPhysicalTransmitter (IIRTransmitter *transmitter)
Public Member Functions inherited from IIRPresentationTransmitter
virtual ~IIRPresentationTransmitter ()
Private Member Functions
void sendGenericRCSPMessageDefault (const RCSPStream &stream)
void sendCommand (uint8_t commandCode)
uint8_t encodeDamage (uint8_t damage)
Private Attributes
uint8_t m_data [maxMessageSize]
Static Private Attributes
static constexpr uint32_t maxMessageSize = 100
Additional Inherited Members
Protected Attributes inherited from IRPresentationTransmitterBase
IIRTransmitter * m_physicalTransmitter = nullptr
Detailed Description
Definition at line 35 of file ir-presentation-mt2.hpp.
Member Function Documentation
encodeDamage()
uint8_t IRPresentationTransmitterMT2::encodeDamage (uint8_t damage) private
Definition at line 82 of file ir-presentation-mt2.cpp.
Referenced by sendMessage().
init()
void IRPresentationTransmitterMT2::init () virtual
Implements IIRPresentationTransmitter.
Definition at line 34 of file ir-presentation-mt2.cpp.
sendCommand()
void IRPresentationTransmitterMT2::sendCommand (uint8_t commandCode) private
Definition at line 136 of file ir-presentation-mt2.cpp.
References MT2Extended::Byte1::command, MT2Extended::Byte3::commandEnd, MT2Extended::commandLength, m_data, IRPresentationTransmitterBase::m_physicalTransmitter, and IIRTransmitter::send().
Referenced by sendMessage().
sendGenericRCSPMessageDefault()
void IRPresentationTransmitterMT2::sendGenericRCSPMessageDefault (const RCSPStream & stream) private
Definition at line 69 of file ir-presentation-mt2.cpp.
References error, RCSPStream::getSize(), RCSPStream::getStream(), m_data, IRPresentationTransmitterBase::m_physicalTransmitter, maxMessageSize, MT2Extended::Byte1::RCSPMessage, and IIRTransmitter::send().
Referenced by sendMessage().
sendMessage()
void IRPresentationTransmitterMT2::sendMessage (const RCSPStream & stream) virtual
Implements IIRPresentationTransmitter.
Definition at line 38 of file ir-presentation-mt2.cpp.
References MT2Extended::Commands::adminKill, RCSPAggregator::Operation::argument, RCSPAggregator::Operation::code, ShotMessage::damage, encodeDamage(), RCSPStream::getSize(), RCSPStream::getStream(), instance, m_data, IRPresentationTransmitterBase::m_physicalTransmitter, ShotMessage::playerId, MT2Extended::Commands::respawn, MT2Extended::Commands::restoreDefaults, IIRTransmitter::send(), sendCommand(), sendGenericRCSPMessageDefault(), MT2Extended::shotLength, MT2Extended::Commands::startGame, and ShotMessage::teamId.
Member Data Documentation
m_data
uint8_t IRPresentationTransmitterMT2::m_data[maxMessageSize] private
Definition at line 48 of file ir-presentation-mt2.hpp.
Referenced by sendCommand(), sendGenericRCSPMessageDefault(), and sendMessage().
maxMessageSize
constexpr uint32_t IRPresentationTransmitterMT2::maxMessageSize = 100 static private
Definition at line 42 of file ir-presentation-mt2.hpp.
Referenced by sendGenericRCSPMessageDefault().
The documentation for this class was generated from the following files:
include/ir/ir-presentation-mt2.hpp
src/ir/ir-presentation-mt2.cpp