Caustic lasertag system: UIStateBase Class Reference
UIStateBase Class Reference abstract
#include <smart-point-ui.hpp>
Public Member Functions
UIStateBase (SmartPointUI &ui)
virtual ~UIStateBase ()
virtual UIStateBase * doIteration ()=0
virtual void prepare ()
Protected Attributes
SmartPointUI & m_ui
bool m_screenUpdated = false
Detailed Description
Definition at line 35 of file smart-point-ui.hpp.
Constructor & Destructor Documentation
UIStateBase()
UIStateBase::UIStateBase (SmartPointUI & ui)
Definition at line 30 of file smart-point-ui.cpp.
~UIStateBase()
virtual UIStateBase::~UIStateBase () inline virtual
Definition at line 39 of file smart-point-ui.hpp.
References doIteration().
Member Function Documentation
doIteration()
virtual UIStateBase* UIStateBase::doIteration () pure virtual
Implemented in UITimeLeftScreen, and UIInitScreen.
Referenced by SmartPointUI::doIteration(), and ~UIStateBase().
prepare()
virtual void UIStateBase::prepare () inline virtual
Reimplemented in UITimeLeftScreen.
Definition at line 41 of file smart-point-ui.hpp.
References m_screenUpdated.
Referenced by UITimeLeftScreen::doIteration(), and UITimeLeftScreen::prepare().
Member Data Documentation
m_screenUpdated
bool UIStateBase::m_screenUpdated = false protected
Definition at line 45 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration(), UITimeLeftScreen::doIteration(), and prepare().
m_ui
SmartPointUI& UIStateBase::m_ui protected
Definition at line 44 of file smart-point-ui.hpp.
Referenced by UIInitScreen::doIteration(), and UITimeLeftScreen::doIteration().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-ui.hpp
src/smart-point/smart-point-ui.cpp