Caustic lasertag system: SmartPointState Class Reference
SmartPointState Class Reference
#include <smart-point-config-and-state.hpp>
Public Member Functions
SmartPointState (const SmartPointConfig &config)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, team1TimeLeft)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, team2TimeLeft)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, team3TimeLeft)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, team4TimeLeft)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, currentTeam)
PAR_ST (RESTORABLE, ConfigCodes::SmartPoint::State, gameState)
void beginGame ()
void stopGame ()
void resetAllTime ()
void ticTime ()
void acitateByTeam (TeamGameId team)
Static Public Attributes
static constexpr uint8_t gameStateInProcess = 1
static constexpr uint8_t gameStateEnd = 2
Private Member Functions
void timeLeftUsToSec ()
void win (TeamGameId team)
Private Attributes
const SmartPointConfig & m_config
Time m_lastTimeTick = 0
Time m_team1TimeLeftus = 0
Time m_team2TimeLeftus = 0
Time m_team3TimeLeftus = 0
Time m_team4TimeLeftus = 0
Detailed Description
Definition at line 38 of file smart-point-config-and-state.hpp.
Constructor & Destructor Documentation
SmartPointState()
SmartPointState::SmartPointState (const SmartPointConfig & config)
Definition at line 34 of file smart-point-config-and-state.cpp.
Member Function Documentation
acitateByTeam()
void SmartPointState::acitateByTeam (TeamGameId team)
Definition at line 116 of file smart-point-config-and-state.cpp.
References gameStateInProcess.
Referenced by SmartPoint::checkPinout().
beginGame()
void SmartPointState::beginGame ()
Definition at line 39 of file smart-point-config-and-state.cpp.
References gameStateInProcess, ISystemClock::getTime(), m_lastTimeTick, resetAllTime(), and systemClock.
Referenced by UIInitScreen::doIteration().
PAR_ST() [1/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , team1TimeLeft)
PAR_ST() [2/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , team2TimeLeft)
PAR_ST() [3/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , team3TimeLeft)
PAR_ST() [4/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , team4TimeLeft)
PAR_ST() [5/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , currentTeam)
PAR_ST() [6/6]
SmartPointState::PAR_ST (RESTORABLE , ConfigCodes::SmartPoint::State , gameState)
resetAllTime()
void SmartPointState::resetAllTime ()
Definition at line 52 of file smart-point-config-and-state.cpp.
References m_config, m_team1TimeLeftus, m_team2TimeLeftus, m_team3TimeLeftus, m_team4TimeLeftus, teamGameIdNotATeam, and timeLeftUsToSec().
Referenced by beginGame(), and stopGame().
stopGame()
void SmartPointState::stopGame ()
Definition at line 46 of file smart-point-config-and-state.cpp.
References gameStateEnd, and resetAllTime().
Referenced by UITimeLeftScreen::doIteration().
ticTime()
void SmartPointState::ticTime ()
Definition at line 63 of file smart-point-config-and-state.cpp.
References gameStateInProcess, ISystemClock::getTime(), m_lastTimeTick, m_team1TimeLeftus, m_team2TimeLeftus, m_team3TimeLeftus, m_team4TimeLeftus, systemClock, teamGameIdNotATeam, timeLeftUsToSec(), and win().
Referenced by SmartPoint::init().
timeLeftUsToSec()
void SmartPointState::timeLeftUsToSec () private
Definition at line 124 of file smart-point-config-and-state.cpp.
References m_team1TimeLeftus, m_team2TimeLeftus, m_team3TimeLeftus, and m_team4TimeLeftus.
Referenced by resetAllTime(), and ticTime().
win()
void SmartPointState::win (TeamGameId team) private
Definition at line 132 of file smart-point-config-and-state.cpp.
References gameStateEnd, and info.
Referenced by ticTime().
Member Data Documentation
gameStateEnd
constexpr uint8_t SmartPointState::gameStateEnd = 2 static
Definition at line 42 of file smart-point-config-and-state.hpp.
Referenced by UITimeLeftScreen::doIteration(), stopGame(), and win().
gameStateInProcess
constexpr uint8_t SmartPointState::gameStateInProcess = 1 static
Definition at line 41 of file smart-point-config-and-state.hpp.
Referenced by acitateByTeam(), beginGame(), and ticTime().
m_config
const SmartPointConfig& SmartPointState::m_config private
Definition at line 62 of file smart-point-config-and-state.hpp.
Referenced by resetAllTime().
m_lastTimeTick
Time SmartPointState::m_lastTimeTick = 0 private
Definition at line 66 of file smart-point-config-and-state.hpp.
Referenced by beginGame(), and ticTime().
m_team1TimeLeftus
Time SmartPointState::m_team1TimeLeftus = 0 private
Definition at line 68 of file smart-point-config-and-state.hpp.
Referenced by resetAllTime(), ticTime(), and timeLeftUsToSec().
m_team2TimeLeftus
Time SmartPointState::m_team2TimeLeftus = 0 private
Definition at line 69 of file smart-point-config-and-state.hpp.
Referenced by resetAllTime(), ticTime(), and timeLeftUsToSec().
m_team3TimeLeftus
Time SmartPointState::m_team3TimeLeftus = 0 private
Definition at line 70 of file smart-point-config-and-state.hpp.
Referenced by resetAllTime(), ticTime(), and timeLeftUsToSec().
m_team4TimeLeftus
Time SmartPointState::m_team4TimeLeftus = 0 private
Definition at line 71 of file smart-point-config-and-state.hpp.
Referenced by resetAllTime(), ticTime(), and timeLeftUsToSec().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-config-and-state.hpp
src/smart-point/smart-point-config-and-state.cpp