Caustic lasertag system: UIInitScreen Class Reference
UIInitScreen Class Reference
#include <smart-point-ui.hpp>
Public Member Functions
UIInitScreen (SmartPointUI &ui)
UIStateBase * doIteration () override
Public Member Functions inherited from UIStateBase
UIStateBase (SmartPointUI &ui)
virtual ~UIStateBase ()
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from UIStateBase
SmartPointUI & m_ui
bool m_screenUpdated = false
Detailed Description
Definition at line 48 of file smart-point-ui.hpp.
Constructor & Destructor Documentation
UIInitScreen()
UIInitScreen::UIInitScreen (SmartPointUI & ui)
Definition at line 104 of file smart-point-ui.cpp.
Member Function Documentation
doIteration()
UIStateBase * UIInitScreen::doIteration () override virtual
Implements UIStateBase.
Definition at line 110 of file smart-point-ui.cpp.
References SmartPointState::beginGame(), LCD5110Controller::clearBuffer(), LCD5110Controller::configureSPI(), debug, LCD5110Controller::fontStandardAscii5x7, MatrixKeyboard::getKeyPressed(), SmartPointUI::keyboard, SmartPointUI::lcd, UIStateBase::m_screenUpdated, UIStateBase::m_ui, UITimeLeftScreen::prepare(), LCD5110Controller::setFont(), SmartPointUI::smartPointState, LCD5110Controller::stringXY(), SmartPointUI::timeLeftScreen, LCD5110Controller::updateContrast(), and LCD5110Controller::write().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-ui.hpp
src/smart-point/smart-point-ui.cpp