Caustic lasertag system: IRTC Class Reference
IRTC Class Reference abstract
#include <rtc.hpp>
Public Member Functions
virtual ~IRTC ()
virtual void init ()=0
virtual void getDate (RTCDate &date)=0
virtual void setDate (const RTCDate &date)=0
virtual void getTime (RTCTime &time)=0
virtual void setTime (const RTCTime &time)=0
virtual void getDateTime (RTCDateTime &dateTime)=0
virtual void setDateTime (const RTCDateTime &dateTime)=0
Detailed Description
Definition at line 30 of file rtc.hpp.
Constructor & Destructor Documentation
~IRTC()
virtual IRTC::~IRTC () inline virtual
Definition at line 33 of file rtc.hpp.
References getDate(), getDateTime(), getTime(), init(), setDate(), setDateTime(), and setTime().
Member Function Documentation
getDate()
virtual void IRTC::getDate (RTCDate & date) pure virtual
Implemented in RTCMgr.
Referenced by RTCBase::getDateTime(), SystemMonitor::printTime(), and ~IRTC().
getDateTime()
virtual void IRTC::getDateTime (RTCDateTime & dateTime) pure virtual
Implemented in RTCBase.
Referenced by ~IRTC().
getTime()
virtual void IRTC::getTime (RTCTime & time) pure virtual
Implemented in RTCMgr.
Referenced by RTCBase::getDateTime(), SystemMonitor::printTime(), and ~IRTC().
init()
virtual void IRTC::init () pure virtual
Implemented in RTCMgr.
Referenced by DeviceInitializer::initEnvironment(), and ~IRTC().
setDate()
virtual void IRTC::setDate (const RTCDate & date) pure virtual
Implemented in RTCMgr.
Referenced by RTCBase::setDateTime(), and ~IRTC().
setDateTime()
virtual void IRTC::setDateTime (const RTCDateTime & dateTime) pure virtual
Implemented in RTCBase.
Referenced by ~IRTC().
setTime()
virtual void IRTC::setTime (const RTCTime & time) pure virtual
Implemented in RTCMgr.
Referenced by RTCBase::setDateTime(), and ~IRTC().
The documentation for this class was generated from the following file:
include/hal/rtc.hpp