Caustic lasertag system: RGBLeds Class Reference
RGBLeds Class Reference
#include <rgb-leds.hpp>
Classes
struct BlinkPattern
Public Member Functions
RGBLeds (const TeamGameId &teamId)
void init (IIOPin *red, IIOPin *green, IIOPin *blue)
void blink (const BlinkPattern &pattern, uint8_t color=selfColor)
void stop ()
uint8_t getTeamColor ()
uint8_t getTeamColor (TeamGameId teamId)
Static Public Attributes
static constexpr uint8_t silence = 0
static constexpr uint8_t red = 1
static constexpr uint8_t green = 2
static constexpr uint8_t blue = 4
static constexpr uint8_t selfColor = 255
Private Member Functions
void changeState (uint8_t state)
void blinkingTask ()
Private Attributes
IIOPin * m_red = nullptr
IIOPin * m_green = nullptr
IIOPin * m_blue = nullptr
uint8_t m_color = red
const TeamGameId & m_teamId
BlinkPattern m_currentPattern
unsigned int blinksCount = 0
TaskCycled m_blinkingTask
Detailed Description
Definition at line 32 of file rgb-leds.hpp.
Constructor & Destructor Documentation
RGBLeds()
RGBLeds::RGBLeds (const TeamGameId & teamId)
Definition at line 28 of file rgb-leds.cpp.
References blinkingTask(), m_blinkingTask, TaskBase::setName(), TaskBase::setStackSize(), and TaskBase::setTask().
Member Function Documentation
blink()
void RGBLeds::blink (const BlinkPattern & pattern, uint8_t color = selfColor)
Definition at line 82 of file rgb-leds.cpp.
References blinksCount, changeState(), getTeamColor(), m_color, m_currentPattern, RGBLeds::BlinkPattern::repetitionsCount, selfColor, and silence.
Referenced by UITimeLeftScreen::doIteration(), and SmartPointUI::init().
blinkingTask()
void RGBLeds::blinkingTask () private
Definition at line 68 of file rgb-leds.cpp.
References blinksCount, changeState(), m_color, m_currentPattern, RGBLeds::BlinkPattern::offStateDuration, RGBLeds::BlinkPattern::onStateDuration, silence, and Kernel::yeld().
Referenced by RGBLeds().
changeState()
void RGBLeds::changeState (uint8_t state) private
Definition at line 50 of file rgb-leds.cpp.
References blue, green, m_blue, m_green, m_red, red, IIOPin::reset(), and IIOPin::set().
Referenced by blink(), and blinkingTask().
getTeamColor() [1/2]
uint8_t RGBLeds::getTeamColor ()
Definition at line 94 of file rgb-leds.cpp.
References m_teamId.
Referenced by blink().
getTeamColor() [2/2]
uint8_t RGBLeds::getTeamColor (TeamGameId teamId)
Definition at line 99 of file rgb-leds.cpp.
References blue, green, red, and silence.
init()
void RGBLeds::init (IIOPin * red, IIOPin * green, IIOPin * blue)
Definition at line 36 of file rgb-leds.cpp.
References blue, green, m_blinkingTask, m_blue, m_green, m_red, red, IIOPin::reset(), TaskCycled::run(), and IIOPin::switchToOutput().
Referenced by SmartPointUI::initLEDs().
stop()
void RGBLeds::stop ()
Definition at line 111 of file rgb-leds.cpp.
References blinksCount.
Member Data Documentation
blinksCount
unsigned int RGBLeds::blinksCount = 0 private
Definition at line 81 of file rgb-leds.hpp.
Referenced by blink(), blinkingTask(), and stop().
blue
constexpr uint8_t RGBLeds::blue = 4 static
Definition at line 38 of file rgb-leds.hpp.
Referenced by changeState(), UITimeLeftScreen::doIteration(), getTeamColor(), init(), and SmartPointUI::init().
green
constexpr uint8_t RGBLeds::green = 2 static
Definition at line 37 of file rgb-leds.hpp.
Referenced by changeState(), UITimeLeftScreen::doIteration(), getTeamColor(), init(), and SmartPointUI::init().
m_blinkingTask
TaskCycled RGBLeds::m_blinkingTask private
Definition at line 82 of file rgb-leds.hpp.
Referenced by init(), and RGBLeds().
m_blue
IIOPin* RGBLeds::m_blue = nullptr private
Definition at line 74 of file rgb-leds.hpp.
Referenced by changeState(), and init().
m_color
uint8_t RGBLeds::m_color = red private
Definition at line 76 of file rgb-leds.hpp.
Referenced by blink(), and blinkingTask().
m_currentPattern
BlinkPattern RGBLeds::m_currentPattern private
Definition at line 79 of file rgb-leds.hpp.
Referenced by blink(), and blinkingTask().
m_green
IIOPin* RGBLeds::m_green = nullptr private
Definition at line 73 of file rgb-leds.hpp.
Referenced by changeState(), and init().
m_red
IIOPin* RGBLeds::m_red = nullptr private
Definition at line 72 of file rgb-leds.hpp.
Referenced by changeState(), and init().
m_teamId
const TeamGameId& RGBLeds::m_teamId private
Definition at line 78 of file rgb-leds.hpp.
Referenced by getTeamColor().
red
constexpr uint8_t RGBLeds::red = 1 static
Definition at line 36 of file rgb-leds.hpp.
Referenced by changeState(), UITimeLeftScreen::doIteration(), getTeamColor(), init(), and SmartPointUI::init().
selfColor
constexpr uint8_t RGBLeds::selfColor = 255 static
Definition at line 39 of file rgb-leds.hpp.
Referenced by blink().
silence
constexpr uint8_t RGBLeds::silence = 0 static
Definition at line 35 of file rgb-leds.hpp.
Referenced by blink(), blinkingTask(), and getTeamColor().
The documentation for this class was generated from the following files:
include/dev/rgb-leds.hpp
src/dev/rgb-leds.cpp