Caustic lasertag system: Kernel Class Reference
Kernel Class Reference
#include <os-wrappers.hpp>
Public Member Functions
void run ()
bool isRunning () const
int getTasksCount ()
void assert (bool shouldBeTrue, const char *message)
SIGLETON_IN_CLASS (Kernel)
Static Public Member Functions
static void yeld ()
Private Member Functions
Kernel ()
Private Attributes
bool m_isRunning = false
Detailed Description
Definition at line 39 of file os-wrappers.hpp.
Constructor & Destructor Documentation
Kernel()
Kernel::Kernel () inline private
Definition at line 53 of file os-wrappers.hpp.
Member Function Documentation
assert()
void Kernel::assert (bool shouldBeTrue, const char * message)
Todo:
Add here code to stop FreeRTOS
Definition at line 50 of file os-wrappers.cpp.
References error, and isRunning().
Referenced by isRunning().
getTasksCount()
int Kernel::getTasksCount ()
Definition at line 44 of file os-wrappers.cpp.
Referenced by isRunning().
isRunning()
bool Kernel::isRunning () const inline
Definition at line 45 of file os-wrappers.hpp.
References assert(), getTasksCount(), m_isRunning, and SIGLETON_IN_CLASS().
Referenced by assert().
run()
void Kernel::run ()
Definition at line 31 of file os-wrappers.cpp.
References info.
Referenced by TaskCycled::TaskCycled(), and TaskOnce::TaskOnce().
SIGLETON_IN_CLASS()
Kernel::SIGLETON_IN_CLASS (Kernel)
Referenced by isRunning().
yeld()
void Kernel::yeld () static
Definition at line 38 of file os-wrappers.cpp.
References instance, and m_isRunning.
Referenced by RGBLeds::blinkingTask(), and BluetoothBridge::sendBluetoothMessage().
Member Data Documentation
m_isRunning
bool Kernel::m_isRunning = false private
Definition at line 54 of file os-wrappers.hpp.
Referenced by isRunning(), and yeld().
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp