Caustic lasertag system: Rifle Class Reference
Rifle Class Reference
#include <rifle.hpp>
Classes
struct PinoutTexts
struct WeaponState
Public Member Functions
Rifle ()
void registerWeapon ()
void init (const Pinout &pinout) override
void setDafaultPinout (Pinout &pinout) override
bool checkPinout (const Pinout &pinout) override
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleTurnOn)
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleTurnOff)
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleReset)
Make rifle absolutely new.
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleRespawn)
Do all things than needed on respawn (+play sound)
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleDie)
Say to rifle that player was killed.
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, headSensorToRifleHeartbeat)
Heartbeat head sensor -> rifle.
FUNCTION_NP (ConfigCodes::Rifle::Functions, Rifle, rifleWound)
FUNCTION_1P (ConfigCodes::Rifle::Functions, Rifle, riflePlayEnemyDamaged)
Play enemy damaged sound.
FUNCTION_1P (ConfigCodes::Rifle::Functions, Rifle, rifleShock)
Play enemy damaged sound.
FUNCTION_1P (ConfigCodes::Rifle::Functions, Rifle, rifleChangeHS)
Play enemy damaged sound.
Public Member Functions inherited from IAnyDevice
virtual ~IAnyDevice ()
Public Attributes
DeviceConfiguration deviceConfig
RifleConfiguration config
RifleOwnerConfiguration rifleOwner
RifleState state {&config}
PlayerPartialState playerState {config.headSensorAddr}
Private Member Functions
void loadConfig ()
void initSounds ()
void makeShot (bool isFirst)
void prepareAndSendShotMsg ()
void distortBolt (bool isFirst)
void magazineSensor (bool isConnected, uint8_t sensorNumber, bool isFirst)
uint8_t getCurrentMagazineNumber ()
void reloadAndPlay ()
void detectRifleState ()
bool isReloading ()
bool isSafeSwitchSelected ()
bool isShocked ()
bool isHSConnected ()
void updatePlayerState ()
void playDamagerNotification (uint8_t state)
void scheduleDamageNotification (uint8_t state)
void checkHeartBeat ()
void onCardReaded (uint8_t *buffer, uint16_t size)
void onHSConnected ()
This function could be called any time when head sensor is connected. Double calling does not hurt anything.
void onHSDisconnected ()
Private Attributes
ButtonManager * m_fireButton = nullptr
ButtonManager * m_reloadButton = nullptr
ButtonManager * m_automaticFireSwitch = nullptr
ButtonManager * m_semiAutomaticFireSwitch = nullptr
ButtonManager * m_magazine1Sensor = nullptr
ButtonManager * m_magazine2Sensor = nullptr
IIOPin * m_vibroEngine = nullptr
IIOPin * m_fireFlash = nullptr
IIRTransmitter * m_irPhysicalTransmitter = nullptr
IIRPresentationTransmitter * m_irPresentationTransmitter = nullptr
SoundPlayer m_systemReadySound
SoundPlayer m_RFIDCardReaded
SoundPlayer m_connectedToHeadSensorSound
SoundPlayer m_shootingSound
SoundPlayer m_reloadingSound
SoundPlayer m_noAmmoSound
SoundPlayer m_noMagazines
SoundPlayer m_respawnSound
SoundPlayer m_dieSound
SoundPlayer m_woundSound
SoundPlayer m_enemyDamaged
SoundPlayer m_enemyKilled
SoundPlayer m_friendDamaged
SoundPlayer m_noHeartbeat
SoundPlayer m_noShockedShooting
SoundPlayer m_hsSwitchRejected
PackageId m_registerWeaponPAckageId = 0
uint8_t m_state = WeaponState::ready
uint8_t m_currentMagazineNumber = 0
zero means no magazine
Interrogator m_buttonsInterrogator {"BtnsIntr"}
TasksPool m_tasksPool {"RiflPool"}
Time m_lastHSHeartBeat = 0
Time m_unshockTime = 0
If current time > m_unshockTime, player is not shocked now.
RifleLCD5110Display m_display {&rifleOwner, &state, &playerState}
RC552Wrapper m_mfrcWrapper
Static Private Attributes
static constexpr uint32_t maxNoHeartbeatDelay = 6500000
Detailed Description
Definition at line 44 of file rifle.hpp.
Constructor & Destructor Documentation
Rifle()
Rifle::Rifle ()
Definition at line 175 of file rifle.cpp.
References DeviceTypes::rifle.
Member Function Documentation
checkHeartBeat()
void Rifle::checkHeartBeat () private
Definition at line 779 of file rifle.cpp.
References ISystemClock::getTime(), info, and systemClock.
checkPinout()
bool Rifle::checkPinout (const Pinout & pinout) override virtual
Implements IAnyDevice.
Definition at line 193 of file rifle.cpp.
References error.
detectRifleState()
void Rifle::detectRifleState () private
Definition at line 430 of file rifle.cpp.
References RifleState::config(), info, RifleConfiguration::isAutoReloading(), and RifleConfiguration::isReloadingByDistortingTheBolt().
distortBolt()
void Rifle::distortBolt (bool isFirst) private
Todo:
Add here removing of one shell
Definition at line 565 of file rifle.cpp.
References RifleState::config(), RifleConfiguration::isReloadingByDistortingTheBolt(), and trace.
Referenced by init().
FUNCTION_1P() [1/3]
Rifle::FUNCTION_1P (ConfigCodes::Rifle::Functions , Rifle , riflePlayEnemyDamaged)
Play enemy damaged sound.
FUNCTION_1P() [2/3]
Rifle::FUNCTION_1P (ConfigCodes::Rifle::Functions , Rifle , rifleShock)
Play enemy damaged sound.
FUNCTION_1P() [3/3]
Rifle::FUNCTION_1P (ConfigCodes::Rifle::Functions , Rifle , rifleChangeHS)
Play enemy damaged sound.
FUNCTION_NP() [1/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleTurnOn)
FUNCTION_NP() [2/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleTurnOff)
FUNCTION_NP() [3/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleReset)
Make rifle absolutely new.
FUNCTION_NP() [4/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleRespawn)
Do all things than needed on respawn (+play sound)
FUNCTION_NP() [5/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleDie)
Say to rifle that player was killed.
FUNCTION_NP() [6/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , headSensorToRifleHeartbeat)
Heartbeat head sensor -> rifle.
FUNCTION_NP() [7/7]
Rifle::FUNCTION_NP (ConfigCodes::Rifle::Functions , Rifle , rifleWound)
getCurrentMagazineNumber()
uint8_t Rifle::getCurrentMagazineNumber () private
Definition at line 651 of file rifle.cpp.
init()
void Rifle::init (const Pinout & pinout) override virtual
Todo:
Chack that rife is turned on/off correctly anway
Implements IAnyDevice.
Definition at line 224 of file rifle.cpp.
References Broadcast::any, broadcast, RifleState::config(), distortBolt(), fireEmittersPool, IFireEmittersPool::getFireEmitter(), IIOPinsPool::getIOPin(), info, HardwareInitializer::init(), instance, IOPins, RifleConfiguration::isAutoReloading(), RifleConfiguration::isReloadingByDistortingTheBolt(), magazineSensor(), makeShot(), Pinout::printPinout(), Broadcast::rifles, IIOPin::switchToOutput(), and warning.
initSounds()
void Rifle::initSounds () private
Definition at line 459 of file rifle.cpp.
isHSConnected()
bool Rifle::isHSConnected () private
Definition at line 821 of file rifle.cpp.
References ISystemClock::getTime(), and systemClock.
isReloading()
bool Rifle::isReloading () private
isSafeSwitchSelected()
bool Rifle::isSafeSwitchSelected () private
Definition at line 684 of file rifle.cpp.
isShocked()
bool Rifle::isShocked () private
Definition at line 816 of file rifle.cpp.
References ISystemClock::getTime(), and systemClock.
loadConfig()
void Rifle::loadConfig () private
Definition at line 448 of file rifle.cpp.
References Result::errorText, Result::isSuccess, IniParcer::parseFile(), and IniParcer::setCallback().
magazineSensor()
void Rifle::magazineSensor (bool isConnected, uint8_t sensorNumber, bool isFirst) private
Definition at line 600 of file rifle.cpp.
References RifleState::config(), info, and warning.
Referenced by init().
makeShot()
void Rifle::makeShot (bool isFirst) private
Definition at line 479 of file rifle.cpp.
References RifleState::config(), delayedSwitchPin(), info, RifleConfiguration::isAutoReloading(), and trace.
Referenced by init().
onCardReaded()
void Rifle::onCardReaded (uint8_t * buffer, uint16_t size) private
Definition at line 826 of file rifle.cpp.
References ADDRESS_TO_STREAM, RifleState::config(), debug, ISystemClock::getTime(), info, instance, RifleState::isHSConnected, printHex(), RCSPStream::remoteCall(), and systemClock.
onHSConnected()
void Rifle::onHSConnected () private
This function could be called any time when head sensor is connected. Double calling does not hurt anything.
Definition at line 793 of file rifle.cpp.
References info.
onHSDisconnected()
void Rifle::onHSDisconnected () private
Definition at line 805 of file rifle.cpp.
References ISystemClock::getTime(), and systemClock.
playDamagerNotification()
void Rifle::playDamagerNotification (uint8_t state) private
Definition at line 762 of file rifle.cpp.
References NotificationSoundCase::enemyInjured, NotificationSoundCase::enemyKilled, and NotificationSoundCase::friendInjured.
prepareAndSendShotMsg()
void Rifle::prepareAndSendShotMsg () private
Definition at line 554 of file rifle.cpp.
References RCSPStream::addCall(), RifleState::config(), ShotMessage::damage, ShotMessage::playerId, and ShotMessage::teamId.
registerWeapon()
void Rifle::registerWeapon ()
Definition at line 896 of file rifle.cpp.
References RifleState::config(), info, RiflePackageTimings::registration, RCSPStream::remoteCall(), and riflePackageTimings.
reloadAndPlay()
void Rifle::reloadAndPlay () private
Definition at line 661 of file rifle.cpp.
References RifleState::config(), and info.
scheduleDamageNotification()
void Rifle::scheduleDamageNotification (uint8_t state) private
setDafaultPinout()
void Rifle::setDafaultPinout (Pinout & pinout) override virtual
Implements IAnyDevice.
Definition at line 181 of file rifle.cpp.
updatePlayerState()
void Rifle::updatePlayerState () private
Definition at line 695 of file rifle.cpp.
References ISystemClock::getTime(), info, Logger::isEnabled(), and systemClock.
Member Data Documentation
config
RifleConfiguration Rifle::config
Definition at line 69 of file rifle.hpp.
deviceConfig
DeviceConfiguration Rifle::deviceConfig
Definition at line 68 of file rifle.hpp.
m_automaticFireSwitch
ButtonManager* Rifle::m_automaticFireSwitch = nullptr private
Definition at line 132 of file rifle.hpp.
m_buttonsInterrogator
Interrogator Rifle::m_buttonsInterrogator {"BtnsIntr"} private
Definition at line 164 of file rifle.hpp.
m_connectedToHeadSensorSound
SoundPlayer Rifle::m_connectedToHeadSensorSound private
Definition at line 144 of file rifle.hpp.
m_currentMagazineNumber
uint8_t Rifle::m_currentMagazineNumber = 0 private
zero means no magazine
Definition at line 162 of file rifle.hpp.
m_dieSound
SoundPlayer Rifle::m_dieSound private
Definition at line 150 of file rifle.hpp.
m_display
RifleLCD5110Display Rifle::m_display {&rifleOwner, &state, &playerState} private
Definition at line 170 of file rifle.hpp.
m_enemyDamaged
SoundPlayer Rifle::m_enemyDamaged private
Definition at line 152 of file rifle.hpp.
m_enemyKilled
SoundPlayer Rifle::m_enemyKilled private
Definition at line 153 of file rifle.hpp.
m_fireButton
ButtonManager* Rifle::m_fireButton = nullptr private
Definition at line 130 of file rifle.hpp.
m_fireFlash
IIOPin* Rifle::m_fireFlash = nullptr private
Definition at line 137 of file rifle.hpp.
m_friendDamaged
SoundPlayer Rifle::m_friendDamaged private
Definition at line 154 of file rifle.hpp.
m_hsSwitchRejected
SoundPlayer Rifle::m_hsSwitchRejected private
Definition at line 157 of file rifle.hpp.
m_irPhysicalTransmitter
IIRTransmitter* Rifle::m_irPhysicalTransmitter = nullptr private
Definition at line 139 of file rifle.hpp.
m_irPresentationTransmitter
IIRPresentationTransmitter* Rifle::m_irPresentationTransmitter = nullptr private
Definition at line 140 of file rifle.hpp.
m_lastHSHeartBeat
Time Rifle::m_lastHSHeartBeat = 0 private
Definition at line 166 of file rifle.hpp.
m_magazine1Sensor
ButtonManager* Rifle::m_magazine1Sensor = nullptr private
Definition at line 134 of file rifle.hpp.
m_magazine2Sensor
ButtonManager* Rifle::m_magazine2Sensor = nullptr private
Definition at line 135 of file rifle.hpp.
m_mfrcWrapper
RC552Wrapper Rifle::m_mfrcWrapper private
Definition at line 172 of file rifle.hpp.
m_noAmmoSound
SoundPlayer Rifle::m_noAmmoSound private
Definition at line 147 of file rifle.hpp.
m_noHeartbeat
SoundPlayer Rifle::m_noHeartbeat private
Definition at line 155 of file rifle.hpp.
m_noMagazines
SoundPlayer Rifle::m_noMagazines private
Definition at line 148 of file rifle.hpp.
m_noShockedShooting
SoundPlayer Rifle::m_noShockedShooting private
Definition at line 156 of file rifle.hpp.
m_registerWeaponPAckageId
PackageId Rifle::m_registerWeaponPAckageId = 0 private
Definition at line 159 of file rifle.hpp.
m_reloadButton
ButtonManager* Rifle::m_reloadButton = nullptr private
Definition at line 131 of file rifle.hpp.
m_reloadingSound
SoundPlayer Rifle::m_reloadingSound private
Definition at line 146 of file rifle.hpp.
m_respawnSound
SoundPlayer Rifle::m_respawnSound private
Definition at line 149 of file rifle.hpp.
m_RFIDCardReaded
SoundPlayer Rifle::m_RFIDCardReaded private
Definition at line 143 of file rifle.hpp.
m_semiAutomaticFireSwitch
ButtonManager* Rifle::m_semiAutomaticFireSwitch = nullptr private
Definition at line 133 of file rifle.hpp.
m_shootingSound
SoundPlayer Rifle::m_shootingSound private
Definition at line 145 of file rifle.hpp.
m_state
uint8_t Rifle::m_state = WeaponState::ready private
Definition at line 161 of file rifle.hpp.
m_systemReadySound
SoundPlayer Rifle::m_systemReadySound private
Definition at line 142 of file rifle.hpp.
m_tasksPool
TasksPool Rifle::m_tasksPool {"RiflPool"} private
Definition at line 165 of file rifle.hpp.
m_unshockTime
Time Rifle::m_unshockTime = 0 private
If current time > m_unshockTime, player is not shocked now.
Definition at line 169 of file rifle.hpp.
m_vibroEngine
IIOPin* Rifle::m_vibroEngine = nullptr private
Definition at line 136 of file rifle.hpp.
m_woundSound
SoundPlayer Rifle::m_woundSound private
Definition at line 151 of file rifle.hpp.
maxNoHeartbeatDelay
constexpr uint32_t Rifle::maxNoHeartbeatDelay = 6500000 static private
Definition at line 79 of file rifle.hpp.
playerState
PlayerPartialState Rifle::playerState {config.headSensorAddr}
Definition at line 74 of file rifle.hpp.
rifleOwner
RifleOwnerConfiguration Rifle::rifleOwner
Definition at line 70 of file rifle.hpp.
state
RifleState Rifle::state {&config}
Definition at line 71 of file rifle.hpp.
The documentation for this class was generated from the following files:
include/rifle/rifle.hpp
src/rifle/rifle.cpp