Caustic lasertag system: ButtonManager Class Reference
ButtonManager Class Reference
#include <buttons.hpp>
Public Member Functions
ButtonManager (IIOPin *inputInterrogator)
~ButtonManager ()
ButtonManager & setCallback (ButtonPressCallback callback)
ButtonManager & setDepressCallback (ButtonDepressCallback callback)
ButtonManager & setAutoRepeat (bool autoRepeat)
ButtonManager & setRepeatPeriod (uint32_t &repeatPeriod)
void useEXTI (bool enabled=true)
void turnOn ()
void turnOff ()
void setPressedState (bool pressedState=false)
bool state ()
void interrogate ()
Public Member Functions inherited from IInterrogatable
virtual ~IInterrogatable ()
Static Public Attributes
static constexpr uint32_t AntiBounceDelay = 5000
Private Member Functions
bool wasBounce ()
void extiCallback (bool state)
Private Attributes
uint32_t m_lastBounceTestTime = 0
ButtonPressCallback m_callback = nullptr
ButtonDepressCallback m_depressCallback = nullptr
IIOPin * m_inputInterrogator = nullptr
uint32_t * m_repeatPeriod = nullptr
uint32_t m_lastPressTime = 0
bool m_autoRepeat = false
bool m_extiDetected = false
bool m_isFirst = false
bool m_isFirstPress = true
Last detected button state (pressed or not)
bool m_isEnabled = true
bool m_pressedState = false
bool m_pressedAndNotDepressed = false
Detailed Description
Definition at line 38 of file buttons.hpp.
Constructor & Destructor Documentation
ButtonManager()
ButtonManager::ButtonManager (IIOPin * inputInterrogator)
Definition at line 31 of file buttons.cpp.
References error, and extiCallback().
Referenced by ButtonsPool::createButtonManager().
~ButtonManager()
ButtonManager::~ButtonManager () inline
Definition at line 42 of file buttons.hpp.
Member Function Documentation
extiCallback()
void ButtonManager::extiCallback (bool state) private
Definition at line 84 of file buttons.cpp.
References ISystemClock::getTime(), m_extiDetected, m_isEnabled, m_isFirst, m_lastPressTime, m_pressedState, m_repeatPeriod, systemClock, and wasBounce().
Referenced by ButtonManager().
interrogate()
void ButtonManager::interrogate () virtual
Returns
true if pressed, false if depressed
Implements IInterrogatable.
Definition at line 97 of file buttons.cpp.
References error, ISystemClock::getTime(), m_autoRepeat, m_callback, m_depressCallback, m_extiDetected, m_inputInterrogator, m_isEnabled, m_isFirst, m_lastPressTime, m_pressedAndNotDepressed, m_pressedState, m_repeatPeriod, IIOPin::state(), systemClock, and wasBounce().
Referenced by setDepressCallback().
setAutoRepeat()
ButtonManager & ButtonManager::setAutoRepeat (bool autoRepeat)
Definition at line 42 of file buttons.cpp.
References m_autoRepeat.
Referenced by setDepressCallback().
setCallback()
ButtonManager& ButtonManager::setCallback (ButtonPressCallback callback) inline
Definition at line 43 of file buttons.hpp.
References m_callback.
setDepressCallback()
ButtonManager& ButtonManager::setDepressCallback (ButtonDepressCallback callback) inline
Definition at line 44 of file buttons.hpp.
References interrogate(), m_depressCallback, setAutoRepeat(), setPressedState(), setRepeatPeriod(), state(), turnOff(), turnOn(), and useEXTI().
setPressedState()
void ButtonManager::setPressedState (bool pressedState = false)
Definition at line 69 of file buttons.cpp.
References m_pressedState.
Referenced by setDepressCallback().
setRepeatPeriod()
ButtonManager & ButtonManager::setRepeatPeriod (uint32_t & repeatPeriod)
Definition at line 48 of file buttons.cpp.
References m_repeatPeriod.
Referenced by setDepressCallback().
state()
bool ButtonManager::state ()
Definition at line 74 of file buttons.cpp.
References error, m_inputInterrogator, m_pressedState, and IIOPin::state().
Referenced by setDepressCallback().
turnOff()
void ButtonManager::turnOff ()
Definition at line 59 of file buttons.cpp.
References m_isEnabled.
Referenced by setDepressCallback().
turnOn()
void ButtonManager::turnOn ()
Definition at line 54 of file buttons.cpp.
References m_isEnabled.
Referenced by setDepressCallback().
useEXTI()
void ButtonManager::useEXTI (bool enabled = true)
Definition at line 64 of file buttons.cpp.
References IIOPin::enableExti(), and m_inputInterrogator.
Referenced by setDepressCallback().
wasBounce()
bool ButtonManager::wasBounce () private
Definition at line 149 of file buttons.cpp.
References AntiBounceDelay, ISystemClock::getTime(), m_lastBounceTestTime, and systemClock.
Referenced by extiCallback(), and interrogate().
Member Data Documentation
AntiBounceDelay
constexpr uint32_t ButtonManager::AntiBounceDelay = 5000 static
Definition at line 56 of file buttons.hpp.
Referenced by wasBounce().
m_autoRepeat
bool ButtonManager::m_autoRepeat = false private
Definition at line 69 of file buttons.hpp.
Referenced by interrogate(), and setAutoRepeat().
m_callback
ButtonPressCallback ButtonManager::m_callback = nullptr private
Definition at line 63 of file buttons.hpp.
Referenced by interrogate(), and setCallback().
m_depressCallback
ButtonDepressCallback ButtonManager::m_depressCallback = nullptr private
Definition at line 64 of file buttons.hpp.
Referenced by interrogate(), and setDepressCallback().
m_extiDetected
bool ButtonManager::m_extiDetected = false private
Definition at line 70 of file buttons.hpp.
Referenced by extiCallback(), and interrogate().
m_inputInterrogator
IIOPin* ButtonManager::m_inputInterrogator = nullptr private
Definition at line 65 of file buttons.hpp.
Referenced by interrogate(), state(), and useEXTI().
m_isEnabled
bool ButtonManager::m_isEnabled = true private
Definition at line 73 of file buttons.hpp.
Referenced by extiCallback(), interrogate(), turnOff(), and turnOn().
m_isFirst
bool ButtonManager::m_isFirst = false private
Definition at line 71 of file buttons.hpp.
Referenced by extiCallback(), and interrogate().
m_isFirstPress
bool ButtonManager::m_isFirstPress = true private
Last detected button state (pressed or not)
Definition at line 72 of file buttons.hpp.
m_lastBounceTestTime
uint32_t ButtonManager::m_lastBounceTestTime = 0 private
Definition at line 61 of file buttons.hpp.
Referenced by wasBounce().
m_lastPressTime
uint32_t ButtonManager::m_lastPressTime = 0 private
Definition at line 68 of file buttons.hpp.
Referenced by extiCallback(), and interrogate().
m_pressedAndNotDepressed
bool ButtonManager::m_pressedAndNotDepressed = false private
Definition at line 75 of file buttons.hpp.
Referenced by interrogate().
m_pressedState
bool ButtonManager::m_pressedState = false private
Definition at line 74 of file buttons.hpp.
Referenced by extiCallback(), interrogate(), setPressedState(), and state().
m_repeatPeriod
uint32_t* ButtonManager::m_repeatPeriod = nullptr private
Definition at line 67 of file buttons.hpp.
Referenced by extiCallback(), interrogate(), and setRepeatPeriod().
The documentation for this class was generated from the following files:
include/dev/buttons.hpp
src/dev/buttons.cpp