Caustic lasertag system: IOPin Class Reference
IOPin Class Reference
#include <io-pins-hw.hpp>
Public Member Functions
IOPin (uint8_t portNumber, uint8_t pinNumber)
bool state ()
void set ()
Switch to state "1".
void reset ()
Switch to state "0".
void switchToOutput ()
void switchToInput ()
void setExtiCallback (const IOPinCallback &callback, bool direclyFromISR=false)
void enableExti (bool enable=true)
void extiInterrupt ()
Public Member Functions inherited from IIOPin
virtual ~IIOPin ()
Static Public Member Functions
static GPIO_TypeDef * parsePortNumber (uint8_t portNumber)
static uint16_t pinNumberToMask (uint8_t pinNumber)
static uint8_t maskToPinNumber (uint16_t pinMask)
Private Attributes
IOPinCallback m_callback = nullptr
GPIO_TypeDef * m_gpio
uint16_t m_pinMask
bool m_extiEnabled = false
bool isOutputMode = false
bool m_runDirectlyFromISR = false
Detailed Description
Definition at line 34 of file io-pins-hw.hpp.
Constructor & Destructor Documentation
IOPin()
IOPin::IOPin (uint8_t portNumber, uint8_t pinNumber)
Definition at line 35 of file io-pins-hw.cpp.
References m_gpio, m_pinMask, parsePortNumber(), pinNumberToMask(), and switchToInput().
Referenced by IOPinsPool::getIOPin().
Member Function Documentation
enableExti()
void IOPin::enableExti (bool enable = true) virtual
Implements IIOPin.
Definition at line 88 of file io-pins-hw.cpp.
References error, m_extiEnabled, m_gpio, m_pinMask, maskToPinNumber(), switchToInput(), and zerify().
extiInterrupt()
void IOPin::extiInterrupt ()
Definition at line 129 of file io-pins-hw.cpp.
References Worker::addFromISR(), m_callback, IOPinsPool::m_callbackCaller, m_runDirectlyFromISR, and state().
Referenced by HAL_GPIO_EXTI_Callback().
maskToPinNumber()
uint8_t IOPin::maskToPinNumber (uint16_t pinMask) static
Definition at line 165 of file io-pins-hw.cpp.
References error.
Referenced by enableExti(), and HAL_GPIO_EXTI_Callback().
parsePortNumber()
GPIO_TypeDef * IOPin::parsePortNumber (uint8_t portNumber) static
Definition at line 147 of file io-pins-hw.cpp.
References error.
Referenced by IOPin().
pinNumberToMask()
uint16_t IOPin::pinNumberToMask (uint8_t pinNumber) static
Definition at line 202 of file io-pins-hw.cpp.
Referenced by IOPin().
reset()
void IOPin::reset () virtual
Switch to state "0".
Implements IIOPin.
Definition at line 53 of file io-pins-hw.cpp.
References m_gpio, and m_pinMask.
set()
void IOPin::set () virtual
Switch to state "1".
Implements IIOPin.
Definition at line 48 of file io-pins-hw.cpp.
References m_gpio, and m_pinMask.
setExtiCallback()
void IOPin::setExtiCallback (const IOPinCallback & callback, bool direclyFromISR = false) virtual
Implements IIOPin.
Definition at line 82 of file io-pins-hw.cpp.
References m_callback, and m_runDirectlyFromISR.
state()
bool IOPin::state () virtual
Implements IIOPin.
Definition at line 42 of file io-pins-hw.cpp.
References m_gpio, and m_pinMask.
Referenced by extiInterrupt().
switchToInput()
void IOPin::switchToInput () virtual
Implements IIOPin.
Definition at line 70 of file io-pins-hw.cpp.
References isOutputMode, m_gpio, m_pinMask, and zerify().
Referenced by enableExti(), and IOPin().
switchToOutput()
void IOPin::switchToOutput () virtual
Implements IIOPin.
Definition at line 58 of file io-pins-hw.cpp.
References isOutputMode, m_gpio, m_pinMask, and zerify().
Member Data Documentation
isOutputMode
bool IOPin::isOutputMode = false private
Definition at line 61 of file io-pins-hw.hpp.
Referenced by switchToInput(), and switchToOutput().
m_callback
IOPinCallback IOPin::m_callback = nullptr private
Definition at line 57 of file io-pins-hw.hpp.
Referenced by extiInterrupt(), and setExtiCallback().
m_extiEnabled
bool IOPin::m_extiEnabled = false private
Definition at line 60 of file io-pins-hw.hpp.
Referenced by enableExti().
m_gpio
GPIO_TypeDef* IOPin::m_gpio private
Definition at line 58 of file io-pins-hw.hpp.
Referenced by enableExti(), IOPin(), reset(), set(), state(), switchToInput(), and switchToOutput().
m_pinMask
uint16_t IOPin::m_pinMask private
Definition at line 59 of file io-pins-hw.hpp.
Referenced by enableExti(), IOPin(), reset(), set(), state(), switchToInput(), and switchToOutput().
m_runDirectlyFromISR
bool IOPin::m_runDirectlyFromISR = false private
Definition at line 62 of file io-pins-hw.hpp.
Referenced by extiInterrupt(), and setExtiCallback().
The documentation for this class was generated from the following files:
include/hw/io-pins-hw.hpp
src/hw/io-pins-hw.cpp