Caustic lasertag system: UITimeLeftScreen Class Reference
UITimeLeftScreen Class Reference
#include <smart-point-ui.hpp>
Public Member Functions
UITimeLeftScreen (SmartPointUI &ui)
UIStateBase * doIteration () override
void prepare () override
Public Member Functions inherited from UIStateBase
UIStateBase (SmartPointUI &ui)
virtual ~UIStateBase ()
Private Attributes
TeamGameId m_lastLeader = teamGameIdNotATeam
bool m_winRegisered = false
Additional Inherited Members
Protected Attributes inherited from UIStateBase
SmartPointUI & m_ui
bool m_screenUpdated = false
Detailed Description
Definition at line 55 of file smart-point-ui.hpp.
Constructor & Destructor Documentation
UITimeLeftScreen()
UITimeLeftScreen::UITimeLeftScreen (SmartPointUI & ui)
Definition at line 165 of file smart-point-ui.cpp.
Member Function Documentation
doIteration()
UIStateBase * UITimeLeftScreen::doIteration () override virtual
Implements UIStateBase.
Definition at line 171 of file smart-point-ui.cpp.
References RGBLeds::blink(), RGBLeds::blue, LCD5110Controller::clearBuffer(), LCD5110Controller::configureSPI(), LCD5110Controller::fontStandardAscii5x7, formatTime(), SmartPointState::gameStateEnd, MatrixKeyboard::getKeyPressed(), RGBLeds::green, SmartPointUI::initScreen, SmartPointUI::keyboard, MatrixKeyboard::keyNotPressed, SmartPointUI::lcd, SmartPointUI::leds, m_lastLeader, UIStateBase::m_screenUpdated, UIStateBase::m_ui, m_winRegisered, UIStateBase::prepare(), RGBLeds::red, LCD5110Controller::setFont(), SmartPointUI::smartPointState, SmartPointState::stopGame(), LCD5110Controller::stringXY(), and LCD5110Controller::write().
prepare()
void UITimeLeftScreen::prepare () override virtual
Reimplemented from UIStateBase.
Definition at line 244 of file smart-point-ui.cpp.
References m_lastLeader, m_winRegisered, UIStateBase::prepare(), and teamGameIdNotATeam.
Referenced by UIInitScreen::doIteration().
Member Data Documentation
m_lastLeader
TeamGameId UITimeLeftScreen::m_lastLeader = teamGameIdNotATeam private
Definition at line 63 of file smart-point-ui.hpp.
Referenced by doIteration(), and prepare().
m_winRegisered
bool UITimeLeftScreen::m_winRegisered = false private
Definition at line 64 of file smart-point-ui.hpp.
Referenced by doIteration(), and prepare().
The documentation for this class was generated from the following files:
include/smart-point/smart-point-ui.hpp
src/smart-point/smart-point-ui.cpp