Caustic lasertag system: IFragmentPlayer Class Reference
IFragmentPlayer Class Reference abstract
#include <fragment-player.hpp>
Public Member Functions
virtual ~IFragmentPlayer ()
virtual void setFragmentSize (uint32_t size)=0
virtual void init ()=0
virtual void setFragmentDoneCallback (FragmentDoneCallback callback)=0
virtual void playFragment (SoundSample *buffer)=0
virtual void stop ()=0
Detailed Description
Definition at line 32 of file fragment-player.hpp.
Constructor & Destructor Documentation
~IFragmentPlayer()
virtual IFragmentPlayer::~IFragmentPlayer () inline virtual
Definition at line 35 of file fragment-player.hpp.
References fragmentPlayer, init(), playFragment(), setFragmentDoneCallback(), setFragmentSize(), and stop().
Member Function Documentation
init()
virtual void IFragmentPlayer::init () pure virtual
Implemented in FragmentPlayer.
Referenced by WavPlayer::init(), and ~IFragmentPlayer().
playFragment()
virtual void IFragmentPlayer::playFragment (SoundSample * buffer) pure virtual
Implemented in FragmentPlayer.
Referenced by WavPlayer::fragmentDoneCallback(), WavPlayer::play(), and ~IFragmentPlayer().
setFragmentDoneCallback()
virtual void IFragmentPlayer::setFragmentDoneCallback (FragmentDoneCallback callback) pure virtual
Implemented in FragmentPlayerBase.
Referenced by WavPlayer::init(), and ~IFragmentPlayer().
setFragmentSize()
virtual void IFragmentPlayer::setFragmentSize (uint32_t size) pure virtual
Implemented in FragmentPlayerBase.
Referenced by WavPlayer::init(), and ~IFragmentPlayer().
stop()
virtual void IFragmentPlayer::stop () pure virtual
Implemented in FragmentPlayer.
Referenced by ~IFragmentPlayer().
The documentation for this class was generated from the following file:
include/hal/fragment-player.hpp