Caustic lasertag system: RCSPStream Class Reference
RCSPStream Class Reference
#include <RCSP-stream.hpp>
Public Member Functions
RCSPStream (uint16_t size=defaultLength)
~RCSPStream ()
uint8_t * getStream () const
uint16_t getSize () const
RCSPAggregator::ResultType addValue (OperationCode code)
RCSPAggregator::ResultType addRequest (OperationCode code)
RCSPAggregator::ResultType addCall (OperationCode code)
template<typename Type >
RCSPAggregator::ResultType addCall (OperationCode code, const Type &arg)
PackageId send (DeviceAddress target, bool waitForAck=false, PackageSendingDoneCallback doneCallback=nullptr, PackageTimings &&timings=PackageTimings())
void dispatch ()
bool empty ()
Static Public Member Functions
static PackageId remoteCall (DeviceAddress target, OperationCode code, bool waitForAck=true, PackageSendingDoneCallback callback=nullptr, PackageTimings &&timings=PackageTimings())
template<typename Type >
static PackageId remoteCall (DeviceAddress target, OperationCode code, Type &argument, bool waitForAck=true, PackageSendingDoneCallback callback=nullptr, PackageTimings &&timings=PackageTimings())
static PackageId remotePullValue (DeviceAddress target, OperationCode code, bool waitForAck=true, PackageSendingDoneCallback callback=nullptr, PackageTimings &&timings=PackageTimings())
Static Public Attributes
static constexpr uint16_t defaultLength = Package::payloadLength
Private Types
using SerializationFunc = std::function< RCSPAggregator::ResultType(uint8_t *, OperationCode, uint16_t &)>
Private Member Functions
RCSPAggregator::ResultType serializeAnything (OperationCode code, SerializationFunc serializer)
Private Attributes
uint8_t * m_stream = nullptr
uint16_t m_cursor = 0
uint16_t m_freeSpace = 0
uint16_t m_size = 0
Detailed Description
Definition at line 34 of file RCSP-stream.hpp.
Member Typedef Documentation
SerializationFunc
using RCSPStream::SerializationFunc = std::function<RCSPAggregator::ResultType (uint8_t * , OperationCode , uint16_t &)> private
Definition at line 123 of file RCSP-stream.hpp.
Constructor & Destructor Documentation
RCSPStream()
RCSPStream::RCSPStream (uint16_t size = defaultLength)
Definition at line 31 of file RCSP-stream.cpp.
~RCSPStream()
RCSPStream::~RCSPStream ()
Definition at line 39 of file RCSP-stream.cpp.
References m_stream.
Member Function Documentation
addCall() [1/2]
RCSPAggregator::ResultType RCSPStream::addCall (OperationCode code)
Definition at line 79 of file RCSP-stream.cpp.
References instance, m_cursor, m_size, and serializeAnything().
Referenced by Rifle::prepareAndSendShotMsg(), remoteCall(), remotePullValue(), and HeadSensor::sendHeartbeat().
addCall() [2/2]
template<typename Type > RCSPAggregator::ResultType RCSPStream::addCall (OperationCode code, const Type & arg) inline
Definition at line 89 of file RCSP-stream.hpp.
References dispatch(), empty(), instance, m_cursor, m_size, send(), and serializeAnything().
addRequest()
RCSPAggregator::ResultType RCSPStream::addRequest (OperationCode code)
Definition at line 67 of file RCSP-stream.cpp.
References instance, m_cursor, m_size, and serializeAnything().
Referenced by remotePullValue().
addValue()
RCSPAggregator::ResultType RCSPStream::addValue (OperationCode code)
Definition at line 55 of file RCSP-stream.cpp.
References instance, m_cursor, m_size, and serializeAnything().
Referenced by remotePullValue(), and HeadSensor::sendHeartbeat().
dispatch()
void RCSPStream::dispatch ()
Definition at line 122 of file RCSP-stream.cpp.
References empty(), instance, m_cursor, and m_stream.
Referenced by addCall(), and RCSPMultiStream::addCall().
empty()
bool RCSPStream::empty ()
Definition at line 131 of file RCSP-stream.cpp.
References m_cursor.
Referenced by addCall(), RCSPMultiStream::addCall(), and dispatch().
getSize()
uint16_t RCSPStream::getSize () const
Definition at line 50 of file RCSP-stream.cpp.
References m_size.
Referenced by remotePullValue(), IRPresentationTransmitterMT2::sendGenericRCSPMessageDefault(), and IRPresentationTransmitterMT2::sendMessage().
getStream()
uint8_t * RCSPStream::getStream () const
Definition at line 45 of file RCSP-stream.cpp.
References m_stream.
Referenced by remotePullValue(), IRPresentationTransmitterMT2::sendGenericRCSPMessageDefault(), and IRPresentationTransmitterMT2::sendMessage().
remoteCall() [1/2]
static PackageId RCSPStream::remoteCall (DeviceAddress target, OperationCode code, bool waitForAck = true, PackageSendingDoneCallback callback = nullptr, PackageTimings && timings = PackageTimings()) inline static
Definition at line 41 of file RCSP-stream.hpp.
References addCall(), and send().
Referenced by WeaponManager::die(), HeadSensor::notifyDamager(), Rifle::onCardReaded(), Rifle::registerWeapon(), WeaponManager::respawn(), GameLog::BaseStatsCounter::sendNextPackage(), and HeadSensor::turnOffWeapons().
remoteCall() [2/2]
template<typename Type > static PackageId RCSPStream::remoteCall (DeviceAddress target, OperationCode code, Type & argument, bool waitForAck = true, PackageSendingDoneCallback callback = nullptr, PackageTimings && timings = PackageTimings()) inline static
Definition at line 55 of file RCSP-stream.hpp.
References addCall(), and send().
remotePullValue()
static PackageId RCSPStream::remotePullValue (DeviceAddress target, OperationCode code, bool waitForAck = true, PackageSendingDoneCallback callback = nullptr, PackageTimings && timings = PackageTimings()) inline static
Definition at line 69 of file RCSP-stream.hpp.
References addCall(), addRequest(), addValue(), getSize(), getStream(), and send().
Referenced by HeadSensor::sendHeartbeat().
send()
PackageId RCSPStream::send (DeviceAddress target, bool waitForAck = false, PackageSendingDoneCallback doneCallback = nullptr, PackageTimings && timings = PackageTimings())
Send current stream with specified timeout, resend period and resend period delta Move sending function from stream. Stream only for multiply serializetion
Parameters
target Address of receiver
waitForAck Need resend while no ACK received
doneCallback Callback after successful/not successful delivery
timings Package timings
Returns
Package id
Definition at line 105 of file RCSP-stream.cpp.
References instance, m_size, and m_stream.
Referenced by addCall(), RCSPMultiStream::addCall(), remoteCall(), remotePullValue(), and HeadSensor::sendHeartbeat().
serializeAnything()
RCSPAggregator::ResultType RCSPStream::serializeAnything (OperationCode code, SerializationFunc serializer) private
Definition at line 91 of file RCSP-stream.cpp.
References Result::isSuccess, m_cursor, and m_stream.
Referenced by addCall(), addRequest(), and addValue().
Member Data Documentation
defaultLength
constexpr uint16_t RCSPStream::defaultLength = Package::payloadLength static
Definition at line 37 of file RCSP-stream.hpp.
Referenced by MainStateSaver::tryRestore().
m_cursor
uint16_t RCSPStream::m_cursor = 0 private
Definition at line 126 of file RCSP-stream.hpp.
Referenced by addCall(), addRequest(), addValue(), dispatch(), empty(), and serializeAnything().
m_freeSpace
uint16_t RCSPStream::m_freeSpace = 0 private
Definition at line 127 of file RCSP-stream.hpp.
m_size
uint16_t RCSPStream::m_size = 0 private
Definition at line 128 of file RCSP-stream.hpp.
Referenced by addCall(), addRequest(), addValue(), getSize(), and send().
m_stream
uint8_t* RCSPStream::m_stream = nullptr private
Definition at line 125 of file RCSP-stream.hpp.
Referenced by dispatch(), getStream(), send(), serializeAnything(), and ~RCSPStream().
The documentation for this class was generated from the following files:
include/rcsp/RCSP-stream.hpp
src/rscp/RCSP-stream.cpp