Caustic lasertag system: RifleState Class Reference
RifleState Class Reference
#include <rifle-config-and-state.hpp>
Public Member Functions
RifleState (RifleConfiguration *config)
void reset ()
PAR_ST (RESTORABLE, ConfigCodes::Rifle::State, bulletsInMagazineCurrent)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::State, magazinesCountCurrent)
PAR_ST (RESTORABLE, ConfigCodes::Rifle::State, heatnessCurrent)
const RifleConfiguration & config ()
Public Attributes
uint32_t lastReloadTime
bool isEnabled = false
bool isHSConnected = false
Private Attributes
RifleConfiguration * m_config = nullptr
Detailed Description
Definition at line 89 of file rifle-config-and-state.hpp.
Constructor & Destructor Documentation
RifleState()
RifleState::RifleState (RifleConfiguration * config)
Definition at line 160 of file rifle.cpp.
References reset().
Member Function Documentation
config()
const RifleConfiguration& RifleState::config () inline
Definition at line 101 of file rifle-config-and-state.hpp.
Referenced by Rifle::detectRifleState(), Rifle::distortBolt(), Rifle::init(), Rifle::magazineSensor(), Rifle::makeShot(), Rifle::onCardReaded(), Rifle::prepareAndSendShotMsg(), Rifle::registerWeapon(), and Rifle::reloadAndPlay().
PAR_ST() [1/3]
RifleState::PAR_ST (RESTORABLE , ConfigCodes::Rifle::State , bulletsInMagazineCurrent)
PAR_ST() [2/3]
RifleState::PAR_ST (RESTORABLE , ConfigCodes::Rifle::State , magazinesCountCurrent)
PAR_ST() [3/3]
RifleState::PAR_ST (RESTORABLE , ConfigCodes::Rifle::State , heatnessCurrent)
reset()
void RifleState::reset ()
Definition at line 167 of file rifle.cpp.
References lastReloadTime, and m_config.
Referenced by RifleState().
Member Data Documentation
isEnabled
bool RifleState::isEnabled = false
Definition at line 99 of file rifle-config-and-state.hpp.
isHSConnected
bool RifleState::isHSConnected = false
Definition at line 100 of file rifle-config-and-state.hpp.
Referenced by Rifle::onCardReaded(), and RifleLCD5110Display::update().
lastReloadTime
uint32_t RifleState::lastReloadTime
Definition at line 98 of file rifle-config-and-state.hpp.
Referenced by reset().
m_config
RifleConfiguration* RifleState::m_config = nullptr private
Definition at line 104 of file rifle-config-and-state.hpp.
Referenced by reset().
The documentation for this class was generated from the following files:
include/rifle/rifle-config-and-state.hpp
src/rifle/rifle.cpp