Caustic lasertag system: SystemClock Class Reference
SystemClock Class Reference
#include <system-clock-hw.hpp>
Public Member Functions
void init ()
void wait_us (uint32_t time)
Time getTime ()
Public Member Functions inherited from ISystemClock
virtual ~ISystemClock ()
Private Member Functions
void MX_TIM4_Init ()
void MX_TIM5_Init ()
Private Attributes
TIM_HandleTypeDef htim4
TIM_HandleTypeDef htim5
Static Private Attributes
static constexpr uint32_t msInSec = 1000000
static constexpr uint32_t msTimerPeriod = UINT16_MAX
static constexpr uint32_t slaveTimerPeriod = UINT16_MAX
Detailed Description
Definition at line 32 of file system-clock-hw.hpp.
Member Function Documentation
getTime()
Time SystemClock::getTime () virtual
Implements ISystemClock.
Definition at line 82 of file system-clock.cpp.
References msTimerPeriod.
Referenced by wait_us().
init()
void SystemClock::init () virtual
Implements ISystemClock.
Definition at line 35 of file system-clock.cpp.
References htim4, htim5, MX_TIM4_Init(), and MX_TIM5_Init().
MX_TIM4_Init()
void SystemClock::MX_TIM4_Init () private
Definition at line 43 of file system-clock.cpp.
References htim4, msTimerPeriod, and zerify().
Referenced by init().
MX_TIM5_Init()
void SystemClock::MX_TIM5_Init () private
Definition at line 65 of file system-clock.cpp.
References htim5, and slaveTimerPeriod.
Referenced by init().
wait_us()
void SystemClock::wait_us (uint32_t time) virtual
Implements ISystemClock.
Definition at line 97 of file system-clock.cpp.
References getTime().
Member Data Documentation
htim4
TIM_HandleTypeDef SystemClock::htim4 private
Definition at line 45 of file system-clock-hw.hpp.
Referenced by init(), and MX_TIM4_Init().
htim5
TIM_HandleTypeDef SystemClock::htim5 private
Definition at line 46 of file system-clock-hw.hpp.
Referenced by init(), and MX_TIM5_Init().
msInSec
constexpr uint32_t SystemClock::msInSec = 1000000 static private
Definition at line 39 of file system-clock-hw.hpp.
msTimerPeriod
constexpr uint32_t SystemClock::msTimerPeriod = UINT16_MAX static private
Definition at line 40 of file system-clock-hw.hpp.
Referenced by getTime(), and MX_TIM4_Init().
slaveTimerPeriod
constexpr uint32_t SystemClock::slaveTimerPeriod = UINT16_MAX static private
Definition at line 41 of file system-clock-hw.hpp.
Referenced by MX_TIM5_Init().
The documentation for this class was generated from the following files:
include/hw/system-clock-hw.hpp
src/hw/system-clock.cpp