Caustic lasertag system: PlayerPartialState Class Reference
PlayerPartialState Class Reference
#include <rifle-config-and-state.hpp>
Public Member Functions
PlayerPartialState (const DeviceAddress &headSensorAddress)
void syncAll ()
void print ()
bool isAlive ()
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::Configuration, healthMax)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::Configuration, armorMax)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, healthCurrent)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, armorCurrent)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, lifesCountCurrent)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, pointsCount)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, killsCount)
PAR_ST (NOT_RESTORABLE, ConfigCodes::HeadSensor::State, deathsCount)
Private Attributes
const DeviceAddress * m_headSensorAddress
Detailed Description
Definition at line 108 of file rifle-config-and-state.hpp.
Constructor & Destructor Documentation
PlayerPartialState()
PlayerPartialState::PlayerPartialState (const DeviceAddress & headSensorAddress)
Definition at line 44 of file rifle.cpp.
Member Function Documentation
isAlive()
bool PlayerPartialState::isAlive ()
Definition at line 96 of file rifle.cpp.
PAR_ST() [1/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::Configuration , healthMax)
PAR_ST() [2/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::Configuration , armorMax)
PAR_ST() [3/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , healthCurrent)
PAR_ST() [4/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , armorCurrent)
PAR_ST() [5/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , lifesCountCurrent)
PAR_ST() [6/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , pointsCount)
PAR_ST() [7/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , killsCount)
PAR_ST() [8/8]
PlayerPartialState::PAR_ST (NOT_RESTORABLE , ConfigCodes::HeadSensor::State , deathsCount)
print()
void PlayerPartialState::print ()
Definition at line 74 of file rifle.cpp.
References printBar().
syncAll()
void PlayerPartialState::syncAll ()
Definition at line 59 of file rifle.cpp.
References RCSPMultiStream::addRequest(), m_headSensorAddress, and RCSPMultiStream::send().
Member Data Documentation
m_headSensorAddress
const DeviceAddress* PlayerPartialState::m_headSensorAddress private
Definition at line 128 of file rifle-config-and-state.hpp.
Referenced by syncAll().
The documentation for this class was generated from the following files:
include/rifle/rifle-config-and-state.hpp
src/rifle/rifle.cpp