Caustic lasertag system: IIOPin Class Reference
IIOPin Class Reference abstract
#include <io-pins.hpp>
Public Member Functions
virtual ~IIOPin ()
virtual bool state ()=0
virtual void set ()=0
Switch to state "1".
virtual void reset ()=0
Switch to state "0".
virtual void switchToOutput ()=0
virtual void switchToInput ()=0
virtual void setExtiCallback (const IOPinCallback &callback, bool direclyFromISR=false)=0
virtual void enableExti (bool enable=true)=0
Detailed Description
Definition at line 32 of file io-pins.hpp.
Constructor & Destructor Documentation
~IIOPin()
virtual IIOPin::~IIOPin () inline virtual
Definition at line 35 of file io-pins.hpp.
References enableExti(), reset(), setExtiCallback(), state(), switchToInput(), and switchToOutput().
Member Function Documentation
enableExti()
virtual void IIOPin::enableExti (bool enable = true) pure virtual
Implemented in IOPin.
Referenced by NRF24L01Manager::init(), ButtonManager::useEXTI(), and ~IIOPin().
reset()
virtual void IIOPin::reset () pure virtual
Switch to state "0".
Implemented in IOPin.
Referenced by RGBLeds::changeState(), NRF24L01Manager::chipEnableOff(), NRF24L01Manager::chipSelect(), delayedSwitchPin(), MatrixKeyboard::getKeyPressed(), GLCD_DC_LOW_impl(), GLCD_RESET_LOW_impl(), GLCD_SELECT_impl(), RGBLeds::init(), MFRC522::PCD_ReadRegister(), MFRC522::PCD_WriteRegister(), and ~IIOPin().
set()
virtual void IIOPin::set () pure virtual
Switch to state "1".
Implemented in IOPin.
Referenced by blinkPin(), RGBLeds::changeState(), NRF24L01Manager::chipDeselect(), NRF24L01Manager::chipEnableOn(), delayedSwitchPin(), MatrixKeyboard::getKeyPressed(), GLCD_DC_HIGH_impl(), GLCD_DESELECT_impl(), glcd_init(), GLCD_RESET_HIGH_impl(), SPIManager::init(), MatrixKeyboard::init(), MFRC522::PCD_Init(), MFRC522::PCD_ReadRegister(), and MFRC522::PCD_WriteRegister().
setExtiCallback()
virtual void IIOPin::setExtiCallback (const IOPinCallback & callback, bool direclyFromISR = false) pure virtual
Implemented in IOPin.
Referenced by NRF24L01Manager::init(), and ~IIOPin().
state()
virtual bool IIOPin::state () pure virtual
Implemented in IOPin.
Referenced by NRF24L01Manager::init(), ButtonManager::interrogate(), NRF24L01Manager::interrogate(), MFRC522::PCD_Init(), ButtonManager::state(), and ~IIOPin().
switchToInput()
virtual void IIOPin::switchToInput () pure virtual
Implemented in IOPin.
Referenced by MatrixKeyboard::init(), NRF24L01Manager::init(), and ~IIOPin().
switchToOutput()
virtual void IIOPin::switchToOutput () pure virtual
Implemented in IOPin.
Referenced by glcd_init(), SPIManager::init(), MatrixKeyboard::init(), Rifle::init(), RGBLeds::init(), NRF24L01Manager::init(), MFRC522::PCD_Init(), and ~IIOPin().
The documentation for this class was generated from the following file:
include/hal/io-pins.hpp