Caustic lasertag system: IniParcer Class Reference
IniParcer Class Reference
#include <string-utils.hpp>
Public Types
using AcceptKeyValueCallback = std::function< void(const char *key, const char *value)>
Public Member Functions
void setCallback (AcceptKeyValueCallback callback)
Result parseFile (const char *filename)
Private Types
enum ParcerState {
PS_COMMENT = 0, PS_WAITING_KEY, PS_READING_KEY, PS_WAITING_EQ,
PS_WAITING_VALUE, PS_READING_VALUE
}
Private Attributes
char buffer [blockSize]
char key [keyValMaxLength]
char value [keyValMaxLength]
AcceptKeyValueCallback m_acceptKeyValueCallback = nullptr
char m_errorMessage [128]
Static Private Attributes
static constexpr unsigned int blockSize = 100
static constexpr unsigned int keyValMaxLength = 100
Detailed Description
Definition at line 67 of file string-utils.hpp.
Member Typedef Documentation
AcceptKeyValueCallback
using IniParcer::AcceptKeyValueCallback = std::function<void(const char* key, const char* value)>
Definition at line 70 of file string-utils.hpp.
Member Enumeration Documentation
ParcerState
enum IniParcer::ParcerState private
Enumerator
PS_COMMENT
PS_WAITING_KEY
PS_READING_KEY
PS_WAITING_EQ
PS_WAITING_VALUE
PS_READING_VALUE
Definition at line 76 of file string-utils.hpp.
Member Function Documentation
parseFile()
Result IniParcer::parseFile (const char * filename)
Definition at line 151 of file string-utils.cpp.
References blockSize, buffer, error, Result::fail(), isCharacter(), isNumber(), isSpace(), key, keyValMaxLength, m_acceptKeyValueCallback, m_errorMessage, parseFRESULT(), PS_COMMENT, PS_READING_KEY, PS_READING_VALUE, PS_WAITING_EQ, PS_WAITING_KEY, PS_WAITING_VALUE, and value.
Referenced by DeviceInitializer::initDevice(), Rifle::loadConfig(), Pinout::readIni(), and RCSPAggregator::readIni().
setCallback()
void IniParcer::setCallback (AcceptKeyValueCallback callback)
Definition at line 146 of file string-utils.cpp.
References m_acceptKeyValueCallback.
Referenced by DeviceInitializer::initDevice(), Rifle::loadConfig(), Pinout::readIni(), and RCSPAggregator::readIni().
Member Data Documentation
blockSize
constexpr unsigned int IniParcer::blockSize = 100 static private
Definition at line 86 of file string-utils.hpp.
Referenced by parseFile().
buffer
char IniParcer::buffer[blockSize] private
Definition at line 89 of file string-utils.hpp.
Referenced by parseFile().
key
char IniParcer::key[keyValMaxLength] private
Definition at line 90 of file string-utils.hpp.
Referenced by parseFile().
keyValMaxLength
constexpr unsigned int IniParcer::keyValMaxLength = 100 static private
Definition at line 87 of file string-utils.hpp.
Referenced by parseFile().
m_acceptKeyValueCallback
AcceptKeyValueCallback IniParcer::m_acceptKeyValueCallback = nullptr private
Definition at line 93 of file string-utils.hpp.
Referenced by parseFile(), and setCallback().
m_errorMessage
char IniParcer::m_errorMessage[128] private
Definition at line 94 of file string-utils.hpp.
Referenced by parseFile().
value
char IniParcer::value[keyValMaxLength] private
Definition at line 91 of file string-utils.hpp.
Referenced by parseFile().
The documentation for this class was generated from the following files:
include/core/string-utils.hpp
src/core/string-utils.cpp