Caustic lasertag system: RTCMgr Class Reference
RTCMgr Class Reference
#include <rtc-hw.hpp>
Public Member Functions
void init ()
void getDate (RTCDate &date)
void setDate (const RTCDate &date)
void getTime (RTCTime &time)
void setTime (const RTCTime &time)
Public Member Functions inherited from RTCBase
void getDateTime (RTCDateTime &dateTime)
void setDateTime (const RTCDateTime &dateTime)
Public Member Functions inherited from IRTC
virtual ~IRTC ()
Private Member Functions
bool isTurnedOn ()
void RTC_CalendarConfig ()
Static Private Member Functions
static void timeToHalTime (const RTCTime &time, RTC_TimeTypeDef &halTime)
static void halTimeToTime (RTCTime &time, const RTC_TimeTypeDef &halTime)
static void dateToHalDate (const RTCDate &date, RTC_DateTypeDef &halDate)
static void halDateToDate (RTCDate &date, const RTC_DateTypeDef &halDate)
Private Attributes
RTC_HandleTypeDef m_hrtc
Detailed Description
Definition at line 31 of file rtc-hw.hpp.
Member Function Documentation
dateToHalDate()
void RTCMgr::dateToHalDate (const RTCDate & date, RTC_DateTypeDef & halDate) static private
Definition at line 134 of file rtc-hw.cpp.
References RTCDate::day, RTCDate::month, and RTCDate::year.
Referenced by setDate().
getDate()
void RTCMgr::getDate (RTCDate & date) virtual
Implements IRTC.
Definition at line 92 of file rtc-hw.cpp.
References halDateToDate(), and m_hrtc.
getTime()
void RTCMgr::getTime (RTCTime & time) virtual
Implements IRTC.
Definition at line 99 of file rtc-hw.cpp.
References halTimeToTime(), and m_hrtc.
halDateToDate()
void RTCMgr::halDateToDate (RTCDate & date, const RTC_DateTypeDef & halDate) static private
Definition at line 141 of file rtc-hw.cpp.
References RTCDate::day, RTCDate::month, and RTCDate::year.
Referenced by getDate().
halTimeToTime()
void RTCMgr::halTimeToTime (RTCTime & time, const RTC_TimeTypeDef & halTime) static private
Definition at line 127 of file rtc-hw.cpp.
References RTCTime::hours, RTCTime::mins, and RTCTime::secs.
Referenced by getTime().
init()
void RTCMgr::init () virtual
Initialize RTC and set the Time and Date
Implements IRTC.
Definition at line 32 of file rtc-hw.cpp.
References info, isTurnedOn(), m_hrtc, setDate(), setTime(), and zerify().
isTurnedOn()
bool RTCMgr::isTurnedOn () private
Definition at line 148 of file rtc-hw.cpp.
Referenced by init().
RTC_CalendarConfig()
void RTCMgr::RTC_CalendarConfig () private
Definition at line 154 of file rtc-hw.cpp.
References error, and m_hrtc.
setDate()
void RTCMgr::setDate (const RTCDate & date) virtual
Implements IRTC.
Definition at line 106 of file rtc-hw.cpp.
References dateToHalDate(), and m_hrtc.
Referenced by init().
setTime()
void RTCMgr::setTime (const RTCTime & time) virtual
Implements IRTC.
Definition at line 113 of file rtc-hw.cpp.
References m_hrtc, and timeToHalTime().
Referenced by init().
timeToHalTime()
void RTCMgr::timeToHalTime (const RTCTime & time, RTC_TimeTypeDef & halTime) static private
Definition at line 120 of file rtc-hw.cpp.
References RTCTime::hours, RTCTime::mins, and RTCTime::secs.
Referenced by setTime().
Member Data Documentation
m_hrtc
RTC_HandleTypeDef RTCMgr::m_hrtc private
Definition at line 41 of file rtc-hw.hpp.
Referenced by getDate(), getTime(), init(), RTC_CalendarConfig(), setDate(), and setTime().
The documentation for this class was generated from the following files:
include/hw/rtc-hw.hpp
src/hw/rtc-hw.cpp