Caustic lasertag system: SoundPlayer Class Reference
SoundPlayer Class Reference
#include <wav-player.hpp>
Public Member Functions
void readVariants (const char *filenamePrexix, const char *filenameSuffix, uint8_t channel=0)
void addVariant (const char *filename)
void addVariant (std::string &filename)
void addVariant (std::string &&filename)
void play ()
Private Attributes
std::vector< std::string > m_variants
uint8_t m_channel
Detailed Description
Definition at line 99 of file wav-player.hpp.
Member Function Documentation
addVariant() [1/3]
void SoundPlayer::addVariant (const char * filename)
Definition at line 258 of file wav-player.cpp.
addVariant() [2/3]
void SoundPlayer::addVariant (std::string & filename)
Definition at line 263 of file wav-player.cpp.
addVariant() [3/3]
void SoundPlayer::addVariant (std::string && filename)
Definition at line 268 of file wav-player.cpp.
play()
void SoundPlayer::play ()
Definition at line 291 of file wav-player.cpp.
References debug, instance, Random::random(), and warning.
Referenced by SmartPoint::init().
readVariants()
void SoundPlayer::readVariants (const char * filenamePrexix, const char * filenameSuffix, uint8_t channel = 0)
Definition at line 273 of file wav-player.cpp.
References debug.
Referenced by SmartPoint::initSounds().
Member Data Documentation
m_channel
uint8_t SoundPlayer::m_channel private
Definition at line 110 of file wav-player.hpp.
m_variants
std::vector<std::string> SoundPlayer::m_variants private
Definition at line 109 of file wav-player.hpp.
The documentation for this class was generated from the following files:
include/dev/wav-player.hpp
src/dev/wav-player.cpp