Caustic lasertag system: Interrogator Class Reference
Interrogator Class Reference
#include <os-wrappers.hpp>
Public Member Functions
Interrogator (const char *name="UnkIntr")
void registerObject (IInterrogatable *object)
void run (uint32_t period=1)
void setStackSize (uint32_t stackSize)
void setName (const char *name)
Private Member Functions
void interrogateAll ()
Private Attributes
TaskCycled m_task
std::vector< IInterrogatable * > m_objects
Detailed Description
Definition at line 271 of file os-wrappers.hpp.
Constructor & Destructor Documentation
Interrogator()
Interrogator::Interrogator (const char * name = "UnkIntr")
Definition at line 254 of file os-wrappers.cpp.
References interrogateAll().
Member Function Documentation
interrogateAll()
void Interrogator::interrogateAll () private
Definition at line 281 of file os-wrappers.cpp.
Referenced by Interrogator().
registerObject()
void Interrogator::registerObject (IInterrogatable * object)
Definition at line 260 of file os-wrappers.cpp.
Referenced by SmartPoint::init().
run()
void Interrogator::run (uint32_t period = 1)
Definition at line 265 of file os-wrappers.cpp.
Referenced by SmartPoint::init().
setName()
void Interrogator::setName (const char * name)
Definition at line 275 of file os-wrappers.cpp.
setStackSize()
void Interrogator::setStackSize (uint32_t stackSize)
Definition at line 270 of file os-wrappers.cpp.
Referenced by SmartPoint::init().
Member Data Documentation
m_objects
std::vector<IInterrogatable*> Interrogator::m_objects private
Definition at line 283 of file os-wrappers.hpp.
m_task
TaskCycled Interrogator::m_task private
Definition at line 282 of file os-wrappers.hpp.
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp