Caustic lasertag system: FragmentPlayer Class Reference
FragmentPlayer Class Reference
#include <fragment-player.hpp>
Public Member Functions
FragmentPlayer ()
void playFragment (SoundSample *buffer)
void init ()
void DMAInterruptionHandler ()
void stop ()
Public Member Functions inherited from FragmentPlayerBase
void setFragmentSize (uint32_t size)
void setFragmentDoneCallback (FragmentDoneCallback callback)
Public Member Functions inherited from IFragmentPlayer
virtual ~IFragmentPlayer ()
Private Member Functions
void stopFragment ()
Private Attributes
DMA_InitTypeDef m_DMA_InitStructure
Additional Inherited Members
Protected Attributes inherited from FragmentPlayerBase
uint32_t m_size
SoundSample * m_buffer = nullptr
FragmentDoneCallback m_callback
Detailed Description
Definition at line 30 of file fragment-player.hpp.
Constructor & Destructor Documentation
FragmentPlayer()
FragmentPlayer::FragmentPlayer ()
Definition at line 35 of file fragment-player.cpp.
Member Function Documentation
DMAInterruptionHandler()
void FragmentPlayer::DMAInterruptionHandler ()
Definition at line 147 of file fragment-player.cpp.
References FragmentPlayerBase::m_buffer, FragmentPlayerBase::m_callback, and stopFragment().
Referenced by DMA2_Channel3_IRQHandler().
init()
void FragmentPlayer::init () virtual
Todo:
Why not working?
Implements IFragmentPlayer.
Definition at line 39 of file fragment-player.cpp.
References m_DMA_InitStructure, and sampleRate.
playFragment()
void FragmentPlayer::playFragment (SoundSample * buffer) virtual
Implements IFragmentPlayer.
Definition at line 110 of file fragment-player.cpp.
References FragmentPlayerBase::m_buffer, m_DMA_InitStructure, and FragmentPlayerBase::m_size.
stop()
void FragmentPlayer::stop () virtual
Implements IFragmentPlayer.
Definition at line 139 of file fragment-player.cpp.
stopFragment()
void FragmentPlayer::stopFragment () private
Definition at line 132 of file fragment-player.cpp.
Referenced by DMAInterruptionHandler().
Member Data Documentation
m_DMA_InitStructure
DMA_InitTypeDef FragmentPlayer::m_DMA_InitStructure private
Definition at line 41 of file fragment-player.hpp.
Referenced by init(), and playFragment().
The documentation for this class was generated from the following files:
include/hw/fragment-player.hpp
src/hw/fragment-player.cpp