Caustic lasertag system: IIOPinsPool Class Reference
IIOPinsPool Class Reference abstract
#include <io-pins.hpp>
Public Member Functions
virtual ~IIOPinsPool ()
virtual IIOPin * getIOPin (uint8_t portNumber, uint8_t pinNumber)=0
virtual void resetAllPins ()=0
Detailed Description
Definition at line 49 of file io-pins.hpp.
Constructor & Destructor Documentation
~IIOPinsPool()
virtual IIOPinsPool::~IIOPinsPool () inline virtual
Definition at line 52 of file io-pins.hpp.
References IOPins.
Member Function Documentation
getIOPin()
virtual IIOPin* IIOPinsPool::getIOPin (uint8_t portNumber, uint8_t pinNumber) pure virtual
Implemented in IOPinsPool.
Referenced by ButtonsPool::createButtonManager(), RC552Wrapper::init(), SmartPoint::init(), BluetoothBridge::init(), Rifle::init(), HeadSensor::init(), SmartPointUI::initKbd(), and SmartPointUI::initLEDs().
resetAllPins()
virtual void IIOPinsPool::resetAllPins () pure virtual
Implemented in IOPinsPool.
Referenced by HardwareInitializer::MX_GPIO_Init().
The documentation for this class was generated from the following file:
include/hal/io-pins.hpp