Caustic lasertag system: Worker Class Reference
Worker Class Reference
#include <os-wrappers.hpp>
Public Types
using WTask = std::function< void(void)>
Public Member Functions
Worker (uint8_t maxQueueSize)
void setStackSize (uint32_t stackSize)
void run ()
void add (WTask task)
void addFromISR (WTask task)
void setName (const char *name)
Private Member Functions
void mainLoop ()
Private Attributes
TaskOnce m_workerThread
Queue< WTask > m_queue
WTask m_nextTask = nullptr
Detailed Description
Definition at line 324 of file os-wrappers.hpp.
Member Typedef Documentation
WTask
using Worker::WTask = std::function<void(void)>
Definition at line 327 of file os-wrappers.hpp.
Constructor & Destructor Documentation
Worker()
Worker::Worker (uint8_t maxQueueSize)
Definition at line 401 of file os-wrappers.cpp.
References m_workerThread, mainLoop(), and TaskBase::setTask().
Member Function Documentation
add()
void Worker::add (WTask task) inline
Definition at line 333 of file os-wrappers.hpp.
Referenced by WavPlayer::play().
addFromISR()
void Worker::addFromISR (WTask task) inline
Definition at line 338 of file os-wrappers.hpp.
Referenced by IOPin::extiInterrupt(), and WavPlayer::fragmentDoneCallback().
mainLoop()
void Worker::mainLoop () private
Definition at line 417 of file os-wrappers.cpp.
References m_nextTask, m_queue, and Queue< T >::popFront().
Referenced by Worker().
run()
void Worker::run ()
Definition at line 412 of file os-wrappers.cpp.
References m_workerThread, and TaskOnce::run().
Referenced by WavPlayer::init().
setName()
void Worker::setName (const char * name) inline
Definition at line 342 of file os-wrappers.hpp.
setStackSize()
void Worker::setStackSize (uint32_t stackSize)
Definition at line 407 of file os-wrappers.cpp.
References m_workerThread, and TaskBase::setStackSize().
Member Data Documentation
m_nextTask
WTask Worker::m_nextTask = nullptr private
Definition at line 349 of file os-wrappers.hpp.
Referenced by mainLoop().
m_queue
Queue<WTask> Worker::m_queue private
Definition at line 348 of file os-wrappers.hpp.
Referenced by mainLoop().
m_workerThread
TaskOnce Worker::m_workerThread private
Definition at line 347 of file os-wrappers.hpp.
Referenced by run(), setStackSize(), and Worker().
The documentation for this class was generated from the following files:
include/core/os-wrappers.hpp
src/core/os-wrappers.cpp