Caustic lasertag system: MFRC522 Class Reference
MFRC522 Class Reference
#include <RC522.hpp>
Classes
struct MIFARE_Key
struct RC522IO
struct Uid
Public Types
enum PCD_Register {
CommandReg = 0x01 << 1, ComIEnReg = 0x02 << 1, DivIEnReg = 0x03 << 1, ComIrqReg = 0x04 << 1,
DivIrqReg = 0x05 << 1, ErrorReg = 0x06 << 1, Status1Reg = 0x07 << 1, Status2Reg = 0x08 << 1,
FIFODataReg = 0x09 << 1, FIFOLevelReg = 0x0A << 1, WaterLevelReg = 0x0B << 1, ControlReg = 0x0C << 1,
BitFramingReg = 0x0D << 1, CollReg = 0x0E << 1, ModeReg = 0x11 << 1, TxModeReg = 0x12 << 1,
RxModeReg = 0x13 << 1, TxControlReg = 0x14 << 1, TxASKReg = 0x15 << 1, TxSelReg = 0x16 << 1,
RxSelReg = 0x17 << 1, RxThresholdReg = 0x18 << 1, DemodReg = 0x19 << 1, MfTxReg = 0x1C << 1,
MfRxReg = 0x1D << 1, SerialSpeedReg = 0x1F << 1, CRCResultRegH = 0x21 << 1, CRCResultRegL = 0x22 << 1,
ModWidthReg = 0x24 << 1, RFCfgReg = 0x26 << 1, GsNReg = 0x27 << 1, CWGsPReg = 0x28 << 1,
ModGsPReg = 0x29 << 1, TModeReg = 0x2A << 1, TPrescalerReg = 0x2B << 1, TReloadRegH = 0x2C << 1,
TReloadRegL = 0x2D << 1, TCounterValueRegH = 0x2E << 1, TCounterValueRegL = 0x2F << 1, TestSel1Reg = 0x31 << 1,
TestSel2Reg = 0x32 << 1, TestPinEnReg = 0x33 << 1, TestPinValueReg = 0x34 << 1, TestBusReg = 0x35 << 1,
AutoTestReg = 0x36 << 1, VersionReg = 0x37 << 1, AnalogTestReg = 0x38 << 1, TestDAC1Reg = 0x39 << 1,
TestDAC2Reg = 0x3A << 1, TestADCReg = 0x3B << 1
}
enum PCD_Command {
PCD_Idle = 0x00, PCD_Mem = 0x01, PCD_GenerateRandomID = 0x02, PCD_CalcCRC = 0x03,
PCD_Transmit = 0x04, PCD_NoCmdChange = 0x07, PCD_Receive = 0x08, PCD_Transceive = 0x0C,
PCD_MFAuthent = 0x0E, PCD_SoftReset = 0x0F
}
enum PCD_RxGain {
RxGain_18dB = 0x00 << 4, RxGain_23dB = 0x01 << 4, RxGain_18dB_2 = 0x02 << 4, RxGain_23dB_2 = 0x03 << 4,
RxGain_33dB = 0x04 << 4, RxGain_38dB = 0x05 << 4, RxGain_43dB = 0x06 << 4, RxGain_48dB = 0x07 << 4,
RxGain_min = 0x00 << 4, RxGain_avg = 0x04 << 4, RxGain_max = 0x07 << 4
}
enum PICC_Command {
PICC_CMD_REQA = 0x26, PICC_CMD_WUPA = 0x52, PICC_CMD_CT = 0x88, PICC_CMD_SEL_CL1 = 0x93,
PICC_CMD_SEL_CL2 = 0x95, PICC_CMD_SEL_CL3 = 0x97, PICC_CMD_HLTA = 0x50, PICC_CMD_MF_AUTH_KEY_A = 0x60,
PICC_CMD_MF_AUTH_KEY_B = 0x61, PICC_CMD_MF_READ = 0x30, PICC_CMD_MF_WRITE = 0xA0, PICC_CMD_MF_DECREMENT = 0xC0,
PICC_CMD_MF_INCREMENT = 0xC1, PICC_CMD_MF_RESTORE = 0xC2, PICC_CMD_MF_TRANSFER = 0xB0, PICC_CMD_UL_WRITE = 0xA2
}
enum MIFARE_Misc { MF_ACK = 0xA, MF_KEY_SIZE = 6 }
enum PICC_Type : byte {
PICC_TYPE_UNKNOWN, PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_MINI,
PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_UL, PICC_TYPE_MIFARE_PLUS,
PICC_TYPE_TNP3XXX, PICC_TYPE_NOT_COMPLETE = 0xff
}
enum StatusCode : byte {
STATUS_OK, STATUS_ERROR, STATUS_COLLISION, STATUS_TIMEOUT,
STATUS_NO_ROOM, STATUS_INTERNAL_ERROR, STATUS_INVALID, STATUS_CRC_WRONG,
STATUS_MIFARE_NACK = 0xff
}
Public Member Functions
MFRC522 ()
void configureSPI () override
void PCD_WriteRegister (byte reg, byte value)
void PCD_WriteRegister (byte reg, byte count, byte *values)
byte PCD_ReadRegister (byte reg)
void PCD_ReadRegister (byte reg, byte count, byte *values, byte rxAlign=0)
void setBitMask (unsigned char reg, unsigned char mask)
void PCD_SetRegisterBitMask (byte reg, byte mask)
void PCD_ClearRegisterBitMask (byte reg, byte mask)
StatusCode PCD_CalculateCRC (byte *data, byte length, byte *result)
bool PCD_Init (const RC522IO &io)
bool PCD_Reset ()
void PCD_AntennaOn ()
void PCD_AntennaOff ()
byte PCD_GetAntennaGain ()
void PCD_SetAntennaGain (byte mask)
bool PCD_PerformSelfTest ()
StatusCode PCD_TransceiveData (byte *sendData, byte sendLen, byte *backData, byte *backLen, byte *validBits=nullptr, byte rxAlign=0, bool checkCRC=false)
StatusCode PCD_CommunicateWithPICC (byte command, byte waitIRq, byte *sendData, byte sendLen, byte *backData=nullptr, byte *backLen=nullptr, byte *validBits=nullptr, byte rxAlign=0, bool checkCRC=false)
StatusCode PICC_RequestA (byte *bufferATQA, byte *bufferSize)
StatusCode PICC_WakeupA (byte *bufferATQA, byte *bufferSize)
StatusCode PICC_REQA_or_WUPA (byte command, byte *bufferATQA, byte *bufferSize)
StatusCode PICC_Select (Uid *uid, byte validBits=0)
StatusCode PICC_HaltA ()
StatusCode PCD_Authenticate (byte command, byte blockAddr, MIFARE_Key *key, Uid *uid)
void PCD_StopCrypto1 ()
StatusCode MIFARE_Read (byte blockAddr, byte *buffer, byte *bufferSize)
StatusCode MIFARE_Write (byte blockAddr, byte *buffer, byte bufferSize)
StatusCode MIFARE_Ultralight_Write (byte page, byte *buffer, byte bufferSize)
StatusCode MIFARE_Decrement (byte blockAddr, long delta)
StatusCode MIFARE_Increment (byte blockAddr, long delta)
StatusCode MIFARE_Restore (byte blockAddr)
StatusCode MIFARE_Transfer (byte blockAddr)
StatusCode MIFARE_GetValue (byte blockAddr, long *value)
StatusCode MIFARE_SetValue (byte blockAddr, long value)
StatusCode PCD_NTAG216_AUTH (byte *passWord, byte pACK[])
StatusCode PCD_MIFARE_Transceive (byte *sendData, byte sendLen, bool acceptTimeout=false)
void PCD_DumpVersionToSerial ()
void PICC_DumpToSerial (Uid *uid)
void PICC_DumpDetailsToSerial (Uid *uid)
void PICC_DumpMifareClassicToSerial (Uid *uid, PICC_Type piccType, MIFARE_Key *key)
void PICC_DumpMifareClassicSectorToSerial (Uid *uid, MIFARE_Key *key, byte sector)
void PICC_DumpMifareUltralightToSerial ()
void MIFARE_SetAccessBits (byte *accessBitBuffer, byte g0, byte g1, byte g2, byte g3)
bool MIFARE_OpenUidBackdoor (bool logErrors)
bool MIFARE_SetUid (byte *newUid, byte uidSize, bool logErrors)
bool MIFARE_UnbrickUidSector (bool logErrors)
bool PICC_IsNewCardPresent ()
bool PICC_ReadCardSerial ()
Public Member Functions inherited from ISPIUser
virtual ~ISPIUser ()
Static Public Member Functions
static const __FlashStringHelper * GetStatusCodeName (StatusCode code)
static PICC_Type PICC_GetType (byte sak)
static const __FlashStringHelper * PICC_GetTypeName (PICC_Type type)
Public Attributes
Uid uid
Static Public Attributes
static const byte FIFO_SIZE = 64
Private Member Functions
StatusCode MIFARE_TwoStepHelper (byte command, byte blockAddr, long data)
Private Attributes
byte _chipSelectPin
byte _resetPowerDownPin
RC522IO m_io
Detailed Description
Definition at line 145 of file RC522.hpp.
Member Enumeration Documentation
MIFARE_Misc
enum MFRC522::MIFARE_Misc
Enumerator
MF_ACK
MF_KEY_SIZE
Definition at line 280 of file RC522.hpp.
PCD_Command
enum MFRC522::PCD_Command
Enumerator
PCD_Idle
PCD_Mem
PCD_GenerateRandomID
PCD_CalcCRC
PCD_Transmit
PCD_NoCmdChange
PCD_Receive
PCD_Transceive
PCD_MFAuthent
PCD_SoftReset
Definition at line 224 of file RC522.hpp.
PCD_Register
enum MFRC522::PCD_Register
Enumerator
CommandReg
ComIEnReg
DivIEnReg
ComIrqReg
DivIrqReg
ErrorReg
Status1Reg
Status2Reg
FIFODataReg
FIFOLevelReg
WaterLevelReg
ControlReg
BitFramingReg
CollReg
ModeReg
TxModeReg
RxModeReg
TxControlReg
TxASKReg
TxSelReg
RxSelReg
RxThresholdReg
DemodReg
MfTxReg
MfRxReg
SerialSpeedReg
CRCResultRegH
CRCResultRegL
ModWidthReg
RFCfgReg
GsNReg
CWGsPReg
ModGsPReg
TModeReg
TPrescalerReg
TReloadRegH
TReloadRegL
TCounterValueRegH
TCounterValueRegL
TestSel1Reg
TestSel2Reg
TestPinEnReg
TestPinValueReg
TestBusReg
AutoTestReg
VersionReg
AnalogTestReg
TestDAC1Reg
TestDAC2Reg
TestADCReg
Definition at line 149 of file RC522.hpp.
PCD_RxGain
enum MFRC522::PCD_RxGain
Enumerator
RxGain_18dB
RxGain_23dB
RxGain_18dB_2
RxGain_23dB_2
RxGain_33dB
RxGain_38dB
RxGain_43dB
RxGain_48dB
RxGain_min
RxGain_avg
RxGain_max
Definition at line 239 of file RC522.hpp.
PICC_Command
enum MFRC522::PICC_Command
Enumerator
PICC_CMD_REQA
PICC_CMD_WUPA
PICC_CMD_CT
PICC_CMD_SEL_CL1
PICC_CMD_SEL_CL2
PICC_CMD_SEL_CL3
PICC_CMD_HLTA
PICC_CMD_MF_AUTH_KEY_A
PICC_CMD_MF_AUTH_KEY_B
PICC_CMD_MF_READ
PICC_CMD_MF_WRITE
PICC_CMD_MF_DECREMENT
PICC_CMD_MF_INCREMENT
PICC_CMD_MF_RESTORE
PICC_CMD_MF_TRANSFER
PICC_CMD_UL_WRITE
Definition at line 254 of file RC522.hpp.
PICC_Type
enum MFRC522::PICC_Type : byte
Enumerator
PICC_TYPE_UNKNOWN
PICC_TYPE_ISO_14443_4
PICC_TYPE_ISO_18092
PICC_TYPE_MIFARE_MINI
PICC_TYPE_MIFARE_1K
PICC_TYPE_MIFARE_4K
PICC_TYPE_MIFARE_UL
PICC_TYPE_MIFARE_PLUS
PICC_TYPE_TNP3XXX
PICC_TYPE_NOT_COMPLETE
Definition at line 287 of file RC522.hpp.
StatusCode
enum MFRC522::StatusCode : byte
Enumerator
STATUS_OK
STATUS_ERROR
STATUS_COLLISION
STATUS_TIMEOUT
STATUS_NO_ROOM
STATUS_INTERNAL_ERROR
STATUS_INVALID
STATUS_CRC_WRONG
STATUS_MIFARE_NACK
Definition at line 302 of file RC522.hpp.
Constructor & Destructor Documentation
MFRC522()
MFRC522::MFRC522 ()
Constructor.
Definition at line 23 of file RC522.cpp.
Member Function Documentation
configureSPI()
void MFRC522::configureSPI () override virtual
Implements ISPIUser.
Definition at line 26 of file RC522.cpp.
References ISPIManager::BaudRatePrescaler128, MFRC522::RC522IO::chipSelect, ISPIManager::init(), m_io, MFRC522::RC522IO::spi, and ISPIManager::SPIPhase1edge.
Referenced by RC552Wrapper::interrogate(), and PCD_Init().
GetStatusCodeName()
const __FlashStringHelper * MFRC522::GetStatusCodeName (MFRC522::StatusCode code) static
Returns a __FlashStringHelper pointer to a status code name.
Returns
const __FlashStringHelper *
Parameters
code One of the StatusCode enums.
Definition at line 1277 of file RC522.cpp.
References STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_INTERNAL_ERROR, STATUS_INVALID, STATUS_MIFARE_NACK, STATUS_NO_ROOM, STATUS_OK, and STATUS_TIMEOUT.
Referenced by PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
MIFARE_Decrement()
MFRC522::StatusCode MFRC522::MIFARE_Decrement (byte blockAddr, long delta)
MIFARE Decrement subtracts the delta from the value of the addressed block, and stores the result in a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr The block (0-0xff) number.
delta This number is subtracted from the value of block blockAddr.
Definition at line 1033 of file RC522.cpp.
References MIFARE_TwoStepHelper(), and PICC_CMD_MF_DECREMENT.
MIFARE_GetValue()
MFRC522::StatusCode MFRC522::MIFARE_GetValue (byte blockAddr, long * value)
Helper routine to read the current value from a Value Block.
Only for MIFARE Classic and only for blocks in "value block" mode, that is: with access bits [C1 C2 C3] = [110] or [001]. The sector containing the block must be authenticated before calling this function.
Parameters
[in] blockAddr The block (0x00-0xff) number.
[out] value Current value of the Value Block.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Definition at line 1130 of file RC522.cpp.
References MIFARE_Read(), and STATUS_OK.
MIFARE_Increment()
MFRC522::StatusCode MFRC522::MIFARE_Increment (byte blockAddr, long delta)
MIFARE Increment adds the delta to the value of the addressed block, and stores the result in a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr The block (0-0xff) number.
delta This number is added to the value of block blockAddr.
Definition at line 1047 of file RC522.cpp.
References MIFARE_TwoStepHelper(), and PICC_CMD_MF_INCREMENT.
MIFARE_OpenUidBackdoor()
bool MFRC522::MIFARE_OpenUidBackdoor (bool logErrors)
Referenced by PICC_GetTypeName().
MIFARE_Read()
MFRC522::StatusCode MFRC522::MIFARE_Read (byte blockAddr, byte * buffer, byte * bufferSize)
Reads 16 bytes (+ 2 bytes CRC_A) from the active PICC.
For MIFARE Classic the sector containing the block must be authenticated before calling this function.
For MIFARE Ultralight only addresses 00h to 0Fh are decoded. The MF0ICU1 returns a NAK for higher addresses. The MF0ICU1 responds to the READ command by sending 16 bytes starting from the page address defined by the command argument. For example; if blockAddr is 03h then pages 03h, 04h, 05h, 06h are returned. A roll-back is implemented: If blockAddr is 0Eh, then the contents of pages 0Eh, 0Fh, 00h and 01h are returned.
The buffer must be at least 18 bytes because a CRC_A is also returned. Checks the CRC_A before returning STATUS_OK.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr MIFARE Classic: The block (0-0xff) number. MIFARE Ultralight: The first page to return data from.
buffer The buffer to store the data in
bufferSize Buffer size, at least 18 bytes. Also number of bytes returned if STATUS_OK.
Definition at line 930 of file RC522.cpp.
References PCD_CalculateCRC(), PCD_TransceiveData(), PICC_CMD_MF_READ, STATUS_NO_ROOM, and STATUS_OK.
Referenced by MIFARE_GetValue(), PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
MIFARE_Restore()
MFRC522::StatusCode MFRC522::MIFARE_Restore (byte blockAddr)
MIFARE Restore copies the value of the addressed block into a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr The block (0-0xff) number.
Definition at line 1061 of file RC522.cpp.
References MIFARE_TwoStepHelper(), and PICC_CMD_MF_RESTORE.
MIFARE_SetAccessBits()
void MFRC522::MIFARE_SetAccessBits (byte * accessBitBuffer, byte g0, byte g1, byte g2, byte g3)
Referenced by PICC_GetTypeName().
MIFARE_SetUid()
bool MFRC522::MIFARE_SetUid (byte * newUid, byte uidSize, bool logErrors)
Referenced by PICC_GetTypeName().
MIFARE_SetValue()
MFRC522::StatusCode MFRC522::MIFARE_SetValue (byte blockAddr, long value)
Helper routine to write a specific value into a Value Block.
Only for MIFARE Classic and only for blocks in "value block" mode, that is: with access bits [C1 C2 C3] = [110] or [001]. The sector containing the block must be authenticated before calling this function.
Parameters
[in] blockAddr The block (0x00-0xff) number.
[in] value New value of the Value Block.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Definition at line 1155 of file RC522.cpp.
References MIFARE_Write().
MIFARE_Transfer()
MFRC522::StatusCode MFRC522::MIFARE_Transfer (byte blockAddr)
MIFARE Transfer writes the value stored in the volatile memory into one MIFARE Classic block. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001].
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr The block (0-0xff) number.
Definition at line 1104 of file RC522.cpp.
References PCD_MIFARE_Transceive(), PICC_CMD_MF_TRANSFER, and STATUS_OK.
MIFARE_TwoStepHelper()
MFRC522::StatusCode MFRC522::MIFARE_TwoStepHelper (byte command, byte blockAddr, long data) private
Helper function for the two-step MIFARE Classic protocol operations Decrement, Increment and Restore.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
command The command to use
blockAddr The block (0-0xff) number.
data The data to transfer in step 2
Definition at line 1073 of file RC522.cpp.
References MT2Extended::Byte1::command, PCD_MIFARE_Transceive(), and STATUS_OK.
Referenced by MIFARE_Decrement(), MIFARE_Increment(), and MIFARE_Restore().
MIFARE_Ultralight_Write()
MFRC522::StatusCode MFRC522::MIFARE_Ultralight_Write (byte page, byte * buffer, byte bufferSize)
Writes a 4 byte page to the active MIFARE Ultralight PICC.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
page The page (2-15) to write to.
buffer The 4 bytes to write to the PICC
bufferSize Buffer size, must be at least 4 bytes. Exactly 4 bytes are written.
Definition at line 1000 of file RC522.cpp.
References PCD_MIFARE_Transceive(), PICC_CMD_UL_WRITE, STATUS_INVALID, and STATUS_OK.
MIFARE_UnbrickUidSector()
bool MFRC522::MIFARE_UnbrickUidSector (bool logErrors)
Referenced by PICC_GetTypeName().
MIFARE_Write()
MFRC522::StatusCode MFRC522::MIFARE_Write (byte blockAddr, byte * buffer, byte bufferSize)
Writes 16 bytes to the active PICC.
For MIFARE Classic the sector containing the block must be authenticated before calling this function.
For MIFARE Ultralight the operation is called "COMPATIBILITY WRITE". Even though 16 bytes are transferred to the Ultralight PICC, only the least significant 4 bytes (bytes 0 to 3) are written to the specified address. It is recommended to set the remaining bytes 04h to 0Fh to all logic 0.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
blockAddr MIFARE Classic: The block (0-0xff) number. MIFARE Ultralight: The page (2-15) to write to.
buffer The 16 bytes to write to the PICC
bufferSize Buffer size, must be at least 16 bytes. Exactly 16 bytes are written.
Definition at line 965 of file RC522.cpp.
References PCD_MIFARE_Transceive(), PICC_CMD_MF_WRITE, STATUS_INVALID, and STATUS_OK.
Referenced by MIFARE_SetValue(), PICC_GetTypeName(), and RC552Wrapper::writeBlockLoop().
PCD_AntennaOff()
void MFRC522::PCD_AntennaOff ()
Turns the antenna off by disabling pins TX1 and TX2.
Definition at line 328 of file RC522.cpp.
References PCD_ClearRegisterBitMask(), and TxControlReg.
PCD_AntennaOn()
void MFRC522::PCD_AntennaOn ()
Turns the antenna on by enabling pins TX1 and TX2. After a reset these pins are disabled.
Definition at line 318 of file RC522.cpp.
References PCD_ReadRegister(), PCD_WriteRegister(), and TxControlReg.
Referenced by PCD_Init().
PCD_Authenticate()
MFRC522::StatusCode MFRC522::PCD_Authenticate (byte command, byte blockAddr, MIFARE_Key * key, Uid * uid)
Executes the MFRC522 MFAuthent command. This command manages MIFARE authentication to enable a secure communication to any MIFARE Mini, MIFARE 1K and MIFARE 4K card. The authentication is described in the MFRC522 datasheet section 10.3.1.9 and http://www.nxp.com/documents/data_sheet/MF1S503x.pdf section 10.1. For use with MIFARE Classic PICCs. The PICC must be selected - ie in state ACTIVE(*) - before calling this function. Remember to call PCD_StopCrypto1() after communicating with the authenticated PICC - otherwise no new communications can start.
All keys are set to FFFFFFFFFFFFh at chip delivery.
Returns
STATUS_OK on success, STATUS_??? otherwise. Probably STATUS_TIMEOUT if you supply the wrong key.
Parameters
command PICC_CMD_MF_AUTH_KEY_A or PICC_CMD_MF_AUTH_KEY_B
blockAddr The block number. See numbering in the comments in the .h file.
key Pointer to the Crypteo1 key to use (6 bytes)
uid Pointer to Uid struct. The first 4 bytes of the UID is used.
Definition at line 883 of file RC522.cpp.
References MT2Extended::Byte1::command, MFRC522::MIFARE_Key::keyByte, MF_KEY_SIZE, PCD_CommunicateWithPICC(), PCD_MFAuthent, and MFRC522::Uid::uidByte.
Referenced by PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
PCD_CalculateCRC()
MFRC522::StatusCode MFRC522::PCD_CalculateCRC (byte * data, byte length, byte * result)
Use the CRC coprocessor in the MFRC522 to calculate a CRC_A.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
data In: Pointer to the data to transfer to the FIFO for CRC calculation.
length In: The number of bytes to transfer.
result Out: Pointer to result buffer. Result is written to result[0..1], low byte first.
Definition at line 204 of file RC522.cpp.
References CommandReg, CRCResultRegH, CRCResultRegL, DivIrqReg, FIFODataReg, FIFOLevelReg, PCD_CalcCRC, PCD_Idle, PCD_ReadRegister(), PCD_SetRegisterBitMask(), PCD_WriteRegister(), STATUS_OK, and STATUS_TIMEOUT.
Referenced by MIFARE_Read(), PCD_CommunicateWithPICC(), PCD_MIFARE_Transceive(), PCD_NTAG216_AUTH(), PICC_HaltA(), and PICC_Select().
PCD_ClearRegisterBitMask()
void MFRC522::PCD_ClearRegisterBitMask (byte reg, byte mask)
Clears the bits given in mask from register reg.
Parameters
reg The register to update. One of the PCD_Register enums.
mask The bits to clear.
Definition at line 190 of file RC522.cpp.
References PCD_ReadRegister(), and PCD_WriteRegister().
Referenced by PCD_AntennaOff(), PCD_SetAntennaGain(), PCD_StopCrypto1(), PICC_REQA_or_WUPA(), and PICC_Select().
PCD_CommunicateWithPICC()
MFRC522::StatusCode MFRC522::PCD_CommunicateWithPICC (byte command, byte waitIRq, byte * sendData, byte sendLen, byte * backData = nullptr, byte * backLen = nullptr, byte * validBits = nullptr, byte rxAlign = 0, bool checkCRC = false)
Transfers data to the MFRC522 FIFO, executes a command, waits for completion and transfers data back from the FIFO. CRC validation can only be done if backData and backLen are specified.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
command The command to execute. One of the PCD_Command enums.
waitIRq The bits in the ComIrqReg register that signals successful completion of the command.
sendData Pointer to the data to transfer to the FIFO.
sendLen Number of bytes to transfer to the FIFO.
backData NULL or pointer to buffer if data should be read back after executing the command.
backLen In: Max number of bytes to write to *backData. Out: The number of bytes returned.
validBits In/Out: The number of valid bits in the last byte. 0 for 8 valid bits.
rxAlign In: Defines the bit position in backData[0] for the first bit received. Default 0.
checkCRC In: True => The last two bytes of the response is assumed to be a CRC_A that must be validated.
Definition at line 461 of file RC522.cpp.
References BitFramingReg, ComIrqReg, CommandReg, ControlReg, ErrorReg, FIFODataReg, FIFOLevelReg, PCD_CalculateCRC(), PCD_Idle, PCD_ReadRegister(), PCD_SetRegisterBitMask(), PCD_Transceive, PCD_WriteRegister(), STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_MIFARE_NACK, STATUS_NO_ROOM, STATUS_OK, and STATUS_TIMEOUT.
Referenced by PCD_Authenticate(), PCD_MIFARE_Transceive(), PCD_NTAG216_AUTH(), and PCD_TransceiveData().
PCD_DumpVersionToSerial()
void MFRC522::PCD_DumpVersionToSerial ()
Referenced by PICC_GetTypeName().
PCD_GetAntennaGain()
byte MFRC522::PCD_GetAntennaGain ()
Get the current MFRC522 Receiver Gain (RxGain[2:0]) value. See 9.3.3.6 / table 98 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf NOTE: Return value scrubbed with (0x07<<4)=01110000b as RCFfgReg may use reserved bits.
Returns
Value of the RxGain, scrubbed to the 3 bits used.
Definition at line 339 of file RC522.cpp.
References PCD_ReadRegister(), and RFCfgReg.
Referenced by PCD_SetAntennaGain().
PCD_Init()
bool MFRC522::PCD_Init (const RC522IO & io)
Initializes the MFRC522 chip.
Definition at line 242 of file RC522.cpp.
References MFRC522::RC522IO::chipSelect, configureSPI(), m_io, ModeReg, PCD_AntennaOn(), PCD_Reset(), PCD_WriteRegister(), MFRC522::RC522IO::resetPowerDown, IIOPin::set(), IIOPin::state(), IIOPin::switchToOutput(), systemClock, TModeReg, TPrescalerReg, TReloadRegH, TReloadRegL, TxASKReg, and ISystemClock::wait_us().
Referenced by RC552Wrapper::init().
PCD_MIFARE_Transceive()
MFRC522::StatusCode MFRC522::PCD_MIFARE_Transceive (byte * sendData, byte sendLen, bool acceptTimeout = false)
Wrapper for MIFARE protocol communication. Adds CRC_A, executes the Transceive command and checks that the response is MF_ACK or a timeout.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
sendData Pointer to the data to transfer to the FIFO. Do NOT include the CRC_A.
sendLen Number of bytes in sendData.
acceptTimeout True => A timeout is also success
Definition at line 1231 of file RC522.cpp.
References MF_ACK, PCD_CalculateCRC(), PCD_CommunicateWithPICC(), PCD_Transceive, STATUS_ERROR, STATUS_INVALID, STATUS_MIFARE_NACK, STATUS_OK, and STATUS_TIMEOUT.
Referenced by MIFARE_Transfer(), MIFARE_TwoStepHelper(), MIFARE_Ultralight_Write(), and MIFARE_Write().
PCD_NTAG216_AUTH()
MFRC522::StatusCode MFRC522::PCD_NTAG216_AUTH (byte * passWord, byte pACK[])
Authenticate with a NTAG216.
Only for NTAG216. First implemented by Gargantuanman.
Parameters
[in] passWord password.
[in] pACK result success???.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Definition at line 1185 of file RC522.cpp.
References PCD_CalculateCRC(), PCD_CommunicateWithPICC(), PCD_Transceive, and STATUS_OK.
PCD_PerformSelfTest()
bool MFRC522::PCD_PerformSelfTest ()
Performs a self-test of the MFRC522 See 16.1.1 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf
Returns
Whether or not the test passed. Or false if no firmware reference is available.
Definition at line 361 of file RC522.cpp.
References AutoTestReg, CommandReg, DivIrqReg, FIFODataReg, FIFOLevelReg, PCD_CalcCRC, PCD_Idle, PCD_Mem, PCD_ReadRegister(), PCD_Reset(), PCD_SetRegisterBitMask(), PCD_WriteRegister(), pgm_read_byte, and VersionReg.
PCD_ReadRegister() [1/2]
byte MFRC522::PCD_ReadRegister (byte reg)
Reads a byte from the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
Parameters
reg The register to read from. One of the PCD_Register enums.
Definition at line 85 of file RC522.cpp.
References MFRC522::RC522IO::chipSelect, m_io, IIOPin::reset(), IIOPin::set(), MFRC522::RC522IO::spi, ISPIManager::Transmit(), and ISPIManager::TransmitReceive().
Referenced by PCD_AntennaOn(), PCD_CalculateCRC(), PCD_ClearRegisterBitMask(), PCD_CommunicateWithPICC(), PCD_GetAntennaGain(), PCD_PerformSelfTest(), PCD_Reset(), PCD_SetRegisterBitMask(), PICC_GetTypeName(), and PICC_Select().
PCD_ReadRegister() [2/2]
void MFRC522::PCD_ReadRegister (byte reg, byte count, byte * values, byte rxAlign = 0)
Reads a number of bytes from the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
Parameters
reg The register to read from. One of the PCD_Register enums.
count The number of bytes to read
values Byte array to store the values in.
rxAlign Only bit positions rxAlign..7 in values[0] are updated.
Definition at line 109 of file RC522.cpp.
References MFRC522::RC522IO::chipSelect, m_io, IIOPin::reset(), IIOPin::set(), MFRC522::RC522IO::spi, ISPIManager::Transmit(), and ISPIManager::TransmitReceive().
PCD_Reset()
bool MFRC522::PCD_Reset ()
Performs a soft reset on the MFRC522 chip and waits for it to be ready again.
Definition at line 297 of file RC522.cpp.
References CommandReg, ISystemClock::getTime(), PCD_ReadRegister(), PCD_SoftReset, PCD_WriteRegister(), systemClock, and ISystemClock::wait_us().
Referenced by PCD_Init(), and PCD_PerformSelfTest().
PCD_SetAntennaGain()
void MFRC522::PCD_SetAntennaGain (byte mask)
Set the MFRC522 Receiver Gain (RxGain) to value specified by given mask. See 9.3.3.6 / table 98 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf NOTE: Given mask is scrubbed with (0x07<<4)=01110000b as RCFfgReg may use reserved bits.
Definition at line 348 of file RC522.cpp.
References PCD_ClearRegisterBitMask(), PCD_GetAntennaGain(), PCD_SetRegisterBitMask(), and RFCfgReg.
Referenced by RC552Wrapper::init().
PCD_SetRegisterBitMask()
void MFRC522::PCD_SetRegisterBitMask (byte reg, byte mask)
Sets the bits given in mask in register reg.
Parameters
reg The register to update. One of the PCD_Register enums.
mask The bits to set.
Definition at line 179 of file RC522.cpp.
References PCD_ReadRegister(), and PCD_WriteRegister().
Referenced by PCD_CalculateCRC(), PCD_CommunicateWithPICC(), PCD_PerformSelfTest(), and PCD_SetAntennaGain().
PCD_StopCrypto1()
void MFRC522::PCD_StopCrypto1 ()
Used to exit the PCD from its authenticated state. Remember to call this function after communicating with an authenticated PICC - otherwise no new communications can start.
Definition at line 909 of file RC522.cpp.
References PCD_ClearRegisterBitMask(), and Status2Reg.
Referenced by PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
PCD_TransceiveData()
MFRC522::StatusCode MFRC522::PCD_TransceiveData (byte * sendData, byte sendLen, byte * backData, byte * backLen, byte * validBits = nullptr, byte rxAlign = 0, bool checkCRC = false)
Executes the Transceive command. CRC validation can only be done if backData and backLen are specified.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
sendData Pointer to the data to transfer to the FIFO.
sendLen Number of bytes to transfer to the FIFO.
backData NULL or pointer to buffer if data should be read back after executing the command.
backLen In: Max number of bytes to write to *backData. Out: The number of bytes returned.
validBits In/Out: The number of valid bits in the last byte. 0 for 8 valid bits. Default NULL.
rxAlign In: Defines the bit position in backData[0] for the first bit received. Default 0.
checkCRC In: True => The last two bytes of the response is assumed to be a CRC_A that must be validated.
Definition at line 443 of file RC522.cpp.
References PCD_CommunicateWithPICC(), and PCD_Transceive.
Referenced by MIFARE_Read(), PICC_GetTypeName(), PICC_HaltA(), PICC_REQA_or_WUPA(), and PICC_Select().
PCD_WriteRegister() [1/2]
void MFRC522::PCD_WriteRegister (byte reg, byte value)
Writes a byte to the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
Parameters
reg The register to write to. One of the PCD_Register enums.
value The value to write.
Definition at line 38 of file RC522.cpp.
References MFRC522::RC522IO::chipSelect, m_io, IIOPin::reset(), IIOPin::set(), MFRC522::RC522IO::spi, and ISPIManager::Transmit().
Referenced by PCD_AntennaOn(), PCD_CalculateCRC(), PCD_ClearRegisterBitMask(), PCD_CommunicateWithPICC(), PCD_Init(), PCD_PerformSelfTest(), PCD_Reset(), PCD_SetRegisterBitMask(), and PICC_Select().
PCD_WriteRegister() [2/2]
void MFRC522::PCD_WriteRegister (byte reg, byte count, byte * values)
Writes a number of bytes to the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
Parameters
reg The register to write to. One of the PCD_Register enums.
count The number of bytes to write to the register
values The values to write. Byte array.
Definition at line 59 of file RC522.cpp.
References MFRC522::RC522IO::chipSelect, m_io, IIOPin::reset(), IIOPin::set(), MFRC522::RC522IO::spi, and ISPIManager::Transmit().
PICC_DumpDetailsToSerial()
void MFRC522::PICC_DumpDetailsToSerial (Uid * uid)
Referenced by PICC_GetTypeName().
PICC_DumpMifareClassicSectorToSerial()
void MFRC522::PICC_DumpMifareClassicSectorToSerial (Uid * uid, MIFARE_Key * key, byte sector)
Referenced by PICC_GetTypeName().
PICC_DumpMifareClassicToSerial()
void MFRC522::PICC_DumpMifareClassicToSerial (Uid * uid, PICC_Type piccType, MIFARE_Key * key)
Referenced by PICC_GetTypeName().
PICC_DumpMifareUltralightToSerial()
void MFRC522::PICC_DumpMifareUltralightToSerial ()
Referenced by PICC_GetTypeName().
PICC_DumpToSerial()
void MFRC522::PICC_DumpToSerial (Uid * uid)
Referenced by PICC_GetTypeName().
PICC_GetType()
MFRC522::PICC_Type MFRC522::PICC_GetType (byte sak) static
Translates the SAK (Select Acknowledge) to a PICC type.
Returns
PICC_Type
Parameters
sak The SAK byte returned from PICC_Select().
Definition at line 1298 of file RC522.cpp.
References PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, PICC_TYPE_MIFARE_PLUS, PICC_TYPE_MIFARE_UL, PICC_TYPE_NOT_COMPLETE, PICC_TYPE_TNP3XXX, and PICC_TYPE_UNKNOWN.
Referenced by RC552Wrapper::cardReadyToOperate(), and PICC_GetTypeName().
PICC_GetTypeName()
const __FlashStringHelper * MFRC522::PICC_GetTypeName (PICC_Type piccType) static
Returns a __FlashStringHelper pointer to the PICC type name.
Returns
const __FlashStringHelper *
Parameters
piccType One of the PICC_Type enums.
Definition at line 1325 of file RC522.cpp.
References GetStatusCodeName(), MFRC522::MIFARE_Key::keyByte, MIFARE_OpenUidBackdoor(), MIFARE_Read(), MIFARE_SetAccessBits(), MIFARE_SetUid(), MIFARE_UnbrickUidSector(), MIFARE_Write(), PCD_Authenticate(), PCD_DumpVersionToSerial(), PCD_ReadRegister(), PCD_StopCrypto1(), PCD_TransceiveData(), PICC_CMD_MF_AUTH_KEY_A, PICC_DumpDetailsToSerial(), PICC_DumpMifareClassicSectorToSerial(), PICC_DumpMifareClassicToSerial(), PICC_DumpMifareUltralightToSerial(), PICC_DumpToSerial(), PICC_GetType(), PICC_HaltA(), PICC_IsNewCardPresent(), PICC_ReadCardSerial(), PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, PICC_TYPE_MIFARE_PLUS, PICC_TYPE_MIFARE_UL, PICC_TYPE_NOT_COMPLETE, PICC_TYPE_TNP3XXX, PICC_TYPE_UNKNOWN, PICC_WakeupA(), MFRC522::Uid::sak, MFRC522::Uid::size, STATUS_OK, STATUS_TIMEOUT, uid, MFRC522::Uid::uidByte, and VersionReg.
Referenced by RC552Wrapper::cardReadyToOperate().
PICC_HaltA()
MFRC522::StatusCode MFRC522::PICC_HaltA ()
Instructs a PICC in state ACTIVE(*) to go to state HALT.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Definition at line 838 of file RC522.cpp.
References PCD_CalculateCRC(), PCD_TransceiveData(), PICC_CMD_HLTA, STATUS_ERROR, STATUS_OK, and STATUS_TIMEOUT.
Referenced by PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
PICC_IsNewCardPresent()
bool MFRC522::PICC_IsNewCardPresent ()
Returns true if a PICC responds to PICC_CMD_REQA. Only "new" cards in state IDLE are invited. Sleeping cards in state HALT are ignored.
Returns
bool
Definition at line 1900 of file RC522.cpp.
References PICC_RequestA(), STATUS_COLLISION, and STATUS_OK.
Referenced by RC552Wrapper::cardReadyToOperate(), and PICC_GetTypeName().
PICC_ReadCardSerial()
bool MFRC522::PICC_ReadCardSerial ()
Simple wrapper around PICC_Select. Returns true if a UID could be read. Remember to call PICC_IsNewCardPresent(), PICC_RequestA() or PICC_WakeupA() first. The read UID is available in the class variable uid.
Returns
bool
Definition at line 1915 of file RC522.cpp.
References PICC_Select(), and STATUS_OK.
Referenced by RC552Wrapper::cardReadyToOperate(), and PICC_GetTypeName().
PICC_REQA_or_WUPA()
MFRC522::StatusCode MFRC522::PICC_REQA_or_WUPA (byte command, byte * bufferATQA, byte * bufferSize)
Transmits REQA or WUPA commands. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
command The command to send - PICC_CMD_REQA or PICC_CMD_WUPA
bufferATQA The buffer to store the ATQA (Answer to request) in
bufferSize Buffer size, at least two bytes. Also number of bytes returned if STATUS_OK.
Definition at line 584 of file RC522.cpp.
References CollReg, PCD_ClearRegisterBitMask(), PCD_TransceiveData(), STATUS_ERROR, STATUS_NO_ROOM, and STATUS_OK.
Referenced by PICC_RequestA(), and PICC_WakeupA().
PICC_RequestA()
MFRC522::StatusCode MFRC522::PICC_RequestA (byte * bufferATQA, byte * bufferSize)
Transmits a REQuest command, Type A. Invites PICCs in state IDLE to go to READY and prepare for anticollision or selection. 7 bit frame. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
bufferATQA The buffer to store the ATQA (Answer to request) in
bufferSize Buffer size, at least two bytes. Also number of bytes returned if STATUS_OK.
Definition at line 560 of file RC522.cpp.
References PICC_CMD_REQA, and PICC_REQA_or_WUPA().
Referenced by PICC_IsNewCardPresent().
PICC_Select()
MFRC522::StatusCode MFRC522::PICC_Select (Uid * uid, byte validBits = 0)
Transmits SELECT/ANTICOLLISION commands to select a single PICC. Before calling this function the PICCs must be placed in the READY(*) state by calling PICC_RequestA() or PICC_WakeupA(). On success:
The chosen PICC is in state ACTIVE(*) and all other PICCs have returned to state IDLE/HALT. (Figure 7 of the ISO/IEC 14443-3 draft.)
The UID size and value of the chosen PICC is returned in *uid along with the SAK.
A PICC UID consists of 4, 7 or 10 bytes. Only 4 bytes can be specified in a SELECT command, so for the longer UIDs two or three iterations are used: UID size Number of UID bytes Cascade levels Example of PICC ======== =================== ============== =============== single 4 1 MIFARE Classic double 7 2 MIFARE Ultralight triple 10 3 Not currently in use?
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
uid Pointer to Uid struct. Normally output, but can also be used to supply a known UID.
validBits The number of known UID bits supplied in *uid. Normally 0. If set you must also supply uid->size.
Definition at line 623 of file RC522.cpp.
References BitFramingReg, CollReg, PCD_CalculateCRC(), PCD_ClearRegisterBitMask(), PCD_ReadRegister(), PCD_TransceiveData(), PCD_WriteRegister(), PICC_CMD_CT, PICC_CMD_SEL_CL1, PICC_CMD_SEL_CL2, PICC_CMD_SEL_CL3, MFRC522::Uid::sak, MFRC522::Uid::size, STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_INTERNAL_ERROR, STATUS_INVALID, STATUS_OK, and MFRC522::Uid::uidByte.
Referenced by PICC_ReadCardSerial().
PICC_WakeupA()
MFRC522::StatusCode MFRC522::PICC_WakeupA (byte * bufferATQA, byte * bufferSize)
Transmits a Wake-UP command, Type A. Invites PICCs in state IDLE and HALT to go to READY(*) and prepare for anticollision or selection. 7 bit frame. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design.
Returns
STATUS_OK on success, STATUS_??? otherwise.
Parameters
bufferATQA The buffer to store the ATQA (Answer to request) in
bufferSize Buffer size, at least two bytes. Also number of bytes returned if STATUS_OK.
Definition at line 572 of file RC522.cpp.
References PICC_CMD_WUPA, and PICC_REQA_or_WUPA().
Referenced by PICC_GetTypeName().
setBitMask()
void MFRC522::setBitMask (unsigned char reg, unsigned char mask)
Member Data Documentation
_chipSelectPin
byte MFRC522::_chipSelectPin private
Definition at line 428 of file RC522.hpp.
_resetPowerDownPin
byte MFRC522::_resetPowerDownPin private
Definition at line 429 of file RC522.hpp.
FIFO_SIZE
const byte MFRC522::FIFO_SIZE = 64 static
Definition at line 337 of file RC522.hpp.
m_io
RC522IO MFRC522::m_io private
Definition at line 431 of file RC522.hpp.
Referenced by configureSPI(), PCD_Init(), PCD_ReadRegister(), and PCD_WriteRegister().
uid
Uid MFRC522::uid
Definition at line 334 of file RC522.hpp.
Referenced by RC552Wrapper::cardReadyToOperate(), PICC_GetTypeName(), RC552Wrapper::readBlockLoop(), and RC552Wrapper::writeBlockLoop().
The documentation for this class was generated from the following files:
include/dev/RC522.hpp
src/dev/RC522.cpp