Caustic lasertag system: IIRTransmitter Class Reference
IIRTransmitter Class Reference abstract
#include <ir-physical.hpp>
Public Member Functions
virtual ~IIRTransmitter ()
virtual void init (const Pinout &pinout)=0
virtual void setFireEmitter (IFireEmitter *emitter)=0
virtual void setPower (const UintParameter &power)=0
virtual void send (const uint8_t *buffer, uint16_t size)=0
virtual bool busy ()=0
Detailed Description
Definition at line 37 of file ir-physical.hpp.
Constructor & Destructor Documentation
~IIRTransmitter()
virtual IIRTransmitter::~IIRTransmitter () inline virtual
Definition at line 40 of file ir-physical.hpp.
References busy(), init(), send(), setFireEmitter(), and setPower().
Member Function Documentation
busy()
virtual bool IIRTransmitter::busy () pure virtual
Implemented in IRTransmitterTV.
Referenced by ~IIRTransmitter().
init()
virtual void IIRTransmitter::init (const Pinout & pinout) pure virtual
Implemented in IRTransmitterTV.
Referenced by IIRPhysicalReceiver::~IIRPhysicalReceiver(), and ~IIRTransmitter().
send()
virtual void IIRTransmitter::send (const uint8_t * buffer, uint16_t size) pure virtual
Implemented in IRTransmitterTV.
Referenced by IRPresentationTransmitterMT2::sendCommand(), IRPresentationTransmitterMT2::sendGenericRCSPMessageDefault(), IRPresentationTransmitterMT2::sendMessage(), and ~IIRTransmitter().
setFireEmitter()
virtual void IIRTransmitter::setFireEmitter (IFireEmitter * emitter) pure virtual
Implemented in IRTransmitterBase.
Referenced by ~IIRTransmitter().
setPower()
virtual void IIRTransmitter::setPower (const UintParameter & power) pure virtual
Implemented in IRTransmitterBase.
Referenced by ~IIRTransmitter().
The documentation for this class was generated from the following file:
include/ir/ir-physical.hpp