Caustic lasertag system: GameLog::BaseStatsCounter Class Reference
GameLog::BaseStatsCounter Class Reference
#include <game-log.hpp>
Public Member Functions
BaseStatsCounter (const PlayerGameId &hostPlayerId)
void registerDamage (PlayerGameId player, uint16_t damage)
void registerHit (PlayerGameId player)
void registerKill (PlayerGameId player)
void clear ()
void saveState () override
void restoreFromFile ()
void interrogate ()
void sendStats (DeviceAddress target)
Public Member Functions inherited from IAnyStateSaver
virtual ~IAnyStateSaver ()
Private Types
enum StatsSendingState { S_NOTHING = 0, S_READY_TO_TRANSMIT, S_WAITING_FOR_TRANSMISSIO_RESULT, S_WAIT_DELAY_AFTER_CHUNK }
Private Member Functions
void sendNextPackage ()
void prepareTransmission ()
void waitDelay ()
void onTransmissionBroken ()
void onTransmissionSucceeded ()
void checkAndCreate (PlayerGameId enemy)
Private Attributes
std::map< PlayerGameId, PvPDamageResults > m_results
std::map< PlayerGameId, PvPDamageResults >::iterator m_sendingIterator
bool m_iteratorCorrupted = false
FIL m_file
DeviceAddress m_statsReceiver
StatsSendingState m_sendingState = S_NOTHING
CritialSection m_iteratorCheck
Time m_waitingBeginned = 0
const PlayerGameId & m_hostPlayerId
Static Private Attributes
static const char * filename = "base-stat.bin"
static constexpr uint32_t delayAfterChunk = 50000
Detailed Description
Definition at line 40 of file game-log.hpp.
Member Enumeration Documentation
StatsSendingState
enum GameLog::BaseStatsCounter::StatsSendingState private
Enumerator
S_NOTHING
S_READY_TO_TRANSMIT
S_WAITING_FOR_TRANSMISSIO_RESULT
S_WAIT_DELAY_AFTER_CHUNK
Definition at line 59 of file game-log.hpp.
Constructor & Destructor Documentation
BaseStatsCounter()
BaseStatsCounter::BaseStatsCounter (const PlayerGameId & hostPlayerId)
Definition at line 34 of file game-log.cpp.
Member Function Documentation
checkAndCreate()
void BaseStatsCounter::checkAndCreate (PlayerGameId enemy) private
Definition at line 40 of file game-log.cpp.
References m_hostPlayerId, m_iteratorCorrupted, and m_results.
Referenced by registerDamage(), registerHit(), and registerKill().
clear()
void BaseStatsCounter::clear ()
Definition at line 70 of file game-log.cpp.
References m_results, and saveState().
interrogate()
void BaseStatsCounter::interrogate ()
Definition at line 136 of file game-log.cpp.
References m_sendingState, S_NOTHING, S_READY_TO_TRANSMIT, S_WAIT_DELAY_AFTER_CHUNK, sendNextPackage(), and waitDelay().
onTransmissionBroken()
void BaseStatsCounter::onTransmissionBroken () private
Definition at line 213 of file game-log.cpp.
References debug, m_sendingState, and S_NOTHING.
Referenced by sendNextPackage().
onTransmissionSucceeded()
void BaseStatsCounter::onTransmissionSucceeded () private
Definition at line 219 of file game-log.cpp.
References debug, ISystemClock::getTime(), m_sendingState, m_waitingBeginned, S_WAIT_DELAY_AFTER_CHUNK, and systemClock.
Referenced by sendNextPackage().
prepareTransmission()
void BaseStatsCounter::prepareTransmission () private
Definition at line 197 of file game-log.cpp.
References m_iteratorCorrupted, m_results, m_sendingIterator, m_sendingState, and S_READY_TO_TRANSMIT.
Referenced by sendNextPackage(), and sendStats().
registerDamage()
void BaseStatsCounter::registerDamage (PlayerGameId player, uint16_t damage)
Definition at line 52 of file game-log.cpp.
References checkAndCreate(), and m_results.
registerHit()
void BaseStatsCounter::registerHit (PlayerGameId player)
Definition at line 58 of file game-log.cpp.
References checkAndCreate(), and m_results.
registerKill()
void BaseStatsCounter::registerKill (PlayerGameId player)
Definition at line 64 of file game-log.cpp.
References checkAndCreate(), and m_results.
restoreFromFile()
void BaseStatsCounter::restoreFromFile ()
Definition at line 105 of file game-log.cpp.
References GameLog::PvPDamageResults::enemyId, error, filename, m_file, m_results, and warning.
saveState()
void BaseStatsCounter::saveState () override virtual
Implements IAnyStateSaver.
Definition at line 76 of file game-log.cpp.
References error, filename, info, m_file, and m_results.
Referenced by clear().
sendNextPackage()
void BaseStatsCounter::sendNextPackage () private
Definition at line 159 of file game-log.cpp.
References debug, GameLog::PvPDamageResults::enemyId, m_iteratorCheck, m_iteratorCorrupted, m_results, m_sendingIterator, m_sendingState, m_statsReceiver, onTransmissionBroken(), onTransmissionSucceeded(), prepareTransmission(), RCSPStream::remoteCall(), S_NOTHING, S_WAITING_FOR_TRANSMISSIO_RESULT, and ScopedLock< Lockable >::unlock().
Referenced by interrogate().
sendStats()
void BaseStatsCounter::sendStats (DeviceAddress target)
Definition at line 152 of file game-log.cpp.
References m_statsReceiver, and prepareTransmission().
waitDelay()
void BaseStatsCounter::waitDelay () private
Definition at line 204 of file game-log.cpp.
References debug, delayAfterChunk, ISystemClock::getTime(), m_sendingState, m_waitingBeginned, S_READY_TO_TRANSMIT, and systemClock.
Referenced by interrogate().
Member Data Documentation
delayAfterChunk
constexpr uint32_t GameLog::BaseStatsCounter::delayAfterChunk = 50000 static private
Definition at line 57 of file game-log.hpp.
Referenced by waitDelay().
filename
const char * BaseStatsCounter::filename = "base-stat.bin" static private
Definition at line 56 of file game-log.hpp.
Referenced by restoreFromFile(), and saveState().
m_file
FIL GameLog::BaseStatsCounter::m_file private
Definition at line 78 of file game-log.hpp.
Referenced by restoreFromFile(), and saveState().
m_hostPlayerId
const PlayerGameId& GameLog::BaseStatsCounter::m_hostPlayerId private
Definition at line 86 of file game-log.hpp.
Referenced by checkAndCreate().
m_iteratorCheck
CritialSection GameLog::BaseStatsCounter::m_iteratorCheck private
Definition at line 83 of file game-log.hpp.
Referenced by sendNextPackage().
m_iteratorCorrupted
bool GameLog::BaseStatsCounter::m_iteratorCorrupted = false private
Definition at line 76 of file game-log.hpp.
Referenced by checkAndCreate(), prepareTransmission(), and sendNextPackage().
m_results
std::map<PlayerGameId, PvPDamageResults> GameLog::BaseStatsCounter::m_results private
Definition at line 74 of file game-log.hpp.
Referenced by checkAndCreate(), clear(), prepareTransmission(), registerDamage(), registerHit(), registerKill(), restoreFromFile(), saveState(), and sendNextPackage().
m_sendingIterator
std::map<PlayerGameId, PvPDamageResults>::iterator GameLog::BaseStatsCounter::m_sendingIterator private
Definition at line 75 of file game-log.hpp.
Referenced by prepareTransmission(), and sendNextPackage().
m_sendingState
StatsSendingState GameLog::BaseStatsCounter::m_sendingState = S_NOTHING private
Definition at line 81 of file game-log.hpp.
Referenced by interrogate(), onTransmissionBroken(), onTransmissionSucceeded(), prepareTransmission(), sendNextPackage(), and waitDelay().
m_statsReceiver
DeviceAddress GameLog::BaseStatsCounter::m_statsReceiver private
Definition at line 80 of file game-log.hpp.
Referenced by sendNextPackage(), and sendStats().
m_waitingBeginned
Time GameLog::BaseStatsCounter::m_waitingBeginned = 0 private
Definition at line 84 of file game-log.hpp.
Referenced by onTransmissionSucceeded(), and waitDelay().
The documentation for this class was generated from the following files:
include/game/game-log.hpp
src/game/game-log.cpp