Caustic lasertag system: Loggers Class Reference
Loggers Class Reference
#include <logging.hpp>
Static Public Member Functions
static void initLoggers (uint8_t portNumber)
static bool isInitialized ()
static IUARTManager * __attribute__ ((always_inline)) getUsart()
static uint32_t write (const char *buf, size_t nbyte)
Static Public Attributes
static Mutex loggersMutex
Static Private Member Functions
static void infoOnOff (const char *arg)
static void debugOnOff (const char *arg)
static void radioOnOff (const char *arg)
static void traceOnOff (const char *arg)
Static Private Attributes
static std::list< const char * > tags
static IUARTManager * uart = nullptr
static bool m_isInitialized = false
static char * m_tmpBuffer = nullptr
static uint16_t m_tmpBufferCurrent = 0
static constexpr uint16_t tmpBufferSize = 1000
Friends
class Logger
class ScopedTag
Detailed Description
Definition at line 32 of file logging.hpp.
Member Function Documentation
__attribute__()
static IUARTManager* Loggers::__attribute__ ((always_inline)) inline static
Definition at line 39 of file logging.hpp.
References uart.
Referenced by __attribute__(), and _write().
debugOnOff()
static void Loggers::debugOnOff (const char * arg) static private
infoOnOff()
static void Loggers::infoOnOff (const char * arg) static private
initLoggers()
void Loggers::initLoggers (uint8_t portNumber) static
Definition at line 48 of file logging.cpp.
References IUARTsFactory::create(), Logger::enable(), error, info, IUARTManager::init(), m_isInitialized, m_tmpBuffer, m_tmpBufferCurrent, uart, UARTSFactory, and warning.
Referenced by DeviceInitializer::initEnvironment().
isInitialized()
bool Loggers::isInitialized () static
Definition at line 64 of file logging.cpp.
References m_isInitialized.
Referenced by write().
radioOnOff()
static void Loggers::radioOnOff (const char * arg) static private
traceOnOff()
static void Loggers::traceOnOff (const char * arg) static private
write()
uint32_t Loggers::write (const char * buf, size_t nbyte) static
Definition at line 149 of file logging.cpp.
References isInitialized(), m_tmpBuffer, m_tmpBufferCurrent, and tmpBufferSize.
Referenced by _write().
Friends And Related Function Documentation
Logger
friend class Logger friend
Definition at line 34 of file logging.hpp.
ScopedTag
friend class ScopedTag friend
Definition at line 35 of file logging.hpp.
Member Data Documentation
loggersMutex
Mutex Loggers::loggersMutex static
Definition at line 40 of file logging.hpp.
Referenced by Logger::operator<<().
m_isInitialized
bool Loggers::m_isInitialized = false static private
Definition at line 50 of file logging.hpp.
Referenced by initLoggers(), and isInitialized().
m_tmpBuffer
char * Loggers::m_tmpBuffer = nullptr static private
Definition at line 51 of file logging.hpp.
Referenced by initLoggers(), and write().
m_tmpBufferCurrent
uint16_t Loggers::m_tmpBufferCurrent = 0 static private
Definition at line 52 of file logging.hpp.
Referenced by initLoggers(), and write().
tags
std::list< const char * > Loggers::tags static private
Definition at line 48 of file logging.hpp.
Referenced by Logger::operator<<().
tmpBufferSize
constexpr uint16_t Loggers::tmpBufferSize = 1000 static private
Definition at line 53 of file logging.hpp.
Referenced by write().
uart
IUARTManager * Loggers::uart = nullptr static private
Definition at line 49 of file logging.hpp.
Referenced by __attribute__(), initLoggers(), and Logger::operator<<().
The documentation for this class was generated from the following files:
include/core/logging.hpp
src/core/logging.cpp