Caustic lasertag system: IUARTManager Class Reference
IUARTManager Class Reference abstract
#include <uart.hpp>
Public Types
using TXDoneCallback = std::function< void(void)>
using RXDoneCallback = std::function< void(uint8_t *, uint16_t)>
Public Member Functions
virtual ~IUARTManager ()
virtual void init (uint8_t portNumber, uint32_t baudrate)=0
virtual void setTXDoneCallback (TXDoneCallback callback)=0
virtual void setRXDoneCallback (RXDoneCallback callback)=0
virtual void setStopChar (uint8_t stopChar)=0
virtual void enableStopChar (bool enabled)=0
virtual void setBlockSize (uint16_t blockSize)=0
virtual void setRXWorker (Worker *worker)=0
virtual void transmit (uint8_t *buffer, uint16_t size)=0
virtual void transmitSync (uint8_t *buffer, uint16_t size, uint32_t timeout=100000)=0
virtual bool txBusy ()=0
virtual bool rxBusy ()=0
Detailed Description
Definition at line 30 of file uart.hpp.
Member Typedef Documentation
RXDoneCallback
using IUARTManager::RXDoneCallback = std::function<void(uint8_t*, uint16_t)>
Definition at line 35 of file uart.hpp.
TXDoneCallback
using IUARTManager::TXDoneCallback = std::function<void(void)>
Definition at line 34 of file uart.hpp.
Constructor & Destructor Documentation
~IUARTManager()
virtual IUARTManager::~IUARTManager () inline virtual
Definition at line 33 of file uart.hpp.
Member Function Documentation
enableStopChar()
virtual void IUARTManager::enableStopChar (bool enabled) pure virtual
Implemented in UARTManagerBase.
init()
virtual void IUARTManager::init (uint8_t portNumber, uint32_t baudrate) pure virtual
Implemented in UARTManager.
Referenced by Loggers::initLoggers().
rxBusy()
virtual bool IUARTManager::rxBusy () pure virtual
Implemented in UARTManager.
setBlockSize()
virtual void IUARTManager::setBlockSize (uint16_t blockSize) pure virtual
Implemented in UARTManagerBase.
Referenced by BluetoothBridge::init().
setRXDoneCallback()
virtual void IUARTManager::setRXDoneCallback (RXDoneCallback callback) pure virtual
Implemented in UARTManagerBase.
setRXWorker()
virtual void IUARTManager::setRXWorker (Worker * worker) pure virtual
Implemented in UARTManagerBase.
setStopChar()
virtual void IUARTManager::setStopChar (uint8_t stopChar) pure virtual
Implemented in UARTManagerBase.
setTXDoneCallback()
virtual void IUARTManager::setTXDoneCallback (TXDoneCallback callback) pure virtual
Implemented in UARTManagerBase.
transmit()
virtual void IUARTManager::transmit (uint8_t * buffer, uint16_t size) pure virtual
Implemented in UARTManager.
transmitSync()
virtual void IUARTManager::transmitSync (uint8_t * buffer, uint16_t size, uint32_t timeout = 100000) pure virtual
Implemented in UARTManager.
Referenced by Logger::operator<<(), and Logger::LoggerUnnamed::operator<<().
txBusy()
virtual bool IUARTManager::txBusy () pure virtual
Implemented in UARTManager.
The documentation for this class was generated from the following file:
include/hal/uart.hpp