Causticlasertagsystem: Middlewares/Third_Party/glcd/glcd.h File Reference
glcd.h File Reference
GLCD Library main header file. This file must be included into project.
#include <stdint.h>
#include "glcd_devices.h"
#include "glcd_controllers.h"
#include "glcd_graphics.h"
#include "glcd_graphs.h"
#include "glcd_text_tiny.h"
#include "glcd_text.h"
#include "unit_tests.h"
Classes
struct glcd_BoundingBox_t
struct glcd_FontConfig_t
Macros
#define swap(a, b) { uint8_t t = a; a = b; b = t; }
#define GLCD_RESET_TIME 1
Colour Constants
#define BLACK 1
#define WHITE 0
LCD Dimensions
#define GLCD_LCD_WIDTH 0
#define GLCD_LCD_HEIGHT 0
#define GLCD_LCD_WIDTH 128
#define GLCD_LCD_HEIGHT 64
#define GLCD_NUMBER_OF_BANKS (GLCD_LCD_WIDTH / 8)
#define GLCD_NUMBER_OF_COLS GLCD_LCD_WIDTH
Enumerations
enum font_table_type_t { STANG, MIKRO, GLCD_UTILS }
Functions
Base Functions
void glcd_update_bbox (uint8_t xmin, uint8_t ymin, uint8_t xmax, uint8_t ymax)
void glcd_reset_bbox (void)
void glcd_bbox_reset (void)
void glcd_bbox_refresh (void)
void glcd_clear (void)
void glcd_clear_buffer (void)
void glcd_select_screen (uint8_t *buffer, glcd_BoundingBox_t *bbox)
void glcd_scroll (int8_t x, int8_t y)
void glcd_scroll_line (void)
Variables
uint8_t glcd_buffer [GLCD_LCD_WIDTH *GLCD_LCD_HEIGHT/8]
glcd_BoundingBox_t glcd_bbox
uint8_t * glcd_buffer_selected
glcd_BoundingBox_t * glcd_bbox_selected
glcd_FontConfig_t font_current
Detailed Description
GLCD Library main header file. This file must be included into project.
Author
Andy Gock
Definition in file glcd.h.
Macro Definition Documentation
BLACK
#define BLACK 1
Definition at line 157 of file glcd.h.
Referenced by glcd_bar_graph_horizontal(), glcd_bar_graph_vertical(), glcd_draw_char_xy(), glcd_scrolling_bar_graph(), glcd_test_circles(), and glcd_test_rectangles().
GLCD_LCD_HEIGHT [1/2]
#define GLCD_LCD_HEIGHT 0
User specified GLCD height in pixels Set to 0 for automatic assignment based on controller.
Definition at line 200 of file glcd.h.
Referenced by glcd_bbox_refresh(), glcd_clear(), glcd_clear_buffer(), glcd_draw_bitmap(), glcd_draw_char_xy(), glcd_draw_string_xy(), glcd_draw_string_xy_P(), glcd_get_pixel(), glcd_invert_pixel(), glcd_reset_bbox(), glcd_scroll(), glcd_scroll_line(), glcd_set_pixel(), glcd_test_circles(), glcd_test_text_up_down(), glcd_tiny_draw_char(), glcd_tiny_draw_char_xy(), glcd_tiny_draw_string(), glcd_tiny_draw_string_ammend(), glcd_tiny_draw_string_ammend_P(), glcd_tiny_draw_string_P(), and glcd_update_bbox().
GLCD_LCD_HEIGHT [2/2]
#define GLCD_LCD_HEIGHT 64
User specified GLCD height in pixels Set to 0 for automatic assignment based on controller.
Definition at line 200 of file glcd.h.
GLCD_LCD_WIDTH [1/2]
#define GLCD_LCD_WIDTH 0
User specified GLCD width in pixels Set to 0 for automatic assignment based on controller.
Definition at line 199 of file glcd.h.
Referenced by glcd_bbox_refresh(), glcd_clear(), glcd_clear_buffer(), glcd_draw_bitmap(), glcd_draw_char_xy(), glcd_get_pixel(), glcd_invert_pixel(), glcd_reset_bbox(), glcd_scroll(), glcd_scroll_line(), glcd_set_pixel(), glcd_test_circles(), glcd_test_tiny_text(), glcd_tiny_draw_char(), glcd_tiny_draw_char_xy(), glcd_tiny_draw_string(), glcd_tiny_draw_string_P(), glcd_tiny_invert_line(), and glcd_update_bbox().
GLCD_LCD_WIDTH [2/2]
#define GLCD_LCD_WIDTH 128
User specified GLCD width in pixels Set to 0 for automatic assignment based on controller.
Definition at line 199 of file glcd.h.
GLCD_NUMBER_OF_BANKS
#define GLCD_NUMBER_OF_BANKS (GLCD_LCD_WIDTH / 8)
Definition at line 210 of file glcd.h.
Referenced by glcd_test_rectangles().
GLCD_NUMBER_OF_COLS
#define GLCD_NUMBER_OF_COLS GLCD_LCD_WIDTH
Definition at line 211 of file glcd.h.
GLCD_RESET_TIME
#define GLCD_RESET_TIME 1
Reset duration by glcd_reset(), in milliseconds
Definition at line 217 of file glcd.h.
Referenced by glcd_reset().
swap
#define swap (a, b) { uint8_t t = a; a = b; b = t; }
Definition at line 121 of file glcd.h.
Referenced by formatTime(), WavPlayer::fragmentDoneCallback(), glcd_draw_line(), and MainStateSaver::saveState().
WHITE
#define WHITE 0
Definition at line 158 of file glcd.h.
Referenced by glcd_draw_char_xy(), glcd_scrolling_bar_graph(), and glcd_test_circles().
Enumeration Type Documentation
font_table_type_t
enum font_table_type_t
Font table type
Enumerator
STANG
MIKRO
GLCD_UTILS
Definition at line 128 of file glcd.h.
Function Documentation
glcd_bbox_refresh()
void glcd_bbox_refresh (void)
Marks the entire display for re-writing.
Definition at line 114 of file glcd.c.
References GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_BoundingBox_t::x_max, glcd_BoundingBox_t::x_min, glcd_BoundingBox_t::y_max, and glcd_BoundingBox_t::y_min.
Referenced by glcd_draw_bitmap().
glcd_bbox_reset()
void glcd_bbox_reset (void)
Same as glcd_reset_bbox()
Definition at line 110 of file glcd.c.
References glcd_reset_bbox().
glcd_clear()
void glcd_clear (void)
Clear the display. This will clear the buffer and physically write and commit it to the LCD
Definition at line 122 of file glcd.c.
References glcd_buffer_selected, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_update_bbox(), and glcd_write().
Referenced by glcd_init(), glcd_test_circles(), glcd_test_rectangles(), and glcd_test_scrolling_graph().
glcd_clear_buffer()
void glcd_clear_buffer (void)
Clear the display buffer only. This does not physically write the changes to the LCD
Definition at line 128 of file glcd.c.
References glcd_buffer_selected, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, and glcd_update_bbox().
Referenced by LCD5110Controller::clearBuffer(), glcd_test_counter_and_graph(), glcd_test_glcdutils(), glcd_test_hello_world(), glcd_test_rectangles(), and glcd_test_text_up_down().
glcd_reset_bbox()
void glcd_reset_bbox (void)
Reset the bounding box. After resetting the bounding box, no pixels are marked as needing refreshing.
Definition at line 101 of file glcd.c.
References GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_BoundingBox_t::x_max, glcd_BoundingBox_t::x_min, glcd_BoundingBox_t::y_max, and glcd_BoundingBox_t::y_min.
Referenced by glcd_bbox_reset().
glcd_scroll()
void glcd_scroll (int8_t x, int8_t y)
Scroll entire screne buffer by x and y pixels. (not implemented yet)
Note
Items scrolled off the extents of the display dimensions will be lost.
Parameters
x X distance to scroll
y Y distance to scroll
Todo:
Skeleton
Definition at line 139 of file glcd.c.
References GLCD_LCD_HEIGHT, and GLCD_LCD_WIDTH.
glcd_scroll_line()
void glcd_scroll_line (void)
Scroll screen buffer up by 8 pixels. This is designed to be used in conjunciton with tiny text functions which are 8 bits high.
See also
Tiny Text
Definition at line 153 of file glcd.c.
References glcd_buffer_selected, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, and glcd_update_bbox().
Referenced by glcd_tiny_draw_string_ammend(), and glcd_tiny_draw_string_ammend_P().
glcd_select_screen()
void glcd_select_screen (uint8_t * buffer, glcd_BoundingBox_t * bbox)
Select screen buffer and bounding box structure. This should be selected at initialisation. There are future plans to support multiple screen buffers but this not yet available.
Parameters
buffer Pointer to screen buffer
bbox Pointer to bounding box object.
See also
glcd_BoundingBox_t
Definition at line 133 of file glcd.c.
References glcd_buffer_selected.
Referenced by glcd_draw_bitmap(), and glcd_init().
glcd_update_bbox()
void glcd_update_bbox (uint8_t xmin, uint8_t ymin, uint8_t xmax, uint8_t ymax)
Update bounding box.
The bounding box defines a rectangle in which needs to be refreshed next time glcd_write() is called. glcd_write() only writes to those pixels inside the bounding box plus any surrounding pixels which are required according to the bank/column write method of the controller.
Define a rectangle here, and it will be added to the existing bounding box.
Parameters
xmin Minimum x value of rectangle
ymin Minimum y value of rectangle
xmax Maximum x value of rectangle
ymax Maximum y value of rectangle
See also
glcd_bbox
glcd_bbox_selected
Definition at line 69 of file glcd.c.
References GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_BoundingBox_t::x_max, glcd_BoundingBox_t::x_min, glcd_BoundingBox_t::y_max, and glcd_BoundingBox_t::y_min.
Referenced by glcd_clear(), glcd_clear_buffer(), glcd_draw_circle(), glcd_draw_line(), glcd_draw_rect(), glcd_draw_rect_thick(), glcd_fill_circle(), glcd_fill_rect(), glcd_invert_pixel(), glcd_scroll_line(), glcd_set_pixel(), glcd_tiny_draw_char(), and glcd_tiny_draw_char_xy().
Variable Documentation
font_current
glcd_FontConfig_t font_current
Definition at line 41 of file text.c.
Referenced by glcd_test_text_up_down(), glcd_tiny_draw_char(), glcd_tiny_draw_char_xy(), glcd_tiny_draw_string(), glcd_tiny_draw_string_P(), and glcd_tiny_set_font().