Causticlasertagsystem: Devices
Devices
Functions
void glcd_init (void)
void glcd_spi_write (uint8_t c)
void glcd_reset (void)
Detailed Description
Functions specific to certain devices (microcontrollers)
Function Documentation
glcd_init()
void glcd_init (void)
Initialise the LCD. This function is platform and controller specific.
Definition at line 75 of file lcd5110.cpp.
References ISPIManager::BaudRatePrescaler32, LCD5110Controller::LcdIO::chipEnable, LCD5110Controller::LcdIO::dataCommand, glcd_bbox, glcd_buffer, glcd_clear(), glcd_PCD8544_init(), glcd_select_screen(), ISPIManager::init(), LCD5110Controller::LcdIO::reset, IIOPin::set(), LCD5110Controller::LcdIO::spi, ISPIManager::SPIPhase2edge, and IIOPin::switchToOutput().
Referenced by LCD5110Controller::init().
glcd_reset()
void glcd_reset (void)
Reset the LCD.
Note
Not all LCD controllers support reset.
Definition at line 98 of file lcd5110.cpp.
References delay_ms(), GLCD_DESELECT_impl(), GLCD_RESET_HIGH_impl(), GLCD_RESET_LOW_impl(), GLCD_RESET_TIME, and GLCD_SELECT_impl().
glcd_spi_write()
void glcd_spi_write (uint8_t c)
Write a byte to the connected SPI slave.
Parameters
c Byte to be written
Returns
Returned value from SPI (often not used)
Definition at line 91 of file lcd5110.cpp.
References GLCD_DESELECT_impl(), GLCD_SELECT_impl(), LCD5110Controller::LcdIO::spi, and ISPIManager::Transmit().