Causticlasertagsystem: Standard Text
Standard Text
Text
Functions
void glcd_set_font (const char *font_table, uint8_t width, uint8_t height, char start_char, char end_char)
void glcd_font (const char *font_table, uint8_t width, uint8_t height, char start_char, char end_char, font_table_type_t type)
uint8_t glcd_draw_char_xy (uint8_t x, uint8_t y, char c)
void glcd_draw_string_xy (uint8_t x, uint8_t y, const char *c)
void glcd_draw_string_xy_P (uint8_t x, uint8_t y, const char *str)
Detailed Description
Functions relating to using text fonts of all sizes.
Function Documentation
glcd_draw_char_xy()
uint8_t glcd_draw_char_xy (uint8_t x, uint8_t y, char c)
Draw a char at specified location.
Parameters
x x location to place top-left of character frame
y y location to place top-left of character frame
c character to be drawn
Returns
width of character, 0 on error (e.g could not read font table)
Definition at line 73 of file text.c.
References BLACK, glcd_FontConfig_t::end_char, glcd_FontConfig_t::font_table, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_set_pixel(), GLCD_UTILS, glcd_FontConfig_t::height, MIKRO, pgm_read_byte, STANG, glcd_FontConfig_t::start_char, glcd_FontConfig_t::table_type, WHITE, and glcd_FontConfig_t::width.
Referenced by glcd_draw_string_xy(), and glcd_draw_string_xy_P().
glcd_draw_string_xy()
void glcd_draw_string_xy (uint8_t x, uint8_t y, const char * c)
Draw a string at specified location.
Parameters
x x location to place top-left of character frame
y y location to place top-left of character frame
c pointer to string to be drawn
Definition at line 271 of file text.c.
References glcd_draw_char_xy(), GLCD_LCD_HEIGHT, and glcd_FontConfig_t::height.
Referenced by glcd_test_counter_and_graph(), glcd_test_glcdutils(), glcd_test_text_up_down(), and LCD5110Controller::stringXY().
glcd_draw_string_xy_P()
void glcd_draw_string_xy_P (uint8_t x, uint8_t y, const char * str)
Draw a string from program memory at specified location.
Parameters
x x location to place top-left of character frame
y y location to place top-left of character frame
str pointer to string in program memory to be drawn
Definition at line 287 of file text.c.
References glcd_draw_char_xy(), GLCD_LCD_HEIGHT, glcd_FontConfig_t::height, and pgm_read_byte.
glcd_font()
void glcd_font (const char * font_table, uint8_t width, uint8_t height, char start_char, char end_char, font_table_type_t type)
Set GLCD font to predefined font table. Suitable for different different types of font tables.
Parameters
font_table pointer to font table to be used
width width of each character
height height of each character
start_char first character of font table
end_char last character of font table
type font table type
Note
Only suitable for MikroElektronika font storage format. For Stang format, use glcd_tiny_set_font()
See also
glcd_tiny_set_font()
Definition at line 61 of file text.c.
References glcd_FontConfig_t::end_char, glcd_FontConfig_t::font_table, glcd_FontConfig_t::height, glcd_FontConfig_t::start_char, glcd_FontConfig_t::table_type, and glcd_FontConfig_t::width.
Referenced by glcd_set_font(), and glcd_test_glcdutils().
glcd_set_font()
void glcd_set_font (const char * font_table, uint8_t width, uint8_t height, char start_char, char end_char)
Set GLCD font to predefined font table. Only suitable for MikroElektronika font storage format.
Parameters
font_table pointer to font table to be used
width width of each character
height height of each character
start_char first character of font table
end_char last character of font table
Note
Only suitable for MikroElektronika font storage format. For Stang format, use glcd_tiny_set_font()
See also
glcd_tiny_set_font()
Definition at line 46 of file text.c.
References glcd_FontConfig_t::end_char, glcd_FontConfig_t::font_table, glcd_font(), glcd_FontConfig_t::height, MIKRO, glcd_FontConfig_t::start_char, glcd_FontConfig_t::table_type, and glcd_FontConfig_t::width.
Referenced by glcd_test_counter_and_graph(), glcd_test_text_up_down(), and LCD5110Controller::setFont().