Causticlasertagsystem: Graphing
Graphing
Functions
void glcd_bar_graph_horizontal (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void glcd_bar_graph_horizontal_no_border (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void glcd_bar_graph_vertical (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void glcd_bar_graph_vertical_no_border (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
void glcd_scrolling_bar_graph (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Detailed Description
Functions for graphing, e.g drawing bar graphs etc.
Function Documentation
glcd_bar_graph_horizontal()
void glcd_bar_graph_horizontal (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Draw horizontal bar graph with 1 px wide border. The bar graph draws from left to right as val increases.
Parameters
x x location for top-left of border
y y location for top-left of border
width width of the border
height height of the border (must be over 2)
val value to display in graph (0-255 8 bit value).
Definition at line 39 of file graphs.c.
References BLACK, glcd_draw_rect(), and glcd_fill_rect().
Referenced by LCD5110Controller::barHorizontal(), and glcd_test_counter_and_graph().
glcd_bar_graph_horizontal_no_border()
void glcd_bar_graph_horizontal_no_border (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Draw horizontal bar graph with no border. The bar graph draws from left to right as val increases.
Parameters
x x location for top-left of bar
y y location for top-left of bar
width width of the bar at full val
height height of the bar
val value to display in graph (0-255 8 bit value).
Definition at line 48 of file graphs.c.
References glcd_fill_rect().
glcd_bar_graph_vertical()
void glcd_bar_graph_vertical (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Draw vertical bar graph with 1px wide border. The bar graph draws from bottom to top as val increases.
Parameters
x x location for top-left of border
y y location for top-left of border
width width of the border
height height of the border
val value to display in graph (0-255 8 bit value).
Definition at line 56 of file graphs.c.
References BLACK, glcd_draw_rect(), and glcd_fill_rect().
Referenced by LCD5110Controller::barVertical(), and glcd_test_counter_and_graph().
glcd_bar_graph_vertical_no_border()
void glcd_bar_graph_vertical_no_border (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Draw vertical bar graph with no border. The bar graph draws from bottom to top as val increases.
Parameters
x x location for top-left of bar
y y location for top-left of bar
width width of the bar
height height of the bar
val value to display in graph (0-255 8 bit value).
Definition at line 62 of file graphs.c.
References glcd_fill_rect().
glcd_scrolling_bar_graph()
void glcd_scrolling_bar_graph (uint8_t x, uint8_t y, uint8_t width, uint8_t height, uint8_t val)
Todo:
write doc
Definition at line 67 of file graphs.c.
References BLACK, glcd_draw_line(), glcd_draw_rect(), glcd_get_pixel(), glcd_set_pixel(), glcd_write(), and WHITE.
Referenced by glcd_scrolling_bar_graph_timing(), and glcd_test_scrolling_graph().