Causticlasertagsystem: Tiny Text
Tiny Text
Macros
#define GLCD_TEXT_INIT() glcd_tiny_set_font(Font5x7,5,7,32,127);
#define GLCD_WRITE(str) glcd_tiny_draw_string_ammend(str)
#define GLCD_WRITE_P(str) glcd_tiny_draw_string_ammend_P(str)
Functions
void glcd_tiny_set_font (const char *font_table, uint8_t width, uint8_t height, char start_char, char end_char)
void glcd_tiny_draw_char (uint8_t x, uint8_t line, char c)
void glcd_tiny_draw_string (uint8_t x, uint8_t line, const char *str)
void glcd_tiny_draw_string_P (uint8_t x, uint8_t line, const char *str)
void glcd_tiny_draw_string_ammend (char *str)
void glcd_tiny_draw_string_ammend_P (const char *str)
void glcd_tiny_invert_line (uint8_t line)
void glcd_tiny_draw_char_xy (uint8_t x, uint8_t y, char c)
Detailed Description
Functions relating to using tiny 5x7 text fonts.
Tiny text functions are usually used on a line by line basis. Each line being 8 bits high. Characters start on the top most bit and are 7 bits high, leaving a one bit space underneath.
Macro Definition Documentation
GLCD_TEXT_INIT
#define GLCD_TEXT_INIT () glcd_tiny_set_font(Font5x7,5,7,32,127);
Initialise 5x7 text
Definition at line 126 of file glcd_text_tiny.h.
Referenced by glcd_test_tiny_text().
GLCD_WRITE
#define GLCD_WRITE (str) glcd_tiny_draw_string_ammend(str)
Write string to bottom-most line after scrolling everything else up
Definition at line 129 of file glcd_text_tiny.h.
Referenced by glcd_test_tiny_text().
GLCD_WRITE_P
#define GLCD_WRITE_P (str) glcd_tiny_draw_string_ammend_P(str)
Write string from program memory to bottom-most line after scrolling everything else up
Definition at line 132 of file glcd_text_tiny.h.
Function Documentation
glcd_tiny_draw_char()
void glcd_tiny_draw_char (uint8_t x, uint8_t line, char c)
Write character to LCD in tiny 5x7 font.
Parameters
x column position to start
line line number to be written (each line is 8 pixels high)
c char to be written
Definition at line 51 of file text_tiny.c.
References glcd_FontConfig_t::end_char, font_current, glcd_FontConfig_t::font_table, glcd_buffer_selected, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_update_bbox(), glcd_FontConfig_t::height, pgm_read_byte, glcd_FontConfig_t::start_char, and glcd_FontConfig_t::width.
Referenced by glcd_tiny_draw_string(), and glcd_tiny_draw_string_P().
glcd_tiny_draw_char_xy()
void glcd_tiny_draw_char_xy (uint8_t x, uint8_t y, char c)
Write character to LCD in tiny 5x7 font to specified X, Y location. If position is aligned with 8 bit line heights, use glcd_tiny_draw_char() instead as it will be faster.
Parameters
x column position to start
y row position to start (pixel based, not 8 bit high rows)
c char to be written
See also
glcd_tiny_draw_char()
Note
This does the same thing as glcd_tiny_draw_char_xy() but is limited to Stang format font tables.
Definition at line 145 of file text_tiny.c.
References glcd_FontConfig_t::end_char, font_current, glcd_FontConfig_t::font_table, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_set_pixel(), glcd_update_bbox(), glcd_FontConfig_t::height, pgm_read_byte, STANG, glcd_FontConfig_t::start_char, glcd_FontConfig_t::table_type, and glcd_FontConfig_t::width.
glcd_tiny_draw_string()
void glcd_tiny_draw_string (uint8_t x, uint8_t line, const char * str)
Write string to display buffer in tiny 5x7 font. Will wrap to next line if needed. Screen is not updated. Use glcd_write() to physically update display.
Parameters
x column position to start
line line number to be written (each line is 8 pixels high)
str string to be written
Definition at line 81 of file text_tiny.c.
References font_current, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_tiny_draw_char(), glcd_tiny_draw_string_P(), glcd_FontConfig_t::height, and glcd_FontConfig_t::width.
Referenced by glcd_test_hello_world(), glcd_test_rectangles(), glcd_tiny_draw_string_ammend(), and LCD5110Controller::stringXY().
glcd_tiny_draw_string_ammend()
void glcd_tiny_draw_string_ammend (char * str)
Write string to bottom row of display. Screen buffer is scrolled up by one line. Screen is then physically updated.
Parameters
str string to be written
Definition at line 128 of file text_tiny.c.
References GLCD_LCD_HEIGHT, glcd_scroll_line(), glcd_tiny_draw_string(), and glcd_write().
glcd_tiny_draw_string_ammend_P()
void glcd_tiny_draw_string_ammend_P (const char * str)
Write string from flash memory to bottom row of display. Screen buffer is scrolled up by one line. Screen is then physically updated.
Parameters
str string to be written
Definition at line 134 of file text_tiny.c.
References GLCD_LCD_HEIGHT, glcd_scroll_line(), glcd_tiny_draw_string_P(), and glcd_write().
glcd_tiny_draw_string_P()
void glcd_tiny_draw_string_P (uint8_t x, uint8_t line, const char * str)
Write flash string to display buffer in tiny 5x7 font. Will wrap to next line if needed. Screen is not updated. Use glcd_write() to physically update display.
Parameters
x column position to start
line line to be written (each line is 8 pixels high)
str string stored in flash memory to be written
Definition at line 101 of file text_tiny.c.
References font_current, GLCD_LCD_HEIGHT, GLCD_LCD_WIDTH, glcd_tiny_draw_char(), glcd_FontConfig_t::height, pgm_read_byte, and glcd_FontConfig_t::width.
Referenced by glcd_tiny_draw_string(), and glcd_tiny_draw_string_ammend_P().
glcd_tiny_invert_line()
void glcd_tiny_invert_line (uint8_t line)
Invert all contents of line number. Line 0 is the top most line.
Parameters
line Line number (0 is top most line)
Definition at line 140 of file text_tiny.c.
References glcd_invert_area(), and GLCD_LCD_WIDTH.
glcd_tiny_set_font()
void glcd_tiny_set_font (const char * font_table, uint8_t width, uint8_t height, char start_char, char end_char)
Set font to be used from now on. This is the tiny 5x7 monospace font.
Parameters
font_table flash pointer to start from font table
width width of each character
height height of each character
start_char start character
end_char end character
Note
Only suitable for Stang font storage format. For MikroElektronika format, use glcd_set_font()
See also
glcd_set_font()
Definition at line 40 of file text_tiny.c.
References glcd_FontConfig_t::end_char, font_current, glcd_FontConfig_t::font_table, glcd_FontConfig_t::height, STANG, glcd_FontConfig_t::start_char, glcd_FontConfig_t::table_type, and glcd_FontConfig_t::width.
Referenced by glcd_test_hello_world(), glcd_test_rectangles(), and LCD5110Controller::setFont().