Caustic lasertag system: src/dev/io-pins-utils.cpp File Reference
io-pins-utils.cpp File Reference
#include "dev/io-pins-utils.hpp"
Functions
void delayedSwitchPin (TasksPool &pool, IIOPin *pin, bool state, uint32_t delay)
void blinkPin (TasksPool &pool, IIOPin *pin, uint32_t delay)
Function Documentation
blinkPin()
void blinkPin (TasksPool & pool, IIOPin * pin, uint32_t delay)
Definition at line 43 of file io-pins-utils.cpp.
References delayedSwitchPin(), and IIOPin::set().
delayedSwitchPin()
void delayedSwitchPin (TasksPool & pool, IIOPin * pin, bool state, uint32_t delay)
Definition at line 27 of file io-pins-utils.cpp.
References TasksPool::addOnce(), IIOPin::reset(), and IIOPin::set().
Referenced by blinkPin(), and Rifle::makeShot().