Caustic lasertag system: src/dev/lcd5110.cpp File Reference
lcd5110.cpp File Reference
#include "dev/lcd5110.hpp"
#include "hal/system-clock.hpp"
#include "core/logging.hpp"
#include "utils/memory.hpp"
#include "glcd.h"
#include "fonts/font5x7.h"
#include "fonts/Liberation_Sans15x21_Numbers.h"
#include <stdio.h>
Functions
void GLCD_SELECT_impl (void)
void GLCD_DESELECT_impl ()
void GLCD_DC_LOW_impl ()
void GLCD_DC_HIGH_impl ()
void GLCD_RESET_LOW_impl ()
void GLCD_RESET_HIGH_impl ()
void delay_ms (uint32_t ms)
void glcd_init (void)
void glcd_spi_write (uint8_t c)
void glcd_reset (void)
Function Documentation
delay_ms()
void delay_ms (uint32_t ms)
Definition at line 69 of file lcd5110.cpp.
References systemClock, and ISystemClock::wait_us().
Referenced by glcd_reset().
GLCD_DC_HIGH_impl()
void GLCD_DC_HIGH_impl ()
Definition at line 54 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::dataCommand, and IIOPin::set().
GLCD_DC_LOW_impl()
void GLCD_DC_LOW_impl ()
Definition at line 49 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::dataCommand, and IIOPin::reset().
GLCD_DESELECT_impl()
void GLCD_DESELECT_impl ()
Definition at line 44 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::chipEnable, and IIOPin::set().
Referenced by glcd_reset(), and glcd_spi_write().
glcd_init()
void glcd_init (void)
Definition at line 75 of file lcd5110.cpp.
References ISPIManager::BaudRatePrescaler32, LCD5110Controller::LcdIO::chipEnable, LCD5110Controller::LcdIO::dataCommand, ISPIManager::init(), LCD5110Controller::LcdIO::reset, IIOPin::set(), LCD5110Controller::LcdIO::spi, ISPIManager::SPIPhase2edge, and IIOPin::switchToOutput().
Referenced by LCD5110Controller::init().
glcd_reset()
void glcd_reset (void)
Definition at line 98 of file lcd5110.cpp.
References delay_ms(), GLCD_DESELECT_impl(), GLCD_RESET_HIGH_impl(), GLCD_RESET_LOW_impl(), and GLCD_SELECT_impl().
GLCD_RESET_HIGH_impl()
void GLCD_RESET_HIGH_impl ()
Definition at line 64 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::reset, and IIOPin::set().
Referenced by glcd_reset().
GLCD_RESET_LOW_impl()
void GLCD_RESET_LOW_impl ()
Definition at line 59 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::reset, and IIOPin::reset().
Referenced by glcd_reset().
GLCD_SELECT_impl()
void GLCD_SELECT_impl (void)
Definition at line 39 of file lcd5110.cpp.
References LCD5110Controller::LcdIO::chipEnable, and IIOPin::reset().
Referenced by glcd_reset(), and glcd_spi_write().
glcd_spi_write()
void glcd_spi_write (uint8_t c)
Definition at line 91 of file lcd5110.cpp.
References GLCD_DESELECT_impl(), GLCD_SELECT_impl(), LCD5110Controller::LcdIO::spi, and ISPIManager::Transmit().