Caustic lasertag system: src/core/logging.cpp File Reference
logging.cpp File Reference
#include "core/logging.hpp"
#include "core/string-utils.hpp"
#include <stdio.h>
#include <string.h>
#include <algorithm>
Functions
ssize_t _write (int fd __attribute__((unused)), const char *buf __attribute__((unused)), size_t nbyte __attribute__((unused)))
int __attribute__ ((weak)) _fstat(int fildes __attribute__((unused))
int struct stat *st __attribute__ ((unused)))
Variables
Logger error ("ERROR")
Logger warning ("warn ")
Logger info ("info ")
Logger debug ("debug")
Logger radio ("radio")
Logger trace ("trace")
Function Documentation
__attribute__() [1/2]
int __attribute__ ((weak))
Definition at line 207 of file logging.cpp.
References Loggers::__attribute__().
__attribute__() [2/2]
int char *ptr int len __attribute__ ((unused))
Definition at line 193 of file logging.cpp.
References Loggers::__attribute__().
_write()
ssize_t _write (int fd __attribute__(unused), const char *buf __attribute__(unused), size_t nbyte __attribute__(unused))
Definition at line 185 of file logging.cpp.
References Loggers::__attribute__(), buf, and Loggers::write().
Variable Documentation
debug
Logger debug("debug")
Referenced by RC552Wrapper::cardReadyToOperate(), RCSPAggregator::dispatchOperation(), UIInitScreen::doIteration(), NRF24L01Manager::enableDebug(), NetworkLayer::enableDebug(), NRF24L01Manager::init(), HeadSensor::init(), NetworkLayer::interrogate(), main(), Rifle::onCardReaded(), GameLog::BaseStatsCounter::onTransmissionBroken(), GameLog::BaseStatsCounter::onTransmissionSucceeded(), WavPlayer::openFile(), IRPresentationReceiverMT2::parseRCSP(), SoundPlayer::play(), SystemMonitor::printOSDetails(), SystemMonitor::printStagers(), Stager::printStages(), SystemMonitor::printTime(), SystemMonitor::printVoltage(), RC552Wrapper::readBlockLoop(), SoundPlayer::readVariants(), BluetoothBridge::receiveNetworkPackage(), IRPresentationReceiverMT2::receiverCallback(), BluetoothBridge::sendBluetoothMessage(), HeadSensor::sendHeartbeat(), BluetoothBridge::sendNetworkPackage(), GameLog::BaseStatsCounter::sendNextPackage(), GameLog::BaseStatsCounter::waitDelay(), WavPlayer::WavPlayer(), and RC552Wrapper::writeBlockLoop().
error
Logger error("ERROR")
Referenced by Kernel::assert(), ButtonManager::ButtonManager(), RC552Wrapper::cardReadyToOperate(), Rifle::checkPinout(), DeviceAddress::convertFromString(), ConnectedWeaponsList::deserialize(), IOPin::enableExti(), ADC::get(), UARTManager::init(), SPIManager::init(), SmartPoint::init(), NRF24L01Manager::init(), HeadSensor::init(), DeviceInitializer::initDevice(), DeviceInitializer::initFatFS(), Loggers::initLoggers(), ConnectedWeaponsList::insert(), ButtonManager::interrogate(), IRReceiverTV::interrogate(), WavPlayer::loadFragment(), IOPin::maskToPinNumber(), WavPlayer::openFile(), IniParcer::parseFile(), IOPin::parsePortNumber(), IRPresentationReceiverMT2::parseRCSP(), RC552Wrapper::readBlockLoop(), Pinout::readConfigLine(), WavPlayer::ChannelContext::readHeader(), SPIManager::Receive(), RCSPAggregator::registerAccessor(), GameLog::BaseStatsCounter::restoreFromFile(), RTCMgr::RTC_CalendarConfig(), TaskOnce::run(), TaskCycled::run(), GameLog::BaseStatsCounter::saveState(), MainStateSaver::saveState(), IRTransmitterTV::send(), NetworkLayer::send(), IRPresentationTransmitterMT2::sendGenericRCSPMessageDefault(), SPIManager::SPIManager(), ButtonManager::state(), SPIManager::Transmit(), SPIManager::TransmitReceive(), MainStateSaver::tryRestore(), and RC552Wrapper::writeBlockLoop().
info
Logger info("info ")
Referenced by Rifle::checkHeartBeat(), SmartPoint::checkPinout(), ConnectedWeaponsList::deserialize(), Rifle::detectRifleState(), HeadSensor::dieWeapons(), RTCMgr::init(), SmartPoint::init(), Rifle::init(), HeadSensor::init(), NetworkLayer::init(), DeviceInitializer::initDevice(), DeviceInitializer::initEnvironment(), DeviceInitializer::initFatFS(), Loggers::initLoggers(), RC552Wrapper::interrogate(), Rifle::magazineSensor(), main(), Rifle::makeShot(), HeadSensor::notifyDamager(), Rifle::onCardReaded(), Rifle::onHSConnected(), Pinout::printPinout(), BluetoothBridge::receiveBluetoothPackageISR(), Rifle::registerWeapon(), Rifle::reloadAndPlay(), WeaponManager::respawn(), HeadSensor::respawnWeapons(), Kernel::run(), TaskOnce::run(), TaskCycled::run(), MainStateSaver::runSaver(), GameLog::BaseStatsCounter::saveState(), MainStateSaver::saveState(), HeadSensor::sendHeartbeat(), DeviceInitializer::startOS(), HeadSensor::turnOffWeapons(), Rifle::updatePlayerState(), HeadSensor::weaponWoundAndShock(), and SmartPointState::win().
radio
Logger radio("radio")
Referenced by main(), NetworkLayer::printAndSend(), NetworkLayer::receiveIncoming(), NetworkLayer::RXCallback(), and NetworkLayer::sendNext().
trace
Logger trace("trace")
Referenced by DeviceAddress::convertFromString(), ConnectedWeaponsList::deserialize(), RCSPAggregator::dispatchOperation(), Rifle::distortBolt(), NRF24L01Manager::init(), Rifle::makeShot(), NRF24L01Manager::onRXDataReady(), NetworkLayer::printAndSend(), BluetoothBridge::receiveNetworkPackage(), NetworkLayer::RXCallback(), MainStateSaver::saveState(), NRF24L01Manager::sendData(), HeadSensor::sendHeartbeat(), ConnectedWeaponsList::serialize(), and WavPlayer::WavPlayer().
warning
Logger warning("warn ")
Referenced by IOPinsPool::getIOPin(), SmartPoint::init(), Rifle::init(), HeadSensor::init(), DeviceInitializer::initDevice(), Loggers::initLoggers(), Rifle::magazineSensor(), IRPresentationReceiverMT2::parseRCSP(), IRPresentationReceiverMT2::parseSetTeam(), IRPresentationReceiverMT2::parseShot(), SoundPlayer::play(), RCSPAggregator::printWarningUnknownCode(), NetworkLayer::reinitNRF(), GameLog::BaseStatsCounter::restoreFromFile(), and MainStateSaver::tryRestore().