Caustic lasertag system: src/main.cpp File Reference
main.cpp File Reference
#include "head-sensor/head-sensor.hpp"
#include "core/logging.hpp"
#include "core/os-wrappers.hpp"
#include "core/device-initializer.hpp"
#include "core/diagnostic.hpp"
#include "core/debug-settings.hpp"
#include "dev/wav-player.hpp"
#include "hal/adc.hpp"
#include "hal/rtc.hpp"
#include "core/power-monitor.hpp"
#include <functional>
#include <stdio.h>
Functions
int main (void)
Variables
DeviceInitializer deviceInitializer
IADC * adc = nullptr
TaskOnce sound ([](){ info<< "Sound here";})
char buf [10]
Function Documentation
main()
int main (void)
Definition at line 49 of file main.cpp.
References debug, Logger::enable(), info, DeviceInitializer::initDevice(), DeviceInitializer::initEnvironment(), instance, radio, TaskBase::setStackSize(), and sound.
Variable Documentation
adc
IADC* adc = nullptr
Definition at line 40 of file main.cpp.
buf
char buf[10]
Definition at line 85 of file main.cpp.
Referenced by _write(), and interpretBuffer().
deviceInitializer
DeviceInitializer deviceInitializer
Definition at line 38 of file main.cpp.
sound
TaskOnce sound([](){ info<< "Sound here"; })
Referenced by main(), and HeadSensor::notifyDamager().