Caustic lasertag system: include/utils/memory.hpp File Reference
memory.hpp File Reference
#include <string.h>
#include <stdint.h>
Classes
class ChangeWatcher< T >
Functions
template<typename T >
void zerify (T &object)
template<typename T >
void copyToBuffer (void *buffer, const T &object)
template<typename T >
T & interpretBuffer (void *buffer)
uint32_t hashLyC (uint32_t hash, const uint8_t *buf, uint32_t size)
template<typename T1 >
uint32_t hashLy (const T1 &a1, uint32_t hash=0)
template<typename T1 , typename T2 >
uint32_t hashLy (const T1 &a1, const T2 &a2)
template<typename T1 , typename T2 , typename T3 >
uint32_t hashLy (const T1 &a1, const T2 &a2, const T3 &a3)
Function Documentation
copyToBuffer()
template<typename T > void copyToBuffer (void * buffer, const T & object)
Definition at line 37 of file memory.hpp.
hashLy() [1/3]
template<typename T1 > uint32_t hashLy (const T1 & a1, uint32_t hash = 0)
Definition at line 51 of file memory.hpp.
References hashLyC().
Referenced by SPIManager::init().
hashLy() [2/3]
template<typename T1 , typename T2 > uint32_t hashLy (const T1 & a1, const T2 & a2)
Definition at line 57 of file memory.hpp.
References hashLyC().
hashLy() [3/3]
template<typename T1 , typename T2 , typename T3 > uint32_t hashLy (const T1 & a1, const T2 & a2, const T3 & a3)
Definition at line 65 of file memory.hpp.
References hashLyC().
hashLyC()
uint32_t hashLyC (uint32_t hash, const uint8_t * buf, uint32_t size)
Definition at line 26 of file memory-utils.cpp.
Referenced by hashLy(), and interpretBuffer().
interpretBuffer()
template<typename T > T& interpretBuffer (void * buffer)
Definition at line 43 of file memory.hpp.
References buf, and hashLyC().
zerify()
template<typename T > void zerify (T & object)
Definition at line 31 of file memory.hpp.
Referenced by IOPin::enableExti(), ADC::init(), RTCMgr::init(), SystemClock::MX_TIM4_Init(), IOPinsPool::resetAllPins(), SPIManager::SPIManager(), IOPin::switchToInput(), and IOPin::switchToOutput().