Caustic lasertag system: include/rcsp/RCSP-aggregator.hpp File Reference
RCSP-aggregator.hpp File Reference
#include "rcsp/RCSP-base-types.hpp"
#include "rcsp/RCSP-codes-manipulation.hpp"
#include "utils/macro.hpp"
#include "core/string-utils.hpp"
#include "core/result-code.hpp"
#include <vector>
#include <map>
#include <functional>
#include <string>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
Classes
class IOperationAccessor
Any kind of object that can read data from stream and write data to stream.
class RCSPAggregator
struct RCSPAggregator::Operation
class DefaultFunctionAccessor< Type >
Realization of IOperationAccessor for function.
class DefaultFunctionAccessor<>
Realization of IOperationAccessor for function without arguments.
class DefaultFunctionAccessor< ArgType >
Realization of IOperationAccessor for function with argument.
class SelfSerializingParameterAccessor< Type >
class ParameterAccessorBase< Type >
Realization of IOperationAccessor for any parameters.
class StandartStrParseParameterAccessor< Type >
Realization of IOperationAccessor for simple typed parameters.
class CustomStrParseParameterAccessor< Type >
Realization of IOperationAccessor for parameters that have convertFromString(...) method.
Macros
#define RESTORABLE true
#define NOT_RESTORABLE false
#define TYPE_OF(NameSpace, parameter) NameSpace::parameter##Type
#define PAR_ST(restorable, NameSpace, name)
#define PAR_CL(restorable, NameSpace, name)
#define PAR_CL_SS(restorable, NameSpace, name)
#define FUNCTION_1P(NameSpace, ClassName, functionName)
Create function in class with 1 parameter and connect it to configs aggregator.
#define FUNCTION_NP(NameSpace, ClassName, functionName)
Create function in class with no parameters and connect it to configs aggregator.
Functions
template<typename T >
void serializeAndInc (void *&cursor, const T &data)
template<typename T >
void deserializeAndInc (const void *&cursor, T &target)
template<typename T >
void deserializeAndInc (const uint8_t *&cursor, T &target)
template<typename T >
void deserializeAndInc (void *&cursor, T &target)
Macro Definition Documentation
FUNCTION_1P
#define FUNCTION_1P (NameSpace, ClassName, functionName)
Value:
void functionName(NameSpace::functionName##Arg1Type argument); \
                                                          DefaultFunctionAccessor<NameSpace::functionName##Arg1Type> \
                                                              functionName##Accessor {NameSpace::functionName, STRINGIFICATE(functionName), \
                                                                  std::bind(&ClassName::functionName, this, std::placeholders::_1)}
Create function in class with 1 parameter and connect it to configs aggregator.
Definition at line 103 of file RCSP-aggregator.hpp.
FUNCTION_NP
#define FUNCTION_NP (NameSpace, ClassName, functionName)
Value:
void functionName(); \
                                                           DefaultFunctionAccessor<> functionName##Accessor {NameSpace::functionName, STRINGIFICATE(functionName), \
                                                           std::bind(&ClassName::functionName, this)}
Create function in class with no parameters and connect it to configs aggregator.
Definition at line 109 of file RCSP-aggregator.hpp.
NOT_RESTORABLE
#define NOT_RESTORABLE false
Definition at line 64 of file RCSP-aggregator.hpp.
PAR_CL
#define PAR_CL (restorable, NameSpace, name)
Value:
NameSpace::name##Type name; \
                                              CustomStrParseParameterAccessor<NameSpace::name##Type> name##Accessor \
                                                  {NameSpace::name, STRINGIFICATE(name), &name, restorable}
The same as PAR_ST, but string parsing using convertFromString function CL = CLass
Definition at line 82 of file RCSP-aggregator.hpp.
PAR_CL_SS
#define PAR_CL_SS (restorable, NameSpace, name)
Value:
NameSpace::name##Type name; \
                                               SelfSerializingParameterAccessor<NameSpace::name##Type> name##Accessor \
                                                   {NameSpace::name, STRINGIFICATE(name), &name, restorable}
The same as PAR_CL, but SS means 'Self serializing' This macro should be used with classes that has methods 'serialize' and 'deseriaize'
Also no str parsing avaliable for typed this macro applied to
Definition at line 92 of file RCSP-aggregator.hpp.
Referenced by PlayerState::PlayerState().
PAR_ST
#define PAR_ST (restorable, NameSpace, name)
Value:
NameSpace::name##Type name; \
                                              StandartStrParseParameterAccessor<NameSpace::name##Type> name##Accessor \
                                                  {NameSpace::name, STRINGIFICATE(name), &name, restorable}
Create variable (in any class) and connect it to configs aggregator. ST = Simple Types, that can be parsed from string using StringParser<Type>::parse(str)
Definition at line 75 of file RCSP-aggregator.hpp.
RESTORABLE
#define RESTORABLE true
Format of any serialized operation:
| data length | Operation code | data |
| 1 byte | 2 bytes | data length bytes |
Operation code: ttxxxxxxxxxxxxxx
tt - operation type:
00 - function call request 01 - set parameter 10 - request parameter 11 - reserved
Definition at line 63 of file RCSP-aggregator.hpp.
Referenced by PlayerState::PlayerState(), and RifleOwnerConfiguration::RifleOwnerConfiguration().
TYPE_OF
#define TYPE_OF (NameSpace, parameter) NameSpace::parameter##Type
Get type for any parameter to avoid type mismatch
Definition at line 69 of file RCSP-aggregator.hpp.
Referenced by HeadSensor::TeamBroadcastTester::TeamBroadcastTester().
Function Documentation
deserializeAndInc() [1/3]
template<typename T > void deserializeAndInc (const void *& cursor, T & target) inline
Definition at line 319 of file RCSP-aggregator.hpp.
Referenced by ConnectedWeaponsList::deserialize(), and RCSPAggregator::extractNextOperation().
deserializeAndInc() [2/3]
template<typename T > void deserializeAndInc (const uint8_t *& cursor, T & target) inline
Definition at line 326 of file RCSP-aggregator.hpp.
deserializeAndInc() [3/3]
template<typename T > void deserializeAndInc (void *& cursor, T & target) inline
Definition at line 333 of file RCSP-aggregator.hpp.
serializeAndInc()
template<typename T > void serializeAndInc (void *& cursor, const T & data) inline
Definition at line 312 of file RCSP-aggregator.hpp.
Referenced by ConnectedWeaponsList::serialize().