Caustic lasertag system: include/core/string-utils.hpp File Reference
string-utils.hpp File Reference
#include "result-code.hpp"
#include <functional>
#include "string.h"
#include <stdint.h>
#include <stdlib.h>
Classes
class IniParcer
class StringParser< Type >
class StringParser< uint32_t >
class StringParser< int32_t >
class StringParser< uint16_t >
class StringParser< int16_t >
class StringParser< uint8_t >
class StringParser< int8_t >
class StringParser< float >
class StringParser< double >
class StringParser< bool >
Functions
void printHex (const uint8_t *buffer, size_t size)
void formatTime (char *buffer, uint16_t min, uint16_t sec)
const char * parseFRESULT (int res)
void floatToString (char *buffer, float value, int bufferSize, int fracDigits)
void doubleToString (char *buffer, double value, int bufferSize, int fracDigits)
char lower (char c)
bool isSpace (char c)
bool isCharacter (char c)
bool isNumber (char c)
void printBar (int barLength, int filled)
bool checkSuffix (const char *where, const char *what)
Function Documentation
checkSuffix()
bool checkSuffix (const char * where, const char * what)
Definition at line 131 of file string-utils.cpp.
Referenced by isNumber(), and Pinout::readConfigLine().
doubleToString()
void doubleToString (char * buffer, double value, int bufferSize, int fracDigits)
Definition at line 67 of file string-utils.cpp.
Referenced by floatToString(), and Logger::LoggerUnnamed::operator<<().
floatToString()
void floatToString (char * buffer, float value, int bufferSize, int fracDigits)
Definition at line 62 of file string-utils.cpp.
References doubleToString().
Referenced by Logger::LoggerUnnamed::operator<<().
formatTime()
void formatTime (char * buffer, uint16_t min, uint16_t sec)
Definition at line 38 of file string-utils.cpp.
Referenced by UITimeLeftScreen::doIteration().
isCharacter()
bool isCharacter (char c) inline
Definition at line 54 of file string-utils.hpp.
Referenced by IniParcer::parseFile().
isNumber()
bool isNumber (char c) inline
Definition at line 59 of file string-utils.hpp.
References checkSuffix(), and printBar().
Referenced by IniParcer::parseFile().
isSpace()
bool isSpace (char c) inline
Definition at line 49 of file string-utils.hpp.
Referenced by StringParser< bool >::parse(), and IniParcer::parseFile().
lower()
char lower (char c) inline
Definition at line 41 of file string-utils.hpp.
Referenced by StringParser< bool >::parse().
parseFRESULT()
const char* parseFRESULT (int res)
Definition at line 90 of file string-utils.cpp.
Referenced by WavPlayer::loadFragment(), WavPlayer::openFile(), IniParcer::parseFile(), MainStateSaver::saveState(), and MainStateSaver::tryRestore().
printBar()
void printBar (int barLength, int filled)
Definition at line 120 of file string-utils.cpp.
Referenced by isNumber(), and PlayerPartialState::print().
printHex()
void printHex (const uint8_t * buffer, size_t size)
Definition at line 29 of file string-utils.cpp.
Referenced by Rifle::onCardReaded(), NRF24L01Manager::onRXDataReady(), NetworkLayer::printAndSend(), BluetoothBridge::receiveBluetoothPackageISR(), BluetoothBridge::receiveNetworkPackage(), IRPresentationReceiverMT2::receiverCallback(), NetworkLayer::RXCallback(), and NRF24L01Manager::sendData().