Caustic lasertag system: src/core/string-utils.cpp File Reference
string-utils.cpp File Reference
#include "core/string-utils.hpp"
#include "fatfs.h"
#include <string.h>
Functions
void printHex (const uint8_t *buffer, size_t size)
void formatTime (char *buffer, uint16_t min, uint16_t sec)
void floatToString (char *buffer, float value, int bufferSize, int fracDigits)
void doubleToString (char *buffer, double value, int bufferSize, int fracDigits)
const char * parseFRESULT (int res)
void printBar (int barLength, int filled)
bool checkSuffix (const char *where, const char *what)
Function Documentation
checkSuffix()
bool checkSuffix (const char * where, const char * what)
Definition at line 131 of file string-utils.cpp.
Referenced by isNumber(), and Pinout::readConfigLine().
doubleToString()
void doubleToString (char * buffer, double value, int bufferSize, int fracDigits)
Definition at line 67 of file string-utils.cpp.
Referenced by floatToString(), and Logger::LoggerUnnamed::operator<<().
floatToString()
void floatToString (char * buffer, float value, int bufferSize, int fracDigits)
Definition at line 62 of file string-utils.cpp.
References doubleToString().
Referenced by Logger::LoggerUnnamed::operator<<().
formatTime()
void formatTime (char * buffer, uint16_t min, uint16_t sec)
Definition at line 38 of file string-utils.cpp.
Referenced by UITimeLeftScreen::doIteration().
parseFRESULT()
const char* parseFRESULT (int res)
Definition at line 90 of file string-utils.cpp.
Referenced by WavPlayer::loadFragment(), WavPlayer::openFile(), IniParcer::parseFile(), MainStateSaver::saveState(), and MainStateSaver::tryRestore().
printBar()
void printBar (int barLength, int filled)
Definition at line 120 of file string-utils.cpp.
Referenced by isNumber(), and PlayerPartialState::print().
printHex()
void printHex (const uint8_t * buffer, size_t size)
Definition at line 29 of file string-utils.cpp.
Referenced by Rifle::onCardReaded(), NRF24L01Manager::onRXDataReady(), NetworkLayer::printAndSend(), BluetoothBridge::receiveBluetoothPackageISR(), BluetoothBridge::receiveNetworkPackage(), IRPresentationReceiverMT2::receiverCallback(), NetworkLayer::RXCallback(), and NRF24L01Manager::sendData().