Caustic lasertag system: Bluetooth::Message Struct Reference
Bluetooth::Message Struct Reference
#include <bluetooth-protocol.hpp>
Public Member Functions
uint8_t payloadLength ()
Public Attributes
uint8_t length = headerLength
DeviceAddress address
uint8_t data [maxMessageLen - sizeof(length)]
Static Public Attributes
static constexpr uint8_t headerLength = sizeof(uint8_t) + sizeof(DeviceAddress)
Detailed Description
Definition at line 35 of file bluetooth-protocol.hpp.
Member Function Documentation
payloadLength()
uint8_t Bluetooth::Message::payloadLength () inline
Definition at line 42 of file bluetooth-protocol.hpp.
References headerLength.
Referenced by BluetoothBridge::sendNetworkPackage().
Member Data Documentation
address
DeviceAddress Bluetooth::Message::address
Definition at line 39 of file bluetooth-protocol.hpp.
Referenced by BluetoothBridge::sendNetworkPackage(), and Bluetooth::MessageCreator::setSender().
data
uint8_t Bluetooth::Message::data[maxMessageLen - sizeof(length)]
Definition at line 40 of file bluetooth-protocol.hpp.
Referenced by Bluetooth::MessageCreator::addData(), and BluetoothBridge::sendNetworkPackage().
headerLength
constexpr uint8_t Bluetooth::Message::headerLength = sizeof(uint8_t) + sizeof(DeviceAddress) static
Definition at line 37 of file bluetooth-protocol.hpp.
Referenced by Bluetooth::MessageCreator::addData(), Bluetooth::MessageCreator::clear(), and payloadLength().
length
uint8_t Bluetooth::Message::length = headerLength
Definition at line 38 of file bluetooth-protocol.hpp.
Referenced by Bluetooth::MessageCreator::addData(), Bluetooth::MessageCreator::clear(), and Bluetooth::MessageReceiver::ready().
The documentation for this struct was generated from the following file:
include/bluetooth-bridge/bluetooth-protocol.hpp