Caustic lasertag system: Logger::LoggerUnnamed Struct Reference
Logger::LoggerUnnamed Struct Reference
Public Member Functions
LoggerUnnamed & operator<< (const char *str)
LoggerUnnamed & operator<< (const std::string &str)
LoggerUnnamed & operator<< (int d)
LoggerUnnamed & operator<< (unsigned int d)
LoggerUnnamed & operator<< (uint32_t d)
LoggerUnnamed & operator<< (uint64_t d)
LoggerUnnamed & operator<< (float f)
LoggerUnnamed & operator<< (double f)
LoggerUnnamed & operator<< (bool b)
Public Attributes
bool enabled = false
Static Public Attributes
static constexpr unsigned int numbersBufferSize = 30
Detailed Description
Definition at line 88 of file logging.hpp.
Member Function Documentation
operator<<() [1/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (const char * str)
Definition at line 71 of file logging.cpp.
References IUARTManager::transmitSync().
operator<<() [2/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (const std::string & str)
Definition at line 81 of file logging.cpp.
operator<<() [3/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (int d)
Definition at line 87 of file logging.cpp.
operator<<() [4/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (unsigned int d)
Definition at line 94 of file logging.cpp.
operator<<() [5/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (uint32_t d)
Definition at line 101 of file logging.cpp.
operator<<() [6/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (uint64_t d)
Definition at line 112 of file logging.cpp.
operator<<() [7/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (float f)
Definition at line 123 of file logging.cpp.
References floatToString().
operator<<() [8/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (double f)
Definition at line 132 of file logging.cpp.
References doubleToString().
operator<<() [9/9]
Logger::LoggerUnnamed & Logger::LoggerUnnamed::operator<< (bool b)
Definition at line 141 of file logging.cpp.
Member Data Documentation
enabled
bool Logger::LoggerUnnamed::enabled = false
Definition at line 100 of file logging.hpp.
numbersBufferSize
constexpr unsigned int Logger::LoggerUnnamed::numbersBufferSize = 30 static
Definition at line 90 of file logging.hpp.
The documentation for this struct was generated from the following files:
include/core/logging.hpp
src/core/logging.cpp