/*
 * debug-settings.hpp
 *
 *  Created on: 20 окт. 2016 г.
 *      Author: dalexies
 */

#ifndef UNIVERSAL_DEVICE_INCLUDE_CORE_DEBUG_SETTINGS_HPP_
#define UNIVERSAL_DEVICE_INCLUDE_CORE_DEBUG_SETTINGS_HPP_

//#define DBG_SYSTEM_MONITOR_DISABLE
//#define DBG_RADIO_DISABLE
//#define DBG_NRF_DISABLE


#endif /* UNIVERSAL_DEVICE_INCLUDE_CORE_DEBUG_SETTINGS_HPP_ */
